'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const app=path.resolve(__dirname,'StressClient.exe'),base=path.resolve(__dirname,'../../benchmarks/stress-2026-09-20'),run=path.join(base,'run-'+Date.now());fs.mkdirSync(run,{recursive:true});
const period=Buffer.alloc(251*65536);for(let i=0;i<period.length;i++)period[i]=(i*31+Math.floor(i/65536)+7)%251;
const variants=[period,Buffer.from(period.map(x=>(x+1)%251))],digestCache=new Map();
function digest(size,v=0){const key=size+':'+v;if(!digestCache.has(key)){const h=crypto.createHash('sha256');for(let at=0;at<size;at+=period.length)h.update(variants[v].subarray(0,Math.min(period.length,size-at)));digestCache.set(key,h.digest('hex'));}return digestCache.get(key);}
const files=new Map(),events=[],sockets=new Set();let active=0,peak=0,sequence=0;
const server=http.createServer((req,res)=>{const f=files.get(new URL(req.url,'http://local').pathname);if(!f){res.writeHead(404,{'Content-Length':0});return res.end();}
 const range=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range||''),probe=range&&+range[1]===0&&+range[2]===0;
 let start=range?+range[1]:0,end=range&&range[2]?+range[2]:f.size-1;const ev={id:++sequence,label:f.label,start,end,probe,range:req.headers.range||null,at:Date.now(),sent:0};events.push(ev);active++;peak=Math.max(peak,active);res.once('close',()=>{active--;ev.closed=Date.now();});
 if(f.mode==='stall-headers'&&!probe)return;
 if(f.mode==='redirect-loop'){res.writeHead(302,{Location:req.url,'Content-Length':0});return res.end();}
 if(f.mode==='http-error'&&!probe&&f.errors++<2){res.writeHead(503,{'Content-Length':0});return res.end();}
 if(f.mode==='changed'&&!probe&&!f.changed){f.changed=true;f.variant=1;}
 if(f.mode==='empty'||f.size===0){res.writeHead(416,{'Content-Range':'bytes */0','Content-Length':0});return res.end();}
 const sequential=['plain','chunked','no-validator','weak-validator'].includes(f.mode);
 if(sequential){start=0;end=f.size-1;}
 if(start<0||end<start||end>=f.size){res.writeHead(416,{'Content-Length':0});return res.end();}
 const headers={'Content-Type':'application/octet-stream','Accept-Ranges':'bytes','Connection':'keep-alive'};
 if(f.mode!=='no-validator'&&f.mode!=='modified-only')headers.ETag=f.mode==='weak-validator'?'W/"fixture"':'"fixture-'+f.variant+'"';
 if(f.mode==='modified-only')headers['Last-Modified']='Sun, 20 Sep 2026 00:00:00 GMT';
 if(f.mode!=='chunked')headers['Content-Length']=end-start+1;
 if(range&&!sequential)headers['Content-Range']=`bytes ${f.mode==='bad-range'&&!probe?start+1:start}-${end}/${f.size}`;
 if(f.mode==='encoded')headers['Content-Encoding']='gzip';
 res.writeHead(range&&!sequential?206:200,headers);res.flushHeaders();
 if(f.mode==='stall-body'&&!probe)return;
 let at=start,timer;const willDrop=!probe&&f.mode==='drop'&&f.drops++<2;
 function pump(){if(res.destroyed)return;for(;;){const n=Math.min(65536,end-at+1,period.length-at%period.length);const out=variants[f.variant].subarray(at%period.length,at%period.length+n);at+=n;ev.sent+=n;
  const ok=res.write(out);if(willDrop&&ev.sent>=131072){res.destroy();return;}if(at>end){res.end();return;}
  if(f.delay&&!probe){timer=setTimeout(pump,f.delay);return;}if(!ok){res.once('drain',pump);return;}
 }}res.once('close',()=>clearTimeout(timer));pump();
});server.on('connection',s=>{sockets.add(s);s.on('close',()=>sockets.delete(s));});server.keepAliveTimeout=1000;
const results=[];let origin;
function specJob(label,size,mode='range',connections=8,extra={}){const item={label,size,mode,variant:0,errors:0,drops:0,delay:0,...extra};files.set('/'+label,item);return {name:label+'.bin',url:origin+'/'+label,sha256:digest(size,mode==='changed'?1:0),connections};}
function execute(folder,spec,timeout=45000,killWhen){fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,'input.json'),JSON.stringify(spec));return new Promise(resolve=>{const proc=spawn(app,[path.join(folder,'input.json')],{windowsHide:true});let output='',error='',terminated=false;proc.stdout.on('data',c=>output+=c);proc.stderr.on('data',c=>error+=c);const began=Date.now();const timer=setTimeout(()=>{terminated=true;proc.kill();},timeout);const watch=killWhen?setInterval(()=>{try{if(killWhen(folder)){terminated=true;proc.kill();}}catch{}},25):null;proc.on('error',e=>{error=e.message;});proc.on('close',code=>{clearTimeout(timer);clearInterval(watch);fs.writeFileSync(path.join(folder,'stdout.log'),output);fs.writeFileSync(path.join(folder,'stderr.log'),error);let report;try{report=JSON.parse(fs.readFileSync(path.join(folder,'result.json'),'utf8').replace(/^\uFEFF/,''));}catch{}resolve({code,terminated,wallSeconds:(Date.now()-began)/1000,report});});});}
async function check(name,body){if(process.argv.includes('--handles-only')&&!name.includes('handle stability'))return;const began=Date.now();try{const detail=await body();results.push({name,passed:true,seconds:(Date.now()-began)/1000,...detail});console.log('PASS '+name);}catch(e){results.push({name,passed:false,seconds:(Date.now()-began)/1000,error:e.stack});console.log('FAIL '+name+': '+e.message);}fs.writeFileSync(path.join(run,'report.json'),JSON.stringify({run,results,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length},null,2));}
function completed(result,count){assert.equal(result.code,0);assert.ok(result.report&&!result.report.fatal);assert.equal(result.report.jobs.length,count);for(const j of result.report.jobs){assert.equal(j.status,'Complete',j.error);assert.equal(j.received,j.size);assert.ok(j.exists);const f=files.get('/'+j.name.replace(/\.bin$/,''));assert.equal(j.sha256,digest(f.size,f.mode==='changed'?1:0));}assert.equal(result.report.watcherError,'');}
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));origin='http://127.0.0.1:'+server.address().port;console.log('Evidence '+run);
 for(const mode of ['stall-body','stall-headers'])await check('cancel '+mode,async()=>{const label=mode;const result=await execute(path.join(run,label),{jobs:[specJob(label,8*1024*1024,mode)],cancelAfterMs:600},6000);assert.ok(!result.terminated,'Pause did not complete within six seconds of launch');assert.equal(result.report.jobs[0].status,'Paused');assert.ok(result.report.cancelLatencySeconds<2,'Pause latency '+result.report.cancelLatencySeconds);return {detail:result.report};});
 if(!process.argv.includes('--quick')){
  for(const connections of [1,2,4,8,16])await check('size boundaries with '+connections+' workers',async()=>{const sizes=[0,1,65535,65536,65537,1048575,1048577,16*1048576+731],jobs=sizes.map((size,i)=>specJob('size-'+connections+'-'+i,size,'range',connections));const result=await execute(path.join(run,'sizes-'+connections),{jobs});completed(result,jobs.length);return {files:jobs.length,detail:result.report};});
  for(const mode of ['drop','http-error','changed','plain','chunked','no-validator','weak-validator','modified-only'])await check(mode+' recovery/compatibility',async()=>{const result=await execute(path.join(run,mode),{jobs:[specJob(mode,8*1048576+731,mode)],retries:3});completed(result,1);return {detail:result.report};});
  for(const mode of ['bad-range','encoded','redirect-loop'])await check('reject '+mode,async()=>{const result=await execute(path.join(run,mode),{jobs:[specJob(mode,2*1048576,mode)],retries:0});assert.equal(result.code,0);assert.equal(result.report.jobs[0].status,'Failed');assert.equal(result.report.jobs[0].exists,false);return {detail:result.report};});
  await check('queue concurrency and twelve complete files',async()=>{const jobs=Array.from({length:12},(_,i)=>specJob('queue-'+i,8*1048576+i,'range',16,{delay:1}));const result=await execute(path.join(run,'queue'),{jobs,mode:'queue',parallel:4},90000);completed(result,12);assert.equal(result.report.peakQueueActive,4);return {files:12,detail:result.report};});
  await check('global bandwidth cap across concurrent files',async()=>{const jobs=[0,1].map(i=>specJob('limited-'+i,512*1024,'range',4));const result=await execute(path.join(run,'limited'),{jobs,concurrent:true,globalLimit:256});completed(result,2);assert.ok(result.report.seconds>=3.5,'Aggregate limiter exceeded its budget');assert.ok(result.report.seconds<12,'Aggregate limiter stalled');return {detail:result.report};});
  await check('abrupt process termination and real-process resume',async()=>{const folder=path.join(run,'crash'),job=specJob('crash-resume',64*1048576+731,'range',16,{delay:3});const result=await execute(folder,{jobs:[job]},15000,p=>{const s=JSON.parse(fs.readFileSync(path.join(p,'state/state.json'),'utf8'));return s.Downloads[0].Received>1048576;});assert.ok(result.terminated);const saved=JSON.parse(fs.readFileSync(path.join(folder,'state/state.json'),'utf8'));assert.ok(saved.Downloads[0].Received>0);fs.renameSync(path.join(folder,'input.json'),path.join(folder,'input-first.json'));const resumed=await execute(folder,{jobs:[],resume:true});completed(resumed,1);return {savedBytes:saved.Downloads[0].Received,detail:resumed.report};});
  await check('five process pause/reload cycles',async()=>{const folder=path.join(run,'pause-cycles'),job=specJob('pause-cycles',64*1048576+731,'range',4,{delay:5});let last=0;for(let i=0;i<5;i++){const result=await execute(folder,{jobs:i?[]:[job],resume:i>0,cancelAfterMs:250});assert.equal(result.report.jobs[0].status,'Paused');assert.ok(result.report.jobs[0].received>last);last=result.report.jobs[0].received;fs.copyFileSync(path.join(folder,'result.json'),path.join(folder,'paused-'+i+'.json'));}const final=await execute(folder,{jobs:[],resume:true});completed(final,1);return {savedBytes:last,detail:final.report};});
  await check('240 sequential downloads and handle stability',async()=>{const jobs=Array.from({length:240},(_,i)=>specJob('handles-'+i,4096+i));const result=await execute(path.join(run,'handles'),{jobs,settleMs:65000,settleAfterJobs:120},300000);completed(result,jobs.length);const settled=result.report.settledSamples;assert.equal(settled.length,2);assert.ok(settled[1].handles-settled[0].handles<=12,'Resource growth across settled batches: '+JSON.stringify(settled));assert.ok(settled[1].handles-result.report.initialHandles<=100,'Unexpected retained resources after HTTP initialization');return {files:jobs.length,detail:result.report};});
  await check('file larger than 4 GiB',async()=>{const size=4*1024*1024*1024+65537,job=specJob('over-4gib',size,'range',16);const result=await execute(path.join(run,'over-4gib'),{jobs:[job]},240000);completed(result,1);assert.equal(fs.statSync(path.join(run,'over-4gib/downloads/over-4gib.bin')).size,size);return {bytes:size,detail:result.report};});
 }
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{fs.writeFileSync(path.join(run,'requests.json'),JSON.stringify({peakOutstandingResponses:peak,events},null,2));for(const s of sockets)s.destroy();server.close();console.log(JSON.stringify({run,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length}));if(results.some(r=>!r.passed))process.exitCode=1;});
