'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),https=require('node:https'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
const base=path.resolve(__dirname,'../../benchmarks/stress-2026-09-20'),root=path.join(base,'protocol-'+Date.now()),exe=path.join(__dirname,'StressClient.exe');fs.mkdirSync(root,{recursive:true});
const payload=Buffer.alloc(8*1048576+731);for(let i=0;i<payload.length;i++)payload[i]=(i*31+7)%251;const sha=crypto.createHash('sha256').update(payload).digest('hex');const sockets=new Set(),results=[];
const handler=(req,res)=>{if(req.method==='POST'){const input=[];req.on('data',c=>input.push(c));req.on('end',()=>{if(req.url==='/post-stall')return;const body=Buffer.concat(input);res.writeHead(200,{'Content-Length':body.length});res.end(body);});return;}
const r=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range||''),begin=r?+r[1]:0,end=r&&r[2]?+r[2]:payload.length-1,probe=r&&begin===0&&end===0;
res.writeHead(r?206:200,{'Content-Length':end-begin+1,ETag:'"stable"',...(r?{'Content-Range':`bytes ${begin}-${end}/${payload.length}`}:{})});res.flushHeaders();if(req.url==='/stall'&&!probe)return;let at=begin,timer;function pump(){if(res.destroyed)return;const next=Math.min(end+1,at+65536);res.write(payload.subarray(at,next));at=next;if(at>end)res.end();else timer=setTimeout(pump,5);}res.once('close',()=>clearTimeout(timer));pump();};
const server=http.createServer(handler),tls=https.createServer({key:fs.readFileSync(path.join(base,'tls-fixture/key.pem')),cert:fs.readFileSync(path.join(base,'tls-fixture/cert.pem'))},handler);
for(const srv of [server,tls])srv.on('connection',s=>{sockets.add(s);s.on('close',()=>sockets.delete(s));});tls.on('tlsClientError',()=>{});let origin;
function execute(folder,spec,timeout=20000){fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,'input.json'),JSON.stringify(spec));return new Promise((resolve,reject)=>{const p=spawn(exe,[path.join(folder,'input.json')],{windowsHide:true});let out='',err='';p.stdout.on('data',c=>out+=c);p.stderr.on('data',c=>err+=c);const timer=setTimeout(()=>{p.kill();reject(Error('Test timed out'));},timeout);p.on('error',reject);p.on('close',code=>{clearTimeout(timer);fs.writeFileSync(path.join(folder,'stdout.log'),out);fs.writeFileSync(path.join(folder,'stderr.log'),err);try{resolve({code,...JSON.parse(fs.readFileSync(path.join(folder,'result.json'),'utf8').replace(/^\uFEFF/,''))});}catch(e){reject(e);}});});}
const job=name=>({name:name+'.bin',url:origin+'/file',sha256:sha,connections:8});
async function check(name,fn){try{const detail=await fn();results.push({name,passed:true,detail});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.log('FAIL '+name+': '+e.message);}fs.writeFileSync(path.join(root,'report.json'),JSON.stringify({root,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,results},null,2));}
async function paused(name){const folder=path.join(root,name),r=await execute(folder,{jobs:[job(name)],cancelAfterBytes:131072});assert.equal(r.jobs[0].status,'Paused');assert.ok(r.jobs[0].received>0&&r.jobs[0].received<payload.length);return folder;}
function complete(r){assert.equal(r.code,0);assert.equal(r.jobs[0].status,'Complete',r.jobs[0].error);assert.equal(r.jobs[0].sha256,sha);}
function state(folder){const file=path.join(folder,'state/state.json');return {file,value:JSON.parse(fs.readFileSync(file,'utf8'))};}
function partFiles(folder){const s=state(folder),dir=path.join(folder,'state/parts',s.value.Downloads[0].Id);return fs.readdirSync(dir).filter(n=>n.endsWith('.part')).map(n=>path.join(dir,n));}
(async()=>{await Promise.all([new Promise(r=>server.listen(0,'127.0.0.1',r)),new Promise(r=>tls.listen(0,'127.0.0.1',r))]);origin='http://127.0.0.1:'+server.address().port;console.log('Evidence '+root);
 await check('one MiB POST body and exact echoed response',async()=>{const r=await execute(path.join(root,'post'),{jobs:[{...job('post'),url:origin+'/post'}],postBytes:1048576});assert.equal(r.jobs[0].status,'Complete',r.jobs[0].error);assert.equal(r.jobs[0].size,1048576);return r;});
 await check('cancel POST awaiting response headers',async()=>{const r=await execute(path.join(root,'post-stall'),{jobs:[{...job('post-stall'),url:origin+'/post-stall'}],postBytes:1048576,cancelAfterMs:600},6000);assert.equal(r.jobs[0].status,'Paused');assert.ok(r.cancelLatencySeconds<2);return r;});
 await check('untrusted HTTPS certificate is rejected',async()=>{const r=await execute(path.join(root,'tls'),{jobs:[{...job('tls'),url:'https://localhost:'+tls.address().port+'/file'}]});assert.equal(r.jobs[0].status,'Failed');assert.match(r.jobs[0].error,/12175/);assert.equal(r.jobs[0].exists,false);return r;});
 await check('sixteen simultaneous stalled transfers cancel cleanly',async()=>{const jobs=Array.from({length:16},(_,i)=>({...job('stall-'+i),url:origin+'/stall'}));const r=await execute(path.join(root,'multi-stall'),{jobs,concurrent:true,cancelAfterMs:600},10000);assert.ok(r.cancelLatencySeconds<2);assert.ok(r.jobs.every(j=>j.status==='Paused'&&!j.exists));return {cancelLatency:r.cancelLatencySeconds,handles:r.finalHandles,initialHandles:r.initialHandles};});
 for(const mutation of ['overlap','missing','oversized'])await check(mutation+' partial data recovers exactly',async()=>{const folder=await paused(mutation),s=state(folder);if(mutation==='overlap'){s.value.Downloads[0].Segments[1].Start--;fs.writeFileSync(s.file,JSON.stringify(s.value));}else{const p=partFiles(folder)[0];assert.ok(path.resolve(p).startsWith(path.resolve(folder)+path.sep));if(mutation==='missing')fs.unlinkSync(p);else fs.writeFileSync(p,Buffer.alloc(2*1048576,123));}const r=await execute(folder,{jobs:[],resume:true});complete(r);return r;});
 await check('modified partial bytes fail expected SHA-256',async()=>{const folder=await paused('corrupt-part'),p=partFiles(folder)[0],b=fs.readFileSync(p);b[0]^=255;fs.writeFileSync(p,b);const r=await execute(folder,{jobs:[],resume:true});assert.equal(r.jobs[0].status,'Failed');assert.match(r.jobs[0].error,/SHA-256 mismatch/);assert.equal(r.jobs[0].exists,false);return r;});
 for(const mutation of ['malformed-json','duplicate-id'])await check(mutation+' state is rejected and preserved',async()=>{const folder=await paused(mutation),s=state(folder);let damaged;if(mutation==='malformed-json')damaged='{broken';else{s.value.Downloads[0].Segments[1].Index=s.value.Downloads[0].Segments[0].Index;damaged=JSON.stringify(s.value);}fs.writeFileSync(s.file,damaged);const r=await execute(folder,{jobs:[],resume:true});assert.equal(r.code,1);assert.ok(r.fatal);assert.equal(fs.readFileSync(s.file,'utf8'),damaged);return {error:r.fatal};});
 await check('unwritable destination fails without destroying it',async()=>{const folder=path.join(root,'bad-destination');fs.mkdirSync(folder,{recursive:true});fs.writeFileSync(path.join(folder,'downloads'),'keep');const r=await execute(folder,{jobs:[job('bad-destination')]});assert.equal(r.jobs[0].status,'Failed');assert.equal(fs.readFileSync(path.join(folder,'downloads'),'utf8'),'keep');return r;});
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>{for(const s of sockets)s.destroy();server.close();tls.close();console.log(JSON.stringify({root,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length}));if(results.some(r=>!r.passed))process.exitCode=1;});
