'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto'),{spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const stage=__dirname,root=path.resolve(process.argv[2]),project=process.env.UDM_PROJECT||path.resolve(__dirname,'..'),release=process.env.UDM_TEST_RELEASE||path.join(project,'release-native'),ff=path.join(release,'tools/ffmpeg.exe'),fp=path.join(release,'tools/ffprobe.exe'),state=path.join(root,'state/state.json'),tag='adapt'+crypto.randomBytes(8).toString('hex'),hostName='com.udm.adaptfixture'+Date.now(),registry='HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\'+hostName;
const results=[],traffic=[],hash=b=>crypto.createHash('sha256').update(b).digest('hex'),wait=ms=>new Promise(r=>setTimeout(r,ms));let browser,worker,page,probe,server,base,registered=false,version='old',serial=0;
function pass(name,detail={}){results.push({passed:true,name,...detail});console.log('PASS '+name);}
async function until(fn,ms=45000){const deadline=Date.now()+ms;while(Date.now()<deadline){const v=await fn();if(v)return v;await wait(100);}throw Error('Adaptive refresh fixture timed out');}
const run=args=>execFileSync(ff,['-hide_banner','-loglevel','error','-nostdin',...args],{windowsHide:true,maxBuffer:32e6});
const jobs=()=>{try{return JSON.parse(fs.readFileSync(state)).Downloads;}catch{return [];}};
async function command(action,id){const n=++serial;fs.writeFileSync(path.join(root,n+'.command.json.tmp'),JSON.stringify({action,id}));fs.renameSync(path.join(root,n+'.command.json.tmp'),path.join(root,n+'.command.json'));if(action==='quit')return;const out=path.join(root,n+'.reply.json');const result=await until(()=>fs.existsSync(out)&&JSON.parse(fs.readFileSync(out)),90000);assert.equal(result.ok,true,result.error);return result;}
async function clickAX(name){const session=await browser.newCDPSession(page);try{const node=await until(async()=>{const t=await session.send('Accessibility.getFullAXTree');return t.nodes.find(n=>!n.ignored&&n.role?.value==='button'&&name(n.name?.value||''));});const {model}=await session.send('DOM.getBoxModel',{backendNodeId:node.backendDOMNodeId}),q=model.content;await page.mouse.click((q[0]+q[2])/2,(q[1]+q[5])/2);}finally{await session.detach();}}
async function panel(kind){await page.goto(base+'/'+kind);await page.waitForFunction(()=>document.querySelector('video')?.videoHeight===360&&document.body.dataset.ready==='yes');await until(()=>page.locator('[id^="udm-video-panel-"]').count());await clickAX(n=>n==='Download this video with UDM');await clickAX(n=>n.includes('MP4 · 360p'));}
(async()=>{
 assert(!fs.existsSync(root),'Use a new isolated fixture directory');fs.mkdirSync(root,{recursive:true});const media=path.join(root,'media');fs.mkdirSync(media);
 run(['-y','-f','lavfi','-i','testsrc2=size=640x360:rate=10:duration=6','-f','lavfi','-i','sine=frequency=440:duration=6','-c:v','libx264','-preset','ultrafast','-g','20','-pix_fmt','yuv420p','-c:a','aac',path.join(media,'sample.mp4')]);
 run(['-y','-i',path.join(media,'sample.mp4'),'-c','copy','-hls_time','2','-hls_playlist_type','vod',path.join(media,'index.m3u8')]);
 const sample=fs.readFileSync(path.join(media,'sample.mp4')),split=Math.floor(sample.length/3),ranges=[[0,split-1],[split,2*split-1],[2*split,sample.length-1]];
 server=http.createServer((req,res)=>{
  const u=new URL(req.url,'http://localhost');res.setHeader('Cache-Control','no-store');traffic.push({url:u.pathname,range:req.headers.range||'',phase:version,time:Date.now()});
  if(['/hls','/dash'].includes(u.pathname)){res.setHeader('Content-Type','text/html');res.end(`<!doctype html><title>UDM ${u.pathname.slice(1)} refresh fixture</title><style>body{margin:55px;background:#eef2f6;font:16px Arial}video{width:640px}</style><h1>Recorded video link recovery</h1><video autoplay muted loop controls></video><script>(async()=>{const v=document.querySelector('video');v.src=URL.createObjectURL(new Blob([await fetch('/preview.mp4').then(r=>r.arrayBuffer())],{type:'video/mp4'}));await fetch('/master.${u.pathname==='/hls'?'m3u8':'mpd'}').then(r=>r.text());document.body.dataset.ready='yes';await v.play();})();</script>`);return;}
  if(u.pathname==='/master.m3u8'){res.setHeader('Content-Type','application/vnd.apple.mpegurl');res.end('#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=800000,RESOLUTION=640x360,CODECS="avc1.42c01e,mp4a.40.2"\n/media/'+version+'/index.m3u8\n');return;}
  if(u.pathname==='/master.mpd'){res.setHeader('Content-Type','application/dash+xml');res.end('<MPD type="static" mediaPresentationDuration="PT6S"><Period><AdaptationSet mimeType="video/mp4"><Representation id="video" height="360" bandwidth="800000"><BaseURL>/media/'+version+'/</BaseURL><SegmentList>'+ranges.map(([a,b])=>'<SegmentURL media="sample.mp4" mediaRange="'+a+'-'+b+'"/>').join('')+'</SegmentList></Representation></AdaptationSet></Period></MPD>');return;}
  const match=/^\/media\/(old|fresh)\/(index\.m3u8|index\d+\.ts|sample\.mp4)$/.exec(u.pathname);let name=u.pathname==='/preview.mp4'?'sample.mp4':match?.[2];if(!name){res.writeHead(404).end();return;}
  const range=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range||'');if(match?.[1]==='old'&&((name.endsWith('.ts')&&name!=='index0.ts')||(name==='sample.mp4'&&range&&+range[1]>0))){res.writeHead(403).end();return;}
  const buffer=fs.readFileSync(path.join(media,name)),a=range?+range[1]:0,b=range&&range[2]?+range[2]:buffer.length-1;
  res.writeHead(range?206:200,{'Content-Length':b-a+1,'Content-Type':name.endsWith('m3u8')?'application/vnd.apple.mpegurl':name.endsWith('ts')?'video/mp2t':'video/mp4',ETag:'"same-content"',...(range?{'Content-Range':`bytes ${a}-${b}/${buffer.length}`}:{})});res.end(buffer.subarray(a,b+1));
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;
 const env={...process.env,UDM_INSTANCE_TAG:tag};probe=spawn(path.join(release,'AdaptiveRefreshProbe.exe'),[root],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});let log='';probe.stdout.on('data',b=>log+=b);probe.stderr.on('data',b=>log+=b);await until(()=>{if(probe.exitCode!==null)throw Error(log);return fs.existsSync(path.join(root,'ready.json'));});
 const ext=path.join(root,'extension');fs.cpSync(path.join(project,'browser/chromium'),ext,{recursive:true});const bg=path.join(ext,'background.js');fs.writeFileSync(bg,fs.readFileSync(bg,'utf8').replace("'com.udm.download_manager'",JSON.stringify(hostName)));
 const hostManifest=path.join(root,'host.json');fs.writeFileSync(hostManifest,JSON.stringify({name:hostName,description:'Isolated UDM adaptive recovery test',path:path.join(release,'Udm.NativeHost.exe'),type:'stdio',allowed_origins:['chrome-extension://'+fs.readFileSync(path.join(project,'browser/extension-id.txt'),'utf8').trim()+'/']}));let exists=false;try{execFileSync('reg.exe',['query',registry],{windowsHide:true,stdio:'ignore'});exists=true;}catch{}assert(!exists);execFileSync('reg.exe',['add',registry,'/ve','/t','REG_SZ','/d',hostManifest,'/f'],{windowsHide:true,stdio:'ignore'});registered=true;
 browser=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'msedge',headless:true,ignoreDefaultArgs:['--disable-extensions'],env,viewport:{width:1100,height:820},args:['--enable-unsafe-extension-debugging','--autoplay-policy=no-user-gesture-required']});const cdp=await browser.browser().newBrowserCDPSession();await cdp.send('Extensions.loadUnpacked',{path:ext});worker=browser.serviceWorkers()[0]||await browser.waitForEvent('serviceworker');const identity=await worker.evaluate(()=>nativeRequest({action:'diagnostics'}));assert.equal(identity.version,process.env.UDM_EXPECT_NATIVE||'0.85.0');assert.equal(path.resolve(identity.dataDirectory).toLowerCase(),path.join(root,'state').toLowerCase());pass('Edge reaches the expected native version through real native messaging in an isolated catalog',{nativeVersion:identity.version});page=browser.pages()[0]||await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const kind of ['hls','dash']){
  version='old';const count=jobs().length;await panel(kind);const j=await until(()=>jobs().find(j=>j.Url===base+'/'+kind));assert.equal(j.Status,'Awaiting confirmation');const failed=await command('download',j.Id);assert.equal(failed.status,'Failed');assert.match(failed.error,/403/);const cache=path.join(j.MediaFolder||path.join(root,'state/media',j.Id),'adaptive'),cached=path.join(cache,'0.part'),digest=hash(fs.readFileSync(cached)),receipt=fs.readFileSync(path.join(cache,'completed.json'),'utf8');assert.equal(Object.keys(JSON.parse(receipt)).length,1);pass(kind+' expired download keeps one real completed segment after HTTP 403');
  await command('arm',j.Id);version='fresh';await panel(kind);await until(()=>jobs().find(x=>x.Id===j.Id)?.ProtectedRefreshOffer);assert.equal(jobs().length,count+1);assert.equal(jobs().find(x=>x.Id===j.Id).ProtectedAdaptive,j.ProtectedAdaptive);const ax=await browser.newCDPSession(page);await until(async()=>{const t=await ax.send('Accessibility.getFullAXTree');return t.nodes.some(n=>n.name?.value?.includes('Fresh streams received. Review Refresh media session'));});await page.screenshot({path:path.join(root,kind+'-refresh-panel.png')});await ax.detach();pass(kind+' trusted Edge panel click stages the replacement on the existing download and displays review guidance');
  const applied=await command('apply',j.Id);assert.equal(applied.pending,true);assert.equal(applied.status,'Paused');assert.equal(hash(fs.readFileSync(cached)),digest);assert.equal(fs.readFileSync(path.join(cache,'completed.json'),'utf8'),receipt);assert.equal(jobs().find(x=>x.Id===j.Id).FileName,j.FileName);pass(kind+' applying the candidate preserves filename and saved bytes until validation');
  const start=traffic.length,finished=await command('download',j.Id);assert.equal(finished.status,'Complete',finished.error);assert.equal(finished.pending,false);assert.equal(jobs().length,count+1);const requests=traffic.slice(start).filter(x=>x.url.includes('/media/fresh/'));assert.equal(requests.length,3);assert(requests[0].url.endsWith(kind==='hls'?'index0.ts':'sample.mp4'));if(kind==='dash')assert.equal(requests[0].range,`bytes=0-${split-1}`);const info=JSON.parse(execFileSync(fp,['-v','error','-show_streams','-show_format','-of','json',finished.target],{windowsHide:true}));assert(info.streams.some(s=>s.codec_type==='video'&&s.height===360));assert(info.streams.some(s=>s.codec_type==='audio'));assert(Math.abs(Number(info.format.duration)-6)<.4);const pixels=file=>run(['-i',file,'-map','0:v:0','-f','hash','-hash','sha256','-']).toString().trim();assert.equal(pixels(finished.target),pixels(path.join(media,'sample.mp4')));pass(kind+' refresh verifies retained bytes first and publishes the same decoded video with audio',{requests:requests.length,filename:j.FileName,duration:info.format.duration});
 }
 assert.deepEqual(errors,[]);pass('Recovery pages have no script errors');await command('quit');await until(()=>probe.exitCode!==null);assert.equal(probe.exitCode,0);fs.writeFileSync(path.join(root,'probe.log'),log);
})().catch(e=>{console.error(e);results.push({passed:false,error:e.stack});process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(probe&&probe.exitCode===null)probe.kill();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}if(registered)execFileSync('reg.exe',['delete',registry,'/f'],{windowsHide:true,stdio:'ignore'});if(fs.existsSync(root))fs.writeFileSync(path.join(root,'results.json'),JSON.stringify({scope:'Isolated Edge UI + real native host + same C++ recovery/transfer objects; synthetic clear recorded HLS/DASH. Desktop review is invoked by the test harness, not a rendered native-dialog click.',passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,registryRemoved:registered,results},null,2));});
