'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),M=require('../browser/chromium/media.js');let passed=0;
const check=(name,fn)=>{fn();++passed;console.log('PASS '+name);},base='https://cdn.test/master.m3u8';
const master='#EXTM3U\n#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="a",NAME="English",LANGUAGE="en",DEFAULT=YES,URI="en.m3u8"\n#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="a",NAME="Español",LANGUAGE="es",AUTOSELECT=YES,URI="es.m3u8"\n#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="other",NAME="Commentary",LANGUAGE="en",URI="other.m3u8"\n#EXT-X-STREAM-INF:BANDWIDTH=1200000,RESOLUTION=640x360,CODECS="avc1.42c01e,mp4a.40.2",AUDIO="a"\nvideo.m3u8';
const parsed=M.hls(master,base),audio=M.hlsAudio(parsed,parsed.variants[0]);
check('HLS audio catalog includes only the quality’s declared group',()=>{assert.equal(audio.length,2);assert.equal(audio[1].url,'https://cdn.test/es.m3u8');assert.match(audio[1].label,/Español \(es\)/);assert.equal(audio[0].default,true);assert.equal(audio[1].default,false);});
check('HLS in-band default audio remains selectable beside an external rendition',()=>{const p=M.hls(master.replace(',URI="en.m3u8"',''),base),a=M.hlsAudio(p,p.variants[0]);assert.equal(a[0].url,'');assert.equal(a[0].default,true);assert.equal(a[1].url,'https://cdn.test/es.m3u8');});
check('HLS defaults prefer declared default then autoselect then source order',()=>{let p=M.hls(master.replace('DEFAULT=YES','DEFAULT=NO'),base);assert.equal(M.hlsAudio(p,p.variants[0])[1].default,true);p=M.hls(master.replace('DEFAULT=YES','DEFAULT=NO').replace('AUTOSELECT=YES','AUTOSELECT=NO'),base);assert.equal(M.hlsAudio(p,p.variants[0])[0].default,true);});
for(const [name,text,pattern] of [
 ['missing group',master.replace('AUDIO="a"','AUDIO="absent"'),/missing/],
 ['duplicate names',master.replace('NAME="Español"','NAME="English"'),/Ambiguous/],
 ['multiple defaults',master.replace('AUTOSELECT=YES','DEFAULT=YES'),/Ambiguous/],
 ['ambiguous in-band audio',master.replace(',URI="en.m3u8"','').replace(',URI="es.m3u8"',''),/in-band/],
 ['invalid language',master.replace('LANGUAGE="es"','LANGUAGE="es;option"'),/description/]
])check('HLS rejects '+name,()=>{const p=M.hls(text,base);assert.throws(()=>M.hlsAudio(p,p.variants[0]),pattern);});
const dash='<MPD type="static" mediaPresentationDuration="PT8S"><Period><AdaptationSet mimeType="video/mp4"><Representation id="v" height="360"><BaseURL>video.mp4</BaseURL></Representation></AdaptationSet><AdaptationSet mimeType="audio/mp4" lang="es"><Label>Español</Label><Representation id="a" bandwidth="128000"><BaseURL>es.m4a</BaseURL></Representation></AdaptationSet><AdaptationSet mimeType="audio/mp4" lang="en"><Role value="main"/><Label>English</Label><Representation id="a" bandwidth="64000"><BaseURL>en.m4a</BaseURL></Representation></AdaptationSet></Period></MPD>';
check('DASH keeps both languages and prefers a main role before bitrate',()=>{const c=M.dash(dash,base)[0];assert.equal(c.audioOptions.length,2);assert.equal(c.audioOptions[0].language,'en');assert.equal(c.audioOptions[1].language,'es');assert.equal(c.plan.tracks[1].language,'en');assert.notEqual(c.audioOptions[0].key,c.audioOptions[1].key);});
check('DASH keeps description/commentary labels',()=>{const c=M.dash(dash.replace('<Label>Español</Label>','<Role value="commentary"/>'),base)[0];assert.match(c.audioOptions[1].label,/commentary/);});
check('HLS audio choices are bounded',()=>{const p=structuredClone(parsed);p.audio=Array.from({length:33},(_,i)=>({...p.audio[0],NAME:'Audio '+i,DEFAULT:'NO'}));assert.throws(()=>M.hlsAudio(p,p.variants[0]),/oversized/);});
(async()=>{
 const session={},calls=[],fetches=[],map=new Map([[base,master],['https://cdn.test/video.m3u8','#EXTM3U\nv.ts\n#EXT-X-ENDLIST'],['https://cdn.test/en.m3u8','#EXTM3U\nen.ts\n#EXT-X-ENDLIST'],['https://cdn.test/es.m3u8','#EXTM3U\nes.ts\n#EXT-X-ENDLIST'],['https://cdn.test/master.mpd',dash]]);
 let player={page:'https://player.test/watch',token:'token-1',stamp:'1',current:'blob:https://player.test/movie',sources:[],height:360,width:640,videoCount:1,title:'Movie',encrypted:false,manifests:[{url:base,type:'application/vnd.apple.mpegurl',page:'https://player.test/watch',time:Date.now(),text:master}]};
 const event=()=>({addListener(){}}),api={storage:{local:{get:async()=>({settings:{}})},session:{get:async k=>({[k]:session[k]}),set:async v=>Object.assign(session,v),remove:async()=>{}}},tabs:{get:async id=>({id,url:player.page,incognito:false})},scripting:{executeScript:async()=>[{frameId:0,documentId:'doc',result:structuredClone(player)}]},permissions:{contains:async()=>true,onAdded:event(),onRemoved:event()},runtime:{onStartup:event(),sendNativeMessage:async(_,m)=>{calls.push(m);return {ok:true};}}};
 const sandbox={navigator:{userAgent:'test'},UdmMedia:M,URL,Date,crypto,AbortController,TextEncoder,TextDecoder,setTimeout,clearTimeout,fetch:async u=>{fetches.push(u);assert(map.has(u),u);return {ok:true,url:u,body:new ReadableStream({start(c){c.enqueue(new TextEncoder().encode(map.get(u)));c.close();}})};}};
 vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../browser/chromium/sites.js'),'utf8')+'\nglobalThis.sites=UdmSites;',sandbox);sandbox.sites.install(api);
 const sender={tab:{id:9},frameId:0,documentId:'doc',url:player.page},message={page:player.page,token:player.token};
 let catalog=await sandbox.sites.list(message,sender),choice=catalog.choices.find(c=>c.container==='mp4');
 check('Public audio offers contain labels/keys but no playback URLs',()=>{assert.equal(choice.audioOptions.length,2);assert.match(choice.label,/2 audio tracks/);assert(choice.audioOptions.every(x=>Object.keys(x).sort().join(',')==='default,key,label'));});
 await sandbox.sites.download({...message,key:choice.key,audioKey:choice.audioOptions[1].key},sender);
 check('Selected HLS audio alone reaches the native plan',()=>{const p=calls.at(-1).plan;assert.equal(p.tracks[1].segments[0].url,'https://cdn.test/es.ts');assert.equal(p.audioName,'Español');assert.equal(p.audioLanguage,'es');assert.equal(p.audioExpected,true);assert(!fetches.includes('https://cdn.test/en.m3u8'));});
 await sandbox.sites.download({...message,key:choice.key},sender);check('Omitted audio selection preserves declared default behavior',()=>assert.equal(calls.at(-1).plan.tracks[1].segments[0].url,'https://cdn.test/en.ts'));
 let before=calls.length,requests=fetches.length;await assert.rejects(()=>sandbox.sites.download({...message,key:choice.key,audioKey:'https://evil.invalid/x'},sender),/no longer/);check('Invalid audio selection makes no fetch or native handoff',()=>{assert.equal(calls.length,before);assert.equal(fetches.length,requests);});
 player.manifests=[{url:'https://cdn.test/master.mpd',type:'application/dash+xml',page:player.page,time:Date.now(),text:dash}];catalog=await sandbox.sites.list(message,sender);choice=catalog.choices[0];await sandbox.sites.download({...message,key:choice.key,audioKey:choice.audioOptions[1].key},sender);
 check('Selected DASH audio replaces the default representation',()=>{const p=calls.at(-1).plan;assert.equal(p.tracks.length,2);assert.equal(p.tracks[1].segments[0].url,'https://cdn.test/es.m4a');assert.equal(p.audioLanguage,'es');});
 before=calls.length;player.stamp='2';await assert.rejects(()=>sandbox.sites.download({...message,key:choice.key,audioKey:choice.audioOptions[1].key},sender),/changed/);check('Navigation invalidates the selected audio with its video offer',()=>assert.equal(calls.length,before));
 player.manifests=[{url:base,type:'application/vnd.apple.mpegurl',page:player.page,time:Date.now(),text:master.replace(',URI="en.m3u8"','')}];catalog=await sandbox.sites.list(message,sender);choice=catalog.choices[0];await sandbox.sites.download({...message,key:choice.key},sender);
 check('In-band audio selection retains one input while requiring audio output',()=>{const p=calls.at(-1).plan;assert.equal(p.tracks.length,1);assert.equal(p.audioExpected,true);assert.equal(p.audioLanguage,'en');});

 player.manifests=[{url:base,type:'application/vnd.apple.mpegurl',page:player.page,time:Date.now(),text:master}];catalog=await sandbox.sites.list(message,sender);choice=catalog.choices.find(c=>c.container==='mp4');fetches.length=0;
 await sandbox.sites.download({...message,key:choice.key,audioKey:choice.audioOptions[1].key,output:'audio'},sender);
 check('HLS audio-only excludes video requests and sends a single M4A audio track',()=>{const p=calls.at(-1).plan;assert.equal(p.audioOnly,true);assert.equal(p.container,'m4a');assert.equal(p.height,0);assert.equal(p.tracks.length,1);assert.equal(p.tracks[0].kind,'audio');assert.equal(p.tracks[0].segments[0].url,'https://cdn.test/es.ts');assert(!fetches.includes('https://cdn.test/video.m3u8'));});
 before=calls.length;await assert.rejects(()=>sandbox.sites.download({...message,key:choice.key,output:'exec'},sender),/output/);check('Unrecognized output modes cannot reach the desktop',()=>assert.equal(calls.length,before));
 const subMaster=master.replace('#EXT-X-STREAM-INF:','#EXT-X-MEDIA:TYPE=SUBTITLES,GROUP-ID="s",NAME="Español",LANGUAGE="es",URI="captions.m3u8"\n#EXT-X-STREAM-INF:').replace('AUDIO="a"','AUDIO="a",SUBTITLES="s"');
 const sp=M.hls(subMaster,base);check('HLS subtitle catalog is bound to the variant group',()=>{const a=M.hlsSubtitles(sp,sp.variants[0]);assert.equal(a.length,1);assert.equal(a[0].url,'https://cdn.test/captions.m3u8');assert.equal(a[0].language,'es');assert.deepEqual(M.hlsSubtitles(sp,{subtitleGroup:''}),[]);});
 check('HLS subtitle timelines preserve fractional segment durations',()=>{const p=M.hls('#EXTM3U\n#EXTINF:2.5,\na.vtt\n#EXTINF:3,\nb.vtt\n#EXT-X-ENDLIST',base);assert.deepEqual(p.segments.map(s=>s.timeline),[0,2.5]);});
 for(const duration of ['-1','NaN','Infinity','86401'])check('Invalid HLS subtitle duration '+duration+' is rejected',()=>assert.throws(()=>M.hls('#EXTM3U\n#EXTINF:'+duration+',\na.vtt\n#EXT-X-ENDLIST',base),/duration/));
 player.manifests=[{url:base,type:'application/vnd.apple.mpegurl',page:player.page,time:Date.now(),text:subMaster}];map.set('https://cdn.test/captions.m3u8','#EXTM3U\n#EXTINF:4,\nfirst.vtt\n#EXTINF:4,\nsecond.vtt\n#EXT-X-ENDLIST');catalog=await sandbox.sites.list(message,sender);choice=catalog.choices.find(c=>c.container==='mp4');
 check('Public subtitle offers contain no signed media URLs',()=>{assert.equal(choice.subtitleOptions.length,1);assert.deepEqual(Object.keys(choice.subtitleOptions[0]).sort(),['key','label']);assert(!catalog.choices.find(c=>c.container==='ts').subtitleOptions);});
 await sandbox.sites.download({...message,key:choice.key,subtitleKey:choice.subtitleOptions[0].key},sender);check('Selected subtitles join the native video/audio plan',()=>{const p=calls.at(-1).plan;assert.equal(p.tracks.length,3);assert.equal(p.tracks[2].kind,'subtitle');assert.equal(p.tracks[2].segments[1].timeline,4);assert.equal(p.subtitleLanguage,'es');});
 before=calls.length;requests=fetches.length;await assert.rejects(()=>sandbox.sites.download({...message,key:choice.key,subtitleKey:'https://evil.test/a.vtt'},sender),/no longer/);await assert.rejects(()=>sandbox.sites.download({...message,key:choice.key,subtitleKey:choice.subtitleOptions[0].key,output:'audio'},sender),/MP4/);check('Invalid and audio-only subtitle selections fail before any fetch',()=>{assert.equal(calls.length,before);assert.equal(fetches.length,requests);});
 const subDash=dash.replace('</Period>','<AdaptationSet mimeType="text/vtt" lang="es"><Label>Español subtitles</Label><Representation id="s"><BaseURL>captions.vtt</BaseURL></Representation></AdaptationSet></Period>');
 player.manifests=[{url:'https://cdn.test/master.mpd',type:'application/dash+xml',page:player.page,time:Date.now(),text:subDash}];catalog=await sandbox.sites.list(message,sender);choice=catalog.choices[0];await sandbox.sites.download({...message,key:choice.key,subtitleKey:choice.subtitleOptions[0].key},sender);
 check('Standalone DASH WebVTT retains its selected language',()=>{const p=calls.at(-1).plan;assert.equal(p.tracks[2].segments[0].url,'https://cdn.test/captions.vtt');assert.equal(p.subtitleLanguage,'es');});
 await sandbox.sites.download({...message,key:choice.key,output:'audio',audioKey:choice.audioOptions[1].key},sender);check('DASH audio-only plan has no video or subtitle URLs',()=>{const p=calls.at(-1).plan;assert.equal(p.tracks.length,1);assert.equal(p.tracks[0].kind,'audio');assert.equal(p.tracks[0].segments[0].url,'https://cdn.test/es.m4a');});
 console.log('ALL '+passed+' AUDIO TRACK CHECKS PASSED');
})().catch(e=>{console.error(e);process.exitCode=1;});
