'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const {harness}=require('./browser.test.cjs');
let count=0,failed=0;const tick=()=>new Promise(r=>setImmediate(r));
async function test(name,run){try{await run();count++;console.log('PASS '+name);}catch(e){failed++;console.error('FAIL '+name+': '+e.message);}}
async function bounded(p){return Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(Error('Operation stalled')),200))]);}
const item={id:99,url:'https://example.test/file.zip',filename:'file.zip'};
function controls(store={},sent=[],failure=null){
 const events={},opened=[];
 const api={runtime:{getURL:p=>'chrome-extension://fixture/'+p},storage:{session:{get:async k=>({[k]:structuredClone(store[k])}),set:async v=>Object.assign(store,structuredClone(v)),remove:async k=>{delete store[k];}}},tabs:{get:async id=>({id,url:'https://page.test/watch'}),sendMessage:async()=>{},create:async t=>opened.push(t),onRemoved:{addListener:f=>events.removed=f},onActivated:{addListener:f=>events.activated=f}},contextMenus:{update:async()=>{},create(){}},scripting:{executeScript:async()=>[{frameId:0,documentId:'fixture-document',result:[{url:'https://files.test/one.zip',name:'One',page:'https://page.test/watch'},{url:'https://files.test/two.zip',name:'Two',page:'https://page.test/watch'}]}]}};
 const box={URL,crypto:webcrypto,console,structuredClone,TextEncoder};vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(__dirname,'../browser/chromium/browser-controls.js'),'utf8'),box);
 const instance=box.UdmBrowserControls.create(api,async m=>{sent.push(m);if(failure)await failure(m);return {ok:true};},()=>{});
 return {instance,api,events,opened,sent,store,sender:token=>({url:api.runtime.getURL('links.html')+'#'+token}),token:()=>opened.at(-1).url.split('#')[1]};
}
(async()=>{
 await test('Accepted downloads still cancel in-browser when status storage fails',async()=>{const h=await harness({capture:true});h.api.storage.local.set=async()=>{throw Error('Storage unavailable');};await bounded(h.events.download(item));assert.deepEqual(h.calls.map(c=>c[0]),['pause','native','cancel']);});
 await test('Accepted downloads do not wait for a stalled badge update',async()=>{const h=await harness({capture:true});h.api.action.setBadgeText=()=>new Promise(()=>{});await bounded(h.events.download(item));assert.deepEqual(h.calls.map(c=>c[0]),['pause','native','cancel']);});
 await test('Failed handoffs release browser downloads even if error reporting stalls',async()=>{const h=await harness({capture:true},true);h.api.storage.local.set=()=>new Promise(()=>{});await bounded(h.events.download(item));assert.equal(h.calls.at(-1)[0],'resume');});
 await test('A cancellation error after desktop acceptance never resumes a duplicate transfer',async()=>{const h=await harness({capture:true});h.api.downloads.cancel=async()=>{throw Error('Browser cancellation failed');};await bounded(h.events.download(item));assert(!h.calls.some(c=>c[0]==='resume'));assert.match(h.store.lastError||'',/accepted|added/i);});
 await test('Selected-link partial failure reports exactly how many downloads were accepted',async()=>{const h=await harness();let n=0;h.api.runtime.sendNativeMessage=async()=>{if(++n===2)throw Error('Host disconnected');return {ok:true,id:'accepted'};};const sender={id:'test-extension',url:'https://page.test/watch',tab:{id:1}};const r=await new Promise(resolve=>h.events.message({action:'selected-links',page:sender.url,urls:['https://files.test/one.zip','https://files.test/two.zip']},sender,resolve));assert.equal(r.ok,false);assert.equal(r.count,1);assert.match(r.error,/Check UDM|check.*download/i);});
 await test('Collected link lists survive background-worker recreation',async()=>{const store={},first=controls(store);await first.instance.collect({id:1,url:'https://page.test/watch'},false);const token=first.token(),second=controls(store);const r=await second.instance.message({action:'batch-list',token},second.sender(token));assert.equal(r.links.length,2);});
 await test('A worker restart during a batch cannot resubmit its uncertain downloads',async()=>{const store={},sent=[];let release;const gate=new Promise(r=>release=r);const first=controls(store,sent,()=>gate);await first.instance.collect({id:1,url:'https://page.test/watch'},false);const token=first.token(),pending=first.instance.message({action:'batch-download',token,indexes:[0,1]},first.sender(token));await tick();const second=controls(store,sent);await assert.rejects(second.instance.message({action:'batch-download',token,indexes:[0,1]},second.sender(token)),/Check UDM|already|uncertain/i);release();await pending;assert.equal(sent.length,2);});
 await test('A completed batch remains consumed after worker recreation',async()=>{const store={},first=controls(store);await first.instance.collect({id:1,url:'https://page.test/watch'},false);const token=first.token();await first.instance.message({action:'batch-download',token,indexes:[0]},first.sender(token));const second=controls(store);await assert.rejects(second.instance.message({action:'batch-download',token,indexes:[0]},second.sender(token)),/expired|consumed/i);});
 await test('A failed submission journal write sends no downloads',async()=>{const c=controls();await c.instance.collect({id:1,url:'https://page.test/watch'},false);c.api.storage.session.set=async()=>{throw Error('Session storage unavailable');};const token=c.token();await assert.rejects(c.instance.message({action:'batch-download',token,indexes:[0]},c.sender(token)),/No downloads were sent/);assert.equal(c.sent.length,0);});
 await test('Only the exact link-selection page can consume a batch',async()=>{const c=controls();await c.instance.collect({id:1,url:'https://page.test/watch'},false);await assert.rejects(c.instance.message({action:'batch-download',token:c.token(),indexes:[0]},{url:c.api.runtime.getURL('links.html-other')}),/selection window/);assert.equal(c.sent.length,0);});
 console.log('AUDIT '+count+' passed, '+failed+' failed');if(failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
