'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),M=require('../browser/chromium/media.js');let count=0;
const tick=()=>new Promise(r=>setImmediate(r));
async function harness(family){let holdNative=false;const handlers={},menus=new Map(),sent=[],local={settings:{},desktopPolicy:{}},session={};const event=name=>({addListener:f=>(handlers[name]??=[]).push(f)});
 const api={runtime:{id:'fixture',onInstalled:event('installed'),onStartup:event('startup'),onMessage:event('message'),getURL:f=>'extension://fixture/'+f,sendNativeMessage:async(_,m)=>{sent.push(m);if(holdNative&&m.action==='preferences-if-running')return new Promise(()=>{});return {ok:true}}},storage:{local:{get:async()=>local,set:async v=>Object.assign(local,v)},session:{get:async()=>session,set:async v=>Object.assign(session,v),remove:async()=>{}},onChanged:event('storage')},contextMenus:{onClicked:event('click'),removeAll:async()=>menus.clear(),create:item=>{assert(!menus.has(item.id));menus.set(item.id,item)},update:async()=>{throw Error('menu rebuilding')}},tabs:{onRemoved:event('removed'),onUpdated:event('updated'),onActivated:event('activated'),query:async()=>[{id:7}],sendMessage:async()=>{},create:async()=>{},get:async()=>({id:7,url:'https://page.test/'})},permissions:{contains:async()=>false},action:{setBadgeText:async()=>{}},downloads:{onCreated:event('download')},webRequest:{onHeadersReceived:event('headers')},scripting:{executeScript:async()=>[]}};
 const box={chrome:api,UdmMedia:M,URL,console,crypto:require('node:crypto'),structuredClone,navigator:{userAgent:'fixture'},setTimeout,clearTimeout};vm.createContext(box);
 for(const file of ['file-recognition.js','browser-controls.js','background.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../browser',family,file),'utf8'),box);
 const emit=async(name,...args)=>{await Promise.all((handlers[name]||[]).map(fn=>fn(...args)));for(let i=0;i<5;i++)await tick()};
 return {menus,sent,emit,local,hold(){holdNative=true;vm.runInContext('policyRead=0',box);},message:value=>new Promise(resolve=>{for(const fn of handlers.message)fn(value,{id:'fixture',tab:{id:7},url:'https://page.test/'},resolve);}),set:async menu=>{local.desktopPolicy.contextMenu=menu;await emit('storage',{desktopPolicy:{newValue:local.desktopPolicy}},'local')}};
}
(async()=>{for(const family of ['chromium','firefox']){const h=await harness(family);await h.emit('installed');assert.deepEqual([...h.menus.keys()].sort(),['udm-all-links','udm-link','udm-selected-links','udm-toggle-tab']);count++;console.log('PASS '+family+' default browser menus create the intended entries');
 await h.set({Link:false,All:true});assert(!h.menus.has('udm-link'));assert(!h.menus.has('udm-selected-links'));assert(h.menus.has('udm-all-links'));await h.emit('click',{menuItemId:'udm-link',linkUrl:'https://cdn.test/file.zip'},{id:7,url:'https://page.test/'});assert.equal(h.sent.length,0);count++;console.log('PASS '+family+' disabling Download with UDM removes link/selection entries and rejects a stale click');
 await h.set({Link:true,All:false});assert(h.menus.has('udm-link'));assert(h.menus.has('udm-selected-links'));assert(!h.menus.has('udm-all-links'));count++;console.log('PASS '+family+' Download all switch is independent');
 await h.emit('click',{menuItemId:'udm-link',linkUrl:'https://cdn.test/file.zip'},{id:7,url:'https://page.test/'});assert.equal(h.sent.filter(x=>x.action==='add').length,1);count++;console.log('PASS '+family+' enabled link action reaches native handoff exactly once');
 await h.emit('click',{menuItemId:'udm-toggle-tab'},{id:7,url:'https://page.test/'});await h.set({Link:false,All:false});await h.emit('startup');assert.equal(h.menus.get('udm-toggle-tab').title,'Enable UDM on this tab');assert.deepEqual([...h.menus.keys()],['udm-toggle-tab']);count++;console.log('PASS '+family+' disabled menu settings survive service startup');
 h.hold();let timer;try{const reply=await Promise.race([h.message({action:'integration-state'}),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Local panel state waited for the unavailable desktop')),250);})]);assert(reply.ok&&reply.disabled);assert(h.sent.some(x=>x.action==='preferences-if-running'));count++;console.log('PASS '+family+' disabled-tab state returns while desktop policy refresh is stalled');}finally{clearTimeout(timer);}
 }console.log('ALL '+count+' BROWSER MENU POLICY CHECKS PASSED');})().catch(e=>{console.error(e);process.exitCode=1});
