'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const M=require('../browser/chromium/media.js'),{UdmFormats:F}=require('../browser/chromium/formats.js');let count=0;
async function test(name,fn){await fn();count++;console.log('PASS '+name);}
const source=(family,file)=>fs.readFileSync(path.join(__dirname,'../browser',family,file),'utf8');
function keys(family){
 let time=5000,deny=false,unavailable=false,tabUrl='https://player.test/watch',prefs={capture:true,forceClick:false,forceKey:'Ctrl+Ins',bypassKey:'Alt+Del'},state={page:tabUrl,timeOrigin:1000,focused:true,visible:true,editing:false,player:{url:'https://cdn.test/file.mp4',playing:true,duration:100,visible:true,ad:false,encrypted:false,stamp:'100',title:'Fixture'}},doc='doc',captured={url:state.player.url,method:'GET',mime:'video/mp4',size:2000000,tabId:7,frameId:0,documentId:'doc',pending:false};const sent=[];
 const api={runtime:{id:'fixture'},tabs:{get:async()=>({id:7,url:tabUrl,incognito:unavailable})},scripting:{executeScript:async()=>[{frameId:0,documentId:doc,result:structuredClone(state)}]}};
 const box={URL,UdmMedia:M,Date:{now:()=>time}};vm.createContext(box);vm.runInContext(source(family,'key-capture.js'),box);
 const controller=box.UdmKeyCapture.create(api,async()=>structuredClone(prefs),async()=>deny,{resolve:()=>captured},async item=>{sent.push(item);if(unavailable)throw Error('lost acknowledgement');return {ok:true};});
 const sender={id:'fixture',tab:{id:7},frameId:0,documentId:'doc',url:tabUrl};
 return {controller,sender,prefs,state,sent,get captured(){return captured},set captured(v){captured=v},advance:n=>time+=n,deny:v=>deny=v,document:v=>doc=v,tab:v=>tabUrl=v,unavailable:v=>unavailable=v,
  hold:async(keys={ctrlKey:true,insertKey:true})=>controller.update({keys},sender),intent:()=>controller.intent(captured),player:()=>controller.player({token:'player-1'},sender)};
}
function sites(family){
 const state={settings:{},desktopPolicy:{}},session={},sent=[];const page='https://player.test/watch',url='https://cdn.test/media.mp4';
 const player={page,timeOrigin:100,token:'player-1',stamp:'100',current:url,sources:[],height:720,width:1280,videoCount:1,duration:100,title:'Fixture',encrypted:false,manifests:[]};
 const api={tabs:{get:async()=>({id:7,url:page})},storage:{local:{get:async()=>state},session:{get:async k=>({[k]:session[k]}),set:async v=>Object.assign(session,v)}},scripting:{executeScript:async()=>[{frameId:0,documentId:'doc',result:structuredClone(player)}]},runtime:{onStartup:{addListener(){}},sendNativeMessage:async(_,m)=>{sent.push(m);return {ok:true}}},permissions:{onAdded:{addListener(){}},onRemoved:{addListener(){}},contains:async()=>true}};
 const box={URL,UdmMedia:M,Date,crypto,navigator:{userAgent:'fixture'},handoff:async v=>{sent.push(v);return {ok:true}}};vm.createContext(box);vm.runInContext(source(family,'sites.js')+'\nglobalThis.sites=UdmSites;',box);box.sites.install(api);
 const message={token:player.token,page},sender={tab:{id:7},frameId:0,documentId:'doc',url:page};
 return {state,session,player,sent,list:()=>box.sites.list(message,sender),download:key=>box.sites.download({...message,key},sender),observe:size=>box.sites.observe({tabId:7,frameId:0,documentId:'doc',documentUrl:page,statusCode:206,url,responseHeaders:[{name:'Content-Type',value:'video/mp4'},{name:'Content-Range',value:'bytes 0-99/'+size},{name:'Content-Length',value:'100'}]})};
}
(async()=>{
 await test('Insert and Delete combinations match exact trusted key state',()=>{assert.equal(M.policy.intent({ctrlKey:true,insertKey:true},{forceKey:'Ctrl+Ins'}),'force');assert.equal(M.policy.intent({altKey:true,deleteKey:true},{bypassKey:'Del+Alt'}),'bypass');assert(!M.policy.key({ctrlKey:true,insertKey:true},'Ctrl'));assert(!M.policy.key({ctrlKey:true},'Ctrl+Ctrl'));assert(!M.policy.key({metaKey:true,insertKey:true},'Ins'));});
 await test('Panel wildcard exceptions match the whole host only',()=>{const p={panelExcluded:['*.example.test','media.*']};assert(M.policy.panelBlocked('https://cdn.example.test/watch',p));assert(!M.policy.panelBlocked('https://example.test/watch',p));assert(!M.policy.panelBlocked('https://example.test.evil/watch',p));assert(M.policy.panelBlocked('https://media.test/watch',p));assert(!M.policy.blocked('https://cdn.example.test/file.zip',p));});
 await test('Minimum-size rules preserve unknown sizes and exact boundary',()=>{const p={panelTypes:{mp4:true,webm:false},panelMinKb:{mp4:1000}};assert(!M.policy.panelAllowed({container:'webm'},p));assert(!M.policy.panelAllowed({container:'mp4',size:1023999},p));assert(M.policy.panelAllowed({container:'mp4',size:1024000},p));assert(M.policy.panelAllowed({container:'mp4'},p));assert(!M.policy.panelAllowed({container:'ts'},p));assert(!M.policy.panelAllowed({container:'mp4'},{panelTypes:{}}));});
 await test('Response size uses the whole resource instead of the first playback range',()=>{assert.equal(M.policy.responseSize({statusCode:206,responseHeaders:[{name:'Content-Range',value:'bytes 0-99/2000000'},{name:'Content-Length',value:'100'}]}),2000000);for(const range of ['bytes 90-40/200','bytes 0-299/200','bytes 0-10/*','bytes 0-5/9007199254740992'])assert.equal(M.policy.responseSize({statusCode:206,responseHeaders:[{name:'Content-Range',value:range}]}),0);assert.equal(M.policy.responseSize({statusCode:200,responseHeaders:[{name:'Content-Length',value:'500'},{name:'Content-Encoding',value:'gzip'}]}),0);});
 await test('Forced web resources can be separated from actual file downloads',()=>{assert(M.policy.webResource({url:'https://a.test/file',mime:'text/html; charset=utf-8'}));assert(M.policy.webResource({url:'https://a.test/file.png'}));assert(!M.policy.webResource({url:'https://a.test/report.pdf',mime:'application/pdf'}));});
 await test('YouTube size includes both known adaptive resources, not a fabricated bitrate estimate',()=>{const url=id=>'https://rr1.googlevideo.com/videoplayback?itag='+id+'&id=resource&expire=4102444800';const snapshot={videoId:'Q3TI27IN7X0',formats:[{id:'137',height:1080,mime:'video/mp4; codecs="avc1"',url:url(137),contentLength:2000000},{id:'140',mime:'audio/mp4; codecs="mp4a"',url:url(140),contentLength:100000}]};assert.equal(F.choices(snapshot,snapshot.videoId)[0].size,2100000);delete snapshot.formats[1].contentLength;assert.equal(F.choices(snapshot,snapshot.videoId)[0].size,0);snapshot.formats[0].muxed=true;assert.equal(F.choices(snapshot,snapshot.videoId)[0].size,2000000);});
 for(const family of ['chromium','firefox']){
  await test(family+' held force works without a click only when enabled',async()=>{const h=keys(family);await h.hold();assert.equal(await h.intent(),'force');h.prefs.forceClick=true;assert.equal(await h.intent(),'');h.prefs.forceClick=false;await h.hold({altKey:true,deleteKey:true});assert.equal(await h.intent(),'bypass');});
  await test(family+' key release and timeout immediately revoke capture authority',async()=>{const h=keys(family);await h.hold();await h.hold(null);assert.equal(await h.intent(),'');await h.hold();h.advance(1501);assert.equal(await h.intent(),'');});
  await test(family+' focus, edit fields, permissions and document changes invalidate held keys',async()=>{for(const alter of [h=>h.state.focused=false,h=>h.state.editing=true,h=>h.state.visible=false,h=>h.prefs.capture=false,h=>h.prefs.captureAllowed=false,h=>h.document('different'),h=>h.state.timeOrigin++,h=>h.tab('https://player.test/next'),h=>h.deny(true),h=>h.captured.documentId='other']){const h=keys(family);await h.hold();alter(h);assert.equal(await h.intent(),'');}});
  await test(family+' invalid keyboard messages cannot establish a lease',async()=>{const h=keys(family);await assert.rejects(()=>h.hold({ctrlKey:'yes'}));await assert.rejects(()=>h.hold({text:'password'}));await assert.rejects(()=>h.controller.update({keys:{ctrlKey:true}},{...h.sender,id:'other-extension'}));assert.equal(await h.intent(),'');});
  await test(family+' request-start gesture survives a browser download-popup focus change',async()=>{const h=keys(family);await h.hold();h.controller.observe({requestId:'download',tabId:7,frameId:0,documentId:'doc',url:h.captured.url});h.captured.requestId='download';await h.hold(null);h.state.focused=false;assert.equal(await h.controller.intent(h.captured,true),'force');assert.equal(await h.intent(),'');h.advance(30001);assert.equal(await h.controller.intent(h.captured,true),'');});
  await test(family+' frozen gesture never transfers to a different request or document',async()=>{const h=keys(family);await h.hold();h.controller.observe({requestId:'download',tabId:7,frameId:0,documentId:'doc',url:h.captured.url});h.captured.requestId='different';await h.hold(null);assert.equal(await h.controller.intent(h.captured,true),'');h.captured.requestId='download';h.document('new');assert.equal(await h.controller.intent(h.captured,true),'');});
  await test(family+' direct player creates one handoff per resource even during overlapping events',async()=>{const h=keys(family);await h.hold();await Promise.all([h.player(),h.player(),h.player()]);assert.equal(h.sent.length,1);assert.equal(h.sent[0].url,h.state.player.url);await h.player();assert.equal(h.sent.length,1);});
  await test(family+' optional automatic player capture still requires browser opt-in',async()=>{const h=keys(family);await h.player();assert.equal(h.sent.length,0);h.prefs.captureWebPlayers=true;await h.player();assert.equal(h.sent.length,1);const off=keys(family);off.prefs.capture=false;off.prefs.captureWebPlayers=true;await assert.rejects(()=>off.player());assert.equal(off.sent.length,0);});
  await test(family+' bypass overrides automatic media capture',async()=>{const h=keys(family);h.prefs.captureWebPlayers=true;await h.hold({altKey:true,deleteKey:true});await h.player();assert.equal(h.sent.length,0);});
  await test(family+' protected, ad, paused, blob and fragmented sources never auto-handoff',async()=>{for(const alter of [h=>h.state.player.encrypted=true,h=>h.state.player.ad=true,h=>h.state.player.playing=false,h=>h.state.player.duration=Infinity,h=>h.state.player.url='https://cdn.test/file.mp4?range=0-100',h=>h.state.player.visible=false,h=>h.state.player.url='blob:https://player.test/a',h=>h.state.player.url='https://cdn.test/seg-1.mp4',h=>h.state.player.url='https://cdn.test/a.m3u8',h=>h.state.player.url='https://rr1.googlevideo.com/videoplayback?itag=137',h=>h.captured.pending=true,h=>h.captured.method='POST',h=>h.captured.mime='text/html',h=>h.captured=null]){const h=keys(family);await h.hold();alter(h);await h.player();assert.equal(h.sent.length,0);}});
  await test(family+' direct capture respects format, size, site and native target switches',async()=>{for(const alter of [h=>h.prefs.panelTypes={mp4:false},h=>h.prefs.panelMinKb={mp4:3000},h=>h.prefs.panelExcluded=['player.*'],h=>h.prefs.excluded=['cdn.test'],h=>h.prefs.panelEnabled=false]){const h=keys(family);await h.hold();alter(h);await h.player();assert.equal(h.sent.length,0);}});
  await test(family+' navigation clears both keys and per-resource receipts',async()=>{const h=keys(family);await h.hold();await h.player();h.controller.clear(7);assert.equal(await h.intent(),'');await h.hold();await h.player();assert.equal(h.sent.length,2);});
  await test(family+' direct media list applies observed whole size and rechecks stale offers',async()=>{const h=sites(family);await h.observe(2000000);let list=await h.list();assert.equal(list.choices.length,1);const key=list.choices[0].key;h.state.desktopPolicy.panelMinKb={mp4:3000};list=await h.list();assert.equal(list.choices.length,0);await assert.rejects(()=>h.download(key));assert.equal(h.sent.length,0);h.state.desktopPolicy.panelMinKb={mp4:1000};list=await h.list();assert.equal(list.choices.length,1);h.state.desktopPolicy.panelTypes={mp4:false};await assert.rejects(()=>h.download(list.choices[0].key),/disabled/);assert.equal(h.sent.length,0);});
  await test(family+' panel host exceptions reject a cached offer before native work',async()=>{const h=sites(family),list=await h.list();h.state.desktopPolicy.panelExcluded=['player.*'];await assert.rejects(()=>h.download(list.choices[0].key),/disabled/);assert.equal(h.sent.length,0);});
 }
 for(const file of ['media.js','content.js','background.js','browser-controls.js','key-capture.js','request-context.js','sites.js','formats.js','capture.js'])assert.equal(source('chromium',file),source('firefox',file));
 await test('Chromium and Firefox share the same implemented capture policy',()=>{});
 console.log('ALL '+count+' BROWSER CUSTOMIZATION CHECKS PASSED');
})().catch(e=>{console.error(e);process.exitCode=1});
