'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
let passed=0;const key='captureOwnershipV1';
function harness(options={}){
 const storage={},calls=[],errors=[];let items=new Map(),status='accepted',nativeError=false,cancelError=false,resumeError=false,writeError=false;
 const api={runtime:{getURL:value=>(options.firefox?'moz-extension://fixture/':'chrome-extension://fixture/')+value},alarms:{create:async()=>{},clear:async()=>true,onAlarm:{addListener(){}}},storage:{local:{get:async k=>({[k]:structuredClone(storage[k])}),set:async value=>{if(writeError)throw Error('storage failed');Object.assign(storage,structuredClone(value));}}},
 downloads:{search:async({id})=>items.has(id)?[items.get(id)]:[],cancel:async id=>{calls.push(['cancel',id]);if(cancelError)throw Error('cancel failed');items.get(id).paused=false;items.get(id).state='interrupted';},resume:async id=>{calls.push(['resume',id]);if(resumeError)throw Error('resume failed');items.get(id).paused=false;items.get(id).state='in_progress';}}};
 const request=async m=>{calls.push(['native',m.action]);if(nativeError)throw Error('lost connection');return m.action==='capture-reconcile'?{ok:true,status,id:'saved'}:{ok:true,id:'saved'};};
 function module(){const ctx=vm.createContext({crypto:crypto.webcrypto,TextEncoder,Uint8Array,Date,...(options.firefox?{browser:api}:{}),module:{exports:{}}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../browser/chromium/capture-recovery.js'),'utf8'),ctx);return ctx.UdmCaptureRecovery.create(api,request,async e=>errors.push(e));}
 function item(id=1){const v={id,url:'https://example.test/private?secret=fixture',startTime:'2026-09-27T12:00:00.000Z',state:'in_progress',paused:true,bytesReceived:100};items.set(id,v);return v;}
 return {storage,calls,errors,module,item,items,setStatus:v=>status=v,setNativeError:v=>nativeError=v,setCancelError:v=>cancelError=v,setResumeError:v=>resumeError=v,setWriteError:v=>writeError=v,record:()=>Object.values(storage[key]||{})[0],count:()=>Object.keys(storage[key]||{}).length};
}
async function check(name,fn){await fn();passed++;console.log('PASS '+name);}
(async()=>{
 for(const situation of ['complete','received','resumed','removed','identity'])await check('Final submission does not replay a browser '+situation+' response',async()=>{
  const h=harness(),m=h.module(),v=h.item(),r=await m.begin(v);r.protocol=1;
  if(situation==='complete')v.state='complete';
  if(situation==='received')Object.assign(v,{bytesReceived:4096,totalBytes:4096});
  if(situation==='resumed')v.paused=false;
  if(situation==='removed')h.items.clear();
  if(situation==='identity')v.startTime='2026-09-27T12:01:00.000Z';
  const result=await m.submit(r,{action:'add'});assert.equal(result.browserRetained,true);assert(!h.calls.some(c=>c[0]==='native'));
  await m.finish(r);assert.equal(h.count(),0);assert(!h.calls.some(c=>c[0]==='cancel'));if(situation==='received')assert.equal(h.calls.at(-1)[0],'resume');
 });
 await check('Firefox zero-byte paused response still reaches native ownership',async()=>{const h=harness({firefox:true}),m=h.module(),v=h.item(),r=await m.begin(v);Object.assign(v,{state:'interrupted',paused:false,bytesReceived:0,totalBytes:12,error:'USER_CANCELED'});assert((await m.submit(r,{action:'add'})).ok);await m.finish(r);assert.equal(h.calls.filter(c=>c[0]==='native').length,1);assert.equal(h.calls.at(-1)[0],'cancel');});
 await check('Worker restart releases a download held before submission',async()=>{const h=harness(),m=h.module();await m.begin(h.item());const r=await h.module().recover();assert.equal(r.recovered,1);assert.equal(h.calls[0][0],'resume');assert.equal(h.count(),0);});
 await check('Acknowledged ownership survives restart and cancels the browser',async()=>{const h=harness(),m=h.module(),r=await m.begin(h.item());r.protocol=1;await m.submit(r,{action:'add'});await h.module().recover();assert.deepEqual(h.calls.map(x=>x[0]),['native','cancel']);assert.equal(h.count(),0);});
 for(const [status,expected] of [['accepted','cancel'],['released','resume'],['uncertain',null]])await check('Lost acknowledgement reconciles '+status+' without replay',async()=>{const h=harness(),m=h.module(),r=await m.begin(h.item());r.protocol=1;h.setNativeError(true);await assert.rejects(m.submit(r,{action:'add',request:{body:'never-persist'}}));h.setNativeError(false);h.setStatus(status);h.calls.length=0;await h.module().recover();assert.deepEqual(h.calls.filter(c=>c[0]==='native'),[['native','capture-reconcile']]);assert.equal(h.calls.find(c=>c[0]!=='native')?.[0]||null,expected);assert.equal(h.count(),expected?0:1);});
 await check('Missing native host keeps an ambiguous transfer for later reconciliation',async()=>{const h=harness(),m=h.module(),r=await m.begin(h.item());r.protocol=1;h.setNativeError(true);await assert.rejects(m.submit(r,{action:'add'}));await h.module().recover();assert.equal(h.count(),1);assert(!h.calls.some(c=>c[0]==='resume'||c[0]==='cancel'));h.setNativeError(false);await h.module().recover();assert.equal(h.count(),0);assert.equal(h.calls.at(-1)[0],'cancel');});
 await check('Older desktop ambiguity never replays or resumes automatically',async()=>{const h=harness(),m=h.module(),r=await m.begin(h.item());h.setNativeError(true);await assert.rejects(m.submit(r,{action:'add'}));h.calls.length=0;await h.module().recover();assert.equal(h.calls.length,0);assert.equal(h.count(),1);});
 await check('Failed cancellation is retained and retried without another Add',async()=>{const h=harness(),m=h.module(),r=await m.begin(h.item());await m.submit(r,{action:'add'});h.setCancelError(true);await m.finish(r);assert.equal(h.count(),1);h.setCancelError(false);await h.module().recover();assert.equal(h.count(),0);assert.equal(h.calls.filter(c=>c[1]==='add').length,1);});
 await check('Failed resume retains the recovery record',async()=>{const h=harness(),m=h.module();await m.begin(h.item());h.setResumeError(true);await h.module().recover();assert.equal(h.count(),1);h.setResumeError(false);await h.module().recover();assert.equal(h.count(),0);});
 await check('Reused download ID cannot target a different URL',async()=>{const h=harness(),m=h.module(),v=h.item();await m.begin(v);v.url='https://other.test/new.zip';await h.module().recover();assert.equal(h.calls.length,0);assert.equal(h.count(),0);});
 await check('Reused ID and URL with a different start time are not touched',async()=>{const h=harness(),m=h.module(),v=h.item();await m.begin(v);v.startTime='2026-09-27T12:01:00.000Z';await h.module().recover();assert.equal(h.calls.length,0);});
 await check('Removed and completed records are pruned without browser operations',async()=>{for(const complete of [false,true]){const h=harness(),m=h.module(),v=h.item();await m.begin(v);if(complete)v.state='complete';else h.items.clear();await h.module().recover();assert.equal(h.calls.length,0);assert.equal(h.count(),0);}});
 await check('An unpaused preflight download is left running',async()=>{const h=harness(),m=h.module(),v=h.item();await m.begin(v);v.paused=false;await h.module().recover();assert.equal(h.calls.length,0);assert.equal(h.count(),0);});
 await check('Firefox zero-byte pause resumes after preflight worker loss',async()=>{const h=harness({firefox:true}),m=h.module(),v=h.item();await m.begin(v);Object.assign(v,{paused:false,state:'interrupted',bytesReceived:0,error:'USER_CANCELED'});await h.module().recover();assert.equal(h.calls.at(-1)[0],'resume');});
 await check('Active handoffs are skipped by overlapping alarm recovery',async()=>{const h=harness(),m=h.module();await m.begin(h.item());assert.equal((await m.recover()).recovered,0);assert.equal(h.calls.length,0);});
 await check('Concurrent records do not overwrite each other',async()=>{const h=harness(),m=h.module();await Promise.all([m.begin(h.item(1)),m.begin(h.item(2))]);assert.equal(h.count(),2);await h.module().recover();assert.equal(h.calls.filter(c=>c[0]==='resume').length,2);});
 await check('Journal never stores the URL, credentials or POST data',async()=>{const h=harness(),m=h.module(),r=await m.begin(h.item());await m.submit(r,{action:'add',url:'https://example.test/private?secret=fixture',headers:{Authorization:'private-token'},request:{body:'never-persist'}});const s=JSON.stringify(h.storage);for(const secret of ['https:','private','fixture','never-persist','Authorization'])assert(!s.includes(secret));});
 await check('A failed initial checkpoint rejects before native submission',async()=>{const h=harness(),m=h.module();h.setWriteError(true);await assert.rejects(m.begin(h.item()));assert.equal(h.calls.length,0);});
 await check('Duplicate browser IDs cannot start two ownership journals',async()=>{const h=harness(),m=h.module(),v=h.item();await m.begin(v);await assert.rejects(m.begin(v));assert.equal(h.count(),1);});
 await check('Missing stable browser identity is rejected',async()=>{const h=harness(),v=h.item();delete v.startTime;await assert.rejects(h.module().begin(v));assert.equal(h.count(),0);});
 await check('Corrupt journals cause no transfer actions',async()=>{const h=harness();h.storage[key]={x:{id:7}};await assert.rejects(h.module().recover());assert.equal(h.calls.length,0);});
 assert.equal(fs.readFileSync(path.join(__dirname,'../browser/chromium/capture-recovery.js'),'utf8'),fs.readFileSync(path.join(__dirname,'../browser/firefox/capture-recovery.js'),'utf8'));
 console.log('ALL '+passed+' CAPTURE RECOVERY CHECKS PASSED');
})().catch(e=>{console.error(e);process.exitCode=1;});
