'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const key='captureOwnershipV1';let passed=0;
function harness(family){
 const storage={},calls=[],errors=[],native=new Map();let item={id:1,url:'https://example.test/secret.zip',startTime:'2026-09-29T00:00:00.000Z',state:'in_progress',paused:true,bytesReceived:64,totalBytes:4096};
 const hooks={},api={runtime:{getURL:value=>(family==='firefox'?'moz-extension://fixture/':'chrome-extension://fixture/')+value},alarms:{create:async()=>{},clear:async()=>true,onAlarm:{addListener(){}}},storage:{local:{get:async k=>({[k]:structuredClone(storage[k])}),set:async value=>{if(hooks.write)await hooks.write(value);Object.assign(storage,structuredClone(value));}}},downloads:{
  search:async()=>item?[structuredClone(item)]:[],
  cancel:async id=>{calls.push('cancel');if(hooks.cancel)return hooks.cancel(item);Object.assign(item,{paused:false,state:'interrupted',error:'USER_CANCELED'});},
  resume:async()=>{calls.push('resume');Object.assign(item,{paused:false,state:'in_progress'});}
 }};
 const request=async message=>{
  calls.push(message.action);const token=message.captureToken;let status=native.get(token);let result;
  if(message.action==='capture-prepare'){if(!status){status={status:'prepared',download:structuredClone(message.download)};native.set(token,status);}result={ok:true,status:status.status};}
  if(message.action==='capture-status'){if(!status){status={status:'released'};native.set(token,status);}result={ok:true,status:status.status,id:status.id};}
  if(message.action==='capture-release'){if(!status||status.status==='prepared'){status={status:'released'};native.set(token,status);}result={ok:true,status:status.status};}
  if(message.action==='capture-commit'){
   if(status?.status==='prepared'){
    assert(item===null||item.state==='interrupted'&&item.error==='USER_CANCELED','native admission happened before confirmed browser cancellation');
    status={status:'accepted',id:'one-job'};native.set(token,status);
   }
   result={ok:true,status:status?.status||'released',id:status?.id};
  }
  if(hooks[message.action])await hooks[message.action](message,result);
  return result;
 };
 const module=()=>{const ctx=vm.createContext({crypto:crypto.webcrypto,TextEncoder,Uint8Array,Date,...(family==='firefox'?{browser:api}:{}),module:{exports:{}}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../browser',family,'capture-recovery.js'),'utf8'),ctx);return ctx.UdmCaptureRecovery.create(api,request,async e=>errors.push(e));};
 return {storage,calls,errors,native,hooks,module,get item(){return item;},set item(v){item=v;},count:()=>Object.keys(storage[key]||{}).length,record:()=>Object.values(storage[key]||{})[0]};
}
const download={action:'add',url:'https://example.test/secret.zip',headers:{Authorization:'private-test-token'},request:{body:'private-test-body'}};
async function begin(h,running=false){const m=h.module();if(running)h.item.paused=false;const r=await m.begin(h.item,{browserRunning:running});r.protocol=2;return [m,r];}
async function check(family,name,fn){await fn();passed++;console.log('PASS '+family+' '+name);}
(async()=>{
 for(const family of ['chromium','firefox']){
  for(const failure of ['none','reply','storage'])await check(family,'native review survives '+failure+' without browser resume or request replay',async()=>{
   const h=harness(family),[m,r]=await begin(h);
   h.hooks['capture-commit']=async(message,result)=>{h.native.set(message.captureToken,{status:'review'});Object.assign(result,{status:'review',id:undefined});if(failure==='reply')throw Error('lost review reply');};
   if(failure==='storage')h.hooks.write=async value=>{if(Object.values(value[key]||{})[0]?.phase==='accepted')throw Error('worker stopped before acknowledgement');};
   if(failure==='none'){assert.equal((await m.submit(r,download)).status,'review');await m.finish(r);}
   else{await assert.rejects(m.submit(r,download));delete h.hooks.write;delete h.hooks['capture-commit'];await h.module().recover();}
   assert.equal(h.count(),0);assert.equal(h.native.get(r.token).status,'review');assert.equal(h.item.state,'interrupted');assert.equal(h.calls.filter(x=>x==='capture-commit').length,1);assert(!h.calls.includes('resume'));assert.equal(h.calls.filter(x=>x==='capture-prepare').length,1);
  });
  await check(family,'discarded native review remains terminal after worker loss',async()=>{
   const h=harness(family),[m,r]=await begin(h);h.hooks['capture-commit']=async message=>{h.native.set(message.captureToken,{status:'discarded'});throw Error('worker exit after native decision');};
   await assert.rejects(m.submit(r,download));delete h.hooks['capture-commit'];await h.module().recover();assert.equal(h.count(),0);assert.equal(h.native.get(r.token).status,'discarded');assert.equal(h.calls.filter(x=>x==='capture-commit').length,1);assert(!h.calls.includes('resume'));
  });
  await check(family,'native admission follows observed browser cancellation',async()=>{const h=harness(family),[m,r]=await begin(h);assert.equal((await m.submit(r,download)).status,'accepted');assert.deepEqual(h.calls,['capture-prepare','capture-status','cancel','capture-commit']);await m.finish(r);assert.equal(h.count(),0);assert.equal(h.calls.filter(x=>x==='capture-commit').length,1);});
  for(const race of ['complete','received','resumed','removed','reused'])await check(family,'browser '+race+' during native preparation prevents admission',async()=>{const h=harness(family),[m,r]=await begin(h);h.hooks['capture-prepare']=async()=>{if(race==='complete')h.item.state='complete';if(race==='received')h.item.bytesReceived=4096;if(race==='resumed')h.item.paused=false;if(race==='removed')h.item=null;if(race==='reused')h.item.startTime='2026-09-29T01:00:00.000Z';};const result=await m.submit(r,download);assert.equal(result.browserRetained,true);assert(!h.calls.includes('capture-commit'));assert(!h.calls.includes('cancel'));assert.equal(h.count(),0);assert.equal(h.native.get(r.token).status,'released');});
  await check(family,'completion inside cancel defeats even a successful cancel callback',async()=>{const h=harness(family),[m,r]=await begin(h);h.hooks.cancel=async item=>{item.state='complete';item.paused=false;};assert.equal((await m.submit(r,download)).browserRetained,true);assert(!h.calls.includes('capture-commit'));assert.equal(h.count(),0);});
  await check(family,'cancel failure retains preparation for worker restart',async()=>{const h=harness(family),[m,r]=await begin(h);h.hooks.cancel=async()=>{throw Error('cancel denied');};await assert.rejects(m.submit(r,download));assert(!h.calls.includes('capture-commit'));assert.equal(h.record().phase,'canceling');delete h.hooks.cancel;await h.module().recover();assert.equal(h.count(),0);assert.equal(h.calls.filter(x=>x==='capture-commit').length,1);});
  await check(family,'cancel callback without terminal state never authorizes admission',async()=>{const h=harness(family),[m,r]=await begin(h);h.hooks.cancel=async()=>{};await assert.rejects(m.submit(r,download));assert(!h.calls.includes('capture-commit'));await h.module().recover();assert.equal(h.count(),1);assert(!h.calls.includes('capture-commit'));delete h.hooks.cancel;await h.module().recover();assert.equal(h.count(),0);});
  for(const action of ['capture-prepare','capture-commit'])await check(family,'lost '+action+' response recovers without resubmitting a request',async()=>{const h=harness(family),[m,r]=await begin(h);h.hooks[action]=async()=>{throw Error('lost reply');};await assert.rejects(m.submit(r,download));delete h.hooks[action];await h.module().recover();assert.equal(h.count(),0);assert.equal(h.native.get(r.token).status,'accepted');assert.equal(h.calls.filter(x=>x==='capture-prepare').length,1);assert.equal(h.calls.filter(x=>x==='capture-commit').length,1);});
  for(const phase of ['prepared','canceled','committing','accepted'])await check(family,'storage failure at '+phase+' recovers from the durable boundary',async()=>{const h=harness(family),[m,r]=await begin(h);let fail=true;h.hooks.write=async value=>{if(fail&&Object.values(value[key]||{})[0]?.phase===phase){fail=false;throw Error('checkpoint failure');}};await assert.rejects(m.submit(r,download));delete h.hooks.write;await h.module().recover();assert.equal(h.count(),0);assert.equal(h.native.get(r.token).status,'accepted');assert.equal(h.calls.filter(x=>x==='capture-commit').length,1);});
  await check(family,'ambiguous native admission is retained without replay or browser resume',async()=>{const h=harness(family),[m,r]=await begin(h);h.hooks['capture-commit']=async message=>{h.native.set(message.captureToken,{status:'uncertain'});throw Error('desktop failed during admission');};await assert.rejects(m.submit(r,download));const count=h.calls.length;await h.module().recover();assert.deepEqual(h.calls.slice(count),['capture-status']);assert.equal(h.count(),1);assert(!h.calls.includes('resume'));});
  await check(family,'completed browser history during worker loss releases pending native request',async()=>{const h=harness(family),[m,r]=await begin(h);h.hooks['capture-prepare']=async()=>{throw Error('worker exit');};await assert.rejects(m.submit(r,download));h.item.state='complete';h.item.paused=false;delete h.hooks['capture-prepare'];await h.module().recover();assert.equal(h.native.get(r.token).status,'released');assert(!h.calls.includes('capture-commit'));assert.equal(h.count(),0);});
  await check(family,'durable cancellation survives browser history erasure',async()=>{const h=harness(family),[m,r]=await begin(h);let fail=true;h.hooks.write=async value=>{if(fail&&Object.values(value[key]||{})[0]?.phase==='committing'){fail=false;throw Error('worker exit');}};await assert.rejects(m.submit(r,download));assert.equal(h.record().phase,'canceled');h.item=null;delete h.hooks.write;await h.module().recover();assert.equal(h.native.get(r.token).status,'accepted');assert.equal(h.count(),0);});
  await check(family,'browser journal contains no request URLs, body or credentials',async()=>{const h=harness(family),[m,r]=await begin(h);h.hooks.cancel=async()=>{throw Error('hold');};await assert.rejects(m.submit(r,download));const serialized=JSON.stringify(h.storage);for(const secret of ['https:','private-test','Authorization','secret.zip'])assert(!serialized.includes(secret));});
  if(family==='firefox')await check(family,'zero-byte pause still requires an explicit acknowledged cancel',async()=>{const h=harness(family),[m,r]=await begin(h);Object.assign(h.item,{state:'interrupted',error:'USER_CANCELED',paused:false,bytesReceived:0});await m.submit(r,download);assert(h.calls.indexOf('cancel')<h.calls.indexOf('capture-commit'));await m.finish(r);assert.equal(h.count(),0);});
 }
 for(const family of ['chromium','firefox']){
  await check(family,'running response survives preflight abandonment without pause or resume',async()=>{const h=harness(family),[m,r]=await begin(h,true);assert.equal(h.record().browserRunning,true);await m.finish(r);assert.equal(h.count(),0);assert.deepEqual(h.calls,[]);assert.equal(h.item.state,'in_progress');});
  await check(family,'running response commits only after durable preparation and verified cancellation',async()=>{const h=harness(family),[m,r]=await begin(h,true);assert.equal((await m.submit(r,download)).status,'accepted');assert.deepEqual(h.calls,['capture-prepare','capture-status','cancel','capture-commit']);await m.finish(r);assert.equal(h.count(),0);});
  for(const race of ['complete','received','paused','canceled','failed','removed','reused'])await check(family,'running browser '+race+' during preparation releases without modifying browser choice',async()=>{
   const h=harness(family),[m,r]=await begin(h,true);
   h.hooks['capture-prepare']=async()=>{if(race==='complete')h.item.state='complete';if(race==='received')h.item.bytesReceived=h.item.totalBytes;if(race==='paused')Object.assign(h.item,{state:'interrupted',paused:true,canResume:true});if(race==='canceled')Object.assign(h.item,{state:'interrupted',error:'USER_CANCELED',paused:false,canResume:false});if(race==='failed')Object.assign(h.item,{state:'interrupted',error:'NETWORK_FAILED'});if(race==='removed')h.item=null;if(race==='reused')h.item.startTime='2026-09-29T01:00:00.000Z';};
   assert.equal((await m.submit(r,download)).browserRetained,true);await m.finish(r);assert.equal(h.native.get(r.token).status,'released');assert.equal(h.count(),0);assert(!h.calls.some(c=>['cancel','resume','capture-commit'].includes(c)));
  });
  for(const action of ['capture-prepare','capture-commit'])await check(family,'running handoff persists its mode through lost '+action+' and a new worker',async()=>{
   const h=harness(family),[m,r]=await begin(h,true);h.hooks[action]=async()=>{throw Error('worker lost reply');};await assert.rejects(m.submit(r,download));assert.equal(h.record().browserRunning,true);delete h.hooks[action];await h.module().recover();assert.equal(h.count(),0);assert.equal(h.native.get(r.token).status,'accepted');assert.equal(h.calls.filter(c=>c==='capture-prepare').length,1);assert.equal(h.calls.filter(c=>c==='capture-commit').length,1);assert(!h.calls.includes('resume'));
  });
  await check(family,'running handoff releases a lost prepare that completes while native is unreachable',async()=>{const h=harness(family),[m,r]=await begin(h,true);h.hooks['capture-prepare']=async()=>{throw Error('lost reply');};await assert.rejects(m.submit(r,download));h.hooks['capture-status']=async()=>{throw Error('host down');};await h.module().recover();assert.equal(h.item.state,'in_progress');h.item.state='complete';delete h.hooks['capture-status'];await h.module().recover();assert.equal(h.native.get(r.token).status,'released');assert.equal(h.count(),0);assert(!h.calls.some(c=>['cancel','resume','capture-commit'].includes(c)));});
  await check(family,'running handoff missing history after cancellation still commits the saved request',async()=>{const h=harness(family),[m,r]=await begin(h,true);h.hooks.write=async v=>{if(Object.values(v[key]||{})[0]?.phase==='committing')throw Error('worker exit');};await assert.rejects(m.submit(r,download));assert.equal(h.record().phase,'canceled');h.item=null;delete h.hooks.write;await h.module().recover();assert.equal(h.native.get(r.token).status,'accepted');assert.equal(h.count(),0);});
  await check(family,'running handoff cancellation with a lost callback requires a new acknowledgment before commit',async()=>{const h=harness(family),[m,r]=await begin(h,true);h.hooks.cancel=async item=>{Object.assign(item,{state:'interrupted',error:'USER_CANCELED',paused:false,canResume:false,bytesReceived:0});throw Error('cancel acknowledgement lost');};await assert.rejects(m.submit(r,download));assert.equal(h.record().phase,'canceling');assert(!h.calls.includes('capture-commit'));delete h.hooks.cancel;await h.module().recover();assert.equal(h.calls.filter(c=>c==='cancel').length,2);assert.equal(h.calls.filter(c=>c==='capture-commit').length,1);assert.equal(h.native.get(r.token).status,'accepted');assert.equal(h.count(),0);});
  await check(family,'running handoff storage failure before preparation never cancels the response',async()=>{const h=harness(family),[m,r]=await begin(h,true);h.hooks.write=async()=>{throw Error('disk full');};await assert.rejects(m.submit(r,download));assert.equal(h.record().phase,'held');assert.deepEqual(h.calls,[]);delete h.hooks.write;await h.module().recover();assert.equal(h.item.state,'in_progress');assert.equal(h.count(),0);});
  await check(family,'running handoff zero-byte user cancellation is never adopted',async()=>{const h=harness(family),[m,r]=await begin(h,true);Object.assign(h.item,{state:'interrupted',error:'USER_CANCELED',canResume:false,bytesReceived:0});assert.equal((await m.submit(r,download)).browserRetained,true);await m.finish(r);assert.deepEqual(h.calls,[]);assert.equal(h.count(),0);});
  await check(family,'corrupt running mode cannot authorize a legacy handoff',async()=>{const h=harness(family);await begin(h,true);h.storage[key][h.record().token].protocol=1;await assert.rejects(h.module().recover());assert.deepEqual(h.calls,[]);});
 }
 console.log('ALL '+passed+' TRANSACTION CHECKS PASSED');
})().catch(e=>{console.error(e);process.exitCode=1;});
