'use strict';
const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=readFileSync(require('node:path').join(__dirname,'../browser/chromium/capture.js'),'utf8');
const id='Q3TI27IN7X0',ad='aaaaaaaaaaa';
const data=(videoId,formats)=>({videoDetails:{videoId},streamingData:{adaptiveFormats:formats}});
const response=(value)=>new Response(JSON.stringify(value),{headers:{'content-type':'application/json'}});
let playerResponse,requestPromise,receivedArgs;
const context=vm.createContext({URL,URLSearchParams,TextDecoder,location:{href:'https://www.youtube.com/watch?v='+id},document:{getElementById:()=>({getPlayerResponse:()=>playerResponse,getVideoData:()=>({video_id:id})})},fetch:function(...args){receivedArgs=args;return requestPromise;}});
vm.runInContext(source,context);
(async()=>{
  const original=response(data(id,[{itag:137,height:1080,url:'https://rr1.googlevideo.com/videoplayback?id=target&itag=137'}]));requestPromise=Promise.resolve(original);
  const args=['/youtubei/v1/player',{method:'POST',body:'unchanged'}];
  assert.equal(context.fetch(...args),requestPromise);assert.deepEqual(receivedArgs,args);
  await new Promise(r=>setTimeout(r,50));
  assert.equal(original.bodyUsed,false);assert.equal(context.__udmCaptureV1.read(id).streamingData.adaptiveFormats[0].itag,137);
  console.log('PASS early player response capture preserves request, response body and promise');
  playerResponse=data(id,[{itag:137,height:1080},{itag:140,mimeType:'audio/mp4'}]);
  const merged=context.__udmCaptureV1.read(id);assert.equal(merged.streamingData.adaptiveFormats.length,2);assert.ok(merged.streamingData.adaptiveFormats[0].url);
  console.log('PASS later partial player metadata retains early capture URLs');
  playerResponse=data(ad,[{itag:137,url:'https://rr1.googlevideo.com/videoplayback?id=ad&itag=137'}]);
  assert.ok(context.__udmCaptureV1.read(id).streamingData.adaptiveFormats[0].url.includes('id=target'));assert.equal(context.__udmCaptureV1.read(ad).videoDetails.videoId,ad);
  console.log('PASS ad response cannot replace current video catalog');
  requestPromise=Promise.resolve(response(data('bbbbbbbbbbb',[{itag:18}])));context.fetch('https://example.test/youtubei/v1/player');await new Promise(r=>setTimeout(r,30));assert.equal(context.__udmCaptureV1.read('bbbbbbbbbbb'),null);
  assert.equal(context.__udmCaptureV1.prepare(ad,1080),false);
  console.log('PASS unrelated endpoints and mismatched preparation are rejected');
  playerResponse=data(id,[{itag:140,audioTrack:{id:'en.1',displayName:'English'},xtags:'en',bitrate:128000,url:'https://rr1.googlevideo.com/videoplayback?id=target&itag=140&xtags=en'},{itag:140,audioTrack:{id:'es.1',displayName:'Español'},xtags:'es',averageBitrate:130000,url:'https://rr1.googlevideo.com/videoplayback?id=target&itag=140&xtags=es'}]);
  let audio=context.__udmCaptureV1.read(id).streamingData.adaptiveFormats.filter(f=>f.audioTrack);assert.equal(audio.length,2);assert.equal(audio[0].bitrate,128000);assert.equal(audio[1].averageBitrate,130000);
  console.log('PASS same-itag audio languages and bitrate metadata survive repeated capture');
  context.ytInitialPlayerResponse=data(id,[{itag:140,audioTrack:{id:'en.1'},xtags:'en',url:'https://rr1.googlevideo.com/videoplayback?id=target&itag=140&xtags=en&sig=old'}]);
  audio=context.__udmCaptureV1.read(id).streamingData.adaptiveFormats.find(f=>f.audioTrack?.id==='en.1');assert.equal(audio.url,playerResponse.streamingData.adaptiveFormats[0].url);
  console.log('PASS current player metadata wins over the initial page snapshot');
  context.ytInitialPlayerResponse=undefined;playerResponse=data(id,[{itag:141,lastModified:'1',url:'https://rr1.googlevideo.com/videoplayback?id=target&itag=141'}]);context.__udmCaptureV1.read(id);playerResponse=data(id,[{itag:141,lastModified:'2'}]);assert.equal(context.__udmCaptureV1.read(id).streamingData.adaptiveFormats.find(f=>f.itag===141).url,undefined);
  console.log('PASS a changed format revision does not inherit a previous direct URL');
  console.log('ALL 7 CAPTURE CHECKS PASSED');
})().catch(e=>{console.error(e);process.exitCode=1;});
