'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),M=require('../browser/chromium/media.js');
(async()=>{let tabUrl='https://www.dailymotion.com/video/xcurrent',player={page:'https://geo.dailymotion.com/player/test.html',timeOrigin:100,token:'token-1',stamp:'100',current:'blob:https://geo.dailymotion.com/test',sources:[],height:720,width:1280,videoCount:1,duration:100,title:'Generic player',encrypted:false,dailymotion:{id:'xcurrent',url:'https://www.dailymotion.com/cdn/manifest/video/xcurrent.m3u8',type:'application/x-mpegURL',streamType:'recorded',duration:100,title:'Current video',protected:false}},store={},native=[],fetches=[],codecs='';
const event=()=>({addListener(){}}),api={tabs:{get:async()=>({id:7,url:tabUrl,title:'Current video'})},storage:{local:{get:async()=>({settings:{}})},session:{get:async k=>({[k]:store[k]}),set:async x=>Object.assign(store,x)}},scripting:{executeScript:async()=>[{frameId:2,documentId:'doc',result:structuredClone(player)}]},permissions:{contains:async()=>true,onAdded:event(),onRemoved:event()},runtime:{onStartup:event(),sendNativeMessage:async(_,m)=>{native.push(m);return {ok:true};}}};
const box={UdmMedia:M,URL,Date,crypto,AbortController,TextEncoder,TextDecoder,setTimeout,clearTimeout,navigator:{userAgent:'test'},fetch:async url=>{fetches.push(url);return {ok:true,url,body:new ReadableStream({start(c){c.enqueue(new TextEncoder().encode(url.includes('/cdn/manifest/')?'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1000000,RESOLUTION=1280x720'+codecs+'\nhttps://video.dmcdn.net/current.m3u8':'#EXTM3U\n#EXTINF:100,\ncurrent.ts\n#EXT-X-ENDLIST'));c.close();}})};}};vm.createContext(box);vm.runInContext(fs.readFileSync(require.resolve('../browser/chromium/sites.js'),'utf8')+'\nglobalThis.sites=UdmSites;',box);box.sites.install(api);
const sender={tab:{id:7},frameId:2,documentId:'doc',url:player.page},message={token:player.token,page:player.page};
let catalog=await box.sites.list(message,sender);assert.equal(catalog.choices.length,1);assert.match(catalog.choices[0].label,/720p/);console.log('PASS empty capture recovers current Dailymotion playlist from player metadata');
store['site-media:7']=[{frameId:2,documentId:'doc',page:player.page,time:Date.now(),kind:'hls',url:'https://www.dailymotion.com/cdn/manifest/video/xold.m3u8'}];fetches=[];catalog=await box.sites.list(message,sender);assert(fetches.every(x=>!x.includes('xold')));console.log('PASS stale/advertisement network captures cannot override current player metadata');
await box.sites.download({...message,key:catalog.choices[0].key},sender);assert.equal(native[0].filename,'Current video');assert.equal(native[0].plan.tracks[0].segments[0].url,'https://video.dmcdn.net/current.ts');console.log('PASS recovered selection sends correct native segments and video title');
for(const [name,key,value,pattern] of [['wrong video','id','xold',/changing videos/],['DRM','protected',true,/DRM/],['live video','streamType','live',/recorded/],['advertisement duration','duration',30,/main video/],['unrecognized host','url','https://unrelated.test/a.m3u8',/Unrecognized/]]){const prior=player.dailymotion[key];player.dailymotion[key]=value;await assert.rejects(()=>box.sites.list(message,sender),pattern);player.dailymotion[key]=prior;console.log('PASS '+name+' is rejected');}
codecs=',CODECS="avc1.64001f,mp4a.40.2"';catalog=await box.sites.list(message,sender);assert.equal(catalog.choices.length,2);assert.match(catalog.choices[0].label,/Dailymotion · MP4 · 720p HD · 1000 kbps/);assert.equal(catalog.choices[0].source,'');assert.equal(catalog.choices[1].container,'ts');console.log('PASS compatible HLS exposes compact MP4/TS labels and declared bitrate');
await box.sites.download({...message,key:catalog.choices[1].key},sender);assert.equal(native.at(-1).plan.container,'ts');console.log('PASS TS choice reaches the native output-container plan');
codecs=',CODECS="av01.0.05M.08,opus"';const incompatible=await box.sites.list(message,sender);assert.equal(incompatible.choices.length,1);assert.equal(incompatible.choices[0].container,'mp4');console.log('PASS incompatible codecs do not advertise TS');
const sent=native.length;
tabUrl='https://www.dailymotion.com/video/xnext';await assert.rejects(()=>box.sites.download({...message,key:catalog.choices[0].key},sender),/changing videos/);assert.equal(native.length,sent);console.log('PASS SPA navigation prevents old native handoff');
console.log('ALL 12 DAILYMOTION RECOVERY CHECKS PASSED');})().catch(e=>{console.error(e);process.exitCode=1;});
