'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),http=require('node:http'),assert=require('node:assert/strict'),{spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const stage=__dirname,root=path.resolve(process.argv[2]),project=process.env.UDM_PROJECT||path.resolve(__dirname,'..'),release=process.env.UDM_TEST_RELEASE||path.join(project,'release-native'),id='aqz-KE-bpKQ',url='https://www.youtube.com/watch?v='+id,tag='direct'+crypto.randomBytes(6).toString('hex'),hostName='com.udm.directfixture'+Date.now(),registry='HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\'+hostName;
const report={videoId:id,scope:'Synthetic YouTube page; original Edge extension and actual native framing. Desktop review invoked in C++ probe. Production validation uses synthetic Googlevideo identities; probe temporarily substitutes loopback transport only during transfer. Does not establish public YouTube or rendered native-dialog compatibility.',checks:[],startedUtc:new Date().toISOString()};let probe,browser,page,worker,server,base,version="old",registered=false,serial=0;const traffic=[];
const wait=ms=>new Promise(r=>setTimeout(r,ms)),pass=(name,detail={})=>{report.checks.push({passed:true,name,...detail});console.log('PASS '+name);};
async function until(fn,ms=45000){const deadline=Date.now()+ms;while(Date.now()<deadline){const v=await fn();if(v)return v;await wait(150);}throw Error('Edge fixture recovery timed out');}
const jobs=()=>{try{return JSON.parse(fs.readFileSync(path.join(root,'state/state.json'))).Downloads;}catch{return [];}};
async function command(action,id,fixture){const n=++serial,p=path.join(root,n+'.command.json');fs.writeFileSync(p+'.tmp',JSON.stringify({action,id,fixture}));fs.renameSync(p+'.tmp',p);if(action==='quit')return;const out=path.join(root,n+'.reply.json');const value=await until(()=>fs.existsSync(out)&&JSON.parse(fs.readFileSync(out)));assert.equal(value.ok,true,value.error);return value;}
async function click(name){const s=await browser.newCDPSession(page);try{const n=await until(async()=>{const t=await s.send('Accessibility.getFullAXTree');return t.nodes.find(x=>!x.ignored&&x.role?.value==='button'&&name(x.name?.value||''));});const {model}=await s.send('DOM.getBoxModel',{backendNodeId:n.backendDOMNodeId}),q=model.content;await page.mouse.click((q[0]+q[2])/2,(q[1]+q[5])/2);}finally{await s.detach();}}
async function choose(){await until(()=>page.locator('[id^="udm-video-panel-"]:visible').count(),60000);await click(n=>n==='Download this video with UDM');await click(n=>/360p/.test(n));}
(async()=>{
 assert(!fs.existsSync(root));fs.mkdirSync(root,{recursive:true});
 const ff=path.join(release,'tools/ffmpeg.exe');
 execFileSync(ff,['-v','error','-f','lavfi','-i','testsrc2=size=640x360:rate=24:duration=8','-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p',path.join(root,'video.mp4')],{windowsHide:true});
 execFileSync(ff,['-v','error','-f','lavfi','-i','sine=frequency=440:duration=8','-c:a','aac',path.join(root,'audio.mp4')],{windowsHide:true});
 const video=fs.readFileSync(path.join(root,'video.mp4')),audio=fs.readFileSync(path.join(root,'audio.mp4'));
 server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');const buf=u.pathname.endsWith('video.mp4')?video:audio;const range=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range||'');const a=range?+range[1]:0,b=range&&range[2]?+range[2]:buf.length-1;
  traffic.push({path:u.pathname,start:a,end:b});res.writeHead(range?206:200,{'Content-Type':u.pathname.endsWith('video.mp4')?'video/mp4':'audio/mp4','Content-Length':b-a+1,ETag:'"unchanged-track"',...(range?{'Content-Range':`bytes ${a}-${b}/${buf.length}`}:{})});
  if(u.pathname==='/old/video.mp4'&&b>a){res.write(buf.subarray(a,Math.min(b+1,a+131072)));setTimeout(()=>res.destroy(),250);}else res.end(buf.subarray(a,b+1));
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+server.address().port;
 const env={...process.env,UDM_INSTANCE_TAG:tag};probe=spawn(path.join(release,'DirectRefreshProbe.exe'),[root],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});let log='';probe.stderr.on('data',b=>log+=b);await until(()=>{if(probe.exitCode!==null)throw Error(log);return fs.existsSync(path.join(root,'ready.json'));});
 const ext=path.join(root,'extension');fs.cpSync(path.join(project,'browser/chromium'),ext,{recursive:true});const bg=path.join(ext,'background.js');fs.writeFileSync(bg,fs.readFileSync(bg,'utf8').replace("'com.udm.download_manager'",JSON.stringify(hostName)));const manifest=path.join(root,'host.json');fs.writeFileSync(manifest,JSON.stringify({name:hostName,description:'Isolated UDM direct video refresh fixture',path:path.join(release,'Udm.NativeHost.exe'),type:'stdio',allowed_origins:['chrome-extension://'+fs.readFileSync(path.join(project,'browser/extension-id.txt'),'utf8').trim()+'/']}));let exists=false;try{execFileSync('reg.exe',['query',registry],{windowsHide:true,stdio:'ignore'});exists=true;}catch{}assert(!exists);execFileSync('reg.exe',['add',registry,'/ve','/t','REG_SZ','/d',manifest,'/f'],{windowsHide:true,stdio:'ignore'});registered=true;
 browser=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'msedge',headless:true,ignoreDefaultArgs:['--disable-extensions'],env,viewport:{width:1200,height:820},args:['--enable-unsafe-extension-debugging','--autoplay-policy=no-user-gesture-required']});const cdp=await browser.browser().newBrowserCDPSession();await cdp.send('Extensions.loadUnpacked',{path:ext});worker=browser.serviceWorkers()[0]||await browser.waitForEvent('serviceworker');const hello=await worker.evaluate(()=>nativeRequest({action:'hello'}));assert.equal(hello.version,process.env.UDM_EXPECT_NATIVE||'0.84.0');assert(hello.capabilities.includes('direct-media-refresh'));pass('Edge connects to the candidate native direct-refresh capability'); const format=(itag,kind,size)=>({itag,mimeType:kind==='video'?'video/mp4; codecs="avc1.42c01e"':'audio/mp4; codecs="mp4a.40.2"',contentLength:String(size),bitrate:kind==='video'?2000000:128000,...(kind==='video'?{height:360,width:640,qualityLabel:'360p'}:{}),url:'https://rr1.googlevideo.com/videoplayback?itag='+itag+'&expire=4102444800&lmt=12345&clen='+size+'&id='+version});
 await browser.route('https://www.youtube.com/**',route=>{const response={videoDetails:{videoId:id,lengthSeconds:'8'},streamingData:{adaptiveFormats:[format(134,'video',video.length),format(140,'audio',audio.length)]}};return route.fulfill({contentType:'text/html',body:'<!doctype html><title>UDM direct video refresh fixture</title><style>body{margin:50px;font:16px Arial}video{width:640px;height:360px;background:#203345}</style><h1>Direct video and audio recovery</h1><div id="movie_player"><video controls></video></div><script>globalThis.ytInitialPlayerResponse='+JSON.stringify(response)+';const p=document.getElementById("movie_player");p.getVideoData=()=>({video_id:"'+id+'"});p.getPlayerResponse=()=>ytInitialPlayerResponse;</script>'});});
 page=browser.pages()[0]||await browser.newPage();await page.goto(url,{waitUntil:'domcontentloaded'});await choose();const job=await until(()=>jobs().find(j=>j.SourceUrl===url));assert(job.Video&&job.Audio&&!job.ProtectedSabr);pass('Trusted synthetic YouTube panel click captures a direct pair through actual native messaging');
 const failed=await command('download',job.Id,base+'/old');assert.equal(failed.status,'Failed');assert(failed.videoReceived>0);const initial=jobs().find(j=>j.Id===job.Id);assert.equal(initial.Audio.Status,'Complete');const part=path.join(root,'state/parts',initial.Video.Id,'0000.part'),digest=crypto.createHash('sha256').update(fs.readFileSync(part)).digest('hex');pass('Interrupted real transfer preserves partial video and completed audio',{videoBytes:failed.videoReceived,audioBytes:failed.audioReceived});
 await command('arm',job.Id);version='fresh';await page.reload({waitUntil:'domcontentloaded'});await choose();await until(()=>jobs().find(j=>j.Id===job.Id)?.ProtectedRefreshOffer);assert.equal(jobs().length,1);const ax=await browser.newCDPSession(page);await until(async()=>{const t=await ax.send('Accessibility.getFullAXTree');return t.nodes.some(n=>n.name?.value?.includes('Fresh streams received. Review Refresh media session'));});await ax.detach();await page.screenshot({path:path.join(root,'refresh-panel.png')});pass('Fresh trusted panel capture stages a review offer on the same record and shows recovery guidance');
 const applied=await command('apply',job.Id);assert(applied.pending);assert.equal(applied.status,'Paused');assert.equal(crypto.createHash('sha256').update(fs.readFileSync(part)).digest('hex'),digest);assert.equal(jobs()[0].FileName,job.FileName);pass('Applying recapture preserves filename, child identities and partial video bytes');
 const before=traffic.length,begin=performance.now(),finished=await command('download',job.Id,base+'/fresh');assert.equal(finished.status,'Complete',finished.error);const made=traffic.slice(before);assert.equal(made[0].path,'/fresh/audio.mp4');assert.equal(made.filter(x=>x.path.endsWith('audio.mp4')).length,1);assert(made.some(x=>x.path.endsWith('video.mp4')&&x.start===failed.videoReceived));assert.equal(jobs().length,1);pass('Recovery validates completed audio before resuming the exact missing video offset',{requests:made.length,seconds:(performance.now()-begin)/1000});
 const info=JSON.parse(execFileSync(path.join(release,'tools/ffprobe.exe'),['-v','error','-show_streams','-show_format','-of','json',finished.target],{windowsHide:true}));assert(info.streams.some(x=>x.codec_type==='video'&&x.height===360));assert(info.streams.some(x=>x.codec_type==='audio'));const pixels=file=>execFileSync(ff,['-v','error','-i',file,'-map','0:v:0','-f','hash','-hash','sha256','-'],{windowsHide:true}).toString().trim();assert.equal(pixels(finished.target),pixels(path.join(root,'video.mp4')));pass('Recovered output contains video/audio and matches the source decoded video hash');report.outcome='Complete';

})().catch(e=>{report.outcome='Isolated Edge recovery did not complete';report.error=String(e.message).replace(/https?:\/\/[^\s]+/g,'[URL]').slice(0,600);console.error(report.error);process.exitCode=1;}).finally(async()=>{try{if(page)await page.screenshot({path:path.join(root,'last-page.png')});}catch{}if(browser)await browser.close();if(server){server.closeAllConnections();await new Promise(r=>server.close(r));}if(probe&&probe.exitCode===null){try{await command('quit');await until(()=>probe.exitCode!==null,10000);}catch{probe.kill();}}if(registered)execFileSync('reg.exe',['delete',registry,'/f'],{windowsHide:true,stdio:'ignore'});report.registryRemoved=registered;report.finishedUtc=new Date().toISOString();fs.writeFileSync(path.join(root,'result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));});
