'use strict';
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const Native=require('../browser/chromium/native-bridge.js'),Context=require('../browser/chromium/request-context.js');
let count=0;async function test(name,fn){await fn();console.log('PASS '+name);count++;}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
function host(mode='normal'){
 const ports=[],oneShot=[];const api={runtime:{connectNative(){const messages=[],incoming=[],closed=[];const port={messages,onMessage:{addListener:f=>incoming.push(f)},onDisconnect:{addListener:f=>closed.push(f)},disconnect(){if(port.closed)return;port.closed=true;closed.forEach(f=>f());},emit:r=>incoming.forEach(f=>f(r)),postMessage(m){messages.push(m);setImmediate(()=>{if(port.closed)return;if(m.action==='hello')port.emit(mode==='legacy'?{ok:false}:{ok:true,protocol:1,requestId:m.requestId});else if(mode==='disconnect')port.disconnect();else if(mode!=='hold')port.emit({ok:true,requestId:m.requestId,action:m.action});});}};ports.push(port);return port;},sendNativeMessage:async(_,m)=>{oneShot.push(m);return {ok:true};}}};
 return {api,ports,oneShot,client:Native.create(api,'com.udm.download_manager')};
}
(async()=>{
 await test('persistent connection reuses a host and matches acknowledgements',async()=>{const h=host();for(const action of ['ping','preferences','add'])assert.equal((await h.client.request({action})).action,action);assert.equal(h.ports.length,1);assert.equal(h.oneShot.length,0);assert.equal(h.ports[0].messages.filter(m=>m.action==='hello').length,1);h.client.disconnect();});
 await test('out-of-order native replies resolve the correct request',async()=>{const h=host('hold'),a=h.client.request({action:'add'}),b=h.client.request({action:'ping'});await tick();await tick();const messages=h.ports[0].messages.slice(1);assert.equal(messages.length,2);for(const m of messages.reverse())h.ports[0].emit({ok:true,requestId:m.requestId,action:m.action});assert.equal((await a).action,'add');assert.equal((await b).action,'ping');h.client.disconnect();});
 await test('player requests have separate lanes from download commands',async()=>{const h=host();await Promise.all(['youtube-player','youtube-player','add'].map(action=>h.client.request({action})));assert.equal(h.ports.length,3);h.client.disconnect();});
 await test('lost mutation acknowledgement is never replayed',async()=>{const h=host('disconnect');await assert.rejects(h.client.request({action:'add'}),/disconnected/);assert.equal(h.ports[0].messages.filter(m=>m.action==='add').length,1);assert.equal(h.oneShot.length,0);h.client.disconnect();});
 await test('a new user action reconnects after disconnection',async()=>{const h=host('disconnect');await assert.rejects(h.client.request({action:'ping'}));await assert.rejects(h.client.request({action:'ping'}));assert.equal(h.ports.length,2);h.client.disconnect();});
 await test('older host falls back only after a harmless negotiation',async()=>{const h=host('legacy');assert.equal((await h.client.request({action:'add'})).ok,true);assert.deepEqual(h.ports[0].messages.map(m=>m.action),['hello']);assert.deepEqual(h.oneShot.map(m=>m.action),['add']);h.client.disconnect();});
 await test('one-shot browser API remains compatible',async()=>{const h=host();delete h.api.runtime.connectNative;assert.equal((await h.client.request({action:'ping'})).ok,true);assert.equal(h.oneShot.length,1);});
 await test('timeout closes the uncertain channel without retrying',async()=>{const h=host('hold');await assert.rejects(h.client.request({action:'add'},1000),/acknowledge/);assert.equal(h.oneShot.length,0);assert.equal(h.client.diagnostics().pending,0);h.client.disconnect();});
 const e={requestId:'1',url:'https://media.test/file.mp4',method:'GET',tabId:7,frameId:2,documentId:'doc',documentUrl:'https://player.test/watch'};
 const record=(c,event=e)=>{c.begin(event);c.headers({...event,requestHeaders:[{name:'Accept',value:'video/mp4'},{name:'Origin',value:'https://player.test'},{name:'Cookie',value:'fixture=secret'},{name:'Authorization',value:'Bearer fixture'},{name:'Range',value:'bytes=1-2'},{name:'Host',value:'bad.test'}]});};
 await test('request headers are scoped and transport-owned headers excluded',()=>{const c=Context.create({});record(c);const r=c.resolve({url:e.url,tabId:7,frameId:2,documentId:'doc'},true);assert.equal(r.headers.Authorization,'Bearer fixture');assert.equal(r.headers.Host,undefined);assert.equal(r.headers.Range,undefined);assert.equal(r.headers.Origin,'https://player.test');});
 await test('credentials require the enabled permission path',()=>{const c=Context.create({});record(c);const r=c.resolve({url:e.url},false);assert.equal(r.headers.Cookie,undefined);assert.equal(r.headers.Authorization,undefined);assert.equal(r.headers.Accept,'video/mp4');});
 await test('navigation clears context and ambiguous documents disclose nothing',()=>{const c=Context.create({});record(c);record(c,{...e,requestId:'2',tabId:8,documentId:'second'});assert.equal(c.resolve({url:e.url},true),null);assert.equal(c.resolve({url:e.url,tabId:7},true).documentId,'doc');c.clear(7);assert.equal(c.resolve({url:e.url,tabId:7},true),null);});
 await test('redirected request does not inherit previous-origin credentials',()=>{const c=Context.create({});record(c);c.begin({...e,url:'https://cdn.test/file.mp4'});const r=c.resolve({url:'https://cdn.test/file.mp4'},true);assert.deepEqual(r.headers,{});assert.equal(c.resolve({url:e.url},true),null);});
 await test('POST identity is retained so it cannot silently become GET',()=>{const c=Context.create({});record(c,{...e,method:'POST'});assert.equal(c.resolve({url:e.url}).method,'POST');});
 await test('private requests, non-network URLs and injected header values are ignored',()=>{const c=Context.create({});record(c,{...e,incognito:true});assert.equal(c.resolve({url:e.url}),null);c.begin(e);c.headers({...e,requestHeaders:[{name:'Cookie',value:'bad\r\nHeader: yes'}]});assert.deepEqual(c.resolve({url:e.url},true).headers,{});});

 await test('synchronous native connection failure permits a fresh later connection',async()=>{const h=host();const original=h.api.runtime.connectNative;let first=true;h.api.runtime.connectNative=function(){const p=original();if(first){first=false;p.postMessage=()=>{throw Error('fixture connection lost');};}return p;};await assert.rejects(h.client.request({action:'ping'}),/connection lost/);assert((await h.client.request({action:'ping'})).ok);assert.equal(h.ports.length,2);h.client.disconnect();});
 await test('invalid page referrers cannot break request correlation',()=>{const c=Context.create({});record(c);assert.equal(c.resolve({url:e.url,referrer:'not-a-url'}),null);});
 const source=fs.readFileSync(path.join(__dirname,'../browser/chromium/page-observer.js'),'utf8');
 function observer(){let response,seen;const box={URL,TextDecoder,location:{href:'https://player.test/watch'},fetch(...args){seen=args;return Promise.resolve(response);}};vm.createContext(box);vm.runInContext(source,box);return {box,set:r=>response=r,read:()=>JSON.parse(JSON.stringify(box.__udmMediaObserverV1.read())),args:()=>seen};}
 const manifest='#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1000000,RESOLUTION=1280x720\nvideo.m3u8\n';
 await test('early observer captures an opaque manifest URL without consuming playback',async()=>{const f=observer(),r=new Response(manifest,{headers:{'content-type':'application/vnd.apple.mpegurl'}});f.set(r);const opts={headers:{Accept:'*/*'}};const returned=await f.box.fetch('https://cdn.test/opaque?id=fixture',opts);await tick();await tick();assert.equal(returned,r);assert.equal(r.bodyUsed,false);assert.deepEqual(f.args(),['https://cdn.test/opaque?id=fixture',opts]);assert.equal(f.read()[0].text,manifest);});
 await test('early observer ignores unrelated bodies and clears after SPA navigation',async()=>{const f=observer();f.set(new Response(manifest));await f.box.fetch('https://cdn.test/manifest.m3u8');await tick();await tick();assert.equal(f.read().length,1);f.box.location.href='https://player.test/next';assert.equal(f.read().length,0);f.set(new Response('not a manifest',{headers:{'content-type':'application/json'}}));await f.box.fetch('https://cdn.test/a.json');await tick();assert.equal(f.read().length,0);});
 await test('early observer bounds oversized manifests',async()=>{const f=observer();f.set(new Response(manifest,{headers:{'content-type':'application/x-mpegurl','content-length':String(3*1024*1024)}}));await f.box.fetch('https://cdn.test/large.m3u8');await tick();assert.equal(f.read().length,0);});
 await test('a playlist request begun on the previous SPA page cannot attach to the next video',async()=>{const f=observer();let release;f.set(new Promise(r=>release=r));const pending=f.box.fetch('https://cdn.test/previous.m3u8');f.box.location.href='https://player.test/next-video';release(new Response(manifest,{headers:{'content-type':'application/x-mpegurl'}}));await pending;await tick();await tick();assert.equal(f.read().length,0);});
 console.log('ALL '+count+' INTEGRATION PARITY CHECKS PASSED');
})().catch(e=>{console.error(e);process.exitCode=1;});
