const assert=require('node:assert/strict'),{policy}=require('../browser/chromium/media.js');let checks=0;
const check=(name,fn)=>{fn();checks++;console.log('PASS '+name)};
check('host exclusions include subdomains but not suffix lookalikes',()=>{const p={excluded:['example.com']};assert(policy.blocked('https://cdn.example.com/a',p));assert(!policy.blocked('https://example.com.evil.test/a',p));});
check('address patterns preserve path and query case',()=>{const p={excludedUrls:['https://*.example.com/Private/*?file=*']};assert(policy.blocked('https://cdn.example.com/Private/x?file=A',p));assert(!policy.blocked('https://cdn.example.com/private/x?file=A',p));assert(!policy.blocked('http://cdn.example.com/Private/x?file=A',p));});
check('literal pattern regex characters are escaped',()=>{const p={excludedUrls:['https://example.com/a.b?x=(1)*']};assert(policy.blocked('https://example.com/a.b?x=(1)tail',p));assert(!policy.blocked('https://example.com/axb?x=1tail',p));});
check('dangerous schemes and URL passwords rejected',()=>{assert(policy.blocked('file:///C:/a'));assert(policy.blocked('https://user:pass@example.com/a'));});
check('desktop policy cannot enable browser cookie or capture opt-in',()=>{const p=policy.merge({cookies:false,capture:false,excluded:['local.test']},{cookies:true,capture:true,excluded:['desktop.test']});assert(!p.cookies&&!p.capture);assert.equal(p.excluded.length,2);});
check('force and bypass require exact modifier combinations',()=>{assert.equal(policy.intent({altKey:true},{}),'force');assert.equal(policy.intent({ctrlKey:true},{}),'bypass');assert.equal(policy.intent({ctrlKey:true,shiftKey:true},{}),'');assert.equal(policy.intent({metaKey:true,altKey:true},{}),'');assert.equal(policy.intent({altKey:true,shiftKey:true},{forceKey:'Alt+Shift'}),'force');});
check('None disables shortcuts',()=>{assert.equal(policy.intent({ctrlKey:true},{bypassKey:'None'}),'');});
console.log('ALL '+checks+' INTEGRATION POLICY CHECKS PASSED');
