'use strict';
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const key='captureOwnershipV1';let passed=0;
function fixture({firefox=false}={}){
 const store={},calls=[],reports=[];let item={id:1,filename:'C:\\Downloads\\<img src=x>.udmreview',url:'https://example.test/file?secret=private',startTime:'2026-09-29T10:00:00.000Z',paused:true,state:'in_progress',bytesReceived:8};
 let saveFailure=false,nativeFailure=false,cancelFailure=false,resumeFailure=false,noCancel=false,noResume=false,barrier='released',onBarrier=null;
 const api={runtime:{getURL:value=>(firefox?'moz-extension://fixture/':'chrome-extension://fixture/')+value},storage:{local:{get:async k=>({[k]:structuredClone(store[k])}),set:async data=>{if(saveFailure)throw Error('disk full');Object.assign(store,structuredClone(data));}}},alarms:{create:async()=>{},clear:async()=>{}},downloads:{search:async()=>item?[structuredClone(item)]:[],cancel:async id=>{calls.push('cancel');if(cancelFailure)throw Error('cancel failed');if(!noCancel)Object.assign(item,{state:'interrupted',paused:false,error:'USER_CANCELED'});},resume:async id=>{calls.push('resume');if(resumeFailure)throw Error('resume failed');if(!noResume)Object.assign(item,{state:'in_progress',paused:false,error:undefined});}}};
 async function native(message){calls.push(message.action);if(nativeFailure)throw Error('host unavailable');if(message.action==='capture-legacy-release'){assert.equal(message.confirmed,true);if(onBarrier)await onBarrier();return {ok:true,status:barrier};}if(message.action==='capture-reconcile')return {ok:true,status:'uncertain'};throw Error('unexpected native action '+message.action);}
 function module(){const sandbox={crypto:crypto.webcrypto,URL,Date,TextEncoder,Uint8Array,browser:api,module:{exports:{}}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../browser/chromium/capture-recovery.js'),'utf8'),sandbox);return sandbox.UdmCaptureRecovery.create(api,native,async m=>reports.push(m));}
 async function seed(protocol=1,phase='submitting'){const initial=module(),r=await initial.begin(item);store[key][r.token].protocol=protocol;store[key][r.token].phase=phase;return r.token;}
 return {store,calls,reports,api,module,seed,get item(){return item;},set item(value){item=value;},set saveFailure(v){saveFailure=v;},set nativeFailure(v){nativeFailure=v;},set cancelFailure(v){cancelFailure=v;},set resumeFailure(v){resumeFailure=v;},set noCancel(v){noCancel=v;},set noResume(v){noResume=v;},set barrier(v){barrier=v;},set onBarrier(v){onBarrier=v;},count:()=>Object.keys(store[key]||{}).length};
}
async function check(name,fn){await fn();console.log('PASS '+name);passed++;}
(async()=>{
 for(const protocol of [0,1])for(const decision of ['browser','native','dismiss'])await check('Explicit '+decision+' decision resolves legacy protocol '+protocol,async()=>{
  const h=fixture(),token=await h.seed(protocol),m=h.module();const list=await m.reviews();assert.equal(list.items.length,1);assert.equal(list.items[0].name,'<img src=x>.udmreview');assert.equal(list.items[0].host,'example.test');assert(!JSON.stringify(list).includes('private'));
  const r=await m.resolve(token,decision,true);assert.equal(r.owner,decision);assert.equal(h.count(),0);assert.deepEqual(h.calls,[...(protocol===1?['capture-legacy-release']:[]),...(decision==='browser'?['resume']:decision==='native'?['cancel']:[])]);
 });
 await check('No choice or unconfirmed choice never acts',async()=>{const h=fixture(),token=await h.seed();for(const [decision,confirm] of [['browser',false],['native',undefined],['erase',true]])await assert.rejects(h.module().resolve(token,decision,confirm));assert.equal(h.calls.length,0);assert.equal(h.store[key][token].phase,'submitting');});
 await check('Reading and automatic recovery leave an uncertain download paused',async()=>{const h=fixture();await h.seed();const m=h.module();await m.reviews();await m.recover();assert.deepEqual(h.calls,['capture-reconcile']);assert(h.item.paused);assert.equal(h.count(),1);});
 await check('Saved browser choice survives a lost barrier reply without resubmitting Add',async()=>{const h=fixture(),token=await h.seed();h.nativeFailure=true;await assert.rejects(h.module().resolve(token,'browser',true));assert.equal(h.store[key][token].phase,'browser-selected');assert(h.item.paused);h.nativeFailure=false;await h.module().recover();assert.deepEqual(h.calls,['capture-legacy-release','capture-legacy-release','resume']);assert.equal(h.count(),0);});
 await check('Saved cancellation retries after worker restart',async()=>{const h=fixture(),token=await h.seed(0);h.cancelFailure=true;await assert.rejects(h.module().resolve(token,'native',true));h.cancelFailure=false;await h.module().recover();assert.deepEqual(h.calls,['cancel','cancel']);assert.equal(h.count(),0);});
 await check('Failed resume stays pending and can complete after restart',async()=>{const h=fixture(),token=await h.seed();h.resumeFailure=true;await assert.rejects(h.module().resolve(token,'browser',true));h.resumeFailure=false;await h.module().recover();assert.equal(h.calls.filter(x=>x==='resume').length,2);assert.equal(h.count(),0);});
 await check('A failed initial choice checkpoint makes no browser or native call',async()=>{const h=fixture(),token=await h.seed();h.saveFailure=true;await assert.rejects(h.module().resolve(token,'browser',true));assert.equal(h.calls.length,0);assert.equal(h.store[key][token].phase,'submitting');});
 await check('A pending choice cannot be silently changed',async()=>{const h=fixture(),token=await h.seed();h.nativeFailure=true;await assert.rejects(h.module().resolve(token,'browser',true));await assert.rejects(h.module().resolve(token,'native',true),/saved choice/);assert.equal(h.store[key][token].phase,'browser-selected');});
 for(const change of ['url','startTime','removed','complete'])await check('Browser '+change+' during native review is not operated on',async()=>{const h=fixture(),token=await h.seed();h.onBarrier=()=>{if(change==='removed')h.item=null;else if(change==='complete')h.item.state='complete';else if(change==='startTime')h.item.startTime='2026-09-29T11:00:00.000Z';else h.item[change]+='changed';};await h.module().resolve(token,'browser',true);assert.deepEqual(h.calls,['capture-legacy-release']);assert.equal(h.count(),0);});
 await check('A stale review cannot target a reused browser download ID',async()=>{const h=fixture(),token=await h.seed();h.item.url='https://new.test/new';await assert.rejects(h.module().resolve(token,'native',true),/no longer available/);assert.equal(h.calls.length,0);});
 await check('A newly discovered accepted native receipt keeps the browser canceled',async()=>{const h=fixture(),token=await h.seed();h.barrier='accepted';const r=await h.module().resolve(token,'browser',true);assert.equal(r.owner,'native');assert.deepEqual(h.calls,['capture-legacy-release','cancel']);});
 for(const decision of ['browser','native'])await check('Resolved API alone is insufficient to confirm '+decision+' ownership',async()=>{const h=fixture(),token=await h.seed(0);if(decision==='native')h.noCancel=true;else h.noResume=true;await assert.rejects(h.module().resolve(token,decision,true),/not confirmed|not resumed/);assert.equal(h.count(),1);});
 await check('A dismissed already-accepted receipt changes neither copy',async()=>{const h=fixture(),token=await h.seed();h.barrier='accepted';const r=await h.module().resolve(token,'dismiss',true);assert.equal(r.owner,'dismiss');assert.deepEqual(h.calls,['capture-legacy-release']);assert(h.item.paused);});
 await check('Firefox zero-byte cancellation is not proof that resume works',async()=>{const h=fixture({firefox:true}),token=await h.seed(0);Object.assign(h.item,{paused:false,state:'interrupted',bytesReceived:0,canResume:false,error:'USER_CANCELED'});const m=h.module();assert.equal((await m.reviews()).items[0].resumable,false);await assert.rejects(m.resolve(token,'browser',true),/cannot resume/);assert.deepEqual(h.calls,[]);assert.equal(h.count(),1);});
 await check('Firefox explicit resume capability permits a recoverable response',async()=>{const h=fixture({firefox:true}),token=await h.seed(0);Object.assign(h.item,{paused:false,state:'interrupted',bytesReceived:0,canResume:true,error:'USER_CANCELED'});const m=h.module();assert.equal((await m.reviews()).items[0].resumable,true);await m.resolve(token,'browser',true);assert.deepEqual(h.calls,['resume']);});
 await check('Explicit browser refusal takes priority over the paused flag',async()=>{const h=fixture(),token=await h.seed(0);Object.assign(h.item,{state:'interrupted',canResume:false});await assert.rejects(h.module().resolve(token,'browser',true),/cannot resume/);assert.deepEqual(h.calls,[]);});
 await check('Refreshing recovery reflects a newly resumable browser response',async()=>{const h=fixture({firefox:true});await h.seed(0);Object.assign(h.item,{paused:false,state:'interrupted',canResume:false});const m=h.module();assert.equal((await m.reviews()).items[0].resumable,false);h.item.canResume=true;assert.equal((await m.reviews()).items[0].resumable,true);});
 await check('An unavailable saved resume choice remains dismissible without replay',async()=>{const h=fixture({firefox:true}),token=await h.seed(0,'browser-selected');Object.assign(h.item,{paused:false,state:'interrupted',bytesReceived:0,canResume:false,error:'USER_CANCELED'});const m=h.module(),review=(await m.reviews()).items[0];assert.equal(review.decision,'browser');assert.equal(review.resumable,false);await m.resolve(token,'dismiss',true);assert.equal(h.count(),0);assert.deepEqual(h.calls,[]);});
 await check('Edge browser API alias does not make a canceled response resumable',async()=>{const h=fixture(),token=await h.seed();Object.assign(h.item,{paused:false,state:'interrupted',bytesReceived:0,canResume:false,error:'USER_CANCELED'});const m=h.module();assert.equal((await m.reviews()).items[0].resumable,false);await assert.rejects(m.resolve(token,'browser',true),/cannot resume/);assert.deepEqual(h.calls,['capture-legacy-release']);});
 await check('Resumable Chromium interruption after restart uses the same browser record',async()=>{const h=fixture(),token=await h.seed();Object.assign(h.item,{paused:false,state:'interrupted',canResume:true,error:'CRASH'});await h.module().resolve(token,'browser',true);assert.deepEqual(h.calls,['capture-legacy-release','resume']);assert.equal(h.count(),0);});
 await check('An unresumable response can be handled manually and its notice explicitly dismissed',async()=>{const h=fixture(),token=await h.seed();Object.assign(h.item,{paused:false,state:'interrupted',canResume:false,error:'NETWORK_FAILED'});const m=h.module();await assert.rejects(m.resolve(token,'browser',true),/cannot resume/);assert.equal(h.count(),1);await m.resolve(token,'dismiss',true);assert.deepEqual(h.calls,['capture-legacy-release','capture-legacy-release']);assert.equal(h.count(),0);});
 await check('Protocol-2 saved requests are not exposed to legacy choices',async()=>{const h=fixture(),token=await h.seed(2,'committing');assert.equal((await h.module().reviews()).items.length,0);await assert.rejects(h.module().resolve(token,'dismiss',true));assert.equal(h.calls.length,0);});
 await check('Overlapping choices and automatic recovery cannot act twice',async()=>{const h=fixture(),token=await h.seed();let release;const wait=new Promise(r=>release=r);h.onBarrier=()=>wait;const m=h.module(),work=m.resolve(token,'native',true);await new Promise(r=>setImmediate(r));await assert.rejects(m.resolve(token,'browser',true),/being recovered/);assert.equal((await m.recover()).recovered,0);release();await work;assert.equal(h.calls.filter(x=>x==='cancel').length,1);});
 await check('Review choices persist no address, name, credentials or body',async()=>{const h=fixture(),token=await h.seed();h.nativeFailure=true;await assert.rejects(h.module().resolve(token,'browser',true));const value=JSON.stringify(h.store);for(const secret of ['https:','private','example.test','img','Downloads'])assert(!value.includes(secret));});
 assert.equal(fs.readFileSync(path.join(__dirname,'../browser/chromium/capture-recovery.js'),'utf8'),fs.readFileSync(path.join(__dirname,'../browser/firefox/capture-recovery.js'),'utf8'));
 console.log(passed+' legacy review checks passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
