'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawn,execFileSync}=require('node:child_process'),{chromium}=require('playwright');
const stage=__dirname,root=path.resolve(process.argv[2]),project=process.env.UDM_PROJECT||path.resolve(__dirname,'..'),release=process.env.UDM_TEST_RELEASE||path.join(project,'release-native'),id='aqz-KE-bpKQ',url='https://www.youtube.com/watch?v='+id,tag='direct'+crypto.randomBytes(6).toString('hex'),hostName='com.udm.directfixture'+Date.now(),registry='HKCU\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\'+hostName;
const report={videoId:id,scope:'Public Big Buck Bunny page in isolated Edge with original extension capture, actual native host and C++ transfer objects. Desktop arm/apply actions use a test probe; no account cookies or resolver subprocess.',checks:[],startedUtc:new Date().toISOString()};let probe,browser,page,worker,registered=false,serial=0;
const wait=ms=>new Promise(r=>setTimeout(r,ms)),pass=(name,detail={})=>{report.checks.push({passed:true,name,...detail});console.log('PASS '+name);};
async function until(fn,ms=45000){const deadline=Date.now()+ms;while(Date.now()<deadline){const v=await fn();if(v)return v;await wait(150);}throw Error('Public video recovery timed out');}
const jobs=()=>{try{return JSON.parse(fs.readFileSync(path.join(root,'state/state.json'))).Downloads;}catch{return [];}};
async function command(action,id){const n=++serial,p=path.join(root,n+'.command.json');fs.writeFileSync(p+'.tmp',JSON.stringify({action,id}));fs.renameSync(p+'.tmp',p);if(action==='quit')return;const out=path.join(root,n+'.reply.json');const value=await until(()=>fs.existsSync(out)&&JSON.parse(fs.readFileSync(out)));assert.equal(value.ok,true,value.error);return value;}
async function click(name){const s=await browser.newCDPSession(page);try{const n=await until(async()=>{const t=await s.send('Accessibility.getFullAXTree');return t.nodes.find(x=>!x.ignored&&x.role?.value==='button'&&name(x.name?.value||''));});const {model}=await s.send('DOM.getBoxModel',{backendNodeId:n.backendDOMNodeId}),q=model.content;await page.mouse.click((q[0]+q[2])/2,(q[1]+q[5])/2);}finally{await s.detach();}}
async function choose(){
 report.phase='Find video panel';await until(()=>page.locator('[id^="udm-video-panel-"]:visible').count(),60000);
 const session=await browser.newCDPSession(page);let opens=0,lastOpen=0;
 try{report.phase='Select 360p';await until(async()=>{
  const tree=await session.send('Accessibility.getFullAXTree');const nodes=tree.nodes.filter(n=>!n.ignored&&n.role?.value==='button');
  const choice=nodes.find(n=>/360p/.test(n.name?.value||''));
  if(choice){await session.send('DOM.focus',{backendNodeId:choice.backendDOMNodeId});await page.keyboard.press('Enter');return true;}
  const toggle=nodes.find(n=>n.name?.value==='Download this video with UDM');const expanded=toggle?.properties?.find(p=>p.name==='expanded')?.value?.value;
  if(toggle&&expanded===false&&Date.now()-lastOpen>1500){if(++opens>4)throw Error('Video panel repeatedly closed during playback initialization');lastOpen=Date.now();await session.send('DOM.focus',{backendNodeId:toggle.backendDOMNodeId});await page.keyboard.press('Enter');}
  return false;
 },45000);}finally{await session.detach();}
}

(async()=>{
 assert(!fs.existsSync(root));fs.mkdirSync(root,{recursive:true});const env={...process.env,UDM_INSTANCE_TAG:tag};probe=spawn(path.join(release,'DirectRefreshProbe.exe'),[root],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});let log='';probe.stderr.on('data',b=>log+=b);await until(()=>{if(probe.exitCode!==null)throw Error(log);return fs.existsSync(path.join(root,'ready.json'));});
 const ext=path.join(root,'extension');fs.cpSync(path.join(project,'browser/chromium'),ext,{recursive:true});const bg=path.join(ext,'background.js');fs.writeFileSync(bg,fs.readFileSync(bg,'utf8').replace("'com.udm.download_manager'",JSON.stringify(hostName)));const manifest=path.join(root,'host.json');fs.writeFileSync(manifest,JSON.stringify({name:hostName,description:'Isolated UDM direct video refresh fixture',path:path.join(release,'Udm.NativeHost.exe'),type:'stdio',allowed_origins:['chrome-extension://'+fs.readFileSync(path.join(project,'browser/extension-id.txt'),'utf8').trim()+'/']}));let exists=false;try{execFileSync('reg.exe',['query',registry],{windowsHide:true,stdio:'ignore'});exists=true;}catch{}assert(!exists);execFileSync('reg.exe',['add',registry,'/ve','/t','REG_SZ','/d',manifest,'/f'],{windowsHide:true,stdio:'ignore'});registered=true;
 browser=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'msedge',headless:true,ignoreDefaultArgs:['--disable-extensions'],env,viewport:{width:1200,height:820},args:['--enable-unsafe-extension-debugging','--autoplay-policy=no-user-gesture-required']});const cdp=await browser.browser().newBrowserCDPSession();await cdp.send('Extensions.loadUnpacked',{path:ext});worker=browser.serviceWorkers()[0]||await browser.waitForEvent('serviceworker');const hello=await worker.evaluate(()=>nativeRequest({action:'hello'}));assert.equal(hello.version,'0.69.0');assert(hello.capabilities.includes('direct-media-refresh'));pass('Edge connects to the candidate native direct-refresh capability');page=browser.pages()[0]||await browser.newPage();await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});await choose();const job=await until(()=>jobs().find(j=>j.SourceUrl===url));const direct=!job.ProtectedSabr;report.transport=direct?'direct':'SABR';assert(job.Video);pass('Trusted public YouTube panel click captures video/audio using '+report.transport,{height:job.MediaHeight,formatId:job.MediaFormatId,hasSeparateAudio:!!job.Audio});
 await command('start',job.Id);await until(async()=>{const j=await command('status',job.Id);if(j.status==='Failed')throw Error(j.error);if(j.status==='Complete')throw Error('Download completed before the pause threshold');return j.received>=262144;},60000);await command('pause',job.Id);const paused=await until(async()=>{const j=await command('status',job.Id);return j.status==='Paused'&&j;});assert(paused.received>0);pass('Real '+report.transport+' transfer pauses with retained bytes',{retainedBytes:paused.received,videoBytes:paused.videoReceived,audioBytes:paused.audioReceived});
 report.phase='Arm refresh';await command('arm',job.Id);report.phase='Reload original page';await page.reload({waitUntil:'domcontentloaded'});await choose();report.phase='Wait for matching refresh offer';await until(()=>jobs().find(j=>j.Id===job.Id)?.ProtectedRefreshOffer);assert.equal(jobs().length,1);pass('A fresh public browser capture is staged on the same paused download');await page.screenshot({path:path.join(root,'refresh-panel.png')});const applied=await command('apply',job.Id);if(direct)assert(applied.pending);assert.equal(applied.status,'Paused');const begin=performance.now();report.phase='Resume refreshed capture';await command('start',job.Id);const finished=await until(async()=>{const j=await command('status',job.Id);if(j.status==='Failed')throw Error(j.error);return j.status==='Complete'&&j;},180000);const elapsed=performance.now()-begin;assert.equal(jobs().length,1);const info=JSON.parse(execFileSync(path.join(release,'tools/ffprobe.exe'),['-v','error','-show_streams','-show_format','-of','json',finished.target],{windowsHide:true}));assert(info.streams.some(x=>x.codec_type==='video'&&x.height===360));assert(info.streams.some(x=>x.codec_type==='audio'));pass('Refreshed public '+report.transport+' capture resumes and produces 360p video with audio',{resumeToCompleteSeconds:elapsed/1000,bytes:fs.statSync(finished.target).size,duration:info.format.duration});report.outcome='Complete';
})().catch(e=>{report.outcome='Public acceptance did not complete';report.error=String(e.message).replace(/https?:\/\/[^\s]+/g,'[URL]').slice(0,600);console.error(report.error);process.exitCode=1;}).finally(async()=>{try{if(worker)report.playerDiagnostics=await worker.evaluate(()=>[...playerReports.values()]);if(page)report.playback=await page.evaluate(()=>{const v=document.querySelector('video'),p=document.getElementById('movie_player');return {readyState:v?.readyState,paused:v?.paused,playerVideoId:p?.getVideoData?.()?.video_id,advertisement:!!p?.classList.contains('ad-showing')};});}catch{}try{if(page)await page.screenshot({path:path.join(root,'last-page.png')});}catch{}if(browser)await browser.close();if(probe&&probe.exitCode===null){try{await command('quit');await until(()=>probe.exitCode!==null,10000);}catch{probe.kill();}}if(registered)execFileSync('reg.exe',['delete',registry,'/f'],{windowsHide:true,stdio:'ignore'});report.registryRemoved=registered;report.finishedUtc=new Date().toISOString();fs.writeFileSync(path.join(root,'result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));});
