'use strict';
const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const output=path.resolve(__dirname,'../benchmarks/workflows-0.13.0');fs.mkdirSync(output,{recursive:true});
const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><body style="font:16px Arial;padding:30px"><p id="selected">Download <a href="/one.zip">First file</a>, <a href="/two.iso">Second file</a>, <a href="/one.zip">duplicate</a> and <a href="javascript:void(0)">unsafe</a></p><a href="/outside.zip">Outside selection</a></body></html>');});
let browser;const results=[];async function check(name,fn){await fn();results.push({name,passed:true});console.log('PASS '+name);}
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1100,height:700}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 await page.evaluate(()=>{window.sent=[];window.preferenceListener=null;window.chrome={storage:{local:{get:async()=>({settings:{}})},onChanged:{addListener:fn=>window.preferenceListener=fn,removeListener:()=>{}}},runtime:{sendMessage:async message=>{sent.push(message);return {ok:true,count:message.urls.length};}}};});
 await page.addScriptTag({path:path.resolve(__dirname,'../browser/chromium/selection.js')});
 const select=()=>page.evaluate(()=>{const range=document.createRange();range.selectNodeContents(document.querySelector('#selected'));const selection=getSelection();selection.removeAllRanges();selection.addRange(range);});
 const panel=page.locator('#udm-selected-links-panel');
 await check('Selected text creates a panel containing only unique HTTP links in the selection',async()=>{await select();await panel.waitFor();await page.getByRole('button',{name:'Download selected links with UDM',exact:true}).click();assert.equal(await panel.getByRole('checkbox').count(),2);assert.equal((await page.evaluate(()=>sent)).length,0);});
 await check('No link is sent before confirmation, and unchecked links are excluded',async()=>{await panel.getByRole('checkbox').nth(1).uncheck();await panel.getByRole('button',{name:'Download selected',exact:true}).click();await page.waitForFunction(()=>sent.length===1);const sent=await page.evaluate(()=>window.sent[0]);assert.equal(sent.action,'selected-links');assert.equal(sent.urls.length,1);assert.match(sent.urls[0],/\/one.zip$/);assert.match(await panel.getByRole('status').textContent(),/Added 1 links/);});
 await check('Turning the selected-link panel off removes it without changing selection',async()=>{await page.evaluate(()=>preferenceListener({settings:{newValue:{selectedLinks:'off'}}},'local'));await panel.waitFor({state:'detached'});assert.ok(await page.evaluate(()=>getSelection().toString().length));});
 await check('Site-specific mode rejects unlisted sites',async()=>{await page.evaluate(()=>preferenceListener({settings:{newValue:{selectedLinks:'sites',selectedLinkHosts:['example.com']}}},'local'));assert.equal(await panel.count(),0);});
 await check('Site-specific mode and compact view work on an allowed host',async()=>{await page.evaluate(()=>preferenceListener({settings:{newValue:{selectedLinks:'sites',selectedLinkHosts:['127.0.0.1'],selectedLinksMini:true}}},'local'));await panel.waitFor();assert.equal(await panel.getByRole('button',{name:'Download selected links with UDM'}).textContent(),'↓ UDM');});
 await check('Excluded hosts override selected-link preferences',async()=>{await page.evaluate(()=>preferenceListener({settings:{newValue:{selectedLinks:'all',excluded:['127.0.0.1']}}},'local'));await panel.waitFor({state:'detached'});});
 await check('Clearing the selection removes the panel',async()=>{await page.evaluate(()=>preferenceListener({settings:{newValue:{}}},'local'));await panel.waitFor();await page.evaluate(()=>getSelection().removeAllRanges());await panel.waitFor({state:'detached'});});
 assert.deepEqual(errors,[]);await page.screenshot({path:path.join(output,'selection-panel-test.png')});console.log('ALL '+results.length+' SELECTED-LINK BROWSER CHECKS PASSED');
})().catch(e=>{results.push({passed:false,error:e.stack});console.error(e);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(output,'selection-results.json'),JSON.stringify(results,null,2));if(browser)await browser.close();server.close();});
