'use strict';
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const project=path.resolve(__dirname,'..'),Access=require('../browser/chromium/site-access.js'),root=path.resolve(process.argv[2]),results=[];
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<70;i++){const result=await fn();if(result)return result;await wait(100);}throw Error('Timed out waiting for panel');}
async function scenario(name,origins,expected,allSites=false){const dir=path.join(root,name),ext=path.join(dir,'extension');fs.mkdirSync(dir,{recursive:true});fs.cpSync(path.join(project,'browser/chromium'),ext,{recursive:true});const manifest=JSON.parse(fs.readFileSync(path.join(ext,'manifest.json')));if(!allSites){manifest.host_permissions=origins;manifest.content_scripts=manifest.content_scripts.filter(s=>s.js.includes('content.js')||s.js.includes('page-observer.js')).map(s=>({...s,matches:origins}));}fs.writeFileSync(path.join(ext,'manifest.json'),JSON.stringify(manifest));let ctx;
try{ctx=await chromium.launchPersistentContext(path.join(dir,'profile'),{headless:true,channel:'chrome',ignoreDefaultArgs:['--disable-extensions'],viewport:{width:1100,height:800},args:['--enable-unsafe-extension-debugging','--autoplay-policy=no-user-gesture-required']});
await ctx.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='www.dailymotion.com')return route.fulfill({contentType:'text/html',body:'<!doctype html><title>Cross-origin permission fixture</title><iframe title="video" width="800" height="500" src="https://geo.dailymotion.com/player/test.html"></iframe><iframe src="https://unrelated.example.test/"></iframe>'});
if(u.hostname==='geo.dailymotion.com')return route.fulfill({contentType:'text/html',body:'<!doctype html><title>Synthetic media player</title><body style="margin:30px 8px"><video controls autoplay loop muted style="width:720px;height:405px" src="https://video.dmcdn.net/sample.mp4"></video>'});
if(u.hostname==='video.dmcdn.net')return route.fulfill({contentType:'video/mp4',body:fs.readFileSync(path.join(project,'native/browser-fixture-data/sample.mp4'))});
if(u.hostname==='unrelated.example.test')return route.fulfill({contentType:'text/html',body:'<!doctype html><title>Unrelated frame</title><video style="width:400px;height:250px"></video>'});return route.abort();});
const cdp=await ctx.browser().newBrowserCDPSession();await cdp.send('Extensions.loadUnpacked',{path:ext});const worker=ctx.serviceWorkers()[0]||await ctx.waitForEvent('serviceworker');await worker.evaluate(()=>UdmSites.sync());const page=await ctx.newPage();await page.goto('https://www.dailymotion.com/video/fixture');const frame=await until(()=>page.frames().find(f=>f.url().startsWith('https://geo.dailymotion.com/')));await frame.waitForSelector('video');await frame.waitForFunction(()=>document.querySelector('video').videoHeight===360);await wait(1800);
const state=()=>frame.evaluate(()=>({panels:[...document.querySelectorAll('[id^="udm-video-panel-"]')].filter(p=>getComputedStyle(p).display!=='none').length,marker:!!document.querySelector('video').getAttribute('data-udm-player')}));let observed=await state();assert.equal(observed.panels,expected);assert.equal(observed.marker,!!expected);results.push({name:name+' cross-origin player panel',passed:true,...observed});console.log('PASS '+name+' panel count '+expected);
if(expected){
 const tabId=await worker.evaluate(async()=> (await chrome.tabs.query({url:'https://www.dailymotion.com/*'}))[0].id);
 const activations=await worker.evaluate(async tabId=>Promise.all([UdmSites.sync(true,tabId),UdmSites.sync(true,tabId),UdmSites.sync(true,tabId)]),tabId);assert.equal((await worker.evaluate(()=>chrome.scripting.getRegisteredContentScripts({ids:['udm-video-panels']}))).length,1);
 assert.equal((await state()).panels,1);results.push({name:'concurrent sync preserves single registration and panel',passed:true,activations});console.log('PASS concurrent activation');
 const detail=await frame.evaluate(()=>({page:location.href,token:document.querySelector('video').getAttribute('data-udm-player')}));
 const catalog=await worker.evaluate(async({tabId,detail})=>{const frame=(await chrome.scripting.executeScript({target:{tabId,allFrames:true},func:()=>({url:location.href})})).find(x=>x.result.url===detail.page);return UdmSites.list(detail,{tab:{id:tabId},frameId:frame.frameId,documentId:frame.documentId,url:detail.page});},{tabId,detail});assert.equal(catalog.choices.length,1);assert.match(catalog.choices[0].label,/360p/);results.push({name:'embedded panel identifies actual 360p source',passed:true,choices:catalog.choices.map(x=>x.label)});console.log('PASS embedded source catalog');
 const other=page.frames().find(f=>f.url().startsWith('https://unrelated.example.test/'));assert.equal(await other.locator('[id^="udm-video-panel-"]').count(),allSites?1:0);results.push({name:allSites?'all-site access covers unrelated embedded player':'unrelated host remains ungranted',passed:true});console.log('PASS embedded frame respects actual scope');
 await page.reload();const again=await until(()=>page.frames().find(f=>f.url().startsWith('https://geo.dailymotion.com/')));await until(()=>again.locator('[id^="udm-video-panel-"]').count());results.push({name:'panel persists across navigation',passed:true});console.log('PASS panel after reload');
}
await page.screenshot({path:path.join(dir,'result.png')});
}finally{await ctx?.close();}}
(async()=>{fs.mkdirSync(root,{recursive:true});await scenario('before-parent-only',['https://www.dailymotion.com/*'],0);await scenario('after-platform-scope',Access.origins('https://www.dailymotion.com/video/fixture'),1);await scenario('current-all-sites',[],1,true);assert.deepEqual(Access.origins('https://dailymotion.com.evil.test/'),['https://dailymotion.com.evil.test/*']);console.log('ALL CROSS-ORIGIN EXTENSION CHECKS PASSED');})().catch(e=>{console.error(e);results.push({passed:false,error:e.message});process.exitCode=1;}).finally(()=>fs.writeFileSync(path.join(root,'regression-results.json'),JSON.stringify({scope:'Real Chrome extension, synthetic page/player/CDN responses; fixture permissions pre-granted only in isolated profiles',results},null,2)));
