'use strict';
// Real Chrome, synthetic HTTPS routes only. No request reaches YouTube or Googlevideo.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(process.argv[2]),project=path.resolve(__dirname,'..'),id='abcdefghijk',url='https://www.youtube.com/watch?v='+id,endpoint='https://rr1.googlevideo.com/videoplayback?sabr=1';let context;const report={scope:'Real Chrome extension; synthetic routed HTTPS player and worker; no live media service'};
(async()=>{fs.mkdirSync(root,{recursive:true});context=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'chrome',headless:true,ignoreDefaultArgs:['--disable-extensions'],args:['--enable-unsafe-extension-debugging']});
 const cdp=await context.browser().newBrowserCDPSession();await cdp.send('Extensions.loadUnpacked',{path:path.join(project,'browser/chromium')});const worker=context.serviceWorkers()[0]||await context.waitForEvent('serviceworker');
 await worker.evaluate(()=>{globalThis.requestEvidence=[];chrome.webRequest.onBeforeRequest.addListener(e=>{requestEvidence.push({phase:'request',requestId:e.requestId,tabId:e.tabId,frameId:e.frameId,documentId:e.documentId,initiator:e.initiator,method:e.method,bodyBytes:e.requestBody?.raw?.reduce((n,p)=>n+(p.bytes?.byteLength||0),0)});},{urls:['https://*.googlevideo.com/*']},['requestBody']);chrome.webRequest.onHeadersReceived.addListener(e=>{requestEvidence.push({phase:'response',requestId:e.requestId,tabId:e.tabId,frameId:e.frameId,documentId:e.documentId,status:e.statusCode});},{urls:['https://*.googlevideo.com/*']});});
 await context.route('**/*',async route=>{const request=route.request(),u=new URL(request.url());if(u.hostname==='rr1.googlevideo.com'){return route.fulfill({status:request.method()==='OPTIONS'?204:200,headers:{'access-control-allow-origin':'https://www.youtube.com','access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type','content-type':'application/vnd.yt-ump'},body:request.method()==='OPTIONS'?'':Buffer.from([20,13,18,11,...Buffer.from(id)])});}
 if(u.hostname==='www.youtube.com'&&u.pathname==='/watch')return route.fulfill({contentType:'text/html',body:`<!doctype html><title>UDM isolated worker capture fixture</title><div id="movie_player"></div><script>
 const p=document.getElementById('movie_player');p.getVideoData=()=>({video_id:'${id}'});p.getAvailableQualityLevels=()=>['hd1080'];p.getPlayerResponse=()=>({videoDetails:{videoId:'${id}',lengthSeconds:'1'},streamingData:{adaptiveFormats:[{itag:137,height:1080,width:1920,mimeType:'video/mp4; codecs="avc1"',lastModified:'123'},{itag:140,mimeType:'audio/mp4; codecs="mp4a"',lastModified:'456'}]}});
 window.startWorker=()=>{const source="fetch('${endpoint}',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:new Uint8Array([42,1,1,154,1,2,8,1])}).then(r=>r.arrayBuffer()).then(b=>postMessage({bytes:b.byteLength})).catch(e=>postMessage({error:e.message}))";const w=new Worker(URL.createObjectURL(new Blob([source],{type:'text/javascript'})));w.onmessage=e=>{window.workerResult=e.data;w.terminate();};};</script>`});return route.fulfill({status:404,body:''});});
 const page=context.pages()[0]||await context.newPage();await page.goto(url);await page.waitForFunction(()=>!!globalThis.__udmCaptureV1);await page.evaluate(()=>startWorker());await page.waitForFunction(()=>!!window.workerResult);await new Promise(r=>setTimeout(r,1500));
 report.worker=await page.evaluate(()=>workerResult);report.observer=await page.evaluate(()=>__udmCaptureV1.diagnostics());report.browser=await worker.evaluate(async({url,id})=>{const tab=(await chrome.tabs.query({url:['https://www.youtube.com/*']}))[0];const context=await availableMedia({url,tabId:tab.id},{});const s=await UdmStreamingCapture.session(context);return {counts:UdmStreamingCapture.diagnostics(tab.id),events:requestEvidence,captured:!!s,videoId:s?.videoId,bodyMatches:s?.body===btoa(String.fromCharCode(42,1,1,154,1,2,8,1))};},{url,id});
 assert.equal(report.observer.requests,0);assert.equal(report.worker.bytes,15);assert.equal(report.browser.captured,true);assert.equal(report.browser.bodyMatches,true);report.passed=true;console.log('PASS Real Chrome captures a worker streaming request missed by the page observer');
})().catch(e=>{report.passed=false;report.error=e.message;process.exitCode=1;}).finally(async()=>{if(context)await context.close();fs.writeFileSync(path.join(root,'result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));});
