'use strict';
// Opt-in diagnostic against the public service. Never reports fixture success
// as live CDN compatibility, and never saves signed stream URLs in its report.
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn,execFileSync}=require('node:child_process');
const root=path.resolve(process.argv[2]),id=process.argv[3]||'Q3TI27IN7X0',url='https://www.youtube.com/watch?v='+id,tag='ytaLive'+crypto.randomBytes(6).toString('hex'),state=path.join(root,'state/state.json'),project=path.resolve(__dirname,'..'),report={scope:'Public YouTube in a fresh Edge profile, production capture and audio handoff; optional test transport forwards unchanged messages to the staged native host',videoId:id,started:new Date().toISOString()};
let browser,app,page,worker,nativeBridge;const wait=ms=>new Promise(r=>setTimeout(r,ms));function jobs(){try{return JSON.parse(fs.readFileSync(state)).Downloads;}catch{return [];}}
(async()=>{
 if(!/^[\w-]{11}$/.test(id)||fs.existsSync(state))throw Error('Provide a valid ID and a fresh output directory');fs.mkdirSync(path.dirname(state),{recursive:true});
 fs.writeFileSync(state,JSON.stringify({Schema:1,Settings:{DownloadFolder:path.join(root,'downloads'),CategoryFolders:false,Connections:4,Parallel:1,Retries:0,SkipBrowserFileInfo:true,PrefetchFileInfo:false,SuppressProgressDialog:true,SuppressCompletionDialog:true,Sound:false},Queues:[{Name:'Main queue',Enabled:true,Parallel:1}],Downloads:[],Projects:[]}));
 app=spawn(process.env.UDM_APP_EXE,['--background','--data-dir',path.dirname(state),'--instance-tag',tag],{windowsHide:true,stdio:'ignore'});
 browser=await chromium.launchPersistentContext(path.join(root,'profile'),{channel:'msedge',headless:true,ignoreDefaultArgs:['--disable-extensions'],env:{...process.env,UDM_INSTANCE_TAG:tag},args:['--enable-unsafe-extension-debugging','--autoplay-policy=no-user-gesture-required']});const cdp=await browser.browser().newBrowserCDPSession();await cdp.send('Extensions.loadUnpacked',{path:path.join(project,'browser/chromium')});worker=browser.serviceWorkers()[0]||await browser.waitForEvent('serviceworker');if(process.env.UDM_HOST_EXE){nativeBridge=await require('./isolated-native-bridge.cjs')(process.env.UDM_HOST_EXE,tag);await worker.evaluate(url=>{nativeRequest=async message=>(await fetch(url,{method:'POST',body:JSON.stringify(message)})).json();},nativeBridge.url);}
 const diagnostic=await worker.evaluate(()=>nativeRequest({action:'diagnostics'}));if(!diagnostic.ok||path.resolve(diagnostic.dataDirectory).toLowerCase()!==path.dirname(state).toLowerCase())throw Error('Wrong native instance');report.nativeVersion=diagnostic.version;
 await worker.evaluate(()=>{const original=nativeRequest;globalThis.lastAudioOffer=null;nativeRequest=m=>{if(m.action==='sabr'&&m.output==='audio')lastAudioOffer=m;return original(m);};});
 page=await browser.newPage();await page.goto(url,{waitUntil:'domcontentloaded',timeout:45000});
 for(let n=0;n<30;n++){
  const u=new URL(page.url());if((u.hostname==='google.com'||u.hostname.endsWith('.google.com'))&&u.pathname.startsWith('/sorry')){report.outcome='Blocked by Google unusual-traffic page before playback';return;}
  const found=await worker.evaluate(async url=>{const tab=(await chrome.tabs.query({url}))[0];if(!tab)return {error:'Video page not present'};try{const c=await availableMedia({url,tabId:tab.id},{});const choices=[];for(const a of c.audioChoices){const ready=!!a.audioUrl||!!await audioSession(c,a);choices.push({key:a.key,label:a.label,default:a.default,ready,transport:a.audioUrl?'direct':'sabr'});}return {tabId:tab.id,choices,videoQualities:c.choices.map(a=>a.height)};}catch(e){return {error:e.message};}},url);
  report.capture=found;if(found.choices?.some(a=>a.ready))break;await page.locator('video').first().evaluate(v=>{v.muted=true;return v.play().catch(()=>{});}).catch(()=>{});await wait(1000);
 }
 if(!report.capture?.choices?.some(a=>a.ready)){report.outcome='Current session did not expose a usable AAC audio file or captured streaming session';return;}
 const started=Date.now(),result=await worker.evaluate(async({url,tabId,audioKey})=>{try{return await audioHandoff({url,tabId,audioKey,title:'UDM live audio test'},{});}catch(e){return {ok:false,error:e.message};}},{url,tabId:report.capture.tabId,audioKey:report.capture.choices.find(a=>a.ready).key});report.handoff={ok:result.ok,milliseconds:Date.now()-started};if(!result.ok){report.outcome='Live audio handoff rejected';report.error=result.error;return;}
 for(let i=0;i<90;i++){await wait(1000);const j=jobs().find(j=>j.Id===result.id);if(!j)continue;if(j.Status==='Failed'){report.outcome='Live native download failed';report.error=j.Error;
 if(process.env.UDM_STREAM_CONTROL==='1'){
  const control=await worker.evaluate(async({url,tabId})=>{const c=await availableMedia({url,tabId},{}),offer=globalThis.lastAudioOffer;if(!offer||offer.sabr.videoId!==c.id)throw Error('No matching control session');const choice=c.choices.find(x=>x.height===360)||c.choices[0],v=c.snapshot.formats.find(x=>x.id===choice.formatId);if(!v)return {ok:false};const {output,...request}=offer;return nativeRequest({...request,filename:'UDM video control.mp4',height:choice.height,pixelHeight:choice.pixelHeight,formatId:choice.formatId,sabr:{...offer.sabr,video:{id:v.id,lastModified:v.lastModified,xtags:v.xtags||'',mime:v.mime}}});},{url,tabId:report.capture.tabId});
  report.videoControl={ok:control.ok};if(control.ok)for(let k=0;k<30;k++){await wait(1000);const controlJob=jobs().find(x=>x.Id===control.id);if(controlJob&&(['Failed','Complete'].includes(controlJob.Status)||controlJob.Received>100000)){report.videoControl.status=controlJob.Status;report.videoControl.bytes=controlJob.Received;report.videoControl.error=controlJob.Error||'';break;}}
 }return;}if(j.Status==='Complete'){const file=path.join(j.Folder,j.FileName),probe=JSON.parse(execFileSync(process.env.UDM_FFPROBE,['-v','error','-show_streams','-show_format','-of','json',file],{windowsHide:true}));report.output={bytes:fs.statSync(file).size,duration:probe.format.duration,streams:probe.streams.map(s=>({type:s.codec_type,codec:s.codec_name})),sha256:j.Sha256,parallelRequests:j.SabrMaxConcurrentRequests,requests:j.SabrRequestCount,elapsedSeconds:j.ElapsedSeconds,videoChild:!!j.Video,audioChild:!!j.Audio};report.outcome=probe.streams.length===1&&probe.streams[0].codec_type==='audio'?'Complete audio-only download':'Unexpected stream layout';return;}}
 report.outcome='Live native download exceeded 90-second diagnostic limit';
})().catch(e=>{report.outcome='Live diagnostic blocked';report.error=String(e.message).slice(0,500);}).finally(async()=>{try{if(page)await page.screenshot({path:path.join(root,'service.png')});}catch{}if(browser)await browser.close();if(app)app.kill();if(nativeBridge)await nativeBridge.close();report.finished=new Date().toISOString();if(report.capture?.choices)report.capture.choices=report.capture.choices.map(({label,default:d,ready,transport})=>({label,default:d,ready,transport}));fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));});
