const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),channel=process.argv[2]||'chrome',out=path.join(root,'benchmarks/gui-0.20/'+channel+'-youtube-isolated');let ctx;
(async()=>{fs.mkdirSync(out,{recursive:true});ctx=await chromium.launchPersistentContext(path.join(out,'profile'),{channel,headless:true,ignoreDefaultArgs:['--disable-extensions'],viewport:{width:1100,height:800},args:['--enable-unsafe-extension-debugging']});
const expectedVersion=JSON.parse(fs.readFileSync(path.join(root,'browser/chromium/manifest.json'))).version;
const control=await ctx.browser().newBrowserCDPSession();await control.send('Extensions.loadUnpacked',{path:path.join(root,'browser/chromium')});
const worker=ctx.serviceWorkers()[0]||await ctx.waitForEvent('serviceworker');assert.equal(await worker.evaluate(()=>chrome.runtime.getManifest().version),expectedVersion);
const page=await ctx.newPage();await page.goto('https://www.youtube.com/watch?v=BewnzhHlQuk',{waitUntil:'load',timeout:45000});await page.waitForFunction(()=>[...document.querySelectorAll('[id^="udm-video-panel-"]')].some(p=>getComputedStyle(p).display!=='none'),{timeout:30000});
const panel=page.locator('[id^="udm-video-panel-"]:visible').first();await panel.waitFor({state:'visible'});let box=await panel.boundingBox();assert(box&&box.width>20&&box.height>0);await page.mouse.click(box.x+box.width/2,box.y+12);
const cdp=await ctx.newCDPSession(page);let nodes=[];for(let i=0;i<150;i++){nodes=(await cdp.send('Accessibility.getFullAXTree')).nodes;if(nodes.some(n=>n.name?.value==='Select a format to open UDM.'))break;await page.waitForTimeout(200);}
const text=nodes.filter(n=>!n.ignored).map(n=>({role:n.role?.value,name:n.name?.value||''}));const report={browser:channel,version:expectedVersion,page:'https://www.youtube.com/watch?v=BewnzhHlQuk',panelVisible:true,panelBounds:box,menu:text.filter(n=>n.name==='Download with UDM'||/\d{3,4}p|formats|captured|Play the video|Download all|Select a format/.test(n.name))};
report.catalog=await worker.evaluate(async()=>{const tabs=await chrome.tabs.query({url:'https://www.youtube.com/watch?v=BewnzhHlQuk'});if(!tabs.length)return {error:'Test tab missing'};return Promise.race([availableMedia({url:tabs[0].url,tabId:tabs[0].id},{id:chrome.runtime.id}).then(c=>({videoId:c.id,choices:c.choices.map(x=>({height:x.height,label:x.label}))})).catch(e=>({error:e.message})),new Promise(resolve=>setTimeout(()=>resolve({error:'Format request timed out'}),15000))]);});
await page.screenshot({path:path.join(out,'panel-and-menu.png')});fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));assert(text.some(n=>n.name==='Download with UDM'));assert(report.catalog.choices?.length,JSON.stringify(report.catalog));assert(text.some(n=>n.role==='button'&&/\d{3,4}p/.test(n.name)),'Menu has not populated with quality buttons');console.log('PASS actual extension renders and opens its menu on the public YouTube page');
})().catch(async e=>{console.error(e);process.exitCode=1;try{const page=ctx.pages().at(-1);const state=await page.evaluate(()=>({title:document.title,url:location.href,ready:document.readyState,videoCount:document.querySelectorAll('video').length,videos:[...document.querySelectorAll('video')].map(v=>({width:v.getBoundingClientRect().width,height:v.getBoundingClientRect().height,marker:!!v.getAttribute('data-udm-player'),paused:v.paused,readyState:v.readyState})),panels:[...document.querySelectorAll('[id^="udm-video-panel-"]')].map(p=>({display:getComputedStyle(p).display,width:p.getBoundingClientRect().width,height:p.getBoundingClientRect().height})),text:document.body.innerText.slice(0,1400)}));fs.writeFileSync(path.join(out,'failure.json'),JSON.stringify(state,null,2));await page.screenshot({path:path.join(out,'failure.png')});console.log(JSON.stringify(state,null,2));}catch{}}).finally(async()=>{await ctx?.close()});
