#pragma once
#include "AdaptiveResources.hpp"
static void adaptiveResourceChecks(Manager& manager,const fs::path& root,Fixture& server,const Json& original){
 auto plan=original;plan["type"]="dash";plan["resourceVersion"]=1;plan["resources"]=Json::array({{{"url",server.url("/range")},{"size",server.payload.size()},{"etag","\"fixture-v1\""}}});
 auto receive=[&](const char* name,const Json& p){auto job=manager.receive({{"action","adaptive"},{"url",server.url("/binding-player")},{"filename",name},{"plan",p}});job->data["Connections"]=1;return job;};
 auto savePart=[&](JobPtr job,const Json& p,bool bound){auto folder=mediaWorkingDirectory(manager,job)/L"adaptive";fs::create_directories(folder);auto part=p["tracks"][0]["segments"][0];auto length=num(part,"length");writeBytes(folder/L"0.part",Bytes(server.payload.begin(),server.payload.begin()+(size_t)length));Json record={{"size",length},{"sha256",fileHash(folder/L"0.part")}};if(bound)record["binding"]=protect(Json{{"part",part},{"resource",p["resources"][0]}}.dump());atomicText(folder/L"completed.json",Json{{"0",record}}.dump());};
 auto job=receive("bound-adaptive",plan);int before=server.adaptiveMatches;adaptiveTransfer(manager,job,std::make_shared<Cancel>());
 check(str(job->data,"Status")=="Complete"&&server.adaptiveMatches-before==2,"Indexed media uses the captured strong ETag on every native range");
 auto state=Json::parse(readText(mediaWorkingDirectory(manager,job)/L"adaptive"/L"completed.json"));check(!str(state["0"],"binding").empty()&&str(state["0"],"binding").find("127.0.0.1")==std::string::npos,"Retained adaptive resource metadata is protected on disk");
 auto resumed=receive("bound-resume",plan);savePart(resumed,plan,true);before=server.requests;adaptiveTransfer(manager,resumed,std::make_shared<Cancel>());check(server.requests-before==1&&str(resumed->data,"Status")=="Complete","Bound resume reuses the exact saved segment with a matching strong ETag");
 auto legacy=receive("bound-legacy-cache",plan);savePart(legacy,plan,false);before=server.requests;adaptiveTransfer(manager,legacy,std::make_shared<Cancel>());check(server.requests-before==2,"A legacy unbound cached part is downloaded again before indexed assembly");
 auto changed=plan;changed["resources"][0]["etag"]="\"changed\"";auto failed=receive("bound-changed",changed);savePart(failed,plan,true);before=server.requests;rejects([&]{adaptiveTransfer(manager,failed,std::make_shared<Cancel>());},"A file version changed after browser capture stops native transfer");check(server.requests-before==1&&!fs::exists(failed->target())&&num(failed->data,"Received")==0,"Version mismatch is not retried and publishes no bytes or output");
 auto sized=plan;sized["resources"][0]["size"]=server.payload.size()+1;auto wrongSize=receive("bound-size-changed",sized);before=server.requests;rejects([&]{adaptiveTransfer(manager,wrongSize,std::make_shared<Cancel>());},"Changed Content-Range total invalidates a captured index");check(server.requests-before==1&&!fs::exists(wrongSize->target()),"Resource size mismatch fails once without publication");
 auto datePlan=plan;datePlan["resources"][0].erase("etag");datePlan["resources"][0]["modified"]="Wed, 21 Oct 2015 07:28:00 GMT";datePlan["resources"][0]["url"]=server.url("/dated");for(auto& p:datePlan["tracks"][0]["segments"])p["url"]=server.url("/dated");auto dated=receive("bound-date",datePlan);savePart(dated,datePlan,true);before=server.adaptiveDates;adaptiveTransfer(manager,dated,std::make_shared<Cancel>());check(server.adaptiveDates-before==2&&str(dated->data,"Status")=="Complete","Date-only sources use conditional requests and re-fetch cached segments");
 auto weak=plan;weak["resources"][0].erase("etag");auto untagged=receive("bound-no-validator",weak);savePart(untagged,weak,true);before=server.requests;adaptiveTransfer(manager,untagged,std::make_shared<Cancel>());check(server.requests-before==2&&str(untagged->data,"Status")=="Complete","Size-only resources do not reuse cached parts across attempts");
 auto redirect=plan;redirect["resources"][0]["url"]=server.url("/redirect");for(auto& p:redirect["tracks"][0]["segments"])p["url"]=server.url("/redirect");auto redirected=receive("bound-redirect",redirect);before=server.requests;rejects([&]{adaptiveTransfer(manager,redirected,std::make_shared<Cancel>());},"Bound adaptive ranges refuse a redirect to a different resource");check(server.requests-before==1&&!fs::exists(redirected->target()),"Rejected redirect is not followed or retried");
 for(auto edit:std::vector<Json>{Json{{"etag","W/\"weak\""}},Json{{"etag","\"with space\""}},Json{{"etag","\"injected\r\nheader\""}},Json{{"etag",17}},Json{{"size",0}},Json{{"size",9007199254740992LL}},Json{{"size",3.14}},Json{{"url",server.url("/outside")}},Json{{"size",1}},Json{{"unexpected",true}},Json{{"modified","invalid"}}}){auto invalid=plan;for(auto i=edit.begin();i!=edit.end();++i)invalid["resources"][0][i.key()]=i.value();rejects([&]{validateAdaptive(invalid);},"Malformed or unrelated adaptive resource binding is rejected");}
 for(auto version:std::vector<Json>{0,2,"1",nullptr}){auto invalid=plan;invalid["resourceVersion"]=version;rejects([&]{validateAdaptive(invalid);},"Unsupported adaptive binding protocol is rejected");}
 auto duplicate=plan;duplicate["resources"].push_back(duplicate["resources"][0]);rejects([&]{validateAdaptive(duplicate);},"Duplicate captured resource identities are rejected");
 Headers h={{"if-match","old"},{"If-Range","old"},{"if-none-match","old"},{"Range","bytes=0-0"},{"Authorization","Basic fixture"}};adaptiveConditions(h,plan["resources"][0]);check(h.size()==3&&h["If-Match"]=="\"fixture-v1\""&&h["Cache-Control"]=="no-cache"&&h["Authorization"]=="Basic fixture","Resource binding replaces conflicting conditional headers without dropping authentication");
 check(num(browserPreferences(Json::object()),"adaptiveResources")==1,"Browser capability negotiation advertises adaptive resource checks");
}
