#pragma once
static void adaptiveChecks(Manager& manager,const fs::path& root){
 Cancel cancel;auto input=root/L"adaptive-source.mp4";
 execute(appDir()/L"tools"/L"ffmpeg.exe",{L"-hide_banner",L"-loglevel",L"error",L"-nostdin",L"-y",L"-i",(root/L"generated-video.mp4").wstring(),L"-i",(root/L"generated-audio.mp4").wstring(),L"-c",L"copy",input.wstring()},30,cancel);
 Fixture server;server.payload=readText(input);i64 split=(i64)server.payload.size()/2;
 Json plan={{"type","hls"},{"height",720},{"audioExpected",true},{"tracks",Json::array({{{"kind","video"},{"segments",Json::array({{{"url",server.url("/range")},{"start",0},{"length",split}},{{"url",server.url("/range")},{"start",split},{"length",(i64)server.payload.size()-split}}})}}})}};
 auto receive=[&](const char* name,Json p){return manager.receive({{"action","adaptive"},{"url",server.url("/player")},{"filename",name},{"plan",p},{"originCookies",Json::object()}});};
 auto job=receive("generic-hls-720p",plan);check(str(job->data,"Status")=="Awaiting confirmation","Cross-site adaptive handoff preserves File Info confirmation");
 check(manager.receive({{"action","adaptive"},{"url",server.url("/player")},{"filename","generic-hls-720p"},{"plan",plan}})->id()==job->id(),"Adaptive duplicate handoff is idempotent");
 auto protectedPlan=str(job->data,"ProtectedAdaptive");check(protectedPlan.find("127.0.0.1")==std::string::npos&&Json::parse(reveal(protectedPlan))==plan,"Adaptive playback URLs encrypted in persisted plan");
 auto priorTemp=str(manager.state["Settings"],"TemporaryFolder");manager.state["Settings"]["TemporaryFolder"]=utf8((root/L"adaptive-temp").wstring());
 adaptiveTransfer(manager,job,std::make_shared<Cancel>());check(mediaWorkingDirectory(manager,job)==root/L"adaptive-temp"/L"UDM-media"/wide(job->id()),"HLS/DASH assembly honors the selected temporary folder");manager.state["Settings"]["TemporaryFolder"]=priorTemp;check(str(job->data,"Status")=="Complete"&&fileHash(job->target())==str(job->data,"Sha256"),"Generic HLS range pieces assemble and publish verified video");
 auto probe=Json::parse(execute(appDir()/L"tools"/L"ffprobe.exe",{L"-v",L"error",L"-show_entries",L"stream=codec_type,height",L"-of",L"json",job->target().wstring()},20,cancel));bool video=false,audio=false;for(auto s:probe["streams"]){video|=str(s,"codec_type")=="video"&&num(s,"height")==720;audio|=str(s,"codec_type")=="audio";}check(video&&audio,"Generic adaptive output contains requested video and audio");
 auto tsPlan=plan;tsPlan["container"]="ts";auto tsJob=receive("generic-720p.ts",tsPlan);adaptiveTransfer(manager,tsJob,std::make_shared<Cancel>());
 auto tsProbe=Json::parse(execute(appDir()/L"tools"/L"ffprobe.exe",{L"-v",L"error",L"-show_entries",L"format=format_name:stream=codec_type,height",L"-of",L"json",tsJob->target().wstring()},20,cancel));
 bool tsVideo=false,tsAudio=false;for(auto stream:tsProbe["streams"]){tsVideo|=str(stream,"codec_type")=="video"&&num(stream,"height")==720;tsAudio|=str(stream,"codec_type")=="audio";}
 check(tsJob->target().extension()==L".ts"&&str(tsProbe["format"],"format_name")=="mpegts"&&tsVideo&&tsAudio,"TS selection creates actual MPEG-TS with requested video and audio");
 execute(appDir()/L"tools"/L"ffmpeg.exe",{L"-v",L"error",L"-i",tsJob->target().wstring(),L"-f",L"null",L"-"},30,cancel);check(true,"TS output fully decodes without media errors");
 auto badContainer=plan;badContainer["container"]="exe";rejects([&]{validateAdaptive(badContainer);},"Unsupported adaptive output container rejected");
 auto invalid=plan;invalid["tracks"][0]["segments"][0]["url"]="file:///C:/Windows/win.ini";rejects([&]{validateAdaptive(invalid);},"Adaptive local-file URL rejected");
 invalid=plan;invalid["tracks"][0]["segments"][0]["start"]=-1;rejects([&]{validateAdaptive(invalid);},"Adaptive invalid byte range rejected");
 invalid=plan;invalid["encrypted"]=true;rejects([&]{validateAdaptive(invalid);},"Adaptive encrypted plan rejected");
 auto wrong=plan;wrong["height"]=1080;auto mismatched=receive("adaptive-wrong-height",wrong);rejects([&]{adaptiveTransfer(manager,mismatched,std::make_shared<Cancel>());},"Adaptive quality mismatch blocks publication");check(!fs::exists(mismatched->target()),"Adaptive incorrect quality output absent");
 auto bad=plan;bad["tracks"][0]["segments"][0]["url"]=server.url("/bad-range");auto badJob=receive("adaptive-bad-range",bad);rejects([&]{adaptiveTransfer(manager,badJob,std::make_shared<Cancel>());},"Adaptive incorrect server Content-Range rejected");
 auto resumedPlan=plan;resumedPlan["type"]="dash";auto resumed=receive("adaptive-resumed",resumedPlan);auto folder=manager.root/L"media"/wide(resumed->id())/L"adaptive";fs::create_directories(folder);writeBytes(folder/L"0.part",Bytes(server.payload.begin(),server.payload.begin()+(size_t)split));atomicText(folder/L"completed.json",Json{{"0",{{"size",split},{"sha256",fileHash(folder/L"0.part")}}}}.dump());int before=server.requests;adaptiveTransfer(manager,resumed,std::make_shared<Cancel>());check(server.requests-before==1&&str(resumed->data,"Status")=="Complete","Adaptive resume verifies and reuses completed segment");
 auto collision=receive("adaptive-collision",plan);writeBytes(collision->target(),Bytes{'k','e','e','p'});rejects([&]{adaptiveTransfer(manager,collision,std::make_shared<Cancel>());},"Adaptive existing output is not overwritten");check(readText(collision->target())=="keep","Adaptive existing file preserved");
 auto hashPlan=plan;hashPlan["type"]="dash";auto hashJob=receive("adaptive-hash-mismatch",hashPlan);manager.configure(hashJob,{{"ExpectedSha256",std::string(64,'0')}});rejects([&]{manager.configure(hashJob,{{"Url",server.url("/different")}});},"Adaptive source URL cannot change independently of captured plan");rejects([&]{adaptiveTransfer(manager,hashJob,std::make_shared<Cancel>());},"Adaptive expected hash mismatch blocks publication");check(!fs::exists(hashJob->target()),"Adaptive hash mismatch leaves no final output");
}
