#pragma once
#include "BrowserCookies.hpp"
static void browserCookieChecks(const fs::path& root){
 const std::string origin="https://files.example.com";Json initial={{"Origin",origin},{"UserAgent","UDM cookie fixture"},{"LogoutPages","*/logout*"},{"Cookies",Json::array({sessionCookie("session","old","/",true,"files.example.com")})}};
 auto value=[](const BrowserCookieJar& jar,const std::string& name){auto saved=jar.snapshot();for(const auto& cookie:saved["Cookies"])if(str(cookie,"name")==name)return str(cookie,"value");return std::string{};};
 check(cookieDate("Wed, 21 Oct 2015 07:28:00 GMT")==std::optional<double>(1445412480.0),"Cookie Expires parses an RFC 1123 date");
 check(cookieDate("Wednesday, 21-Oct-15 07:28:00 GMT")==cookieDate("Wed Oct 21 07:28:00 2015"),"Cookie Expires accepts legacy date layouts and two-digit years");
 check(!cookieDate("Mon, 31 Feb 2025 07:28:00 GMT")&&!cookieDate("Mon, 01 Jan 1599 07:28:00 GMT")&&!cookieDate("nonsense"),"Malformed and impossible cookie expiration dates are ignored");
 BrowserCookieJar jar(initial);jar.receive(origin+"/private/start",{"session=new; Secure; Path=/; HttpOnly","child=private; Path=/private; Secure"});
 check(value(jar,"session")=="new"&&jar.snapshot()["Cookies"].size()==2,"Response cookies replace captured identity and retain independent scopes");
 check(headerValue(jar.headers(origin+"/private/file",{}),"Cookie")=="child=private; session=new","Updated cookies use path-length ordering");
 check(headerValue(jar.headers(origin+"/private-other",{}),"Cookie")=="session=new","Updated cookies enforce path boundaries");
 jar.receive(origin+"/private/start",{"inherited=yes; Secure"});check(headerValue(jar.headers(origin+"/private/file",{}),"Cookie").find("inherited=yes")!=std::string::npos&&headerValue(jar.headers(origin+"/outside",{}),"Cookie").find("inherited=")==std::string::npos,"Missing cookie Path defaults to the response directory");
 jar.receive(origin+"/",{"session=; Secure; Path=/; Max-Age=0; Expires=Tue, 01 Jan 2030 00:00:00 GMT"});check(value(jar,"session").empty(),"Cookie Max-Age zero deletes even with future Expires");
 jar.receive(origin+"/",{"lifetime=yes; Secure; Path=/; Max-Age=120; Expires=Wed, 21 Oct 2015 07:28:00 GMT"});check(value(jar,"lifetime")=="yes"&&real(jar.snapshot()["Cookies"].back(),"expirationDate")>epoch()/1000+115,"Positive Max-Age overrides a past Expires date");
 jar.receive(origin+"/",{"lifetime=gone; Secure; Path=/; Max-Age=-999"});check(value(jar,"lifetime").empty(),"Negative cookie Max-Age deletes existing identity");
 jar.receive(origin+"/",{"old=discard; Secure; Path=/; Expires=Wednesday, 21-Oct-15 07:28:00 GMT"});check(value(jar,"old").empty(),"Past Expires does not retain a stale cookie");
 jar.receive(origin+"/",{"bounded=yes; Secure; Max-Age=99999999999999999999999999999999999999; Path=/"});check(real(jar.snapshot()["Cookies"].back(),"expirationDate")==253402300799.0,"Cookie Max-Age overflow saturates without wrapping");
 auto before=jar.snapshot();jar.receive("https://other.example.com/",{"child=foreign; Path=/private; Secure"});jar.receive("http://files.example.com/",{"child=downgrade; Path=/private"});jar.receive("https://files.example.com:444/",{"child=port; Path=/private; Secure"});check(jar.snapshot()==before,"Cookie updates cannot cross session origin, scheme or port");
 jar.receive(origin+"/logout",{"child=loggedout; Path=/private; Secure"});check(jar.snapshot()==before,"Excluded logout responses cannot mutate a session");
 jar.receive(origin+"/",{"foreign=no; Domain=attacker.test; Secure","suffix=no; Domain=com; Secure","bad-domain=no; Domain=files.example.com.; Secure","bad name=no; Secure","x=bad\r\nInjected: header","no-equals","=emptyname"});check(jar.snapshot()==before,"Foreign, public-suffix and malformed cookies do not modify the jar");
 jar.receive(origin+"/",{"parent=first; Domain=.example.com; Path=/; Secure","parent=second; Domain=example.com; Path=/; Secure"});int count=0;auto saved=jar.snapshot();for(auto& c:saved["Cookies"])if(str(c,"name")=="parent")++count;check(count==1&&value(jar,"parent")=="second","Leading dots do not create duplicate domain-cookie identities");
 jar.receive(origin+"/",{"__Host-good=yes; Path=/; Secure; HttpOnly","__Host-no-path=no; Secure","__Host-domain=no; Domain=files.example.com; Path=/; Secure","__Secure-bad=no; Path=/","__Http-bad=no; Path=/; Secure"});check(value(jar,"__Host-good")=="yes"&&value(jar,"__Host-no-path").empty()&&value(jar,"__Host-domain").empty()&&value(jar,"__Secure-bad").empty()&&value(jar,"__Http-bad").empty(),"Cookie security prefixes enforce their response attributes");
 jar.receive(origin+"/",{"partition=ordinary; Secure; Path=/","partition=isolated; Secure; Path=/; Partitioned","partition=; Secure; Path=/; Partitioned; Max-Age=0"});count=0;saved=jar.snapshot();for(auto& c:saved["Cookies"])if(str(c,"name")=="partition")++count;check(count==1&&value(jar,"partition")=="ordinary","Partitioned deletion retains the separate ordinary cookie");
 before=jar.snapshot();jar.receive(origin+"/",{"oversized="+std::string(9000,'x')+"; Secure; Path=/"});check(jar.snapshot()==before,"Oversized response cookies do not displace an existing session");
 auto insecure=initial;insecure["Origin"]="http://files.example.com";BrowserCookieJar http(insecure);http.receive("http://files.example.com/",{"session=attacker; Path=/","secure=no; Path=/; Secure","partition=no; Path=/; Partitioned"});check(http.snapshot()==insecure,"HTTP cannot replace Secure cookies or set Secure/partitioned cookies");
 BrowserCookieJar transactional(initial,[](const Json&){throw std::runtime_error("simulated disk failure");});rejects([&]{transactional.receive(origin+"/",{"session=unsaved; Path=/; Secure"});},"A cookie persistence failure reaches the caller");check(transactional.snapshot()==initial,"Failed cookie persistence leaves the prior in-memory jar intact");
 std::atomic_int saves{0};BrowserCookieJar parallel(initial,[&](const Json&){++saves;});std::vector<std::thread> threads;for(int i=0;i<24;++i)threads.emplace_back([&,i]{parallel.receive(origin+"/",{"worker"+std::to_string(i)+"=saved; Path=/; Secure"});});for(auto& worker:threads)worker.join();check(parallel.snapshot()["Cookies"].size()==25&&saves==24,"Concurrent response updates preserve all independent cookies");

 auto ipv6=initial;ipv6["Origin"]="https://[::1]";ipv6["Cookies"]=Json::array();BrowserCookieJar numeric(ipv6);numeric.receive("https://[::1]/",{"loopback=accepted; Secure; Path=/"});check(value(numeric,"loopback")=="accepted","IPv6 response hosts can maintain a scoped cookie session");
 auto duplicate=initial;auto dot=duplicate["Cookies"][0];dot["domain"]=".files.example.com";dot["hostOnly"]=false;duplicate["Cookies"].push_back(dot);rejects([&]{validateBrowserSession(duplicate);},"Leading-dot duplicate identities are rejected at browser handoff");
 auto repeated=parallel.snapshot();auto writes=saves.load();parallel.receive(origin+"/",{"worker0=saved; Path=/; Secure"});check(parallel.snapshot()==repeated&&saves==writes,"Unchanged response cookies do not rewrite encrypted state");
 auto ordered=initial;ordered["Cookies"].push_back(sessionCookie("second","old","/",true,"files.example.com"));BrowserCookieJar order(ordered);order.receive(origin+"/",{"session=new; Path=/; Secure"});check(headerValue(order.headers(origin+"/",{}),"Cookie")=="session=new; second=old","Cookie replacement preserves order among equal-length paths");
 BrowserCookieJar bounded(initial);for(int i=0;i<8;++i)bounded.receive(origin+"/",{"large"+std::to_string(i)+"="+std::string(4000,'x')+"; Secure; Path=/"});check(bounded.snapshot()["Cookies"].size()==5&&headerValue(bounded.headers(origin+"/",{}),"Cookie").size()<=16384,"Combined response-cookie limits preserve the previously usable jar");
 GrabberFilterFixture fixture;auto settings=defaultSettings();settings["ProxyMode"]="Connect directly";settings["Retries"]=0;settings["CategoryFolders"]=false;settings["DownloadFolder"]=utf8((root/L"cookie-files").wstring());Cancel cancel;
 auto session=initial;session["Origin"]=Url(fixture.url("/")).origin;session["Cookies"]=Json::array({sessionCookie("session","old")});auto prefs=settings;prefs["ActiveBrowserSession"]=session;
 fixture.redirect("/redirect",fixture.url("/private/file.bin"),"Set-Cookie: session=rotated; Path=/; HttpOnly\r\nSet-Cookie: second=two; Path=/\r\n");std::string payload(3*1024*1024,'r');fixture.file("/private/file.bin",payload,"Content-Type: application/octet-stream\r\nETag: \"cookie-fixture\"\r\n");fixture.requireCookie("/private/file.bin","session=rotated");
 auto pool=std::make_shared<HttpSession>(prefs);Http response(fixture.url("/redirect"),{},prefs,cancel,0,0,"",nullptr,true,pool);check(response.status==206&&response.all(1,cancel)==Bytes{'r'},"Real WinHTTP redirect requires the response's rotated cookie");check(pool->browserSessionSnapshot()["Cookies"].size()==2&&fixture.has("/private/file.bin","second=two"),"Repeated Set-Cookie fields are read independently by WinHTTP");
 fixture.file("/poison","ignored","Set-Cookie: session=foreign; Path=/\r\n");Http foreign(fixture.url("/poison",true),{},prefs,cancel,{},{},"",nullptr,true,pool);check(str(pool->browserSessionSnapshot()["Cookies"][0],"value")=="rotated"&&!fixture.has("/poison","session=rotated"),"Real foreign-origin responses neither receive nor overwrite scoped cookies");
 fixture.redirect("/out-and-back",fixture.url("/return",true),"Set-Cookie: session=rotated; Path=/\r\n");fixture.redirect("/return",fixture.url("/private/file.bin"));Http returned(fixture.url("/out-and-back"),{},prefs,cancel,0,0,"",nullptr,true,pool);check(returned.status==206&&!fixture.has("/return","Cookie:"),"Cross-origin redirects may return to the original scoped session without leaking cookies abroad");
 Manager manager(root/L"cookie-state");manager.setSettings(settings);auto job=manager.add(fixture.url("/redirect"),"","rotating.bin","Main queue",true);job->data["ProtectedBrowserSession"]=protect(session.dump());manager.save();
 auto info=probeDownload(job->data,settings,cancel,browserSessionSaver(manager,job,session));check(num(info,"Size")==static_cast<i64>(payload.size())&&str(readBrowserSession(job->data)["Cookies"][0],"value")=="rotated","File Info metadata persists cookies received before following redirects");
 transfer(manager,job,std::make_shared<Cancel>());check(readText(job->target(),4*1024*1024)==payload&&job->data["Segments"].size()>1,"Parallel native file ranges complete with the updated session");
 check(readText(manager.root/L"state.json").find("\"rotated\"")==std::string::npos,"Rotated cookie headers are not stored as plaintext");
 fixture.requireCookie("/redirect","session=rotated");
 {Manager reopened(manager.root);auto restored=reopened.jobs[0];check(readBrowserSession(restored->data)==readBrowserSession(job->data),"Rotated job session survives application restart");auto copied=reopened.redownload(restored);transfer(reopened,copied,std::make_shared<Cancel>());check(readText(copied->target(),4*1024*1024)==payload,"Redownload uses the persisted rotated session after restart");}
 auto stale=browserSessionSaver(manager,job,readBrowserSession(job->data));auto recaptured=session;recaptured["Cookies"][0]["value"]="new-browser-login";job->data["ProtectedBrowserSession"]=protect(recaptured.dump());manager.save();rejects([&]{stale(session);},"A late response cannot overwrite a newer browser session");check(readBrowserSession(job->data)==recaptured,"The newer browser session wins a stale operation race");
 auto save=browserSessionSaver(manager,job,recaptured);auto beforeSecret=job->data["ProtectedBrowserSession"];{Handle locked(CreateFileW((manager.root/L"state.json").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));rejects([&]{save(session);},"Real catalog write failure rejects a rotated session");check(job->data["ProtectedBrowserSession"]==beforeSecret,"Catalog write failure restores the previous encrypted value");}
 fixture.file("/site/start.html","<a href='child.html'>child</a>","Content-Type: text/html\r\nSet-Cookie: session=explored; Path=/\r\n");fixture.file("/site/child.html","<a href='report.bin'>report</a>","Content-Type: text/html\r\nSet-Cookie: child=collected; Path=/site\r\n");fixture.requireCookie("/site/child.html","session=explored");fixture.file("/site/report.bin","private-report");fixture.requireCookie("/site/report.bin","child=collected");
 auto project=modernGrabber(fixture.url("/site/start.html"));project["FileInclude"]="*.bin";project["BrowserLogin"]=true;project["ProtectedBrowserSession"]=protect(session.dump());project["MaxPages"]=1;auto first=explore(project,settings,cancel);check(yes(first,"ExplorationLimited")&&str(readBrowserSession(first)["Cookies"][0],"value")=="explored","Limited exploration checkpoints its updated authentication");first["MaxPages"]=10;auto collected=explore(first,settings,cancel);check(collected["Errors"].empty()&&collected["Links"].size()==1&&fixture.count("/site/start.html")==1,"Exploration resumes with rotated cookies without restarting visited pages");check(readBrowserSession(collected)["Cookies"].size()==2,"Metadata exploration retains cookies created by child pages");
 manager.saveProject(collected);auto beforeJobs=manager.jobs.size();manager.addProject(collected,"Main queue",true);auto collectedJob=manager.jobs.at(beforeJobs);transfer(manager,collectedJob,std::make_shared<Cancel>());check(readText(collectedJob->target())=="private-report","Collected files inherit the latest exploration session");
 project["MaxPages"]=10;auto archive=manager.addOfflineProject(project,"Main queue",true);offlineTransfer(manager,archive,std::make_shared<Cancel>());check(str(archive->data,"Status")=="Complete"&&readBrowserSession(archive->data)["Cookies"].size()==2,"Offline website requests persist rotated cookies while fetching child pages");
}
