'use strict';
// Local browser/manual fixture. Generates synthetic media; serves only its own files.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{execFileSync}=require('node:child_process');
const root=path.join(__dirname,'browser-fixture-data');fs.mkdirSync(root,{recursive:true});
const ff=path.join(__dirname,'../release/tools/ffmpeg.exe');
execFileSync(ff,['-hide_banner','-loglevel','error','-nostdin','-y','-f','lavfi','-i','testsrc2=size=640x360:rate=24','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','8','-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p','-g','48','-c:a','aac','-movflags','+faststart',path.join(root,'sample.mp4')],{windowsHide:true});
execFileSync(ff,['-hide_banner','-loglevel','error','-nostdin','-y','-i',path.join(root,'sample.mp4'),'-c','copy','-hls_time','2','-hls_playlist_type','vod','-hls_segment_type','fmp4','index.m3u8'],{cwd:root,windowsHide:true});
fs.writeFileSync(path.join(root,'master.m3u8'),'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1800000,RESOLUTION=640x360,CODECS="avc1.42c01e,mp4a.40.2"\nindex.m3u8\n');
const html=`<!doctype html><title>UDM video fixture</title><style>body{font:16px Arial;background:#eef3f8;color:#163249;margin:40px}h1{font-size:24px}section{margin:38px 0}video{width:640px;max-width:90vw;background:#123}iframe{width:420px;height:310px;border:1px solid #789}button{padding:8px}</style><h1>UDM video panel check</h1><p>Synthetic video only. Direct MP4, embedded player and recorded HLS.</p><section><h2>Direct video · 360p</h2><div id="full"><video controls muted loop autoplay src="/sample.mp4"></video><br><button onclick="document.querySelector('#full').requestFullscreen()">Container fullscreen</button></div></section><section><h2>Embedded player</h2><iframe src="/embed"></iframe></section><section><h2>Recorded HLS player</h2><iframe src="/hls" style="width:680px;height:450px"></iframe></section>`;
const hls=`<!doctype html><title>UDM HLS fixture</title><style>body{margin:30px 8px;font:14px Arial}video{width:640px;max-width:100%}</style><video id="v" controls muted autoplay loop></video><p id="s">Loading synthetic HLS…</p><script>(async()=>{try{const m=new MediaSource();v.src=URL.createObjectURL(m);await new Promise(r=>m.addEventListener('sourceopen',r,{once:true}));await fetch('/master.m3u8').then(r=>r.text());const p=await fetch('/index.m3u8').then(r=>r.text());const init=/URI="([^"]+)"/.exec(p)[1];const urls=[init,...p.split(/\\r?\\n/).filter(x=>x&&!x.startsWith('#'))];const b=m.addSourceBuffer('video/mp4; codecs="avc1.42c01e,mp4a.40.2"');for(const u of urls){const a=await fetch('/'+u).then(r=>r.arrayBuffer());await new Promise((r,j)=>{b.addEventListener('updateend',r,{once:true});b.addEventListener('error',j,{once:true});b.appendBuffer(a);});}m.endOfStream();s.textContent='Recorded HLS: 360p with audio';await v.play();}catch(e){s.textContent=e.message;}})();</script>`;
const server=http.createServer((req,res)=>{let url=new URL(req.url,'http://127.0.0.1');res.setHeader('Cache-Control','no-store');if(url.pathname==='/'){res.setHeader('Content-Type','text/html');return res.end(html);}if(url.pathname==='/embed'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><title>UDM embedded fixture</title><body style="margin:30px 8px"><video style="width:390px" controls muted loop autoplay src="/sample.mp4"></video></body>');}if(url.pathname==='/hls'){res.setHeader('Content-Type','text/html');return res.end(hls);}const name=url.pathname.slice(1);if(!/^(sample\.mp4|master\.m3u8|index\.m3u8|init\.mp4|index\d+\.m4s)$/.test(name)){res.writeHead(404);return res.end();}const file=path.join(root,name);if(!fs.existsSync(file)){res.writeHead(404);return res.end();}const data=fs.readFileSync(file);res.setHeader('Accept-Ranges','bytes');res.setHeader('Content-Type',name.endsWith('m3u8')?'application/vnd.apple.mpegurl':'video/mp4');let start=0,end=data.length-1;if(req.headers.range){const m=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range);if(!m||Number(m[1])>end){res.writeHead(416);return res.end();}start=Number(m[1]);if(m[2])end=Math.min(end,Number(m[2]));res.statusCode=206;res.setHeader('Content-Range',`bytes ${start}-${end}/${data.length}`);}res.setHeader('Content-Length',end-start+1);res.end(req.method==='HEAD'?undefined:data.subarray(start,end+1));});
server.listen(43821,'127.0.0.1',()=>console.log('UDM browser fixture: http://127.0.0.1:43821'));
setTimeout(()=>server.close(),40*60*1000).unref();
