#pragma once
#include "BrowserSettings.hpp"
namespace udm {
inline bool browserKeysDialog(CWnd* owner,Json& prefs){
 Form d("Using special keys",318,234,owner);d.dialogUnits=true;Json draft=prefs;
 d.init=[&]{
  d.control(L"STATIC","",SS_ETCHEDHORZ,6,6,306,1);
  auto prevent=d.check("Use the following key(s) to prevent downloading with UDM for any links:",str(draft,"CaptureBypassKey","Alt")!="None",7,13,304,10);
  auto force=d.check("Use the following key(s) to force downloading with UDM for any links:",str(draft,"CaptureForceKey","Ctrl")!="None",7,50,304,10);
  const auto before=browserKeyParts(str(draft,"CaptureBypassKey","Alt"),false),after=browserKeyParts(str(draft,"CaptureForceKey","Ctrl"),true);
  std::vector<std::pair<std::string,CWnd*>> bypass,forcing;
  for(auto row:std::vector<std::pair<std::string,int>>{{"Alt",89},{"Shift",127},{"Ctrl",165},{"Del",203}})bypass.push_back({row.first,d.check(row.first,before.count(row.first)>0,row.second,row.first=="Del"?25:26,row.first=="Del"?41:row.first=="Alt"?34:35,10)});
  d.control(L"STATIC","",SS_ETCHEDHORZ,6,41,306,1);
  for(auto row:std::vector<std::pair<std::string,int>>{{"Alt",89},{"Shift",127},{"Ctrl",165},{"Ins",203}})forcing.push_back({row.first,d.check(row.first,after.count(row.first)>0,row.second,64,row.first=="Ins"?41:row.first=="Alt"?34:35,10)});
  d.label("Note: If a web page starts a download after a delay, clear the following option and hold the selected keys while the download starts.",7,76,304,27);
  auto click=d.check("Check for left mouse button clicked on a link along with the special key(s) pressed to force downloading the link",yes(draft,"CaptureForceClick",true),45,104,235,17);
  d.label("Note 2: Holding a force key can also capture media requests from a supported player. Excluded sites, protected media and browser permissions still apply. Release the keys to stop forcing new requests.",7,130,304,50);
  auto skip=d.check("While holding down a special key DO NOT take over downloads which are web pages, pictures, scripts and etc.",yes(draft,"CaptureForceSkipWeb",true),45,183,266,17);
  auto update=[&,prevent,force,click,skip,bypass,forcing]{for(auto& item:bypass)item.second->EnableWindow(d.checked(prevent));for(auto& item:forcing)item.second->EnableWindow(d.checked(force));click->EnableWindow(d.checked(force));skip->EnableWindow(d.checked(force));};d.bind(prevent,update);d.bind(force,update);update();
  auto key=[&d](CWnd* enabled,const std::vector<std::pair<std::string,CWnd*>>& choices){if(!d.checked(enabled))return std::string("None");std::string result;for(auto& item:choices)if(d.checked(item.second)){if(!result.empty())result+="+";result+=item.first;}if(result.empty())throw std::runtime_error("Select at least one key for each enabled combination.");return result;};
  d.accept=[&,prevent,force,click,skip,bypass,forcing,key]{draft["CaptureBypassKey"]=key(prevent,bypass);draft["CaptureForceKey"]=key(force,forcing);draft["CaptureForceClick"]=d.checked(click);draft["CaptureForceSkipWeb"]=d.checked(skip);validateBrowserSettings(draft);prefs=draft;d.close();};
  d.control(L"STATIC","",SS_ETCHEDHORZ,6,205,306,1);d.defaultButton(d.button("OK",89,213,50,d.accept));d.button("Cancel",178,213,50,[&]{d.close(IDCANCEL);});
 };return d.DoModal()==IDOK;
}
class BrowserTabsForm:public Form {
 ThemeTabs* tabs=nullptr;std::vector<std::vector<CWnd*>> pages;
 void page(){for(size_t i=0;i<pages.size();++i)for(auto item:pages[i])item->ShowWindow((int)i==tabs->GetCurSel()?SW_SHOW:SW_HIDE);}
 BOOL OnNotify(WPARAM w,LPARAM l,LRESULT* result)override{auto event=(NMHDR*)l;if(tabs&&event->hwndFrom==tabs->m_hWnd&&event->code==TCN_SELCHANGE){page();*result=0;return TRUE;}return Form::OnNotify(w,l,result);}
public:
 using Form::Form;
 void createTabs(int width,int height){tabs=make<ThemeTabs>(WS_TABSTOP,5,5,width,height);}
 void addPage(const wchar_t* title,const std::function<void()>& initPage){tabs->InsertItem((int)pages.size(),title);auto first=controls.size();initPage();std::vector<CWnd*> items;for(size_t i=first;i<controls.size();++i)items.push_back(controls[i].get());pages.push_back(std::move(items));page();}
};
inline bool browserMenusDialog(CWnd* owner,Json& prefs){
 BrowserTabsForm d("Customize UDM menu items in browsers",295,124,owner);d.dialogUnits=true;Json draft=prefs;std::vector<std::function<void()>> save;
 d.init=[&]{d.createTabs(285,91);for(const auto& family:std::vector<std::pair<std::string,std::wstring>>{{"chromium",L"Chrome, Edge and Chromium"},{"firefox",L"Firefox and Mozilla"}}){auto name=family.first;d.addPage(family.second.c_str(),[&,name]{auto menu=browserContextMenu(draft,name);d.label("Selected menu items will appear in browser context menu:",17,35,261,9);auto link=d.check("Download with UDM",yes(menu,"Link",true),17,51,261,10);auto all=d.check("Download all links with UDM",yes(menu,"All",true),17,66,261,10);save.push_back([&,name,link,all]{draft["BrowserContextMenus"][name]={{"Link",d.checked(link)},{"All",d.checked(all)}};});});
 }d.accept=[&]{for(auto& action:save)action();validateBrowserSettings(draft);prefs=draft;d.close();};d.defaultButton(d.button("OK",116,103,50,d.accept));d.button("Cancel",228,103,50,[&]{d.close(IDCANCEL);});};return d.DoModal()==IDOK;
}
inline void panelExceptionsDialog(CWnd* owner,Json& prefs){Form d("Download panel exceptions",254,123,owner);d.dialogUnits=true;d.init=[&]{d.label("Don't show UDM download panel for the following sites:",7,6,240,18);auto input=d.edit(str(prefs,"VideoPanelExcludedHosts"),7,27,240,51,false,true);d.label("Separate names by spaces. You may use asterisk as a wildcard pattern.",7,81,240,18);d.accept=[&,input]{auto value=lower(text(input));validatePanelHosts(value);prefs["VideoPanelExcludedHosts"]=value;d.close();};d.defaultButton(d.button("OK",67,102,50,d.accept));d.button("Cancel",136,102,50,[&]{d.close(IDCANCEL);});};d.DoModal();}
inline bool browserPanelsDialog(CWnd* owner,Json& prefs){
 BrowserTabsForm d("Customize UDM Download panels in browsers",342,312,owner);d.dialogUnits=true;Json draft=prefs;ThemeList* list=nullptr;std::vector<std::string> types;std::vector<std::function<void()>> save;auto rules=videoPanelTypes(draft);
 auto saveChecks=[&]{for(int i=0;i<(int)types.size();++i)rules[types[i]]=list->GetCheck(i)!=FALSE;draft["VideoPanelTypes"]=rules;};
 auto refresh=[&]{list->DeleteAllItems();types.clear();int row=0;for(auto it=rules.begin();it!=rules.end();++it){types.push_back(it.key());list->InsertItem(row,cs(it.key()));list->SetCheck(row,yes(rules,it.key().c_str()));auto sizes=draft.value("VideoPanelMinKb",Json::object());auto size=num(sizes,it.key().c_str());list->SetItemText(row++,1,cs(size?std::to_string(size)+" KB":"Any size"));}};
 d.init=[&]{d.createTabs(332,282);
  d.addPage(L"Web players",[&]{const int x=10,y=23;auto L=[&](const char* text,int a,int b,int w,int h=9){return d.label(text,x+a,y+b,w,h);};
   L("UDM can show its Download panel on a web player when it detects a multimedia request from the player.",7,4,308,18);d.control(L"STATIC","",SS_ETCHEDHORZ,x+7,y+26,308,1);L("Panel view:",7,30,79);
   auto full=d.check("Full mode",!yes(draft,"VideoPanelCompact"),x+22,y+43,65,10),mini=d.check("Mini mode",yes(draft,"VideoPanelCompact"),x+22,y+59,64,10);for(auto c:{full,mini})c->ModifyStyle(BS_TYPEMASK,BS_AUTORADIOBUTTON);d.bind(full,[=]{full->SendMessage(BM_SETCHECK,BST_CHECKED);mini->SendMessage(BM_SETCHECK,BST_UNCHECKED);});d.bind(mini,[=]{full->SendMessage(BM_SETCHECK,BST_UNCHECKED);mini->SendMessage(BM_SETCHECK,BST_CHECKED);});
   L("↓ Download this video",123,43,166,14);L("↓ UDM",247,59,42,14);d.control(L"STATIC","",SS_ETCHEDHORZ,x+7,y+75,308,1);L("Show UDM download panel for the following file types:",7,80,308);
   list=d.make<ThemeList>(WS_TABSTOP|WS_BORDER|LVS_REPORT|LVS_SINGLESEL|LVS_SHOWSELALWAYS,x+28,y+92,148,88);list->SetExtendedStyle(LVS_EX_CHECKBOXES|LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);list->theme();list->InsertColumn(0,L"Type",LVCFMT_LEFT,d.pixelsX(46));list->InsertColumn(1,L"Minimum size",LVCFMT_LEFT,d.pixelsX(80));refresh();
   d.button("Add",x+190,y+93,99,[&]{saveChecks();Form add("Add file type",126,49,&d);add.dialogUnits=true;add.init=[&]{auto input=add.edit("",7,7,112,14);add.accept=[&,input]{auto type=lower(trim(text(input)));if(type.empty()||!std::regex_match(type,std::regex("[a-z0-9]{1,16}")))throw std::runtime_error("Enter a file extension without a dot.");if(!rules.contains(type)&&rules.size()>=64)throw std::runtime_error("Use at most 64 file types.");rules[type]=true;add.close();};add.defaultButton(add.button("OK",9,28,50,add.accept));add.button("Cancel",66,28,50,[&]{add.close(IDCANCEL);});};add.DoModal();refresh();});
   d.button("Minimum size",x+190,y+111,99,[&]{int selected=list->GetNextItem(-1,LVNI_SELECTED);if(selected<0)throw std::runtime_error("Select a file type first.");saveChecks();auto type=types[selected];Form size("Minimum size",239,137,&d);size.dialogUnits=true;size.init=[&]{size.label("Minimum size for media file type "+type,7,7,225,32);size.label("Minimum:",40,46,58,8);auto input=size.edit(std::to_string(num(draft.value("VideoPanelMinKb",Json::object()),type.c_str())),103,44,48,14);size.label("KB",155,46,43,8);size.label("Smaller files with a known size are hidden from the panel. Zero allows every size. Files whose size is unknown remain visible.",7,62,225,51);size.accept=[&,input]{auto next=draft;auto raw=trim(text(input));if(!std::regex_match(raw,std::regex("[0-9]{1,10}")))throw std::runtime_error("Enter a whole number of KB.");next["VideoPanelMinKb"][type]=std::stoll(raw);validateBrowserSettings(next);draft=next;size.close();};size.defaultButton(size.button("OK",59,116,50,size.accept));size.button("Cancel",130,116,50,[&]{size.close(IDCANCEL);});};size.DoModal();refresh();list->SetItemState(selected,LVIS_SELECTED,LVIS_SELECTED);});
   d.button("Check All",x+190,y+129,99,[&]{for(int i=0;i<list->GetItemCount();++i)list->SetCheck(i,TRUE);});d.button("Clear All",x+190,y+147,99,[&]{for(int i=0;i<list->GetItemCount();++i)list->SetCheck(i,FALSE);});d.button("Exceptions",x+190,y+165,99,[&]{panelExceptionsDialog(&d,draft);});
   L("Choose the output file types offered by video panels. Automatic player capture applies only to an identified, unprotected media file; unsupported streams still need the panel.",7,184,308,34);
   auto automatic=d.check("Don't capture downloads from web players automatically",!yes(draft,"CaptureWebPlayers"),x+50,y+221,251,9);d.control(L"STATIC","",SS_ETCHEDHORZ,x+7,y+234,308,1);auto protectedPanel=d.check("Show download panel for protected content which UDM may not download",yes(draft,"VideoPanelShowProtected",true),x+22,y+238,279,16);
   save.push_back([&,mini,automatic,protectedPanel]{saveChecks();draft["VideoPanelCompact"]=d.checked(mini);draft["CaptureWebPlayers"]=!d.checked(automatic);draft["VideoPanelShowProtected"]=d.checked(protectedPanel);});
  });
  d.addPage(L"Selected text",[&]{d.label("Download links from selected text",24,43,286);auto mode=d.combo({"All allowed sites","Listed sites only","Off"},str(draft,"SelectedLinksMode","all")=="off"?"Off":str(draft,"SelectedLinksMode","all")=="sites"?"Listed sites only":"All allowed sites",24,64,286);auto compact=d.check("Use a compact panel",yes(draft,"SelectedLinksCompact"),24,91,286,10);d.label("Listed hosts (separate names with spaces):",24,115,286);auto hosts=d.edit(str(draft,"SelectedLinkHosts"),24,130,286,77,false,true);save.push_back([&,mode,compact,hosts]{draft["SelectedLinksMode"]=mode->GetCurSel()==2?"off":mode->GetCurSel()==1?"sites":"all";draft["SelectedLinksCompact"]=d.checked(compact);draft["SelectedLinkHosts"]=text(hosts);});});
  d.addPage(L"Position and display",[&]{auto enabled=d.check("Show video download panels",yes(draft,"VideoPanelEnabled",true),24,43,286,10),hover=d.check("Show only while pointing at a video",yes(draft,"VideoPanelHover"),24,66,286,10);d.label("Panel corner",24,96,96);auto corner=d.combo({"Top right","Top left","Bottom right","Bottom left"},str(draft,"VideoPanelPosition","Top right"),129,92,181);d.label("Maximum menu width",24,123,130);auto width=d.edit(std::to_string(num(draft,"VideoPanelMenuWidth",420)),171,120,87);d.label("pixels",267,124,43);d.button("Reset saved panel positions",24,157,286,[&]{draft["VideoPanelReset"]=epoch();});save.push_back([&,enabled,hover,corner,width]{draft["VideoPanelEnabled"]=d.checked(enabled);draft["VideoPanelHover"]=d.checked(hover);draft["VideoPanelPosition"]=text(corner);draft["VideoPanelMenuWidth"]=std::stoll(text(width));});});
  d.accept=[&]{for(auto& action:save)action();validateBrowserSettings(draft);prefs=draft;d.close();};d.defaultButton(d.button("OK",224,291,50,d.accept));d.button("Cancel",280,291,50,[&]{d.close(IDCANCEL);});
 };return d.DoModal()==IDOK;
}
}
