'use strict';
// Local browser/manual fixture. Generates synthetic media; serves only its own files.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{execFileSync}=require('node:child_process');
const root=path.join(__dirname,'browser-fixture-data');fs.mkdirSync(root,{recursive:true});
const ff=path.join(__dirname,'../release/tools/ffmpeg.exe');
execFileSync(ff,['-hide_banner','-loglevel','error','-nostdin','-y','-f','lavfi','-i','testsrc2=size=640x360:rate=24','-f','lavfi','-i','sine=frequency=440:sample_rate=48000','-t','8','-c:v','libx264','-preset','ultrafast','-pix_fmt','yuv420p','-g','48','-c:a','aac','-movflags','+faststart',path.join(root,'sample.mp4')],{windowsHide:true});
execFileSync(ff,['-hide_banner','-loglevel','error','-nostdin','-y','-i',path.join(root,'sample.mp4'),'-c','copy','-hls_time','2','-hls_playlist_type','vod','-hls_segment_type','fmp4','index.m3u8'],{cwd:root,windowsHide:true});
fs.writeFileSync(path.join(root,'master.m3u8'),'#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=1800000,RESOLUTION=640x360,CODECS="avc1.42c01e,mp4a.40.2"\nindex.m3u8\n');
const html=`<!doctype html><title>UDM video fixture</title><style>body{font:16px Arial;background:#eef3f8;color:#163249;margin:40px}h1{font-size:24px}section{margin:38px 0}video{width:640px;max-width:90vw;background:#123}iframe{width:420px;height:310px;border:1px solid #789}button{padding:8px}</style><h1>UDM video panel check</h1><p>Synthetic video only. Direct MP4, embedded player and recorded HLS.</p><section><h2>Direct video · 360p</h2><div id="full"><video controls muted loop autoplay src="/sample.mp4"></video><br><button onclick="document.querySelector('#full').requestFullscreen()">Container fullscreen</button></div></section><section><h2>Embedded player</h2><iframe src="/embed"></iframe></section><section><h2>Recorded HLS player</h2><iframe src="/hls" style="width:680px;height:450px"></iframe></section>`;
const hls=`<!doctype html><title>UDM HLS fixture</title><style>body{margin:30px 8px;font:14px Arial}video{width:640px;max-width:100%}</style><video id="v" controls muted autoplay loop></video><p id="s">Loading synthetic HLS…</p><script>(async()=>{try{const m=new MediaSource();v.src=URL.createObjectURL(m);await new Promise(r=>m.addEventListener('sourceopen',r,{once:true}));await fetch('/master.m3u8').then(r=>r.text());const p=await fetch('/index.m3u8').then(r=>r.text());const init=/URI="([^"]+)"/.exec(p)[1];const urls=[init,...p.split(/\\r?\\n/).filter(x=>x&&!x.startsWith('#'))];const b=m.addSourceBuffer('video/mp4; codecs="avc1.42c01e,mp4a.40.2"');for(const u of urls){const a=await fetch('/'+u).then(r=>r.arrayBuffer());await new Promise((r,j)=>{b.addEventListener('updateend',r,{once:true});b.addEventListener('error',j,{once:true});b.appendBuffer(a);});}m.endOfStream();s.textContent='Recorded HLS: 360p with audio';await v.play();}catch(e){s.textContent=e.message;}})();</script>`;
const automatic=Buffer.alloc(8*1024*1024);for(let i=0;i<automatic.length;i++)automatic[i]=(i*17+11)%251;
let nativeLivePolls=0;
const liveSource=fs.readFileSync(path.join(root,'index.m3u8'),'utf8'),liveParts=[...liveSource.matchAll(/#EXTINF:([^\n]+)\n([^#\n][^\n]*)/g)].map(match=>({duration:match[1],url:match[2]})),liveMap=/#EXT-X-MAP:[^\n]+/.exec(liveSource)?.[0];
function livePlaylist(native){const poll=native?++nativeLivePolls:0,count=native?Math.min(liveParts.length,poll+1):2,ended=native&&count===liveParts.length;return '#EXTM3U\n#EXT-X-VERSION:7\n#EXT-X-TARGETDURATION:2\n#EXT-X-MEDIA-SEQUENCE:0\n'+liveMap+'\n'+liveParts.slice(0,count).map(part=>'#EXTINF:'+part.duration+'\n'+part.url+'\n').join('')+(ended?'#EXT-X-ENDLIST\n':'');}
const server=http.createServer((req,res)=>{let url=new URL(req.url,'http://127.0.0.1');res.setHeader('Cache-Control','no-store');if(['/capture-fixture.zip','/capture-fixture.udmtest','/capture-fixture.bin','/capture-fixture.udmforce'].includes(url.pathname)){
 let begin=0,end=automatic.length-1;if(req.headers.range){const r=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range);if(!r){res.writeHead(416);return res.end();}begin=+r[1];if(r[2])end=Math.min(end,+r[2]);if(begin>end){res.writeHead(416);return res.end();}res.statusCode=206;res.setHeader('Content-Range','bytes '+begin+'-'+end+'/'+automatic.length);}
 res.setHeader('ETag','"capture-fixture-v1"');res.setHeader('Content-Type','application/octet-stream');res.setHeader('Content-Disposition','attachment; filename="'+url.pathname.slice(1)+'"');res.setHeader('Content-Length',end-begin+1);
 let timer,closed=false;res.on('close',()=>{closed=true;clearTimeout(timer);});const pump=()=>{if(closed)return;if(begin>end)return res.end();const next=Math.min(begin+16384,end+1),chunk=automatic.subarray(begin,next);begin=next;if(res.write(chunk))timer=setTimeout(pump,8);else res.once('drain',()=>{timer=setTimeout(pump,8);});};pump();return;
 }if(url.pathname==='/live-hls'){res.setHeader('Content-Type','text/html');return res.end(hls.replace('/master.m3u8','/live-master.m3u8').replace('/index.m3u8','/live-index.m3u8').replace('Recorded HLS:','Live HLS:'));}if(url.pathname==='/live-master.m3u8'){res.setHeader('Content-Type','application/vnd.apple.mpegurl');return res.end(fs.readFileSync(path.join(root,'master.m3u8'),'utf8').replace('index.m3u8','live-index.m3u8'));}if(url.pathname==='/live-index.m3u8'){res.setHeader('Content-Type','application/vnd.apple.mpegurl');return res.end(livePlaylist(!req.headers['sec-fetch-mode']));}if(url.pathname==='/live-stats'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({nativeLivePolls,segments:liveParts.length}));}if(url.pathname==='/'){res.setHeader('Content-Type','text/html');return res.end(html);}if(url.pathname==='/embed'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><title>UDM embedded fixture</title><body style="margin:30px 8px"><video style="width:390px" controls muted loop autoplay src="/sample.mp4"></video></body>');}if(url.pathname==='/hls'){res.setHeader('Content-Type','text/html');return res.end(hls.replace('/master.m3u8',url.searchParams.get('catalog')==='before'?'/master-before.m3u8':url.searchParams.get('catalog')==='after'?'/master-after.m3u8':'/master.m3u8'));}if(url.pathname==='/download'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><title>UDM download fixture</title><a href="/capture-fixture.udmtest" download>Download fixture file</a>');}if(url.pathname==='/isolation'){res.setHeader('Content-Type','text/html');return res.end('<!doctype html><title>UDM document isolation fixture</title><iframe name=player style="width:720px;height:500px" src="/hls?catalog=before"></iframe>');}const name=url.pathname.slice(1);if(!/^(sample\.mp4|master(?:-before|-after)?\.m3u8|index\.m3u8|init\.mp4|index\d+\.m4s)$/.test(name)){res.writeHead(404);return res.end();}const file=path.join(root,/^master-/.test(name)?'master.m3u8':name);if(!fs.existsSync(file)){res.writeHead(404);return res.end();}const data=fs.readFileSync(file);res.setHeader('Accept-Ranges','bytes');res.setHeader('Content-Type',name.endsWith('m3u8')?'application/vnd.apple.mpegurl':'video/mp4');let start=0,end=data.length-1;if(req.headers.range){const m=/^bytes=(\d+)-(\d*)$/.exec(req.headers.range);if(!m||Number(m[1])>end){res.writeHead(416);return res.end();}start=Number(m[1]);if(m[2])end=Math.min(end,Number(m[2]));res.statusCode=206;res.setHeader('Content-Range',`bytes ${start}-${end}/${data.length}`);}res.setHeader('Content-Length',end-start+1);res.end(req.method==='HEAD'?undefined:data.subarray(start,end+1));});
server.listen(43821,'127.0.0.1',()=>console.log('UDM browser fixture: http://127.0.0.1:43821'));
setTimeout(()=>server.close(),40*60*1000).unref();
