#pragma once
static void catalogChecks(const udm::fs::path& root){
 using namespace udm;Manager source(root/L"catalog-source");auto p=source.state["Settings"];p["DownloadFolder"]=utf8((root/L"catalog-files").wstring());p["CategoryFolders"]=false;source.setSettings(p);auto job=source.add("https://example.com/one.zip","","one.zip","Main queue",true,{{"Authorization","Bearer secret"}});job->data["Description"]="Archive description";job->data["DownloadPage"]="https://example.com/page";
 auto catalog=exportCatalog(source,{job});check(!catalog["Downloads"][0].contains("ProtectedHeaders")&&str(catalog["Downloads"][0],"Description")=="Archive description","Catalog excludes credentials by default and retains metadata");auto protectedCatalog=exportCatalog(source,{job},true);check(protectedCatalog.dump().find("Bearer secret")==std::string::npos&&readHeaders(protectedCatalog["Downloads"][0]).at("Authorization")=="Bearer secret","Opt-in catalog credentials remain Windows-account encrypted");
 Manager target(root/L"catalog-target");auto destination=utf8((root/L"catalog-import").wstring());check(importCatalog(target,catalog,destination)==1&&str(target.jobs[0]->data,"Status")=="Paused"&&str(target.jobs[0]->data,"Description")=="Archive description","Catalog import restores metadata into a paused download");check(importCatalog(target,catalog,destination)==0,"Repeated catalog import avoids duplicate records");
 auto before=target.snapshot();auto bad=catalog;bad["Downloads"][0]["FileName"]="../../escape.zip";rejects([&]{importCatalog(target,bad,destination);},"Catalog path traversal rejected");check(target.snapshot()==before,"Rejected import leaves history unchanged");
 bad=catalog;bad["Downloads"][0]["Url"]="https://example.com/different";bad["Downloads"].push_back({{"Url","javascript:alert(1)"}});rejects([&]{importCatalog(target,bad,destination);},"Invalid later catalog entry cancels the whole import");check(target.snapshot()==before,"Catalog validation is atomic across entries");
 auto blocked=target.root/L"state.json.tmp";fs::create_directory(blocked);auto incoming=catalog;incoming["Downloads"][0]["Url"]="https://example.com/new";rejects([&]{importCatalog(target,incoming,destination);},"Catalog persistence error is reported");fs::remove(blocked);check(target.snapshot()==before,"Catalog write failure rolls back all jobs and queues");
 fs::create_directories(job->target().parent_path());writeBytes(job->target(),Bytes{'z','i','p'});job->data["Status"]="Complete";job->data["Size"]=3;job->data["Sha256"]=fileHash(job->target());auto complete=exportCatalog(source,{job});Manager attached(root/L"catalog-attached");check(importCatalog(attached,complete,"",false,true)==1&&str(attached.jobs[0]->data,"Status")=="Complete"&&readText(job->target())=="zip","Explicit import can attach a hash-verified existing completed file");Manager copied(root/L"catalog-copied");importCatalog(copied,complete,"");check(str(copied.jobs[0]->data,"Status")=="Paused"&&copied.jobs[0]->target()!=job->target()&&readText(job->target())=="zip","Default import creates a distinct paused copy and never overwrites a file");
 auto hostile=complete;hostile["Downloads"][0]["Queue"]="Imported queue";hostile["Queues"]=Json::array({{{"Name","Imported queue"},{"Enabled",true},{"FinishAction","Shut down"},{"RepeatMinutes",1}}});Manager safe(root/L"catalog-safe");importCatalog(safe,hostile,destination);auto q=safe.state["Queues"].back();check(!yes(q,"Enabled")&&str(q,"FinishAction")=="None"&&!num(q,"RepeatMinutes"),"Imported catalogs cannot arm a saved power action or repeating download");
 auto media=catalog;media["Downloads"][0]["RequiresMediaCapture"]=true;media["Downloads"][0]["Url"]="https://example.com/media";Manager mediaTarget(root/L"catalog-media");importCatalog(mediaTarget,media,destination);rejects([&]{mediaTarget.resume(mediaTarget.jobs[0]);},"Imported media requires fresh playback capture instead of downloading a page as video");
 auto proxy=p;proxy["ProxyMode"]="Use a proxy server";proxy["Proxy"]="";rejects([&]{source.setSettings(proxy);},"Manual proxy requires a server");proxy["ProxyMode"]="Connect directly";proxy["Proxy"]="invalid-unused-proxy";source.setSettings(proxy);check(str(source.state["Settings"],"ProxyMode")=="Connect directly","Direct connection preference is preserved");
}
static void zipChecks(const udm::fs::path& root){using namespace udm;Bytes directory;auto put=[&](uint64_t n,int width){for(int i=0;i<width;++i)directory.push_back((unsigned char)(n>>(i*8)));};auto filename=std::string("folder/readme.txt");put(0x02014b50,4);put(20,2);put(20,2);put(0x800,2);put(0,2);put(0,4);put(0,4);put(3,4);put(3,4);put(filename.size(),2);put(0,2);put(0,2);put(0,2);put(0,2);put(0,4);put(0,4);directory.insert(directory.end(),filename.begin(),filename.end());auto size=directory.size();put(0x06054b50,4);put(0,2);put(0,2);put(1,2);put(1,2);put(size,4);put(0,4);put(0,2);auto path=root/L"preview-fixture.zip";writeBytes(path,directory);auto content=zipContents(path);check(content.size()==1&&content[0].name==filename&&content[0].size==3,"ZIP preview reads central-directory names and sizes without extraction");check(!fs::exists(root/L"folder"),"ZIP preview does not extract archive paths");directory.resize(directory.size()-1);writeBytes(path,directory);rejects([&]{zipContents(path);},"Truncated ZIP directory rejected");writeBytes(path,Bytes{'P','K','n','o','t','z','i','p'});rejects([&]{zipContents(path);},"Non-ZIP data rejected by archive preview");}
static void recycleChecks(const udm::fs::path& root){using namespace udm;auto pending=std::async(std::launch::async,[&]{auto hr=CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);if(FAILED(hr))throw std::runtime_error("Cannot initialize recycle test apartment");try{Manager m(root/L"recycle-state");auto j=m.add("https://example.com/disposable",utf8((root/L"recycle-files").wstring()),"udm-disposable-"+guid()+".txt");fs::create_directories(j->target().parent_path());writeBytes(j->target(),Bytes{'t','e','s','t'});rejects([&]{m.recycleCompleted(j);},"Unfinished download cannot be recycled");j->data["Status"]="Complete";m.recycleCompleted(j);check(!fs::exists(j->target())&&!str(j->data,"RecycledAt").empty()&&m.jobs.size()==1,"Disposable completed test file is recycled while its history remains");}catch(...){CoUninitialize();throw;}CoUninitialize();});pending.get();}
