#pragma once
#include "SiteLogins.hpp"
#include "DialUp.hpp"
#include "ClipboardPolicy.hpp"
static void connectionChecks(const fs::path& root){
 auto login=[](const char* address,const char* user){return makeSiteLogin(address,user,"fixture-secret");};
 Json prefs=defaultSettings();prefs["SiteLogins"]=Json::array({login("https://example.test/","root"),login("https://example.test/private/","private"),login("https://example.test/private/deep/","deep"),login("https://other.test/","other")});validateSiteLogins(prefs);
 auto user=[&](const std::string& address,bool sensitive=true){return basicLogin(siteRequestHeaders(address,{},prefs,sensitive)).first;};
 check(user("https://example.test/private/deep/file")=="deep"&&user("https://example.test/private/other")=="private","Saved credentials choose the most specific folder");
 check(user("https://example.test/private")=="private"&&user("https://example.test/privateer/file")=="root","Folder credentials respect path segment boundaries");
 check(user("https://example.test/Private/file")=="root"&&user("https://example.test/private/file?folder=/other")=="private","Folder matching preserves case and ignores query values");
 check(user("https://example.test/%70rivate/file")=="private","Equivalent unreserved URL escapes match the saved folder");
 for(const char* path:{"/private/%2e%2e/escape","/private/%2fescape","/private/%5cescape","/private/%252fescape","/private//escape","/private/%00escape"})check(user(std::string("https://example.test")+path).empty(),"Ambiguous URL paths do not receive saved credentials");
 check(user("http://example.test/private/file").empty()&&user("https://cdn.example.test/private/file").empty()&&user("https://example.test:444/private/file").empty(),"Stored passwords stay on their exact HTTPS origin");
 check(user("https://other.test/file",false).empty(),"Redirect to another origin cannot select that site's saved password");
 auto clean=siteRequestHeaders("https://other.test/file",{{"Cookie","secret"},{"Authorization","Bearer secret"},{"Origin","https://example.test"},{"Referer","secret"},{"Accept","*/*"}},prefs,false);check(clean.size()==1&&clean.count("Accept"),"Cross-origin request rebuilding removes sensitive context");
 Headers explicitHeaders;setBasicLogin(explicitHeaders,"explicit","password");check(basicLogin(siteRequestHeaders("https://example.test/private/file",explicitHeaders,prefs)).first=="explicit","Per-download credentials override the saved folder login");
 check(headerValue(siteRequestHeaders("https://example.test/private/file",{{"Authorization","Bearer token"}},prefs),"Authorization")=="Bearer token","Browser authorization is not replaced by a saved Basic login");
 Headers disabled;setBasicLogin(disabled,"","",false);check(headerValue(siteRequestHeaders("https://example.test/private/file",disabled,prefs),"Authorization").empty(),"Removing a per-file login disables automatic saved credentials");
 Json legacy=prefs;legacy["SiteLogins"][0].erase("Path");validateSiteLogins(legacy);check(basicLogin(siteRequestHeaders("https://example.test/file",{},legacy)).first=="root","Existing origin-only saved logins remain compatible");
 for(const char* address:{"mms://example.test/","https://example.test/private?token=1","https://example.test/private#fragment","https://example.test/private/../"})rejects([&]{login(address,"u");},"Saved login editor rejects an unsafe or ambiguous scope");
 auto duplicate=prefs;duplicate["SiteLogins"].push_back(prefs["SiteLogins"][0]);rejects([&]{validateSiteLogins(duplicate);},"Duplicate saved login scope is rejected");
 Manager manager(root/L"connection-models");prefs["DownloadFolder"]=utf8((root/L"connection-files").wstring());manager.setSettings(prefs);auto job=manager.add("https://example.test/private/file");check(readHeaders(job->data).empty(),"Automatic saved credentials are not frozen in each download record");
 prefs["SiteLogins"][1]=login("https://example.test/private/","updated");manager.setSettings(prefs);check(basicLogin(siteRequestHeaders(str(job->data,"Url"),readHeaders(job->data),manager.state["Settings"])).first=="updated","Editing a saved login reaches previously added downloads");
 check(manager.findDuplicate(str(job->data,"Url"),{})==job,"Duplicate detection uses current scoped credentials consistently");
 {Manager reopened(manager.root);check(basicLogin(siteRequestHeaders(str(job->data,"Url"),{},reopened.state["Settings"])).first=="updated"&&readText(manager.root/L"state.json").find("fixture-secret")==std::string::npos,"Directory credentials survive restart and remain protected at rest");}
 Json socks={{"ProxyMode","Use a SOCKS4 / 4a proxy"},{"Proxy","127.0.0.1:1080"},{"ProxyUser","user-id"}};validateSocksSettings(socks);check(true,"SOCKS4 accepts a user ID without a password");socks["ProxySecret"]=protect("not-supported");rejects([&]{validateSocksSettings(socks);},"SOCKS4 cannot silently discard a configured password");socks["ProxySecret"]="";
 rejects([&]{validateSocksDestination(Url("http://[2001:db8::1]/"),socks);},"SOCKS4 IPv6 requests fail before a direct connection");rejects([&]{validateSocksDestination(Url("http://127.0.0.1/"),socks);},"SOCKS4 keeps the loopback bypass guard");
 struct Fake:DialBackend {std::atomic<int> calls{0};std::atomic_bool online{false};int failures=0,delay=5;bool stall=false;bool connected(const Json&)override{return online;}void connect(const Json&,const Cancel& c)override{++calls;if(stall){for(;;)c.wait(10);}c.wait(delay);if(calls<=failures)throw std::runtime_error("Fixture dial failure");online=true;}};
 Json dial={{"DialEnabled",true},{"DialEntry","Fixture"},{"DialAttempts",3},{"DialRetrySeconds",1},{"DialTimeoutSeconds",10}};
 {auto f=std::make_unique<Fake>();auto raw=f.get();DialUp gate(std::move(f));Cancel c;auto off=dial;off["DialEnabled"]=false;gate.ensure(off,c);check(raw->calls==0,"Disabled automatic dial never contacts the backend");raw->online=true;gate.ensure(dial,c);check(raw->calls==0,"Existing Windows connections are reused without redial");}
 {auto f=std::make_unique<Fake>();auto raw=f.get();raw->delay=150;DialUp gate(std::move(f));std::vector<std::future<void>> pending;for(int i=0;i<8;++i)pending.push_back(std::async(std::launch::async,[&]{Cancel c;gate.ensure(dial,c);}));for(auto& p:pending)p.get();check(raw->calls==1,"Eight concurrent download workers share one connection attempt");}
 {auto f=std::make_unique<Fake>();auto raw=f.get();raw->failures=2;DialUp gate(std::move(f));Cancel c;gate.ensure(dial,c);check(raw->calls==3&&raw->online,"Failed dial attempts retry and then release the download");}
 {auto f=std::make_unique<Fake>();auto raw=f.get();raw->failures=100;DialUp gate(std::move(f));Cancel c;auto once=dial;once["DialAttempts"]=1;rejects([&]{gate.ensure(once,c);},"Exhausted dial retries report the connection failure");rejects([&]{gate.ensure(once,c);},"Concurrent waiters see the same recent connection failure");check(raw->calls==1,"Failed parallel jobs do not each start another dial sequence");}
 {auto f=std::make_unique<Fake>();auto raw=f.get();raw->stall=true;DialUp gate(std::move(f));Cancel c;c.deadline=GetTickCount64()+150;auto started=GetTickCount64();rejects([&]{gate.ensure(dial,c);},"Pause interrupts an in-progress dial attempt");check(GetTickCount64()-started<600&&raw->calls==1,"Dial cancellation does not consume remaining retry attempts");}
 {auto f=std::make_unique<Fake>();auto raw=f.get();raw->failures=100;DialUp gate(std::move(f));Cancel c;c.deadline=GetTickCount64()+150;auto forever=dial;forever["DialAttempts"]=0;auto started=GetTickCount64();rejects([&]{gate.ensure(forever,c);},"Unlimited redial remains cancellable during retry delay");check(GetTickCount64()-started<600,"Pause interrupts retry delay promptly");}
 for(const char* key:{"DialAttempts","DialRetrySeconds","DialTimeoutSeconds"}){auto invalid=dial;invalid[key]=-1;rejects([&]{validateDialSettings(invalid);},"Dial settings reject invalid timing values");}auto invalid=dial;invalid["DialEntry"]="";rejects([&]{validateDialSettings(invalid);},"Automatic dial requires an explicitly selected connection");
 auto badAgent=prefs;badAgent["UserAgent"]="UDM\r\nX-Injected: yes";rejects([&]{manager.setSettings(badAgent);},"Manual User-Agent rejects header injection");
 check(Url("ftp://example.test:2121/file.zip").scheme=="ftp"&&Url("ftp://example.test:2121/file.zip").port==2121,"FTP addresses reach the FTP transport with their explicit port");for(const char* value:{"ftp://example.test:0/file","ftp://example.test:65536/file","ftp://u:p@example.test/file"})rejects([&]{Url parsed(value);},"FTP URL parser rejects invalid ports and embedded credentials");

 auto ftpJob=manager.add("ftp://example.test/archive.zip","","archive.zip","Main queue",true,{{"Authorization","Basic "+b64(Bytes{'u',':','p'})}});ftpJob->data["FtpInvalidated"]=true;ftpJob->data["FtpModified"]="20260926000000";ftpJob->data["Received"]=64;ftpJob->data["Segments"]=Json::array({{{"Index",0},{"Start",0},{"End",127},{"Done",64}}});
 auto ftpCopy=manager.redownload(ftpJob);check(ftpCopy->id()!=ftpJob->id()&&ftpCopy->target()!=ftpJob->target()&&num(ftpJob->data,"Received")==64,"Redownload starts a separate FTP copy and preserves the stopped original");
 check(!ftpCopy->data.contains("FtpInvalidated")&&ftpCopy->data["Segments"].empty()&&num(ftpCopy->data,"Received")==0,"FTP Redownload resets invalidated metadata and segment state");
 check(readHeaders(ftpCopy->data)==readHeaders(ftpJob->data),"FTP Redownload preserves explicitly supplied encrypted login");ftpJob->data["Status"]="Failed";check(manager.redownload(ftpJob)->id()!=ftpJob->id(),"Failed FTP downloads can start a fresh copy without discarding old parts");
 auto clip=defaultSettings();clip["ClipboardMonitor"]=true;clip["CaptureExtensions"]="zip iso";clip["CaptureExcludedHosts"]="blocked.test";
 check(clipboardCandidate("https://files.test/download.ISO?token=fixture",clip)&&!clipboardCandidate("https://files.test/watch?v=123",clip),"Clipboard capture filters file extensions and ignores URL query text");
 check(!clipboardCandidate("https://sub.blocked.test/file.zip",clip)&&!clipboardCandidate("file:///C:/file.zip",clip)&&!clipboardCandidate("https://user:pass@files.test/file.zip",clip),"Clipboard capture rejects excluded hosts, local paths and embedded credentials");
 clip["ClipboardOnlyFileTypes"]=false;check(clipboardCandidate("https://files.test/download",clip),"Clipboard option supports extensionless download addresses");clip["ClipboardMonitor"]=false;check(!clipboardCandidate("https://files.test/download.iso",clip),"Disabled clipboard monitor never offers a URL");
 auto measure=[&](const char* mode){Manager limited(root/wide(std::string("limits-")+mode));auto p=limited.state["Settings"];p["DownloadFolder"]=utf8((root/L"limits-files").wstring());p["LimitKbps"]=128;p["GlobalLimitMode"]=mode;limited.setSettings(p);auto one=limited.add("https://example.test/one"),two=limited.add("https://example.test/two");Rate a,b;Cancel c;auto start=GetTickCount64();auto first=std::async(std::launch::async,[&]{limited.charge(65536,c,a,one);});auto second=std::async(std::launch::async,[&]{limited.charge(65536,c,b,two);});first.get();second.get();return GetTickCount64()-start;};
 auto aggregate=measure("Total across downloads"),individual=measure("Each download");check(aggregate>=900&&individual>=450&&individual<aggregate*0.8,"Actual concurrent rate waits distinguish aggregate and per-download global caps");
 Fixture fixture;Manager real(root/L"dial-failure");auto settings=real.state["Settings"];settings["DownloadFolder"]=utf8((root/L"dial-failure-files").wstring());settings["DialEnabled"]=true;settings["DialEntry"]="UDM-nonexistent-"+guid();settings["DialAttempts"]=1;real.setSettings(settings);auto blocked=real.add(fixture.url("/file"));auto before=fixture.requests.load();real.resume(blocked);for(int i=0;i<300;++i){real.tick();if(!real.isActive(blocked)&&str(blocked->data,"Status")=="Failed")break;Sleep(10);}real.stop();check(str(blocked->data,"Status")=="Failed"&&fixture.requests==before&&!fs::exists(blocked->target()),"Real Windows missing-entry failure blocks the actual download before any HTTP request");check(!blocked->data.contains("ConnectionStatus"),"Dial failure clears the temporary progress message");
}
