#pragma once
#include "DirectMediaRefresh.hpp"
static void directMediaRefreshChecks(const fs::path& root){
 Manager m(root/L"direct-refresh-state");m.state["Settings"]["DownloadFolder"]=utf8((root/L"direct-refresh-downloads").wstring());m.state["Settings"]["CategoryFolders"]=false;m.state["Settings"]["Retries"]=0;
 Fixture video,audio;video.payload=readText(root/L"generated-video.mp4");audio.payload=readText(root/L"generated-audio.mp4");const i64 prefix=(i64)video.payload.size()/2;
 const std::string page="https://www.youtube.com/watch?v=abcdefghijk";
 auto url=[](int itag,const char* token){return "https://rr1.googlevideo.com/videoplayback?itag="+std::to_string(itag)+"&lmt=12345&expire=4102444800&id="+token;};
 auto message=[&](const char* name){return Json{{"action","media"},{"url",page},{"height",720},{"pixelHeight",720},{"formatId","137"},{"exactQuality",true},{"videoUrl",url(137,"new-session")},{"audioUrl",url(140,"new-session")},{"filename",name},{"userAgent","fresh-browser"}};};
 auto seed=[&](const char* name){auto request=message(name);request["videoUrl"]=url(137,"old-session");request["audioUrl"]=url(140,"old-session");auto j=m.receive(request);j->data["Status"]="Paused";auto v=j->video,a=j->audio;v->data["Status"]="Paused";v->data["Size"]=video.payload.size();v->data["ETag"]="\"fixture-v1\"";v->data["RangeSupported"]=true;v->data["Received"]=prefix;v->data["Segments"]=Json::array({{{"Index",0},{"Start",0},{"End",(i64)video.payload.size()-1},{"Done",prefix}}});auto parts=m.root/L"parts"/wide(v->id());fs::create_directories(parts);writeBytes(parts/L"0000.part",Bytes(video.payload.begin(),video.payload.begin()+(size_t)prefix));fs::create_directories(a->target().parent_path());writeBytes(a->target(),Bytes(audio.payload.begin(),audio.payload.end()));a->data["Status"]="Complete";a->data["Size"]=audio.payload.size();a->data["Received"]=audio.payload.size();a->data["ETag"]="\"fixture-v1\"";a->data["Sha256"]=fileHash(a->target());m.save();return j;};
 auto partial=[&](JobPtr j){return m.root/L"parts"/wide(j->video->id())/L"0000.part";};
 auto route=[&](JobPtr j,const char* videoRoute="/range",const char* audioRoute="/range"){j->video->data["Url"]=video.url(videoRoute);j->audio->data["Url"]=audio.url(audioRoute);};
 auto apply=[&](JobPtr j){m.beginAddressRefresh(j);m.receive(message("new browser title"));m.applyMediaRefresh(j);};
 auto j=seed("direct-original.mp4");auto id=j->id(),videoId=j->video->id(),audioId=j->audio->id(),saved=fileHash(partial(j)),savedAudio=fileHash(j->audio->target());auto count=m.jobs.size();check(m.canRefreshAddress(j),"Unfinished direct video/audio capture exposes address recovery");m.beginAddressRefresh(j);auto original=j->snapshot();
 for(const auto& fields:std::vector<Json>{Json{{"height",1080}},Json{{"pixelHeight",1080}},Json{{"formatId","136"}},Json{{"exactQuality",false}},Json{{"audioUrl",""}},Json{{"output","audio"}}}){auto changed=message("changed");for(auto it=fields.begin();it!=fields.end();++it)changed[it.key()]=it.value();rejects([&]{m.receive(changed);},"Direct refresh rejects incompatible quality or track selection");}
 for(const auto& parameter:{"&lmt=999","&itag=141","&expire=1","&range=0-1","&xtags=es"}){auto changed=message("changed");if(std::string(parameter)=="&xtags=es"){j->audio->data["Url"]=str(j->audio->data,"Url")+"&xtags=en";}changed["audioUrl"]=str(changed,"audioUrl")+parameter;rejects([&]{m.receive(changed);},"Direct refresh rejects changed revision, language, expired or fragmented links");j->audio->data=original["Audio"];}
 auto bad=message("changed");bad["videoUrl"]="https://googlevideo.com.evil.invalid/videoplayback";rejects([&]{m.receive(bad);},"Direct refresh rejects a deceptive playback host");bad=message("changed");bad["headers"]={{"Cookie","value\r\nInjected: yes"}};rejects([&]{m.receive(bad);},"Direct refresh rejects injected capture headers");
 check(j->snapshot()==original&&m.jobs.size()==count,"Rejected direct captures preserve both child tracks and the original record");
 bad=message("other");bad["url"]="https://www.youtube.com/watch?v=ZYXwvutsrqp";check(!m.captureMediaRefresh(bad),"A different video cannot replace the armed direct download");
 auto capture=message("title changed");capture["url"]="https://youtu.be/abcdefghijk";capture["headers"]={{"Cookie","fresh-private-cookie"}};
 const auto tag=wide("direct-"+guid().substr(0,16));SetEnvironmentVariableW(L"UDM_INSTANCE_TAG",tag.c_str());{PipeServer pipe(m,[]{});auto reply=send(capture,3000);check(yes(reply,"ok")&&yes(reply,"refreshPending")&&str(reply,"id")==id&&m.jobs.size()==count,"Real native pipe stages direct refresh on the same record, including equivalent page URLs");}SetEnvironmentVariableW(L"UDM_INSTANCE_TAG",nullptr);
 check(str(m.addressRefreshCandidate(j),"kind")=="direct-media"&&str(j->video->data,"Url")==str(original["Video"],"Url"),"Browser recapture remains pending until desktop review");check(readText(m.root/L"state.json").find("fresh-private-cookie")==std::string::npos,"Pending direct capture credentials remain encrypted");
 auto expired=m.addressRefreshCandidate(j);expired["received"]=epoch()-11*60*1000;j->data["ProtectedRefreshOffer"]=protect(expired.dump());rejects([&]{m.applyMediaRefresh(j);},"Expired direct refresh candidates cannot be applied");m.receive(capture);m.cancelAddressRefresh(j);rejects([&]{m.applyMediaRefresh(j);},"Cancelled direct refresh cannot apply a saved candidate");m.beginAddressRefresh(j);check(m.addressRefreshCandidate(j).is_null(),"Reopening direct refresh clears the unapproved candidate");m.receive(capture);
 auto before=j->snapshot();const auto trueRoot=m.root,blocked=root/L"direct-blocked-state";writeBytes(blocked,Bytes{1});m.root=blocked;rejects([&]{m.applyMediaRefresh(j);},"Direct refresh reports state checkpoint failure");m.root=trueRoot;check(j->snapshot()==before,"Failed direct refresh rolls back parent and both child metadata");m.applyMediaRefresh(j);
 check(j->id()==id&&j->video->id()==videoId&&j->audio->id()==audioId&&str(j->data,"FileName")==str(original,"FileName")&&fileHash(partial(j))==saved&&fileHash(j->audio->target())==savedAudio,"Applying direct refresh preserves identities, filename, partial video and completed audio");check(yes(j->video->data,"RefreshPendingValidation")&&yes(j->audio->data,"CompletedMediaRefreshPendingValidation")&&readHeaders(j->video->data)["Cookie"]=="fresh-private-cookie"&&readHeaders(j->audio->data)["User-Agent"]=="fresh-browser","Direct refresh replaces both track sessions and persists separate validation requirements");
 {Manager reopened(m.root);auto restored=reopened.jobs.front();check(restored->id()==id&&yes(restored->video->data,"RefreshPendingValidation")&&yes(restored->audio->data,"CompletedMediaRefreshPendingValidation"),"Direct refresh survives restart with both validation flags intact");route(restored);int vr=video.requests,ar=audio.requests;mediaTransfer(reopened,restored,std::make_shared<Cancel>());check(str(restored->data,"Status")=="Complete"&&video.requests-vr==2&&audio.requests-ar==1,"Direct refresh resumes the saved video offset and validates completed audio with one probe");check(num(restored->video->data,"TransferredBytes")==video.payload.size()-prefix&&!yes(restored->audio->data,"CompletedMediaRefreshPendingValidation"),"Validated direct recovery downloads only the missing video bytes");Cancel c;execute(appDir()/L"tools"/L"ffmpeg.exe",{L"-v",L"error",L"-i",restored->target().wstring(),L"-f",L"null",L"-"},30,c);check(true,"Refreshed direct video/audio output fully decodes");}
 auto rotated=seed("rotated-audio-validator.mp4");rotated->audio->data["ETag"]="\"previous-tag\"";apply(rotated);route(rotated);int ar=audio.requests;mediaTransfer(m,rotated,std::make_shared<Cancel>());check(str(rotated->data,"Status")=="Complete"&&audio.requests-ar==2&&num(rotated->audio->data,"TransferredBytes")==audio.payload.size(),"Rotated complete-track validators fall back to exact streaming byte comparison");
 auto changed=seed("changed-audio.mp4");changed->audio->data["ETag"]="\"previous-tag\"";apply(changed);route(changed);auto audioBytes=audio.payload;audio.payload[audio.payload.size()/2]^=1;int vr=video.requests;rejects([&]{mediaTransfer(m,changed,std::make_shared<Cancel>());},"Changed completed audio blocks mixed-track assembly");audio.payload=audioBytes;check(video.requests==vr&&fileHash(partial(changed))==saved&&fileHash(changed->audio->target())==savedAudio&&!fs::exists(changed->target())&&yes(changed->audio->data,"CompletedMediaRefreshPendingValidation"),"Failed audio comparison preserves both caches and blocks missing-video requests");
 auto corrupted=seed("corrupt-local-audio.mp4");apply(corrupted);route(corrupted);auto altered=Bytes(audioBytes.begin(),audioBytes.end());altered[0]^=1;writeBytes(corrupted->audio->target(),altered);vr=video.requests;ar=audio.requests;rejects([&]{mediaTransfer(m,corrupted,std::make_shared<Cancel>());},"Local completed-track corruption is rejected before reuse");check(video.requests==vr&&audio.requests==ar&&!fs::exists(corrupted->target()),"Local integrity failure starts no fresh transfer and publishes no output");
 auto missing=seed("missing-local-audio.mp4");apply(missing);route(missing);fs::remove(missing->audio->target());vr=video.requests;ar=audio.requests;rejects([&]{mediaTransfer(m,missing,std::make_shared<Cancel>());},"Missing completed audio cannot skip refresh validation");check(video.requests==vr&&audio.requests==ar&&fileHash(partial(missing))==saved&&yes(missing->audio->data,"CompletedMediaRefreshPendingValidation"),"Missing-track rejection preserves partial video and starts no network transfer");
 auto unsafe=seed("changed-partial-validator.mp4");unsafe->video->data["ETag"]="\"different-video\"";apply(unsafe);route(unsafe);rejects([&]{mediaTransfer(m,unsafe,std::make_shared<Cancel>());},"A refreshed partial track still requires matching HTTP resume identity");check(fileHash(partial(unsafe))==saved&&yes(unsafe->video->data,"RefreshPendingValidation")&&!fs::exists(unsafe->target()),"Rejected partial-track identity preserves its bytes and pending checkpoint");
 auto stopped=seed("cancel-direct-validation.mp4");apply(stopped);route(stopped,"/range","/stall-headers");auto cancel=std::make_shared<Cancel>();auto stalled=audio.stalled.load();auto pending=std::async(std::launch::async,[&]{try{mediaTransfer(m,stopped,cancel);return false;}catch(const Cancelled&){return true;}});for(int n=0;n<200&&audio.stalled==stalled;++n)Sleep(5);auto start=GetTickCount64();cancel->stop=true;check(pending.get()&&GetTickCount64()-start<1500,"Pause promptly cancels completed-track refresh verification");check(fileHash(partial(stopped))==saved&&fileHash(stopped->audio->target())==savedAudio&&yes(stopped->audio->data,"CompletedMediaRefreshPendingValidation"),"Cancelled direct verification retains both tracks and its recovery marker");
 auto complete=seed("complete-no-refresh.mp4");complete->data["Status"]="Complete";check(!m.canRefreshAddress(complete),"Completed parent downloads cannot enter direct session recovery");
}
