#pragma once
static void duplicateChecks(const fs::path& root,Fixture& fixture){
 Manager m(root/L"duplicate-state");auto prefs=m.state["Settings"];prefs["DownloadFolder"]=utf8((root/L"duplicate-files").wstring());prefs["CategoryFolders"]=false;prefs["Retries"]=0;prefs["PrefetchFileInfo"]=false;m.setSettings(prefs);fs::create_directories(root/L"duplicate-files");
 auto old=m.add(fixture.url("/duplicate"),"","original.bin");writeBytes(old->target(),Bytes{'o','l','d'});old->data["Status"]="Complete";old->data["Size"]=3;old->data["Received"]=3;old->data["Sha256"]=fileHash(old->target());old->data["QueueMember"]=false;m.save();auto originalPath=old->target();auto originalData=old->data;auto oldHash=fileHash(originalPath);
 auto candidate=m.offerDownload(fixture.url("/duplicate"));check(str(candidate->data,"DuplicateOf")==old->id()&&str(candidate->data,"Status")=="Awaiting duplicate choice","Same URL offers a duplicate choice before transferring");
 auto count=m.jobs.size();check(m.offerDownload(fixture.url("/duplicate"))==candidate&&m.jobs.size()==count,"Repeated handoff reuses a pending duplicate prompt");rejects([&]{m.resume(candidate);},"Resume cannot bypass a pending duplicate choice");m.beginPrefetch(candidate);check(!m.isActive(candidate),"Duplicate choice never triggers prefetch");m.queueRun("Main queue",true);m.tick();check(!m.isActive(candidate),"Starting a queue cannot bypass duplicate confirmation");originalData=old->data;
 check(m.resolveDuplicate(candidate,"Existing")==old&&m.jobs.size()==count-1&&old->data==originalData,"Show existing preserves the original record and bytes");
 auto canonical=m.add("https://EXAMPLE.com:443/File.zip?token=A#one","","canonical.bin");check(m.findDuplicate("https://example.com/File.zip?token=A#two",{})==canonical,"Duplicate identity normalizes host, default port and fragments");check(!m.findDuplicate("https://example.com/file.zip?token=A",{})&&!m.findDuplicate("https://example.com/File.zip?token=B",{}),"Path case and signed query values remain distinct");
 auto auth=m.add("https://example.com/private","","account.bin","Main queue",true,{{"Authorization","Basic A"},{"Cookie","user=1"}});check(m.findDuplicate("https://example.com/private",{{"authorization","Basic A"},{"cookie","user=1"}})==auth,"Duplicate identity matches account header names case-insensitively");check(!m.findDuplicate("https://example.com/private",{{"Authorization","Basic B"},{"Cookie","user=1"}}),"Different credentials never reuse another account's download");
 auto copy=m.resolveDuplicate(m.offerDownload(fixture.url("/duplicate")),"Numbered");check(copy!=old&&copy->target()!=originalPath&&str(copy->data,"DuplicateOf").empty()&&str(copy->data,"Status")=="Paused","Numbered choice creates a separate paused download");m.remove(copy);
 prefs["DuplicatePolicy"]="Existing";m.setSettings(prefs);check(m.offerDownload(fixture.url("/duplicate"))==old,"Remembered existing policy reuses history");prefs["DuplicatePolicy"]="Numbered";m.setSettings(prefs);copy=m.offerDownload(fixture.url("/duplicate"));check(copy!=old&&str(copy->data,"DuplicateOf").empty(),"Remembered numbered policy creates another copy without a prompt");m.remove(copy);prefs["DuplicatePolicy"]="Replace";rejects([&]{m.setSettings(prefs);},"Replacement cannot be made an automatic default");prefs["DuplicatePolicy"]="Ask";m.setSettings(prefs);
 auto replacement=m.resolveDuplicate(m.offerDownload(fixture.url("/duplicate")),"Replace");auto previous=fs::path(wide(str(replacement->data,"PreviousPath")));check(replacement->target()==originalPath&&previous.parent_path()==originalPath.parent_path()&&fileHash(originalPath)==oldHash&&!fs::exists(previous),"Choosing replacement leaves the original intact and reserves a same-volume backup");
 auto reserved=m.add("https://example.com/reserved",utf8(previous.parent_path().wstring()),utf8(previous.filename().wstring()));check(reserved->target()!=previous,"New downloads cannot steal the previous-version location");rejects([&]{m.configure(replacement,{{"FileName","changed.bin"}});},"Replacement properties retain the agreed destination");
 auto extra=m.add(fixture.url("/duplicate"),"","extra.bin");extra->data["DuplicateOf"]=old->id();rejects([&]{m.resolveDuplicate(extra,"Replace");},"Concurrent replacement of the same completed record is rejected");m.remove(extra);
 auto blocked=m.root/L"state.json.tmp";auto staging=originalPath.parent_path()/L"test-new.assembling";writeBytes(staging,Bytes{'n','e','w'});auto newHash=fileHash(staging);auto beforeReplacement=replacement->data;
 fs::create_directory(blocked);rejects([&]{m.publishFile(replacement,staging,newHash);},"Replacement reports a history write failure");fs::remove(blocked);check(fileHash(originalPath)==oldHash&&fileHash(staging)==newHash&&!fs::exists(previous)&&old->data==originalData&&replacement->data==beforeReplacement,"History failure rolls file replacement back and preserves the new staging file");
 writeBytes(previous,Bytes{'k','e','e','p'});rejects([&]{m.publishFile(replacement,staging,newHash);},"Occupied backup path blocks replacement");check(readText(previous)=="keep"&&fileHash(originalPath)==oldHash,"Backup collision preserves both unrelated and original files");fs::remove(previous);
 writeBytes(originalPath,Bytes{'e','d','i','t'});rejects([&]{m.publishFile(replacement,staging,newHash);},"Edited original blocks replacement at publication");check(readText(originalPath)=="edit","User edits remain intact");writeBytes(originalPath,Bytes{'o','l','d'});
 {Handle lock(CreateFileW(originalPath.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));rejects([&]{m.publishFile(replacement,staging,newHash);},"File locked against replacement reports an error");}check(fileHash(originalPath)==oldHash&&fs::exists(staging),"Locked-file failure retains both versions");
 m.publishFile(replacement,staging,newHash);check(readText(originalPath)=="new"&&readText(previous)=="old"&&old->target()==previous&&str(replacement->data,"Status")=="Complete"&&str(replacement->data,"ReplacementOf").empty(),"Successful replacement publishes the new bytes and retains the previous version in history");
 {Manager reopened(m.root);check(reopened.jobs.size()==m.jobs.size(),"Replacement history survives restart");}
 // Real transfer with a saved prefix exercises resume through the duplicate path.
 auto resume=m.add(fixture.url("/resume-duplicate"),"","resume.bin");i64 retained=262144,size=(i64)fixture.payload.size();resume->data["Size"]=size;resume->data["ETag"]="\"fixture-v1\"";resume->data["RangeSupported"]=true;resume->data["Received"]=retained;resume->data["Segments"]=Json::array({{{"Index",0},{"Start",0},{"End",size-1},{"Done",retained}}});auto parts=m.root/L"parts"/wide(resume->id());fs::create_directories(parts);writeBytes(parts/L"0000.part",Bytes(fixture.payload.begin(),fixture.payload.begin()+retained));m.save();auto reuse=m.resolveDuplicate(m.offerDownload(fixture.url("/resume-duplicate")),"Existing");fixture.resumedPrefix=false;transfer(m,reuse,std::make_shared<Cancel>());auto expected=root/L"duplicate-expected.bin";writeBytes(expected,Bytes(fixture.payload.begin(),fixture.payload.end()));check(reuse==resume&&fixture.resumedPrefix&&fileHash(reuse->target())==fileHash(expected),"Duplicate existing choice resumes at the saved offset and produces exact bytes");
 // HTTP failure and checksum mismatch cannot touch a completed original.
 auto failure=m.add(fixture.url("/expired"),"","expired-original.bin");writeBytes(failure->target(),Bytes{'s','a','f','e'});failure->data["Status"]="Complete";failure->data["Sha256"]=fileHash(failure->target());auto failedReplacement=m.resolveDuplicate(m.offerDownload(fixture.url("/expired")),"Replace");rejects([&]{transfer(m,failedReplacement,std::make_shared<Cancel>());},"Rejected URL fails a replacement transfer");check(readText(failure->target())=="safe","HTTP failure leaves the completed original intact");
 auto network=m.add(fixture.url("/network-replacement"),"","network.bin");writeBytes(network->target(),Bytes{'o','l','d'});network->data["Status"]="Complete";network->data["Sha256"]=fileHash(network->target());auto incoming=m.resolveDuplicate(m.offerDownload(fixture.url("/network-replacement")),"Replace");incoming->data["ExpectedSha256"]=std::string(64,'0');rejects([&]{transfer(m,incoming,std::make_shared<Cancel>());},"Replacement checksum mismatch blocks publication");check(readText(network->target())=="old","Checksum failure preserves the original file");incoming->data["ExpectedSha256"]="";transfer(m,incoming,std::make_shared<Cancel>());check(fileHash(incoming->target())==fileHash(expected)&&readText(network->target())=="old","Actual segmented HTTP replacement retains the old version and verifies the new one");
 // Persisted journal states: before swap, after swap, and interrupted Windows rename.
 for(int phase=0;phase<3;++phase){Manager recovery(root/(L"replacement-recovery-"+std::to_wstring(phase)));recovery.state["Settings"]["DownloadFolder"]=utf8((root/L"duplicate-files").wstring());recovery.state["Settings"]["CategoryFolders"]=false;auto prior=recovery.add(fixture.url("/crash"),"","crash-"+std::to_string(phase)+".bin");writeBytes(prior->target(),Bytes{'o','l','d'});prior->data["Status"]="Complete";prior->data["Sha256"]=fileHash(prior->target());auto next=recovery.resolveDuplicate(recovery.offerDownload(fixture.url("/crash")),"Replace");auto target=prior->target(),backup=fs::path(wide(str(next->data,"PreviousPath"))),stage=target.parent_path()/(wide(next->id())+L".stage");writeBytes(stage,Bytes{'n','e','w'});auto a=next->data,b=prior->data;a["Status"]="Complete";a["Sha256"]=fileHash(stage);for(const char* key:{"ReplacementOf","ReplacementHash","PreviousPath"})a.erase(key);b["FileName"]=utf8(backup.filename().wstring());auto journal=recovery.root/L"replacements"/(wide(next->id())+L".json");atomicText(journal,Json{{"Id",next->id()},{"OriginalId",prior->id()},{"Target",utf8(target.wstring())},{"Previous",utf8(backup.wstring())},{"OldHash",fileHash(target)},{"NewHash",fileHash(stage)},{"Before",next->data},{"After",a},{"OriginalBefore",prior->data},{"OriginalAfter",b}}.dump(),false);if(phase==1){if(!ReplaceFileW(target.c_str(),stage.c_str(),backup.c_str(),0,nullptr,nullptr))throw std::runtime_error("Crash fixture swap failed.");}else if(phase==2)fs::rename(target,backup);recovery.recoverReplacements();check(!fs::exists(journal)&&readText(target)==(phase==1?"new":"old")&&str(next->data,"Status")== (phase==1?"Complete":"Paused"),("Replacement journal recovers phase "+std::to_string(phase)).c_str());}
 auto browser=m.receive({{"action","add"},{"url",fixture.url("/browser-duplicate")}});m.pause(browser);auto offer=m.receive({{"action","add"},{"url",fixture.url("/browser-duplicate")}});check(str(offer->data,"DuplicateOf")==browser->id(),"Browser handoff of a paused link uses duplicate choice");m.resolveDuplicate(offer,"Cancel");check(std::find(m.jobs.begin(),m.jobs.end(),browser)!=m.jobs.end(),"Canceling duplicate removes only the unstarted offer");
 m.stop();
}
