#pragma once
#include "GrabberLinks.hpp"
#include "GrabberProject.hpp"

static void grabberLinkRecoveryChecks(const fs::path& root){
 for(int scenario=0;scenario<7;++scenario){
  auto folder=root/L"link-recovery"/wide(std::to_string(scenario)),state=folder/L"state",target=folder/L"page.html";Json before,after;std::string id,oldHash,newHash;auto token=guid();
  {Manager manager(state);manager.state["Queues"][0]["Enabled"]=false;auto job=manager.add("https://example.test/page",utf8(folder.wstring()),"page.html","Main queue",true);writeBytes(target,Bytes{'o','l','d'});job->data["Status"]="Complete";job->data["Size"]=3;job->data["Received"]=3;job->data["ProjectId"]=guid();job->data["Sha256"]=fileHash(target);before=job->data;id=job->id();oldHash=str(before,"Sha256");manager.stop();}
  auto backup=folder/(L".udm-links-"+wide(id)+L"-"+wide(token)+L".before"),pending=folder/(L".udm-links-"+wide(id)+L"-"+wide(token)+L".after"),journal=state/L"link-conversions"/(wide(id)+L".json");
  writeBytes(pending,Bytes{'n','e','w','!'});newHash=fileHash(pending);after=before;after["Sha256"]=newHash;after["GrabberConvertedHash"]=newHash;after["GrabberSourceHash"]=oldHash;after["GrabberSourceBytes"]=3;after["Size"]=4;after["Received"]=4;after["GrabberLinksConvertedAt"]=date();
  if(scenario!=1){fs::rename(target,backup);if(scenario!=2)fs::rename(pending,target);}
  if(scenario==3)after["Folder"]=utf8((folder/L"elsewhere").wstring());
  if(scenario==4)writeBytes(target,Bytes{'e','d','i','t'});
  if(scenario==5){auto catalog=Json::parse(readText(state/L"state.json"));catalog["Downloads"][0]=after;atomicText(state/L"state.json",catalog.dump(),false);fs::remove(backup);}
  if(scenario==6)after["Size"]=9;
  Json operation={{"Version",1},{"Id",id},{"Token",token},{"Target",utf8(target.wstring())},{"OldHash",oldHash},{"NewHash",newHash},{"Before",before},{"After",after}};atomicText(journal,operation.dump(),false);
  if(scenario==3||scenario==4||scenario==6){auto hash=fileHash(target);rejects([&]{Manager recovered(state);},scenario==4?"Recovery refuses to replace a page edited after interruption":"Recovery rejects inconsistent file paths or sizes");check(fileHash(target)==hash&&fs::exists(journal)&&fs::exists(backup),"Rejected recovery preserves the document, backup and journal");}
  else{Manager recovered(state);auto expected=(scenario==0||scenario==5)?newHash:oldHash;check(fileHash(target)==expected&&str(recovered.jobs[0]->data,"Sha256")==expected,"Interrupted conversion recovers a matching document and catalog");check(!fs::exists(journal)&&!fs::exists(pending)&&!fs::exists(backup),"Successful conversion recovery cleans only its verified temporary files");recovered.stop();}
 }
}
static void grabberLinkChecks(const fs::path& root){
 check(grabberLocalReference(L"C:/mirror/docs/index.html",L"C:/mirror/img/a b#%.png")=="../img/a%20b%23%25.png","Offline relative links encode spaces, fragments and percent signs in saved names");
 check(grabberLocalReference(L"C:/mirror/docs/index.html",L"C:/mirror/docs/next.html")=="next.html","Same-folder pages use portable relative links");
 check(grabberLocalReference(L"C:/mirror/index.html",L"D:/images/a.png")=="file:///D:/images/a.png","Different-volume category folders use explicit local file URLs");
 check(grabberLocalReference(L"C:/mirror/index.html",L"//server/share/a b.png")=="file://server/share/a%20b.png","Network-share destinations use correctly formed file URLs");
 std::map<std::string,std::string> files={{"https://example.test/docs/next.php","next.php.html"},{"https://example.test/img/a.png","../Images/a%20(1).png"},{"https://example.test/js/app.js","../js/app.js"},{"https://example.test/css/base.css","../css/base.css"}};
 const std::string page="<head><base href='/docs/'><script src='/js/app.js'></script><script>let markup='<img src=fake.png>';</script></head><a href='next.php#part'>Next</a><img src='../img/a.png'><img src='/missing.png'><a href='/remote?x=1&amp;y=2#part'>Remote</a>";
 auto converted=rewriteGrabberDocument(page,"https://example.test/start",false,files);
 check(converted.find("<base")==std::string::npos&&converted.find("next.php.html#part")!=std::string::npos,"Grabber conversion removes base elements and retains destination anchors");
 check(converted.find("../Images/a%20(1).png")!=std::string::npos&&converted.find("https://example.test/missing.png")!=std::string::npos,"Downloaded assets use actual local names while omitted assets retain absolute internet addresses");
 check(converted.find("https://example.test/remote?x=1&amp;y=2#part")!=std::string::npos,"Remote navigation keeps query strings, HTML escaping and fragments");
 check(converted.find("<script src='../js/app.js'>")!=std::string::npos&&converted.find("let markup='<img src=fake.png>';")!=std::string::npos,"Link conversion preserves script code and rewrites external script sources");
 auto refs=siteReferences("<script src='app.js'>let a='<img src=fake.png>';</script><img src=real.png>",false,true);check(refs.size()==2&&refs[0].value=="app.js"&&refs[1].value=="real.png","Complete-site exploration sees script resources without interpreting JavaScript text as HTML");
 auto css=rewriteGrabberDocument("@import '../css/base.css';a{background:url('../img/a.png')}b{background:url('/remote.png')}","https://example.test/css/main.css",true,files);
 check(css.find("../Images/a%20%281%29.png")!=std::string::npos&&css.find("https://example.test/remote.png")!=std::string::npos,"CSS imports and assets use local or absolute remote addresses");
 auto form=rewriteGrabberDocument("<base href='/forms/'><form action='submit'><button formaction='save'>Save</button></form><a href='#part'>Part</a>","https://example.test/start",false,{});
 check(form.find("action='https://example.test/forms/submit'")!=std::string::npos&&form.find("formaction='https://example.test/forms/save'")!=std::string::npos,"Forms retain their web destinations after the base element is removed");
 check(form.find("href='https://example.test/forms/#part'")!=std::string::npos,"Fragment-only navigation honors a different original base address");
 auto modern=modernGrabber("https://example.test/");modern["ConvertLinks"]=true;check(grabberCollectedName(modern,{{"Url","https://example.test/index.php"},{"FileName","index.php"},{"ContentType","text/html"}})=="index.php.html","HTML endpoints receive a browser-readable saved extension");
 check(grabberCollectedName(modern,{{"Url","https://example.test/index.php"},{"SaveName","chosen.htm"},{"FileName","index.php"},{"ContentType","text/html"}})=="chosen.htm","Explicit collected filenames remain authoritative");
 auto base=root/L"grabber-links";Manager manager(base/L"state");manager.state["Settings"]["DownloadFolder"]=utf8((base/L"downloads").wstring());manager.state["Settings"]["CategoryFolders"]=false;manager.state["Settings"]["ProxyMode"]="Connect directly";manager.state["Queues"][0]["Enabled"]=false;manager.save();auto project=modernGrabber("https://example.test/docs/start.php");project["FileInclude"]="*";project["ConvertLinks"]=true;project["SaveMode"]="Folder";project["Folder"]=utf8((base/L"downloads").wstring());project["Links"]=Json::array();
 auto complete=[&](const std::string& url,const std::string& name,const std::string& body,const std::string& type){auto job=manager.add(url,utf8((base/L"downloads").wstring()),name,"Main queue",true);fs::create_directories(job->target().parent_path());writeBytes(job->target(),Bytes(body.begin(),body.end()));job->data["Status"]="Complete";job->data["Sha256"]=fileHash(job->target());job->data["Size"]=body.size();job->data["Received"]=body.size();job->data["ContentType"]=type;job->data["ProjectId"]=str(project,"Id");job->data["QueueMember"]=false;project["Links"].push_back({{"Url",url},{"FileName",name},{"ContentType",type}});return job;};
 const std::string original="\xEF\xBB\xBF<a href='next.php#anchor'>Next</a><img src='../img/picture.png'><img src='later.png'>";
 auto main=complete("https://example.test/docs/start.php","start.php.html",original,"text/html");auto next=complete("https://example.test/docs/next.php","next (1).html","<p>Next</p>","text/html");auto picture=complete("https://example.test/img/picture.png","picture.png","image","image/png");manager.saveProject(project);
 auto waiting=complete("https://example.test/waiting.png","waiting.png","wait","image/png");waiting->data["Status"]="Queued";manager.saveProject(project);
 check(!manager.convertProjectLinks(str(project,"Id")),"Queued project files defer automatic link conversion");waiting->data["Status"]="Paused";
 project["ExplorationRunning"]=true;manager.saveProject(project);check(!manager.convertProjectLinks(str(project,"Id")),"An active exploration defers link conversion until the final result set");project["ExplorationRunning"]=false;manager.saveProject(project);
 auto waitForConversion=[&]{auto end=GetTickCount64()+10000;for(;;){manager.tick();{Lock lock(manager.mutex);auto p=grabberProject(manager,str(project,"Id"));if(str(p,"LinkConversionState")!="Converting"&&!manager.isActive(main)&&!str(p,"LinkConversionState").empty())return p;}if(GetTickCount64()>end)throw std::runtime_error("Link conversion fixture timed out.");Sleep(10);}};
 auto first=waitForConversion();auto body=readText(main->target());check(str(first,"LinkConversionState")=="Complete"&&body.find("next%20%281%29.html#anchor")!=std::string::npos&&body.find("src='picture.png'")!=std::string::npos,"Idle project automatically converts completed pages to the actual numbered download destinations");
 check(fileHash(base/L"state/grabber-originals"/(wide(main->id())+L".bin"))==str(main->data,"GrabberSourceHash"),"Conversion preserves the exact original page including its byte-order mark");
 {std::ifstream input(main->target(),std::ios::binary);char bom[3]{};input.read(bom,3);check((unsigned char)bom[0]==0xef&&(unsigned char)bom[1]==0xbb&&(unsigned char)bom[2]==0xbf,"Converted UTF-8 pages retain their original byte-order mark");}
 check(fileHash(main->target())==str(main->data,"Sha256")&&num(main->data,"Size")==fs::file_size(main->target()),"Converted file size and SHA-256 match the published document");
 {Lock lock(manager.mutex);check(manager.convertProjectLinks(str(project,"Id"),true),"Completed projects can explicitly retry conversion");manager.pause(main);}
 auto stopped=waitForConversion();check(str(stopped,"LinkConversionState")=="Stopped"&&!manager.isActive(main)&&str(main->data,"Status")=="Complete","Stop cancels link conversion while preserving completed download status");
 check(manager.convertProjectLinks(str(project,"Id"),true),"Stopped conversion can restart");check(str(waitForConversion(),"LinkConversionState")=="Complete","Restarted conversion completes with the queue still disabled");
 auto snapshot=manager.snapshot();for(int i=0;i<6;++i)manager.tick();check(manager.snapshot()==snapshot,"Unchanged completed projects do not repeatedly rewrite files or history");
 project=grabberProject(manager,str(project,"Id"));auto later=complete("https://example.test/docs/later.png","later saved.png","late","image/png");manager.saveProject(project);check(manager.convertProjectLinks(str(project,"Id"),true),"Newly completed resources can trigger link conversion again");auto second=waitForConversion();body=readText(main->target());check(str(second,"LinkConversionState")=="Complete"&&body.find("later%20saved.png")!=std::string::npos&&body.find("https://example.test/docs/next%20") ==std::string::npos,"Repeat conversion uses original source rather than treating prior local links as remote URLs");
 // A disk/catalog failure must restore the exact previous file and job metadata.
 auto mapping=std::map<std::string,fs::path>{{str(next->data,"Url"),base/L"alternate/new.html"}};auto priorData=main->data;auto priorHash=fileHash(main->target());Cancel cancel;{
  Handle lock(CreateFileW((manager.root/L"state.json").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));rejects([&]{convertGrabberFile(manager,main,project,mapping,cancel);},"A catalog-write failure rejects page conversion");
 }check(main->data==priorData&&fileHash(main->target())==priorHash,"Failed page conversion restores the prior file and catalog metadata");
 Cancel cancelled;cancelled.stop=true;rejects([&]{convertGrabberFile(manager,main,project,mapping,cancelled);},"Canceled conversion publishes no document changes");check(fileHash(main->target())==priorHash,"Canceled conversion retains the prior document hash");
 auto encoded=complete("https://example.test/utf16.html","utf16.html",std::string("\xff\xfe<\0p\0>\0",8),"text/html");auto encodedHash=fileHash(encoded->target());rejects([&]{convertGrabberFile(manager,encoded,project,mapping,cancel);},"Unsupported document encodings are reported without corrupting their bytes");check(fileHash(encoded->target())==encodedHash,"Unsupported-encoding documents remain intact");
 manager.save();writeBytes(main->target(),Bytes{'u','s','e','r'});auto edited=fileHash(main->target());rejects([&]{convertGrabberFile(manager,main,project,mapping,cancel);},"A page edited outside UDM is not overwritten during conversion");check(fileHash(main->target())==edited,"External document edits remain byte-for-byte intact");
 rejects([&]{auto invalid=project;invalid["ConvertLinks"]="yes";manager.saveProject(invalid);},"Saved link-conversion settings require an explicit boolean");
 auto templateItem=saveGrabberTemplate(manager,project,"Offline links");check(yes(templateItem["Settings"],"ConvertLinks"),"Reusable project templates retain the local-link setting");
 manager.stop();
 grabberLinkRecoveryChecks(root);
}
static int grabberLinkFeatureSpec(const fs::path& input){
 Json result;try{auto spec=Json::parse(readText(input));auto root=input.parent_path();Manager manager(root/L"state");manager.state["Settings"]["DownloadFolder"]=utf8((root/L"downloads").wstring());manager.state["Settings"]["CategoryFolders"]=false;manager.state["Settings"]["ProxyMode"]="Connect directly";manager.state["Settings"]["Retries"]=0;manager.state["Settings"]["Parallel"]=3;manager.state["Queues"][0]["Enabled"]=false;manager.save();auto project=modernGrabber(str(spec,"url"));project["FileInclude"]="*";project["ConvertLinks"]=true;project["SaveMode"]="Folder";project["Folder"]=utf8((root/L"downloads").wstring());project["OriginalSubfolders"]=true;project["Depth"]=2;Cancel scan;project=runGrabber(manager,project,scan);manager.addProject(project,"Main queue",false,true);auto end=GetTickCount64()+45000;bool done=false;
 for(;GetTickCount64()<end;){manager.tick();{Lock lock(manager.mutex);auto current=grabberProject(manager,str(project,"Id"));if(str(current,"LinkConversionState")=="Complete"){project=current;done=true;break;}for(auto job:manager.jobs)if(str(job->data,"Status")=="Failed")throw std::runtime_error(str(job->data,"Error"));if(str(current,"LinkConversionState")=="Needs attention")throw std::runtime_error(current["LinkConversionErrors"].dump());}Sleep(10);}if(!done)throw std::runtime_error("Timed out finishing the offline site.");manager.stop();Json files=Json::array();for(auto job:manager.jobs)files.push_back({{"url",str(job->data,"Url")},{"path",utf8(job->target().wstring())},{"sha256",fileHash(job->target())},{"status",str(job->data,"Status")}});result={{"project",project},{"files",files},{"queueEnabled",yes(manager.state["Queues"][0],"Enabled")}};
 }catch(const std::exception& e){result["fatal"]=e.what();}atomicText(input.parent_path()/L"result.json",result.dump(2),false);std::cout<<result.dump()<<std::endl;return result.contains("fatal")?1:0;
}
