// Included inside udm after Scheduler.
class GrabberDialog:public Form {
 Manager& manager;Json project;
 CComboBox *projects=nullptr,*preset=nullptr,*queue=nullptr,*saveCategory=nullptr;
 CWnd *name=nullptr,*address=nullptr,*extensions=nullptr,*depth=nullptr,*maximum=nullptr,*folder=nullptr,*browse=nullptr,*status=nullptr,*heading=nullptr,*later=nullptr,*back=nullptr,*next=nullptr,*add=nullptr,*scan=nullptr,*stop=nullptr,*externalAssets=nullptr,*budget=nullptr,*offlineHint=nullptr;
 CWnd *loginEnabled=nullptr,*loginUser=nullptr,*loginPassword=nullptr,*loginHint=nullptr;std::string loginOrigin;
 CWnd *byCategories=nullptr,*byCategory=nullptr,*byFolder=nullptr,*subfolders=nullptr,*categoryPath=nullptr,*destinationHint=nullptr;
 CWnd *pageSame=nullptr,*allSubdomains=nullptr,*noParents=nullptr,*externalDepth=nullptr,*fileSame=nullptr,*hideDuplicates=nullptr,*excludeFiles=nullptr,*minimumSize=nullptr,*maximumSize=nullptr,*pageInclude=nullptr,*pageExclude=nullptr,*fileIncludePaths=nullptr,*fileExcludePaths=nullptr,*pageAdvanced=nullptr,*fileAdvanced=nullptr,*resumeScan=nullptr;std::vector<CWnd*> reviewActions;
 std::vector<CWnd*> pageExtra,fileExtra,pageOptions,fileOptions,offlineFileControls;bool showPageAdvanced=false,showFileAdvanced=false;
 CWnd *downloadWhile=nullptr,*settingsButton=nullptr,*convertLinks=nullptr;std::string conversionNotice;CTreeCtrl* siteTree=nullptr;std::map<HTREEITEM,std::pair<std::string,std::string>> treeFilters;std::map<HTREEITEM,std::string> treeIds;std::string treeKey,viewMode="all",viewValue,templateKind="Files";std::vector<size_t> rowLinks;std::vector<std::string> templateIds;
 CListCtrl* links=nullptr;std::vector<std::string> projectIds;
 std::shared_ptr<Cancel> cancellation;std::future<Json> work;bool running=false,loading=false;int step=0;
 std::vector<std::vector<CWnd*>> pages;std::vector<CWnd*> explorationControls;std::mutex reportMutex;std::string reportText;
 Json blank(){return {{"Id",guid()},{"Name","New project"},{"StartUrl","https://"},{"Template","Files"},{"Extensions","zip pdf jpg png mp4 mp3"},{"FileInclude","*.zip, *.pdf, *.jpg, *.png, *.mp4, *.mp3"},{"Depth",1},{"MaxPages",20},{"Folder",""},{"SaveMode","Categories"},{"SaveCategory","Other"},{"OriginalSubfolders",false},{"Links",Json::array()}};}
 bool offline()const{return templateKind=="Offline website (ZIP)";}
 void destinationDraft(Json& value){
  value["ConvertLinks"]=convertLinks&&checked(convertLinks)&&!offline();
  value["SaveMode"]=checked(byFolder)?"Folder":checked(byCategory)?"Category":"Categories";
  value["Folder"]=trim(text(folder));value["SaveCategory"]=text(saveCategory);
  value["OriginalSubfolders"]=checked(byFolder)&&!offline()&&checked(subfolders);value["Template"]=templateKind;
 }
 void destinationControls(){
  if(!byFolder)return;const bool explicitFolder=checked(byFolder);folder->EnableWindow(explicitFolder);browse->EnableWindow(explicitFolder);saveCategory->EnableWindow(checked(byCategory));subfolders->EnableWindow(explicitFolder&&!offline());
  Json settings;{Lock lock(manager.mutex);settings=manager.state["Settings"];}
  categoryPath->SetWindowText(cs("Category folder: "+categoryFolder(settings,text(saveCategory))));
  destinationHint->SetWindowText(offline()?L"The website is saved as one ZIP archive. Choose its category or folder here.":L"Original subfolders preserve the website's URL path inside your chosen folder. Existing files receive a numbered name.");
 }
 void preview(){renderResults();}
 void page(){
  static const char* titles[]={"1. Name and starting page","2. Save to","3. Explorer filters","4. File filters","5. Explore, review and download"};
  heading->SetWindowText(cs(step==4&&offline()?"5. Save an offline website":titles[step]));for(int i=0;i<5;++i)for(auto w:pages[i])w->ShowWindow(i==step?SW_SHOW:SW_HIDE);
  back->EnableWindow(step>0&&!running);next->ShowWindow(step<4?SW_SHOW:SW_HIDE);next->EnableWindow(!running);add->ShowWindow(step==4?SW_SHOW:SW_HIDE);add->EnableWindow(!running&&(offline()||links->GetItemCount()>0));add->SetWindowText(offline()?L"Add website":L"Add selected");
  externalAssets->EnableWindow(offline());budget->EnableWindow(offline());extensions->EnableWindow(!offline());scan->EnableWindow(!running);stop->EnableWindow(running);projects->EnableWindow(!running);links->EnableWindow(TRUE);for(auto w:reviewActions)w->EnableWindow(TRUE);queue->EnableWindow(!running);downloadWhile->EnableWindow(!offline());convertLinks->EnableWindow(!offline());settingsButton->EnableWindow(!running&&!offline());destinationControls();
  for(auto w:pageOptions)w->EnableWindow(!offline());for(auto w:fileOptions)w->EnableWindow(!offline());
  for(auto w:pageExtra)w->ShowWindow(step==2&&showPageAdvanced&&!offline()?SW_SHOW:SW_HIDE);
  for(auto w:fileExtra)w->ShowWindow(step==3&&showFileAdvanced&&!offline()?SW_SHOW:SW_HIDE);for(auto w:offlineFileControls)w->ShowWindow(step==3&&offline()?SW_SHOW:SW_HIDE);
  pageAdvanced->SetWindowText(showPageAdvanced?L"Advanced <<":L"Advanced >>");fileAdvanced->SetWindowText(showFileAdvanced?L"Advanced <<":L"Advanced >>");
  externalDepth->EnableWindow(!offline()&&!checked(pageSame));hideDuplicates->EnableWindow(!offline()&&!(checked(byFolder)&&checked(subfolders)));
  if(checked(byFolder)&&checked(subfolders))hideDuplicates->SendMessage(BM_SETCHECK,BST_UNCHECKED);
  const auto saved=project.value("ExploreState",Json::object());resumeScan->EnableWindow(!running&&saved.contains("Pending")&&saved["Pending"].is_array()&&!saved["Pending"].empty()&&str(project,"ExplorationLimit")!="files"&&str(project,"ExplorationLimit")!="candidates");
  if(step==4){for(auto w:explorationControls)w->ShowWindow(offline()?SW_HIDE:SW_SHOW);offlineHint->ShowWindow(offline()?SW_SHOW:SW_HIDE);preview();}
 }
 void fillProjects(){projects->ResetContent();projectIds.clear();Lock lock(manager.mutex);for(const auto& p:manager.state["Projects"]){int row=projects->AddString(cs(str(p,"Name")));projectIds.push_back(str(p,"Id"));if(str(p,"Id")==str(project,"Id"))projects->SetCurSel(row);}}
 void load(){
  Json credentials=Json::object();bool reenter=false;try{credentials=grabberLogin(project);}catch(const std::exception&){reenter=true;}loginOrigin=str(credentials,"Origin");bool enabled=reenter||!credentials.empty();loginEnabled->SendMessage(BM_SETCHECK,enabled?BST_CHECKED:BST_UNCHECKED);loginUser->SetWindowText(cs(str(credentials,"UserName")));loginPassword->SetWindowText(cs(str(credentials,"Password")));loginUser->EnableWindow(enabled);loginPassword->EnableWindow(enabled);loginHint->SetWindowText(reenter?L"Saved login is unavailable. Re-enter it, or uncheck the login option.":L"HTTP login for this website. Use Advanced for browser sign-in.");
  loading=true;templateKind=str(project,"Template","Files");fillTemplates();name->SetWindowText(cs(str(project,"Name")));address->SetWindowText(cs(str(project,"StartUrl")));extensions->SetWindowText(cs(str(project,"FileInclude",grabberLegacyPatterns(project))));folder->SetWindowText(cs(str(project,"Folder")));depth->SetWindowText(cs(std::to_string(num(project,"Depth",1))));maximum->SetWindowText(cs(std::to_string(num(project,"MaxPages",20))));
  const auto mode=grabberSaveMode(project);byCategories->SendMessage(BM_SETCHECK,mode=="Categories"?BST_CHECKED:BST_UNCHECKED);byCategory->SendMessage(BM_SETCHECK,mode=="Category"?BST_CHECKED:BST_UNCHECKED);byFolder->SendMessage(BM_SETCHECK,mode=="Folder"?BST_CHECKED:BST_UNCHECKED);
  saveCategory->ResetContent();{Lock lock(manager.mutex);for(const auto& c:manager.categories())saveCategory->AddString(cs(c));}saveCategory->SetCurSel(saveCategory->FindStringExact(-1,cs(str(project,"SaveCategory","Other"))));subfolders->SendMessage(BM_SETCHECK,yes(project,"OriginalSubfolders")?BST_CHECKED:BST_UNCHECKED);
  externalAssets->SendMessage(BM_SETCHECK,yes(project,"ExternalAssets")?BST_CHECKED:BST_UNCHECKED);budget->SetWindowText(cs(std::to_string(num(project,"MaxMiB",256))));
  excludeFiles->SetWindowText(cs(str(project,"FileExclude")));pageInclude->SetWindowText(cs(str(project,"PageIncludePaths")));pageExclude->SetWindowText(cs(str(project,"PageExcludePaths")));fileIncludePaths->SetWindowText(cs(str(project,"FileIncludePaths")));fileExcludePaths->SetWindowText(cs(str(project,"FileExcludePaths")));
  minimumSize->SetWindowText(cs(std::to_string(num(project,"MinFileBytes"))));maximumSize->SetWindowText(cs(std::to_string(num(project,"MaxFileBytes"))));externalDepth->SetWindowText(cs(std::to_string(num(project,"ExternalDepth"))));
  pageSame->SendMessage(BM_SETCHECK,yes(project,"ExploreSameSite",true)?BST_CHECKED:BST_UNCHECKED);fileSame->SendMessage(BM_SETCHECK,yes(project,"FilesSameSite",true)?BST_CHECKED:BST_UNCHECKED);allSubdomains->SendMessage(BM_SETCHECK,yes(project,"ExploreSubdomains")?BST_CHECKED:BST_UNCHECKED);noParents->SendMessage(BM_SETCHECK,yes(project,"NoParentDirectories")?BST_CHECKED:BST_UNCHECKED);hideDuplicates->SendMessage(BM_SETCHECK,yes(project,"HideDuplicates")?BST_CHECKED:BST_UNCHECKED);
  convertLinks->SendMessage(BM_SETCHECK,yes(project,"ConvertLinks")?BST_CHECKED:BST_UNCHECKED);downloadWhile->SendMessage(BM_SETCHECK,yes(project,"DownloadWhileExploring")?BST_CHECKED:BST_UNCHECKED);int queueIndex=queue->FindStringExact(-1,cs(str(project,"DownloadQueue","Main queue")));if(queueIndex>=0)queue->SetCurSel(queueIndex);loading=false;waitingBrowserTicket=str(project.value("PendingBrowserLogin",Json::object()),"Token");browserLoginControls();renderResults();page();
 }
 static i64 whole(CWnd* control){auto value=trim(text(control));if(value.empty()||value.find_first_not_of("0123456789")!=std::string::npos)throw std::runtime_error("Enter a non-negative whole number for each limit.");return std::stoll(value);}
 void collect(){syncBrowserSignIn();project["DownloadWhileExploring"]=checked(downloadWhile)&&!offline();project["DownloadQueue"]=text(queue);project["Name"]=trim(text(name));project["StartUrl"]=trim(text(address));if(checked(loginEnabled)){if(!loginOrigin.empty()&&Url(str(project,"StartUrl")).origin!=loginOrigin)throw std::runtime_error("The starting website changed. Uncheck the login option, then enter credentials for the new website.");setGrabberLogin(project,text(loginUser),text(loginPassword));loginOrigin=Url(str(project,"StartUrl")).origin;}else setGrabberLogin(project,"","",false);project["FileInclude"]=trim(text(extensions));project["FileExclude"]=trim(text(excludeFiles));project["PageIncludePaths"]=trim(text(pageInclude));project["PageExcludePaths"]=trim(text(pageExclude));project["FileIncludePaths"]=trim(text(fileIncludePaths));project["FileExcludePaths"]=trim(text(fileExcludePaths));
  project["ExploreSameSite"]=checked(pageSame);project["FilesSameSite"]=checked(fileSame);project["ExploreSubdomains"]=checked(allSubdomains);project["NoParentDirectories"]=checked(noParents);project["HideDuplicates"]=checked(hideDuplicates)&&!(checked(byFolder)&&checked(subfolders));project["ExternalDepth"]=whole(externalDepth);project["MinFileBytes"]=whole(minimumSize);project["MaxFileBytes"]=whole(maximumSize);project["Depth"]=whole(depth);project["MaxPages"]=whole(maximum);destinationDraft(project);project["ExternalAssets"]=checked(externalAssets);project["MaxMiB"]=whole(budget);for(size_t i=0;i<rowLinks.size();++i)project["Links"][rowLinks[i]]["Selected"]=links->GetCheck((int)i)!=FALSE;}
 void fileProperties(){
  size_t index=selectedFile();
  auto link=project["Links"][index];auto job=grabberJob(manager,str(project,"Id"),str(link,"Url"));bool added=bool(job);if(job){Lock lock(manager.mutex);link["Description"]=str(job->data,"Description");}Form dialog("Collected file properties",670,449,this);dialog.init=[&]{
   dialog.label("File name",14,18,110);auto filename=dialog.edit(grabberCollectedName(project,link),132,14,524,23,added);
   dialog.label("File size",14,57,110);dialog.label(num(link,"Size",-1)<0?"Unknown":bytes(num(link,"Size"))+" ("+std::to_string(num(link,"Size"))+" bytes)",132,57,524);
   dialog.label("Content type",14,94,110);dialog.edit(str(link,"ContentType"),132,90,524,23,true);
   dialog.label("Download address",14,132,200);dialog.edit(str(link,"Url"),14,154,642,48,true,true);
   dialog.label("Referring page",14,218,200);dialog.edit(str(link,"Referrer"),14,240,642,48,true,true);
   dialog.label("Description",14,307,200);dialog.edit(str(link,"Description"),14,329,642,48,true,true);
   if(!added)dialog.button("Save name",431,406,106,[&,filename]{renameGrabberFile(manager,str(project,"Id"),str(link,"Url"),trim(text(filename)));project=grabberProject(manager,str(project,"Id"));renderResults();dialog.close();});dialog.button("Close",550,406,106,[&]{dialog.close();});};dialog.DoModal();
 }
 void exploreNow(bool resume=false){
  if(running)return;collect();if(yes(project,"BrowserLogin")&&(str(project,"ProtectedBrowserSession").empty()||project.contains("PendingBrowserLogin"))){browserSignIn(true,resume);return;}if(!resume)project.erase("ExploreState");manager.saveProject(project);fillProjects();cancellation=std::make_shared<Cancel>();auto input=project;auto token=cancellation;running=true;page();status->SetWindowText(L"Connecting to the starting page...");
  work=std::async(std::launch::async,[this,input,token]{return runGrabber(manager,input,*token,[this](std::string message){std::lock_guard<std::mutex> lock(reportMutex);reportText=std::move(message);});});
 }
 void convertLinksNow(){if(running)return;convertLinks->SendMessage(BM_SETCHECK,BST_CHECKED);collect();manager.saveProject(project);bool started=manager.convertProjectLinks(str(project,"Id"),true);status->SetWindowText(started?L"Converting downloaded HTML and CSS links...":L"Finish or stop the project downloads before converting its completed HTML/CSS files.");}
 void poll(){
  if(syncBrowserSignIn()){page();if(exploreAfterLogin){exploreAfterLogin=false;exploreNow(resumeAfterLogin);return;}}
  if(!running){if(step==4&&!offline()){renderResults();try{auto saved=grabberProject(manager,str(project,"Id"));auto note=str(saved,"LinkConversionState")+"|"+str(saved,"LinkConversionFinished");if(note!=conversionNotice&&!str(saved,"LinkConversionState").empty()){conversionNotice=note;std::string message="Link conversion: "+str(saved,"LinkConversionState");if(str(saved,"LinkConversionState")!="Converting")message+="; "+std::to_string(num(saved,"LinkConversionChanged"))+" files updated.";auto errors=saved.value("LinkConversionErrors",Json::array());if(!errors.empty())message+=" "+str(errors[0],"Message");status->SetWindowText(cs(message));}for(const char* key:{"LinkConversionState","LinkConversionSignature","LinkConversionFinished","LinkConversionErrors","LinkConversionChanged"})if(saved.contains(key))project[key]=saved[key];}catch(...) {}}return;}try{project=grabberProject(manager,str(project,"Id"));renderResults();}catch(...){}std::string message;{std::lock_guard<std::mutex> lock(reportMutex);message=std::move(reportText);reportText.clear();}if(!message.empty())status->SetWindowText(cs(message));
  if(work.wait_for(std::chrono::milliseconds(0))==std::future_status::ready){running=false;try{work.get();project=grabberProject(manager,str(project,"Id"));load();std::string outcome=yes(project,"ExplorationStopped")?"Stopped; results retained. ":yes(project,"ExplorationLimited")?"Limit reached. ":"Exploration complete. ";outcome+=std::to_string(project["Links"].size())+" files; "+std::to_string(num(project,"PagesVisited"))+" pages; "+std::to_string(num(project,"HiddenDuplicates"))+" duplicates hidden; "+std::to_string(project.value("Errors",Json::array()).size())+" errors.";if(str(project,"ExplorationLimit")=="pages")outcome+=" Raise the page limit to resume.";if(str(project,"ExplorationLimit")=="files"||str(project,"ExplorationLimit")=="candidates")outcome+=" Narrow filters and explore again (2,000 files / 10,000 addresses).";status->SetWindowText(cs(outcome));}catch(const std::exception& e){status->SetWindowText(cs(e.what()));}page();}
 }
 BOOL OnCommand(WPARAM w,LPARAM l)override{
  if(projects&&LOWORD(w)==projects->GetDlgCtrlID()&&HIWORD(w)==CBN_SELCHANGE&&!running){int index=projects->GetCurSel();if(index>=0&&index<(int)projectIds.size()){Lock lock(manager.mutex);for(const auto& p:manager.state["Projects"])if(str(p,"Id")==projectIds[index]){project=p;load();break;}}return TRUE;}
  if(preset&&LOWORD(w)==preset->GetDlgCtrlID()&&HIWORD(w)==CBN_SELCHANGE&&!loading){try{applyTemplateChoice(preset->GetCurSel());}catch(const std::exception& e){error(this,e);}return TRUE;}return Form::OnCommand(w,l);
 }
 void OnCancel()override{if(running){cancellation->stop=true;status->SetWindowText(L"Stopping exploration...");return;}Form::OnCancel();}
 #include "GrabberResultUi.hpp"
 #include "GrabberLoginUi.hpp"
 void recordPage(size_t start){std::vector<CWnd*> members;for(size_t i=start;i<controls.size();++i)members.push_back(controls[i].get());pages.push_back(std::move(members));}
public:
 GrabberDialog(Manager& m,CWnd* owner):Form("Site Grabber",736,560,owner),manager(m){project=blank();init=[this]{
  label("Saved project",14,15,103);projects=combo({},"",124,11,468);button("New",604,11,117,[this]{if(running)return;project=blank();step=0;projects->SetCurSel(-1);load();});heading=label("",14,53,707,25);control(L"STATIC","",SS_ETCHEDHORZ,14,83,707,2);
  size_t start=controls.size();label("Project name",24,112,139);name=edit("",176,108,535);label("Starting web page",24,154,139);address=edit("",176,150,535);label("Template",24,196,139);preset=combo({},"",176,192,400);button("Templates...",588,191,123,[this]{templatesDialog();});
  button("Advanced...",587,233,124,[this]{advancedLogin();});loginEnabled=check("This website requires a user name and password",false,24,237,548);bind(loginEnabled,[this]{bool enabled=checked(loginEnabled);loginUser->EnableWindow(enabled);loginPassword->EnableWindow(enabled);if(!enabled){loginUser->SetWindowText(L"");loginPassword->SetWindowText(L"");loginOrigin.clear();project.erase("ProtectedLogin");loginHint->SetWindowText(L"HTTP login for this website. Use Advanced for browser sign-in.");}});
  label("User name",24,283,139);loginUser=edit("",176,279,535);label("Password",24,323,139);loginPassword=edit("",176,319,535,23,false,false,true);loginHint=label("",24,347,687,19);
  label("Choose Complete website to download pages and resources with local links. Choose a folder on the next page to keep the saved site together.",24,369,687,43);label("Offline website (ZIP) creates a separate static archive. Extract it and open index.html. Scripts and forms are disabled only in that archive mode.",24,420,687,45);recordPage(start);
  start=controls.size();byCategories=check("Save each file to its category folder",true,24,104,687,24);byCategory=check("Save all files to this category",false,24,155,687,24);byFolder=check("Save all files to this folder",false,24,275,687,24);saveCategory=combo({},"",45,189,666);categoryPath=label("",45,222,666,38);
  folder=edit("",45,309,549);browse=button("Browse...",604,308,107,[this]{auto value=chooseFolder(this,wide(text(folder)));if(!value.empty())folder->SetWindowText(value.c_str());});subfolders=check("Use original website subfolders",false,45,344,666,24);destinationHint=label("",24,386,687,36);convertLinks=check("Convert links to local files for offline browsing",false,24,432,687,24);label("After downloads finish or stop, saved pages link to downloaded files. Other links keep their website addresses.",45,459,666,25);
  for(auto radio:{byCategories,byCategory,byFolder}){radio->ModifyStyle(BS_TYPEMASK,BS_AUTORADIOBUTTON);bind(radio,[this,radio]{for(auto item:{byCategories,byCategory,byFolder})item->SendMessage(BM_SETCHECK,item==radio?BST_CHECKED:BST_UNCHECKED);destinationControls();});}
  byCategories->ModifyStyle(0,WS_GROUP);saveCategory->ModifyStyle(0,WS_GROUP);folder->ModifyStyle(0,WS_GROUP);bindChange(saveCategory,[this]{if(!loading)destinationControls();});recordPage(start);
  start=controls.size();pageSame=check("Explore pages on the starting website only",true,24,104,687);allSubdomains=check("Include other subdomains of the same main domain",false,24,136,687);noParents=check("Do not explore parent or sibling directories",false,24,168,687);
  label("Website depth (0-20)",24,210,174);depth=edit("1",204,206,66);label("External depth (0-20)",345,210,177);externalDepth=edit("0",540,206,66);label("Page limit (1-10,000)",24,248,174);maximum=edit("20",204,244,100);
  pageAdvanced=button("Advanced >>",556,242,155,[this]{showPageAdvanced=!showPageAdvanced;page();});pageOptions={pageSame,allSubdomains,noParents,externalDepth,pageAdvanced};bind(pageSame,[this]{page();});
  size_t extra=controls.size();label("Include page paths",24,295,152);pageInclude=edit("",184,291,527);label("Exclude page paths",24,337,152);pageExclude=edit("",184,333,527);label("Separate patterns with commas, for example /manuals/*, *.example.org/docs/*. Exclusions take priority. The starting page may be outside an include pattern.",24,377,687,49);for(size_t i=extra;i<controls.size();++i)pageExtra.push_back(controls[i].get());
  label("These rules control which pages are explored. File downloads have separate rules on the next page. Offline ZIP uses depth 0-5 and 1-100 pages; advanced page filters apply to file collection.",24,443,687,43);recordPage(start);
  start=controls.size();label("Include files",24,109,139);extensions=edit("",176,105,535);label("Exclude files",24,149,139);excludeFiles=edit("",176,145,535);label("Use comma-separated patterns such as *.jpg, image*.png or <start page>. Leave Include empty to match all files.",24,180,687,34);
  fileSame=check("Download files from the starting website only",true,24,217,687);hideDuplicates=check("Hide duplicates with the same name and size (unavailable with original subfolders)",false,24,249,687);fileAdvanced=button("Advanced >>",556,280,155,[this]{showFileAdvanced=!showFileAdvanced;page();});fileOptions={extensions,excludeFiles,fileSame,hideDuplicates,fileAdvanced};
  extra=controls.size();label("Include file paths",24,321,147);fileIncludePaths=edit("",176,317,535);label("Exclude file paths",24,361,147);fileExcludePaths=edit("",176,357,535);label("Minimum bytes",24,405,125);minimumSize=edit("0",150,401,177);label("Maximum bytes",350,405,128);maximumSize=edit("0",487,401,224);label("Zero disables a size limit. Unknown sizes cannot match an enabled size limit.",24,438,687,25);for(size_t i=extra;i<controls.size();++i)fileExtra.push_back(controls[i].get());
  externalAssets=check("Offline ZIP: include assets from other hosts (image/font CDNs)",false,24,321,687);label("Offline budget (MiB)",24,367,165);budget=edit("256",198,363,85);auto offlineBudgetLabel=controls[controls.size()-2].get();auto offlineLimits=label("Up to 2,000 resources; 32 MiB per asset. File filters apply to collected files, not offline ZIP archives.",24,409,687,46);recordPage(start);
  // Offline-only controls occupy the advanced-filter area.
  offlineFileControls={externalAssets,offlineBudgetLabel,budget,offlineLimits};
  start=controls.size();scan=button("Explore",14,98,90,[this]{exploreNow();});resumeScan=button("Resume",112,98,90,[this]{exploreNow(true);});stop=button("Stop",210,98,73,[this]{if(cancellation)cancellation->stop=true;});auto checkAll=button("Check all",291,98,98,[this]{checkRows(true);});auto uncheckAll=button("Uncheck all",397,98,108,[this]{checkRows(false);});
  auto properties=button("Properties...",513,98,101,[this]{fileProperties();});reviewActions={checkAll,uncheckAll,properties};
  button("Errors...",622,98,100,[this]{std::string details;for(const auto& e:project.value("Errors",Json::array()))details+=str(e,"Url")+"\r\n"+str(e,"Message")+"\r\n\r\n";if(details.empty())details="No exploration errors recorded.";Form log("Exploration log",630,346,this);log.init=[&]{log.edit(details,13,13,604,280,true,true);log.button("Close",516,307,100,[&]{log.close();});};log.DoModal();});
  button("Start checked",14,129,119,[this]{startChecked();});button("Stop checked",143,129,112,[this]{stopChecked();});button("Statistics...",265,129,105,[this]{statistics();});button("Open file",380,129,101,[this]{openResult(false);});button("Open folder",491,129,109,[this]{openResult(true);});button("Convert links",610,129,112,[this]{convertLinksNow();});
  siteTree=make<CTreeCtrl>(WS_TABSTOP|WS_BORDER|TVS_HASLINES|TVS_HASBUTTONS|TVS_LINESATROOT|TVS_SHOWSELALWAYS,14,164,176,247);
  links=make<CListCtrl>(WS_TABSTOP|WS_BORDER|LVS_REPORT|LVS_SHOWSELALWAYS,198,164,524,247);links->SetExtendedStyle(LVS_EX_CHECKBOXES|LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);links->InsertColumn(0,L"File name",LVCFMT_LEFT,rect(0,0,145,0).Width());links->InsertColumn(1,L"Destination folder",LVCFMT_LEFT,rect(0,0,290,0).Width());links->InsertColumn(2,L"Address",LVCFMT_LEFT,rect(0,0,380,0).Width());links->InsertColumn(3,L"Status",LVCFMT_LEFT,rect(0,0,110,0).Width());links->InsertColumn(4,L"Size",LVCFMT_RIGHT,rect(0,0,80,0).Width());links->InsertColumn(5,L"Content type",LVCFMT_LEFT,rect(0,0,170,0).Width());links->InsertColumn(6,L"Referring page",LVCFMT_LEFT,rect(0,0,300,0).Width());links->InsertColumn(7,L"Received",LVCFMT_RIGHT,rect(0,0,85,0).Width());links->InsertColumn(8,L"Rate",LVCFMT_RIGHT,rect(0,0,85,0).Width());links->InsertColumn(9,L"Description",LVCFMT_LEFT,rect(0,0,240,0).Width());int order[]={0,4,3,7,8,1,2,5,6,9};links->SetColumnOrderArray(10,order);downloadWhile=check("Download matched files while exploring",false,14,419,566);settingsButton=button("Settings...",604,417,117,[this]{grabberSettings();});bind(downloadWhile,[this]{if(running){Lock lock(manager.mutex);auto saved=grabberProject(manager,str(project,"Id"));saved["DownloadWhileExploring"]=checked(downloadWhile);manager.saveProject(saved);}});for(size_t i=start;i<controls.size();++i)explorationControls.push_back(controls[i].get());
  offlineHint=label("Add this website to the selected queue. UDM will save pages within your depth and page limits, plus their styles, images, fonts and media.\r\n\r\nThe result is one ZIP archive. Extract it, then open index.html. Scripts and form submissions are disabled. Missing or oversized resources are listed in the archive report.\r\n\r\nYou can pause and resume the job from the main window. Uncheck Download later to start when the queue is enabled.",24,122,687,239);label("Queue",14,447,55);queue=combo(queueNames(manager),"Main queue",77,443,346);later=check("Download later",true,446,445,276);recordPage(start);
  status=label("Create a project or choose a saved project.",14,490,708,35);back=button("< Back",279,530,95,[this]{if(step>0){--step;page();}});next=button("Next >",384,530,95,[this]{collect();Url url(str(project,"StartUrl"));if(trim(str(project,"Name")).empty())throw std::runtime_error("Enter a project name.");if(step>=1){manager.saveProject(project);fillProjects();}step=std::min(4,step+1);page();if(step==4&&yes(project,"BrowserLogin")&&str(project,"ProtectedBrowserSession").empty())browserSignIn();});
  add=button("Add selected",384,530,117,[this]{collect();int count=manager.addProject(project,text(queue),checked(later));{Lock lock(manager.mutex);for(const auto& saved:manager.state["Projects"])if(str(saved,"Id")==str(project,"Id")){project=saved;break;}}preview();status->SetWindowText(cs("Added "+std::to_string(count)+(offline()?" website archive":" files")+(checked(later)?", paused.":" to the queue.")));fillProjects();});
  button("Templates...",156,530,111,[this]{templatesDialog();});button("Save project",14,530,132,[this]{if(running)return;collect();manager.saveProject(project);fillProjects();status->SetWindowText(L"Project saved.");});button("Close",615,530,107,[this]{OnCancel();});pulse=[this]{poll();};fillProjects();load();
 };}
 ~GrabberDialog(){if(cancellation)cancellation->stop=true;if(work.valid())work.wait();}
};
