#pragma once
#include "GrabberDestinations.hpp"
#include <winioctl.h>
static Json grabberTestProject(const std::string& origin){return {{"Id",guid()},{"Name","Grabber fixture"},{"StartUrl",origin+"/index.html"},{"Depth",1},{"MaxPages",5},{"Links",Json::array()}};}
static void grabberJunction(const fs::path& path,const fs::path& target){
 fs::create_directories(path);std::wstring substitute=L"\\??\\"+target.wstring(),display=target.wstring();std::vector<unsigned char> data(16+(substitute.size()+display.size()+2)*sizeof(wchar_t));
 auto put16=[&](size_t at,USHORT value){memcpy(data.data()+at,&value,sizeof(value));};DWORD tag=IO_REPARSE_TAG_MOUNT_POINT;memcpy(data.data(),&tag,sizeof(tag));put16(4,(USHORT)(data.size()-8));put16(8,0);put16(10,(USHORT)(substitute.size()*2));put16(12,(USHORT)((substitute.size()+1)*2));put16(14,(USHORT)(display.size()*2));memcpy(data.data()+16,substitute.c_str(),(substitute.size()+1)*2);memcpy(data.data()+16+(substitute.size()+1)*2,display.c_str(),(display.size()+1)*2);
 Handle handle(CreateFileW(path.c_str(),GENERIC_WRITE,0,nullptr,OPEN_EXISTING,FILE_FLAG_OPEN_REPARSE_POINT|FILE_FLAG_BACKUP_SEMANTICS,nullptr));DWORD written=0;if(!handle||!DeviceIoControl(handle.h,FSCTL_SET_REPARSE_POINT,data.data(),(DWORD)data.size(),nullptr,0,&written,nullptr))throw std::runtime_error("Cannot create the isolated junction fixture.");
}
static void grabberChecks(const fs::path& root,Fixture& fixture){
 auto base=root/L"grabber";fs::create_directories(base);Manager manager(base/L"state");auto& settings=manager.state["Settings"];settings["DownloadFolder"]=utf8((base/L"downloads").wstring());settings["ProxyMode"]="Connect directly";settings["Retries"]=0;
 auto project=grabberTestProject("https://example.test");check(grabberSaveMode(project)=="Categories","Legacy Grabber projects with no folder use automatic categories");project["Folder"]=utf8((base/L"fixed").wstring());check(grabberSaveMode(project)=="Folder","Legacy Grabber projects retain explicit destinations");
 project["SaveMode"]="Categories";auto dest=grabberDestination(project,settings,"https://example.test/books/book.pdf");check(dest.category=="Documents"&&fs::path(wide(dest.folder))==base/L"downloads/Documents","Automatic Grabber destination uses the file category");
 settings["CustomCategories"].push_back("Books");settings["CategoryRules"].push_back({{"Category","Books"},{"Extensions","pdf"},{"Hosts","example.test"}});settings["CategoryPaths"]=legacyDictionary(Json{{"Books",utf8((base/L"library").wstring())}});
 dest=grabberDestination(project,settings,"https://example.test/books/book.pdf");check(dest.category=="Books"&&fs::path(wide(dest.folder))==base/L"library","Grabber preview honors host rules and custom category paths");
 project["Links"]=Json::array({{{"Url","https://example.test/books/book.pdf"}},{{"Url","https://example.test/data/a.zip"},{"Selected",false}}});check(manager.addProject(project,"Main queue",true)==1,"Only checked Grabber files are added");auto automatic=manager.jobs.back();check(str(automatic->data,"Category")==dest.category&&str(automatic->data,"Folder")==dest.folder,"Grabber preview matches automatic download placement");
 project["Id"]=guid();project["SaveMode"]="Category";project["SaveCategory"]="Books";project["Links"][0]["Url"]="https://example.test/a.mp4";manager.addProject(project,"Main queue",true);check(str(manager.jobs.back()->data,"Category")=="Books"&&manager.jobs.back()->target().parent_path()==base/L"library","One selected category overrides file extension routing");
 auto hierarchy=grabberTestProject(fixture.url(""));hierarchy["SaveMode"]="Folder";hierarchy["Folder"]=utf8((base/L"website").wstring());hierarchy["OriginalSubfolders"]=true;
 auto htmlSettings=settings;htmlSettings["CategoryTypeOverrides"]["Documents"]="pdf html";auto index=grabberDestination(hierarchy,htmlSettings,fixture.url("/docs/"));check(index.name=="index.html"&&index.category=="Documents","Generated index.html uses its final filename for category routing");
 for(auto path:{"/manuals/one/file.pdf","/manuals/two/file.pdf","/manuals/two/file.pdf?version=2","/pictures/a%20b.png","/pictures/%E6%97%A5%E6%9C%AC.png","/slow"})hierarchy["Links"].push_back({{"Url",fixture.url(path)}});
 manager.save();auto before=readText(manager.root/L"state.json");auto count=manager.jobs.size();check(manager.addProject(hierarchy,"Main queue",true)==6,"A hierarchical project adds the whole selected batch");check(readText(manager.root/L"state.json.bak")==before,"A project batch writes history once, with its original checkpoint as backup");
 auto first=manager.jobs[count],second=manager.jobs[count+1],third=manager.jobs[count+2];check(first->target()==base/L"website/manuals/one/file.pdf"&&second->target()==base/L"website/manuals/two/file.pdf","Same base name in different website folders stays unchanged");check(third->target()==base/L"website/manuals/two/file (1).pdf","Query variants in one folder receive distinct non-overwriting names");
 check(manager.jobs[count+3]->target()==base/L"website/pictures/a b.png"&&manager.jobs[count+4]->target()==base/L"website/pictures/日本.png","Percent-encoded spaces and Unicode folder names are decoded correctly");
 check(grabberRelativeFile("https://example.test/docs/")==fs::path(L"docs/index.html")&&grabberRelativeFile("https://example.test/?a=1")==fs::path(L"index.html"),"Folder URLs map to local index.html without query text");
 check(grabberRelativeFile("https://example.test/CON/NUL.txt")==fs::path(L"_CON/_NUL.txt"),"Reserved Windows names cannot become device paths");
 for(auto path:{"/../escape.bin","/%2e%2e/escape.bin","/a/%2fescape.bin","/a/%5cescape.bin","/a/%00evil.bin","/a/./b.bin"})rejects([&]{grabberRelativeFile(std::string("https://example.test")+path);},"Unsafe website path is rejected before queueing");
 check(manager.addProject(hierarchy,"Main queue",true)==0,"Repeated project addition reuses existing records");auto saved=manager.state["Projects"].back();check(str(saved["Links"][0],"DownloadId")==first->id(),"Saved project links point to their actual download record");
 hierarchy["Folder"]=utf8((base/L"later-choice").wstring());check(manager.addProject(hierarchy,"Main queue",true)==0&&first->target()==base/L"website/manuals/one/file.pdf","Changing a saved project does not relocate already-added files");
 auto bad=hierarchy;bad["Id"]=guid();bad["SaveCategory"]="Deleted category";bad["SaveMode"]="Category";bad["OriginalSubfolders"]=false;rejects([&]{manager.addProject(bad,"Main queue",true);},"Deleted categories are rejected instead of silently redirected");
 bad=hierarchy;bad["Folder"]="relative";rejects([&]{manager.saveProject(bad);},"Relative project roots are rejected");bad=hierarchy;bad["OriginalSubfolders"]="yes";rejects([&]{manager.saveProject(bad);},"Malformed hierarchy preferences are rejected");
 auto originalState=manager.snapshot();auto originalDisk=readText(manager.root/L"state.json");auto failedProject=hierarchy;failedProject["Id"]=guid();failedProject["Name"]="Failed replacement";
 {Handle held(CreateFileW((manager.root/L"state.json").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));check((bool)held,"Fixture locks the history file against replacement");rejects([&]{manager.addProject(failedProject,"Main queue",false);},"Locked history rejects the complete batch");check(manager.snapshot()==originalState&&readText(manager.root/L"state.json")==originalDisk,"Failed batch preserves all prior jobs, projects and saved history");}
 check(manager.addProject(failedProject,"Main queue",true)==6&&manager.storageError.empty(),"A batch can be retried after storage recovers");
 auto conflict=grabberTestProject(fixture.url(""));conflict["SaveMode"]="Folder";conflict["Folder"]=utf8((base/L"conflicts").wstring());conflict["OriginalSubfolders"]=true;conflict["Links"]=Json::array({{{"Url",fixture.url("/safe.bin")}},{{"Url",fixture.url("/directory/file.bin")}}});fs::create_directories(base/L"conflicts");writeBytes(base/L"conflicts/directory",Bytes{'k','e','e','p'});
 originalState=manager.snapshot();originalDisk=readText(manager.root/L"state.json");rejects([&]{manager.addProject(conflict,"Main queue",true);},"A later invalid destination rolls back earlier staged files");check(manager.snapshot()==originalState&&readText(manager.root/L"state.json")==originalDisk&&readText(base/L"conflicts/directory")=="keep","Mid-batch failure creates no partial records and preserves existing files");
 conflict["Folder"]=utf8((base/L"planned-conflict").wstring());conflict["Links"]=Json::array({{{"Url",fixture.url("/a")}},{{"Url",fixture.url("/a/file.bin")}}});rejects([&]{manager.addProject(conflict,"Main queue",true);},"A future file cannot occupy another selected file's folder");std::reverse(conflict["Links"].begin(),conflict["Links"].end());rejects([&]{manager.addProject(conflict,"Main queue",true);},"Folder-file conflicts are detected in either selection order");
 auto outside=base/L"outside";fs::create_directories(outside);auto redirected=base/L"redirected";fs::create_directories(redirected);grabberJunction(redirected/L"assets",outside);conflict["Folder"]=utf8(redirected.wstring());conflict["Links"]=Json::array({{{"Url",fixture.url("/assets/file.bin")}}});rejects([&]{manager.addProject(conflict,"Main queue",true);},"Existing website subfolder junctions cannot redirect project writes");check(fs::is_empty(outside),"Rejected junction destinations leave outside files untouched");fs::remove(redirected/L"assets");
 for(size_t i=count;i<count+5;++i)transfer(manager,manager.jobs[i],std::make_shared<Cancel>());check(readText(first->target())==fixture.payload&&readText(third->target())==fixture.payload&&readText(manager.jobs[count+4]->target())==fixture.payload,"Real parallel HTTP downloads publish exact bytes to nested and Unicode folders");
 auto slow=manager.jobs[count+5];auto cancel=std::make_shared<Cancel>();auto future=std::async(std::launch::async,[&]{try{transfer(manager,slow,cancel);}catch(const Cancelled&){};});bool sawBytes=false;for(int i=0;i<300;++i){Sleep(5);Lock lock(manager.mutex);if(num(slow->data,"Received")>65536){sawBytes=true;break;}}cancel->stop=true;future.get();check(sawBytes&&!fs::exists(slow->target()),"Hierarchical transfer pauses with retained parts and no final file");slow->data["Status"]="Paused";manager.save();
 {Manager reopened(manager.root);JobPtr resumed;for(auto j:reopened.jobs)if(j->id()==slow->id())resumed=j;check(resumed&&str(resumed->data,"ProjectDestinationRoot")==str(slow->data,"ProjectDestinationRoot"),"Destination constraints survive a process restart");transfer(reopened,resumed,std::make_shared<Cancel>());check(readText(resumed->target())==fixture.payload,"Restarted hierarchical download resumes to byte-identical output");slow->data=resumed->data;}
 auto changed=grabberTestProject(fixture.url(""));changed["SaveMode"]="Folder";changed["Folder"]=utf8((base/L"changed").wstring());changed["OriginalSubfolders"]=true;changed["Links"]=Json::array({{{"Url",fixture.url("/assets/item.bin")}}});manager.addProject(changed,"Main queue",true);auto guarded=manager.jobs.back();fs::create_directories(base/L"changed");grabberJunction(base/L"changed/assets",outside);rejects([&]{transfer(manager,guarded,std::make_shared<Cancel>());},"A subfolder redirected after queueing is rejected when transfer starts");check(fs::is_empty(outside),"Late folder redirection publishes no outside file");fs::remove(base/L"changed/assets");
 manager.configure(guarded,{{"Folder",utf8((base/L"manual-choice").wstring())}});check(str(guarded->data,"ProjectDestinationRoot").empty(),"Explicit download-property folder edits release the project root constraint");transfer(manager,guarded,std::make_shared<Cancel>());check(readText(guarded->target())==fixture.payload,"An explicit properties destination is used by the real transfer");
 auto zip=grabberTestProject("https://example.test");zip["Template"]="Offline website (ZIP)";zip["SaveMode"]="Category";zip["SaveCategory"]="Books";manager.addProject(zip,"Main queue",true);check(manager.jobs.back()->target().parent_path()==base/L"library"&&str(manager.jobs.back()->data,"Category")=="Books","Offline ZIP projects honor the selected category");zip["OriginalSubfolders"]=true;rejects([&]{manager.saveProject(zip);},"Unsupported ZIP hierarchy is not accepted as a working option");
 manager.editCategory("Books","Library","pdf","example.test",utf8((base/L"new-library").wstring()));
 check(str(manager.state["Projects"].back(),"SaveCategory")=="Library"&&manager.jobs.back()->target().parent_path()==base/L"library","Renaming a category updates saved projects without moving their existing files");
 auto preserved=manager.snapshot();{Handle held(CreateFileW((manager.root/L"state.json").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));rejects([&]{manager.deleteCategory("Library");},"Category deletion reports failed persistence");check(manager.snapshot()==preserved,"Failed category deletion restores project choices as well as jobs and settings");}
 manager.deleteCategory("Library");check(str(manager.state["Projects"].back(),"SaveCategory")=="Other","Deleting a custom category moves saved project choices to Other");
 auto surviving=manager.state["Projects"].back();surviving["Id"]=guid();manager.addProject(surviving,"Main queue",true);check(str(manager.jobs.back()->data,"Category")=="Other","A project stays usable after its selected category is deleted");

}
