// Included inside GrabberDialog.
void fillTemplates(){
 preset->ResetContent();templateIds.clear();for(const auto& label:std::vector<std::string>{"Files","Images","Audio and video files","Archives and installers","Documents","Complete website","Offline website (ZIP)"}){preset->AddString(cs(label));templateIds.push_back("");}
 auto saved=grabberTemplates(manager);for(const auto& item:saved){preset->AddString(cs("Saved: "+str(item,"Name")));templateIds.push_back(str(item,"Id"));}
 int selected=std::max(0,preset->FindStringExact(-1,cs(templateKind)));for(size_t i=7;i<templateIds.size();++i)if(templateIds[i]==str(project,"AppliedTemplateId"))selected=(int)i;preset->SetCurSel(selected);
}
void applyTemplateChoice(int index){
 if(index<0)return;collect();if(index>=7){auto saved=grabberTemplates(manager);for(const auto& item:saved)if(str(item,"Id")==templateIds.at(index)){Json prefs;{Lock lock(manager.mutex);prefs=manager.state["Settings"];}project=applyGrabberTemplate(project,item,prefs);load();return;}throw std::runtime_error("The template no longer exists.");}
 templateKind=text(preset);project.erase("AppliedTemplateId");static const char* patterns[]={"*.zip, *.pdf, *.jpg, *.png, *.mp4, *.mp3","*.jpg, *.jpeg, *.png, *.gif, *.webp, *.avif, *.svg","*.mp4, *.mkv, *.webm, *.mp3, *.m4a, *.flac, *.ogg, *.wav","*.zip, *.7z, *.rar, *.tar, *.gz, *.iso","*.pdf, *.doc, *.docx, *.xls, *.xlsx, *.ppt, *.pptx, *.txt, *.epub","*","*"};extensions->SetWindowText(cs(patterns[index]));convertLinks->SendMessage(BM_SETCHECK,index==5?BST_CHECKED:BST_UNCHECKED);if(offline()){depth->SetWindowText(L"1");maximum->SetWindowText(L"20");}page();
}
void templatesDialog(){
 if(running)return;collect();Form dialog("Grabber templates",580,249,this);Json saved;std::string useId;
 dialog.init=[&]{dialog.label("Saved templates",14,16,552);auto choices=dialog.combo({},"",14,40,552);dialog.label("Template name",14,82,128);auto title=dialog.edit("",149,78,417);dialog.label("Save destinations, filters and concurrency settings. Starting pages, download links and login data are not copied into templates.",14,113,552,42);
  auto refresh=[&,choices,title]{saved=grabberTemplates(manager);choices->ResetContent();for(const auto& item:saved)choices->AddString(cs(str(item,"Name")));if(!saved.empty()){choices->SetCurSel(0);title->SetWindowText(cs(str(saved[0],"Name")));}};refresh();
  dialog.bindChange(choices,[&,choices,title]{int row=choices->GetCurSel();if(row>=0&&row<(int)saved.size())title->SetWindowText(cs(str(saved[row],"Name")));});
  dialog.button("Save as new",14,174,106,[&,title,refresh]{auto item=saveGrabberTemplate(manager,project,text(title));project["AppliedTemplateId"]=str(item,"Id");refresh();fillTemplates();});
  dialog.button("Replace selected",129,174,122,[&,choices,title,refresh]{int row=choices->GetCurSel();if(row<0)throw std::runtime_error("Choose a saved template.");auto item=saveGrabberTemplate(manager,project,text(title),str(saved[row],"Id"));project["AppliedTemplateId"]=str(item,"Id");refresh();fillTemplates();});
  dialog.button("Delete",260,174,87,[&,choices,refresh]{int row=choices->GetCurSel();if(row<0)throw std::runtime_error("Choose a saved template.");if(dialog.MessageBox(L"Delete this saved template? Projects and downloads will remain.",L"Delete template",MB_YESNO|MB_ICONQUESTION)!=IDYES)return;deleteGrabberTemplate(manager,str(saved[row],"Id"));refresh();fillTemplates();});
  dialog.button("Use selected",356,174,106,[&,choices]{int row=choices->GetCurSel();if(row<0)throw std::runtime_error("Choose a saved template.");useId=str(saved[row],"Id");dialog.close();});dialog.button("Close",472,174,94,[&]{dialog.close();});
 };dialog.DoModal();if(!useId.empty()){fillTemplates();for(size_t i=7;i<templateIds.size();++i)if(templateIds[i]==useId){preset->SetCurSel((int)i);applyTemplateChoice((int)i);break;}}
}
void grabberSettings(){
 if(running)return;Form dialog("Grabber settings",455,253,this);dialog.init=[&]{dialog.label("Concurrent file lookups (1-16)",14,20,277);auto lookups=dialog.edit(std::to_string(num(project,"MetadataParallel",4)),324,16,116);dialog.label("Concurrent project downloads (1-16)",14,62,305);auto transfers=dialog.edit(std::to_string(num(project,"DownloadParallel",2)),324,58,116);auto descriptions=dialog.check("Use link text as the download description",yes(project,"UseLinkDescriptions",true),14,102,426);dialog.label("Project downloads also respect UDM's global simultaneous-download limit. Starting a project does not start other queued files.",14,141,426,48);dialog.button("OK",250,211,90,[&,lookups,transfers,descriptions]{auto draft=project;draft["MetadataParallel"]=whole(lookups);draft["DownloadParallel"]=whole(transfers);draft["UseLinkDescriptions"]=checked(descriptions);validateGrabberActions(draft);project=draft;dialog.close();});dialog.button("Cancel",350,211,90,[&]{dialog.close();});};dialog.DoModal();
}
void renderTree(){
 if(!siteTree)return;auto nodes=grabberTree(project);auto key=nodes.dump();if(key==treeKey)return;treeKey=key;std::set<std::string> expanded;for(const auto& item:treeIds)if(siteTree->GetItemState(item.first,TVIS_EXPANDED)&TVIS_EXPANDED)expanded.insert(item.second);if(treeIds.empty()){expanded.insert("folders");expanded.insert("pages");}const bool previous=loading;loading=true;siteTree->SetRedraw(FALSE);siteTree->DeleteAllItems();treeFilters.clear();treeIds.clear();std::map<std::string,HTREEITEM> items;HTREEITEM selected=nullptr;
 for(const auto& node:nodes){auto parent=items.find(str(node,"Parent"));auto item=siteTree->InsertItem(cs(str(node,"Label")),parent==items.end()?TVI_ROOT:parent->second);items[str(node,"Id")]=item;treeIds[item]=str(node,"Id");treeFilters[item]={str(node,"Mode"),str(node,"Value")};if(str(node,"Mode")==viewMode&&str(node,"Value")==viewValue&&!selected)selected=item;}
 for(const auto& keyName:expanded)if(items.count(keyName))siteTree->Expand(items[keyName],TVE_EXPAND);if(!selected){viewMode="all";viewValue="";selected=items["all"];}siteTree->SelectItem(selected);siteTree->SetRedraw(TRUE);siteTree->Invalidate();loading=previous;
}
void renderResults(){
 if(!links||loading)return;std::set<std::string> highlighted;for(int row=links->GetNextItem(-1,LVNI_SELECTED);row>=0;row=links->GetNextItem(row,LVNI_SELECTED))highlighted.insert(utf8((LPCWSTR)links->GetItemText(row,2)));int top=links->GetTopIndex(),horizontal=links->GetScrollPos(SB_HORZ),focus=links->GetNextItem(-1,LVNI_FOCUSED);std::string focused=focus<0?"":utf8((LPCWSTR)links->GetItemText(focus,2));renderTree();auto rows=grabberRows(project,viewMode,viewValue);Json draft=project;destinationDraft(draft);bool rebuild=links->GetItemCount()!=(int)rows.size();if(!rebuild)for(size_t row=0;row<rows.size();++row)if(utf8((LPCWSTR)links->GetItemText((int)row,2))!=str(project["Links"][rows[row]],"Url")){rebuild=true;break;}loading=true;links->SetRedraw(FALSE);if(rebuild)links->DeleteAllItems();rowLinks=rows;
 auto setCell=[&](int row,int column,const CString& value){if(links->GetItemText(row,column)!=value)links->SetItemText(row,column,value);};
 {Lock lock(manager.mutex);std::map<std::string,JobPtr> jobs;for(auto job:manager.jobs)if(str(job->data,"ProjectId")==str(project,"Id"))jobs[str(job->data,"Url")]=job;
  for(size_t row=0;row<rows.size();++row){const auto& link=project["Links"][rows[row]];auto found=jobs.find(str(link,"Url"));JobPtr job=found==jobs.end()?JobPtr{}:found->second;std::string filename=grabberCollectedName(draft,link),folder;
   try{auto dest=grabberDestination(draft,manager.state["Settings"],str(link,"Url"),filename);filename=job?str(job->data,"FileName"):dest.name;folder=job?str(job->data,"Folder"):dest.folder;}catch(const std::exception& e){folder=e.what();}
   if(rebuild)links->InsertItem((int)row,cs(filename));else setCell((int)row,0,cs(filename));setCell((int)row,1,cs(folder));setCell((int)row,2,cs(str(link,"Url")));setCell((int)row,3,cs(job?(manager.isActive(job)&&str(job->data,"Status")=="Complete"&&str(project,"LinkConversionState")=="Converting"?"Converting links":str(job->data,"Status")):"Not added"));auto size=num(link,"Size",-1);if(job&&num(job->data,"Size",-1)>=0)size=num(job->data,"Size");setCell((int)row,4,cs(size<0?"Unknown":bytes(size)));setCell((int)row,5,cs(str(link,"ContentType")));setCell((int)row,6,cs(str(link,"Referrer")));setCell((int)row,9,cs(job?str(job->data,"Description"):str(link,"Description")));setCell((int)row,7,cs(job?bytes(num(job->data,"Received")):""));setCell((int)row,8,cs(job&&manager.isActive(job)?bytes(job->speed)+"/s":""));if((links->GetCheck((int)row)!=FALSE)!=yes(link,"Selected",true))links->SetCheck((int)row,yes(link,"Selected",true));if(str(link,"Url")==focused)links->SetItemState((int)row,LVIS_FOCUSED,LVIS_FOCUSED);if(highlighted.count(str(link,"Url")))links->SetItemState((int)row,LVIS_SELECTED,LVIS_SELECTED);
  }
 }if(rebuild&&!rows.empty()){CRect item;links->GetItemRect(0,&item,LVIR_BOUNDS);links->Scroll(CSize(horizontal-links->GetScrollPos(SB_HORZ),std::min(top,(int)rows.size()-1)*item.Height()));}links->SetRedraw(TRUE);links->Invalidate();loading=false;
}
void saveChecks(){if(loading)return;std::map<std::string,bool> selected;for(size_t row=0;row<rowLinks.size();++row){auto& link=project["Links"][rowLinks[row]];bool value=links->GetCheck((int)row)!=FALSE;link["Selected"]=value;selected[str(link,"Url")]=value;}if(!selected.empty())setGrabberSelection(manager,str(project,"Id"),selected);}
void checkRows(bool value,bool highlighted=false){loading=true;for(int row=0;row<links->GetItemCount();++row)if(!highlighted||(links->GetItemState(row,LVIS_SELECTED)&LVIS_SELECTED))links->SetCheck(row,value);loading=false;saveChecks();}
void startChecked(){saveChecks();if(!running){collect();manager.saveProject(project);}auto current=grabberProject(manager,str(project,"Id"));manager.addProject(current,text(queue),false,true);project=grabberProject(manager,str(project,"Id"));renderResults();status->SetWindowText(L"Checked project files started. Other queued downloads keep their settings.");}
void stopChecked(){saveChecks();auto current=grabberProject(manager,str(project,"Id"));Lock lock(manager.mutex);for(const auto& link:current["Links"])if(yes(link,"Selected",true)){auto job=grabberJob(manager,str(project,"Id"),str(link,"Url"));if(job)manager.pause(job);}renderResults();status->SetWindowText(L"Checked downloads stopped. Exploration can continue.");}
size_t selectedFile(){int row=links->GetNextItem(-1,LVNI_SELECTED);if(row<0||row>=(int)rowLinks.size())throw std::runtime_error("Select a collected file first.");return rowLinks[row];}
void openResult(bool folder){auto index=selectedFile();fs::path target;{Lock lock(manager.mutex);auto job=grabberJob(manager,str(project,"Id"),str(project["Links"][index],"Url"));if(!job)throw std::runtime_error("Add this file to UDM first.");if(!folder&&manager.isActive(job)&&str(job->data,"Status")=="Complete")throw std::runtime_error("Wait for this file to finish updating before opening it.");if(!folder&&str(job->data,"Status")!="Complete")throw std::runtime_error("The file has not finished downloading.");target=folder?job->target().parent_path():job->target();}openFile(this,target);}
void copyResult(bool referrer){auto index=selectedFile();auto value=wide(str(project["Links"][index],referrer?"Referrer":"Url"));if(!OpenClipboard())throw std::runtime_error("The clipboard is busy.");auto memory=GlobalAlloc(GMEM_MOVEABLE,(value.size()+1)*sizeof(wchar_t));if(memory){auto target=GlobalLock(memory);if(target){memcpy(target,value.c_str(),(value.size()+1)*sizeof(wchar_t));GlobalUnlock(memory);EmptyClipboard();if(!SetClipboardData(CF_UNICODETEXT,memory))GlobalFree(memory);}else GlobalFree(memory);}CloseClipboard();}
void resultMenu(){CMenu menu;menu.CreatePopupMenu();menu.AppendMenu(MF_STRING,1,L"Start checked downloads");menu.AppendMenu(MF_STRING,2,L"Stop checked downloads");menu.AppendMenu(MF_SEPARATOR);menu.AppendMenu(MF_STRING,3,L"Check highlighted files");menu.AppendMenu(MF_STRING,4,L"Uncheck highlighted files");menu.AppendMenu(MF_SEPARATOR);menu.AppendMenu(MF_STRING,5,L"Properties...");menu.AppendMenu(MF_STRING,6,L"Open file");menu.AppendMenu(MF_STRING,7,L"Open folder");menu.AppendMenu(MF_STRING,8,L"Copy download address");menu.AppendMenu(MF_STRING,9,L"Copy referring page");CPoint point;GetCursorPos(&point);switch(menu.TrackPopupMenu(TPM_RETURNCMD|TPM_LEFTALIGN,point.x,point.y,this)){case 1:startChecked();break;case 2:stopChecked();break;case 3:checkRows(true,true);break;case 4:checkRows(false,true);break;case 5:fileProperties();break;case 6:openResult(false);break;case 7:openResult(true);break;case 8:copyResult(false);break;case 9:copyResult(true);break;}}
void statistics(){Form dialog("Grabber statistics",440,346,this);CWnd* values=nullptr;auto refresh=[&]{auto current=grabberProject(manager,str(project,"Id"));auto stats=grabberStatistics(manager,current);std::string text;for(const auto& entry:std::vector<std::pair<std::string,std::string>>{{"Files found","Files"},{"Checked files","Selected"},{"Completed","Complete"},{"Downloading","Active"},{"Queued","Queued"},{"Paused","Paused"},{"Failed","Failed"},{"Pages explored","Pages"},{"Exploration errors","Errors"}})text+=entry.first+": "+std::to_string(num(stats,entry.second.c_str()))+"\r\n";text+="Received: "+bytes(num(stats,"Received"))+" / "+bytes(num(stats,"TotalBytes"))+"\r\nUnknown file sizes: "+std::to_string(num(stats,"UnknownSizes"))+"\r\nTransfer rate: "+bytes(real(stats,"Speed"))+"/s";values->SetWindowText(cs(text));};dialog.init=[&]{dialog.SetWindowPos(&CWnd::wndTopMost,0,0,0,0,SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE);values=dialog.label("",16,16,408,277);refresh();dialog.button("Close",324,307,100,[&]{dialog.close();});};dialog.pulse=refresh;dialog.DoModal();}
BOOL OnNotify(WPARAM w,LPARAM l,LRESULT* result)override{
 auto info=reinterpret_cast<NMHDR*>(l);try{if(!loading&&siteTree&&info->hwndFrom==siteTree->GetSafeHwnd()&&info->code==TVN_SELCHANGED){auto selection=reinterpret_cast<NMTREEVIEW*>(l)->itemNew.hItem;auto found=treeFilters.find(selection);if(found!=treeFilters.end()){viewMode=found->second.first;viewValue=found->second.second;renderResults();}*result=0;return TRUE;}
  if(!loading&&links&&info->hwndFrom==links->GetSafeHwnd()){if(info->code==LVN_ITEMCHANGED){auto change=reinterpret_cast<NMLISTVIEW*>(l);if((change->uChanged&LVIF_STATE)&&((change->uNewState^change->uOldState)&LVIS_STATEIMAGEMASK))saveChecks();}else if(info->code==NM_DBLCLK)fileProperties();else if(info->code==NM_RCLICK)resultMenu();}
 }catch(const std::exception& e){error(this,e);}return Form::OnNotify(w,l,result);
}
