#pragma once
#include "GrabberFilters.hpp"
// HTTP fixture records requests so exclusions are checked at the transport boundary.
class GrabberFilterFixture {
 SOCKET listener=INVALID_SOCKET;std::thread server;std::vector<std::thread> clients;std::atomic_bool stop{false};
 mutable std::mutex mutex;std::vector<std::string> requests;
 struct Reply {int status=200;std::string body,headers;bool unknown=false,headUnsupported=false;int delay=0;};
 std::map<std::string,Reply> routes;std::map<std::string,std::string> passwords,cookies;
 static void sendAll(SOCKET s,const std::string& text){for(size_t at=0;at<text.size();){int n=send(s,text.data()+at,(int)std::min<size_t>(65536,text.size()-at),0);if(n<=0)return;at+=n;}}
 void serve(SOCKET s){try{
  DWORD timeout=3000;setsockopt(s,SOL_SOCKET,SO_RCVTIMEO,(const char*)&timeout,sizeof(timeout));setsockopt(s,SOL_SOCKET,SO_SNDTIMEO,(const char*)&timeout,sizeof(timeout));std::string req;char buf[4096];while(req.find("\r\n\r\n")==std::string::npos&&req.size()<32768){int n=recv(s,buf,sizeof(buf),0);if(n<=0)break;req.append(buf,n);}
  auto begin=req.find(' '),end=req.find(' ',begin+1);auto path=req.substr(begin+1,end-begin-1);bool head=req.rfind("HEAD ",0)==0;std::smatch range;bool ranged=std::regex_search(req,range,std::regex("Range: bytes=([0-9]+)-([0-9]*)",std::regex::icase));Reply reply;
  {std::lock_guard<std::mutex> lock(mutex);requests.push_back(req);auto found=routes.find(path);if(found==routes.end())reply={404,"",""};else reply=found->second;auto required=passwords.find(path);if(required!=passwords.end()){std::smatch match;std::string authorization;if(std::regex_search(req,match,std::regex("Authorization: *([^\\r\\n]*)",std::regex::icase)))authorization=match[1];if(authorization!=required->second)reply={401,"","WWW-Authenticate: Basic realm=\"grabber-fixture\"\r\n"};}auto requiredCookie=cookies.find(path);if(requiredCookie!=cookies.end()){std::smatch cookie;auto actual=std::regex_search(req,cookie,std::regex("Cookie: *([^\\r\\n]*)",std::regex::icase))?cookie[1].str():"";if(actual.find(requiredCookie->second)==std::string::npos)reply={403,"missing cookie",""};}}
  if(head){int active=++heads;int before=peakHeads.load();while(active>before&&!peakHeads.compare_exchange_weak(before,active)){};}if(reply.delay)Sleep(reply.delay);
  int status=head&&reply.headUnsupported?405:reply.status;std::string body=reply.body,headers=reply.headers;
  if(status==200&&ranged&&!reply.unknown){auto total=body.size(),begin=(size_t)std::stoull(range[1]),end=range[2].str().empty()?(total?total-1:0):std::min<size_t>((size_t)std::stoull(range[2]),total?total-1:0);status=begin>=total||begin>end?416:206;headers+="Content-Range: "+(status==416?"bytes */"+std::to_string(total):"bytes "+std::to_string(begin)+"-"+std::to_string(end)+"/"+std::to_string(total))+"\r\n";body=status==416?"":body.substr(begin,end-begin+1);}
  if(status==405)body.clear();std::string response="HTTP/1.1 "+std::to_string(status)+" Fixture\r\n"+headers;if(!reply.unknown)response+="Content-Length: "+std::to_string(body.size())+"\r\n";response+="Connection: close\r\n\r\n";sendAll(s,response);if(!head)sendAll(s,body);if(head)--heads;
 }catch(...){}shutdown(s,SD_BOTH);closesocket(s);}
public:
 unsigned short port=0;std::atomic_int heads{0},peakHeads{0};
 GrabberFilterFixture(){listener=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);sockaddr_in a{};a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(bind(listener,(sockaddr*)&a,sizeof(a))||listen(listener,32))throw std::runtime_error("Grabber fixture bind failed.");int n=sizeof(a);getsockname(listener,(sockaddr*)&a,&n);port=ntohs(a.sin_port);server=std::thread([this]{while(!stop){fd_set set;FD_ZERO(&set);FD_SET(listener,&set);timeval wait{0,100000};if(select(0,&set,nullptr,nullptr,&wait)>0){auto s=accept(listener,nullptr,nullptr);if(s!=INVALID_SOCKET)clients.emplace_back([this,s]{serve(s);});}}});}
 ~GrabberFilterFixture(){stop=true;if(server.joinable())server.join();closesocket(listener);for(auto& thread:clients)thread.join();}
 std::string url(const std::string& path,bool alternate=false)const{return std::string("http://")+(alternate?"localhost":"127.0.0.1")+":"+std::to_string(port)+path;}
 void file(const std::string& path,std::string body,std::string headers="Content-Type: application/octet-stream\r\n",bool unknown=false,bool headUnsupported=false,int delay=0){std::lock_guard<std::mutex> lock(mutex);routes[path]={200,std::move(body),std::move(headers),unknown,headUnsupported,delay};}
 void page(const std::string& path,const std::string& body){file(path,body,"Content-Type: text/html\r\n");}
 void redirect(const std::string& path,const std::string& location,const std::string& headers=""){std::lock_guard<std::mutex> lock(mutex);routes[path]={302,"","Location: "+location+"\r\n"+headers};}
 void requireCookie(const std::string& path,const std::string& cookie){std::lock_guard<std::mutex> lock(mutex);cookies[path]=cookie;}
 void requireLogin(const std::string& path,const std::string& authorization){std::lock_guard<std::mutex> lock(mutex);passwords[path]=authorization;}
 int count(const std::string& path,const std::string& method="")const{std::lock_guard<std::mutex> lock(mutex);return (int)std::count_if(requests.begin(),requests.end(),[&](auto& req){return req.find(" "+path+" HTTP/")!=std::string::npos&&(method.empty()||req.rfind(method+" ",0)==0);});}
 bool has(const std::string& path,const std::string& header)const{std::lock_guard<std::mutex> lock(mutex);return std::any_of(requests.begin(),requests.end(),[&](auto& req){return req.find(" "+path+" HTTP/")!=std::string::npos&&req.find(header)!=std::string::npos;});}
};
static Json modernGrabber(const std::string& start){return {{"Id",guid()},{"Name","Filter fixture"},{"StartUrl",start},{"FileInclude","*.pdf, *.zip"},{"Depth",2},{"ExternalDepth",1},{"MaxPages",20},{"Links",Json::array()}};}
static bool grabberHas(const Json& p,const std::string& address){return std::any_of(p["Links"].begin(),p["Links"].end(),[&](const Json& item){return str(item,"Url")==address;});}
static void grabberFilterChecks(const fs::path& root){
 check(grabberPatterns(" *.JPG, image*.png\r\n*.pdf ")==std::vector<std::string>({"*.jpg","image*.png","*.pdf"}),"Grabber parses comma and line-separated filters");
 check(grabberGlob("image*.png","IMAGE thumbnail.PNG")&&!grabberGlob("*.jpg","a.jpg.exe"),"Grabber filename patterns are anchored and case insensitive");
 check(grabberGlob("a*b*c","axybzc")&&!grabberGlob("a*b*c","axybz"),"Grabber wildcard backtracking honors the whole pattern");
 rejects([]{grabberPatterns(std::string(8193,'a'));},"Grabber bounds filter text");rejects([]{grabberPatterns("a\tbad");},"Grabber rejects control characters in filters");
 std::string many;for(int i=0;i<129;++i)many+="*,";rejects([&]{grabberPatterns(many);},"Grabber bounds pattern count");
 PublicSuffix suffix("com\nco.uk\ngithub.io\n*.ck\n!www.ck\n");
 check(suffix.domain("A.B.EXAMPLE.CO.UK.")=="example.co.uk","Main-domain scope recognizes multi-label public suffixes");
 check(suffix.domain("sub.alice.github.io")=="alice.github.io"&&suffix.domain("bob.github.io")!="alice.github.io","Main-domain scope isolates private hosting tenants");
 check(suffix.domain("a.b.ck")=="a.b.ck"&&suffix.domain("b.ck").empty(),"Public suffix wildcard consumes exactly one label");
 check(suffix.domain("a.www.ck")=="www.ck"&&suffix.domain("www.ck")=="www.ck","Public suffix exceptions take priority");
 check(suffix.domain("co.uk").empty()&&suffix.domain("single").empty(),"A public suffix alone has no registrable parent");
 check(suffix.domain("127.0.0.1")=="127.0.0.1"&&suffix.domain("::1")=="::1","Domain scope preserves numeric hosts");
 check(asciiDomain("B\xc3\xbc" "CHER.example")=="xn--bcher-kva.example","Domain scope normalizes international names");
 check(PublicSuffix::installed().domain("www.example.co.uk")=="example.co.uk"&&PublicSuffix::installed().domain("a.tenant.github.io")=="tenant.github.io","Packaged domain list includes ICANN and private boundaries");
 auto p=modernGrabber("https://www.example.co.uk/support/index.html");p["ExploreSubdomains"]=true;p["NoParentDirectories"]=true;GrabberFilters filters(p);
 check(filters.pageAllowed("http://cdn.example.co.uk/support/child.html"),"Whole-domain exploration allows sibling subdomains and schemes");
 check(!filters.pageAllowed("https://other.co.uk/support/")&&!filters.pageAllowed("https://example.co.uk.attacker.test/support/"),"Whole-domain exploration excludes unrelated and deceptive hosts");
 check(!filters.pageAllowed("https://www.example.co.uk/support-other/x")&&!filters.pageAllowed("https://www.example.co.uk/support/%2e%2e/admin"),"No-parent filter blocks siblings and encoded traversal");
 check(!filters.fileLocationAllowed("https://cdn.example.co.uk/file.pdf")&&filters.fileLocationAllowed("http://www.example.co.uk/file.pdf"),"File host restriction remains independent of whole-domain exploration");
 p["StartUrl"]="https://alice.github.io/support/";GrabberFilters tenant(p);check(!tenant.currentSite(Url("https://bob.github.io/support/")),"Whole-domain setting does not merge private tenants");
 p=modernGrabber("https://example.test/start.html");p["PageIncludePaths"]="/docs/*";p["PageExcludePaths"]="/docs/private/*";p["FileIncludePaths"]="example.test/files/*";p["FileExcludePaths"]="/files/private/*";p["FileInclude"]="*.PDF, <start page>";p["FileExclude"]="secret*";GrabberFilters rules(p);
 check(rules.pageAllowed(str(p,"StartUrl"),true)&&!rules.pageAllowed(str(p,"StartUrl")),"Starting page bypasses page include patterns only for initial exploration");
 check(rules.pageAllowed("https://example.test/docs/a")&&!rules.pageAllowed("https://example.test/docs/private/a"),"Page exclusions override includes");
 check(rules.fileLocationAllowed("https://example.test/files/a.pdf")&&!rules.fileLocationAllowed("https://example.test/files/private/a.pdf"),"File path exclusions override includes");
 check(rules.nameAllowed(str(p,"StartUrl"),"start.html",true)&&rules.nameAllowed("https://example.test/files/book.pdf","book.PDF")&&!rules.nameAllowed("https://example.test/files/secret.pdf","secret.pdf"),"Start-page token and filename exclusions work together");
 p["MinFileBytes"]=10;p["MaxFileBytes"]=20;GrabberFilters sizes(p);check(sizes.sizeAllowed(10)&&sizes.sizeAllowed(20)&&!sizes.sizeAllowed(9)&&!sizes.sizeAllowed(21)&&!sizes.sizeAllowed(-1),"Size limits are inclusive and exclude unknown sizes");
 auto oldSignature=sizes.signature();p["MaxPages"]=30;check(GrabberFilters(p).signature()==oldSignature,"Increasing page limit preserves resumable scan identity");p["FileExclude"]="other*";check(GrabberFilters(p).signature()!=oldSignature,"Changing file filters invalidates previous scan identity");
 for(const char* field:{"Depth","ExternalDepth","MaxPages","MinFileBytes","MaxFileBytes"}){auto bad=p;bad[field]=-1;rejects([&]{GrabberFilters invalid(bad);},"Grabber rejects negative numeric limits");}
 auto bad=p;bad["MinFileBytes"]=21;bad["MaxFileBytes"]=20;rejects([&]{GrabberFilters invalid(bad);},"Grabber rejects an inverted size interval");bad=p;bad["FilesSameSite"]="yes";rejects([&]{GrabberFilters invalid(bad);},"Grabber rejects malformed scope switches");
 check(grabberHeaders("https://a.test/page?x=1#anchor","https://a.test/file").at("Referer")=="https://a.test/page?x=1","Same-origin Grabber requests carry the page referrer without a fragment");
 check(grabberHeaders("https://a.test/private?token=x","https://b.test/file").at("Referer")=="https://a.test/","Cross-origin Grabber requests disclose only the origin");
 check(grabberHeaders("https://a.test/page","http://a.test/file").empty(),"HTTPS downgrade omits Grabber referrer");
 GrabberFilterFixture fixture;Json settings={{"ProxyMode","Connect directly"},{"Retries",0}};Cancel cancel;
 fixture.page("/scope/start.html","<base href='/scope/'><a href='first.pdf'>one</a><a href='copy/first.pdf'>duplicate</a><a href='huge.zip'>large</a><a href='unknown.zip'>unknown</a><a href='range.zip'>range</a><a href='excluded.zip'>exclude</a><a href='blocked.html'>blocked</a><a href='child.html'>child</a><a href='../outside.html'>parent</a>");
 fixture.file("/scope/first.pdf","abcdefghij","Content-Type: application/pdf\r\n",false,false,120);fixture.file("/scope/copy/first.pdf","abcdefghij","Content-Type: application/pdf\r\n",false,false,120);fixture.file("/scope/huge.zip",std::string(100,'x'));fixture.file("/scope/unknown.zip","unknown","Content-Type: application/zip\r\n",true);fixture.file("/scope/range.zip","123456789012","Content-Type: application/zip\r\n",false,true);fixture.file("/scope/excluded.zip","ignored");
 fixture.page("/scope/blocked.html","<a href='bad.pdf'>bad</a>");fixture.page("/scope/child.html","<a href='second.pdf'>second</a>");fixture.page("/outside.html","<a href='/escape.pdf'>escape</a>");fixture.file("/scope/second.pdf","second-file");
 p=modernGrabber(fixture.url("/scope/start.html"));p["FileExclude"]="excluded*";p["PageExcludePaths"]="/scope/blocked*";p["NoParentDirectories"]=true;p["MinFileBytes"]=10;p["MaxFileBytes"]=20;p["HideDuplicates"]=true;
 auto result=explore(p,settings,cancel);
 check(result["Links"].size()==3&&grabberHas(result,fixture.url("/scope/first.pdf"))&&grabberHas(result,fixture.url("/scope/range.zip"))&&grabberHas(result,fixture.url("/scope/second.pdf")),"Real Grabber scan combines filenames, size, hierarchy and duplicate filters");
 check(num(result,"HiddenDuplicates")==1&&num(result,"PagesVisited")==2,"Duplicate hiding keeps the first document-order copy");
 check(fixture.count("/scope/excluded.zip")==0&&fixture.count("/scope/blocked.html")==0&&fixture.count("/outside.html")==0,"Excluded files, pages and parent paths receive no HTTP request");
 check(fixture.count("/scope/range.zip","HEAD")==1&&fixture.count("/scope/range.zip","GET")==1&&fixture.has("/scope/range.zip","Range: bytes=0-0"),"Metadata falls back from unsupported HEAD to a one-byte range");
 check(fixture.count("/scope/first.pdf","GET")==0&&fixture.peakHeads>=2&&fixture.peakHeads<=4,"Metadata overlaps up to four requests without downloading file bodies");
 check(fixture.has("/scope/first.pdf","Referer: "+fixture.url("/scope/start.html")),"Grabber transports the discovering page context");
 check(result["Errors"].size()==1&&str(result["Errors"][0],"Message").find("Size is unavailable")!=std::string::npos,"Unknown size produces an explanation when size limits exclude the file");
 p["OriginalSubfolders"]=true;auto hierarchical=explore(p,settings,cancel);check(hierarchical["Links"].size()==4&&num(hierarchical,"HiddenDuplicates")==0,"Original subfolders retain equal-name equal-size files");
 fixture.page("/rename.html","<a href='/download?id=1'>download</a>");fixture.file("/download?id=1","document-data","Content-Type: application/pdf\r\nContent-Disposition: attachment; filename*=UTF-8''guide%20book.pdf\r\n");
 p=modernGrabber(fixture.url("/rename.html"));result=explore(p,settings,cancel);check(result["Links"].size()==1&&str(result["Links"][0],"FileName")=="guide book.pdf"&&num(result["Links"][0],"Size")==13,"Dynamic download routes use server filenames and metadata");
 Manager manager(root/L"filter-state");manager.state["Settings"]["DownloadFolder"]=utf8((root/L"filter-downloads").wstring());manager.state["Settings"]["ProxyMode"]="Connect directly";manager.state["Settings"]["Retries"]=0;
 check(manager.addProject(result,"Main queue",true)==1,"Filtered results are accepted by the real download manager");auto job=manager.jobs.back();transfer(manager,job,std::make_shared<Cancel>());check(job->target().filename()==L"guide book.pdf"&&readText(job->target())=="document-data","Collected metadata filename survives category routing and actual transfer");
 check(str(job->data,"DownloadPage")==fixture.url("/rename.html"),"Collected file retains its refresh-link source page");
 fixture.page("/redirects.html","<a href='/redirect-file.pdf'>redirect</a><a href='/redirect-page.html'>page</a>");fixture.redirect("/redirect-file.pdf",fixture.url("/forbidden/file.pdf"));fixture.redirect("/redirect-page.html",fixture.url("/forbidden/page.html"));fixture.file("/forbidden/file.pdf","forbidden");fixture.page("/forbidden/page.html","forbidden");
 p=modernGrabber(fixture.url("/redirects.html"));p["FileExcludePaths"]="/forbidden/*";p["PageExcludePaths"]="/forbidden/*";result=explore(p,settings,cancel);check(result["Links"].empty()&&result["Errors"].size()==2&&fixture.count("/forbidden/file.pdf")==0&&fixture.count("/forbidden/page.html")==0,"Page and file redirect destinations are filtered before transport");
 fixture.redirect("/start-redirect",fixture.url("/scope/start.html"));p=modernGrabber(fixture.url("/start-redirect"));p["PageIncludePaths"]="/scope/child*";result=explore(p,settings,cancel);check(grabberHas(result,fixture.url("/scope/second.pdf")),"Starting redirect chain is explored before applying page includes to children");
 fixture.page("/external.html","<a href='"+fixture.url("/other.html",true)+"'>external page</a><a href='"+fixture.url("/other.pdf",true)+"'>external file</a>");fixture.page("/other.html","<a href='/third.html'>third</a><a href='/nested.pdf'>file</a>");fixture.page("/third.html","<a href='/too-deep.pdf'>deep</a>");fixture.file("/other.pdf","other");fixture.file("/nested.pdf","nested");fixture.file("/too-deep.pdf","too-deep");
 p=modernGrabber(fixture.url("/external.html"));result=explore(p,settings,cancel);check(result["Links"].empty()&&fixture.count("/other.html")==0&&fixture.count("/other.pdf")==0,"Default page and file scopes reject external hosts without requesting them");
 p["ExploreSameSite"]=false;p["FilesSameSite"]=false;result=explore(p,settings,cancel);check(result["Links"].size()==2&&fixture.count("/third.html")==0,"External page depth and file host permissions are independent");check(fixture.has("/other.pdf","Referer: "+fixture.url("/"))&&!fixture.has("/other.pdf","Referer: "+fixture.url("/external.html")),"Real cross-host metadata requests reduce the referrer to its origin");
 fixture.page("/resume.html","<a href='/resume-one.pdf'>one</a><a href='/resume-child.html'>child</a>");fixture.page("/resume-child.html","<a href='/resume-two.pdf'>two</a>");fixture.file("/resume-one.pdf","one");fixture.file("/resume-two.pdf","two");
 p=modernGrabber(fixture.url("/resume.html"));p["MaxPages"]=1;result=explore(p,settings,cancel);check(result["Links"].size()==1&&yes(result,"ExplorationLimited")&&str(result,"ExplorationLimit")=="pages"&&!result["ExploreState"]["Pending"].empty(),"Page limit retains results and pending exploration");
 result["Links"][0]["Selected"]=false;result["Links"][0]["DownloadId"]="kept-id";result["MaxPages"]=2;auto resumed=explore(result,settings,cancel);check(resumed["Links"].size()==2&&!yes(resumed,"ExplorationLimited")&&!yes(resumed["Links"][0],"Selected")&&str(resumed["Links"][0],"DownloadId")=="kept-id"&&fixture.count("/resume.html")==1,"Resume continues pending pages without losing prior selections or added IDs");
 auto invalid=result;invalid["ExploreState"]["Pending"][0]["Depth"]=-1;rejects([&]{explore(invalid,settings,cancel);},"Resume rejects invalid saved depths");invalid=result;invalid["ExploreState"]["Pending"][0]["Url"]="file:///C:/private";rejects([&]{explore(invalid,settings,cancel);},"Resume rejects non-HTTP pending requests");invalid=result;invalid["ExploreState"]["Pending"][0]["First"]=true;rejects([&]{explore(invalid,settings,cancel);},"Resume rejects forged starting-page exemption");invalid=result;invalid["ExploreState"]["Visited"]="bad";rejects([&]{explore(invalid,settings,cancel);},"Resume rejects malformed saved collections");
 result["FileExclude"]="resume-one*";result["MaxPages"]=2;auto refiltered=explore(result,settings,cancel);check(refiltered["Links"].size()==1&&grabberHas(refiltered,fixture.url("/resume-two.pdf")),"Changing filters starts fresh and discards stale results");
 p=modernGrabber(fixture.url("/resume.html"));Cancel stopped;int reports=0;result=explore(p,settings,stopped,[&](auto){if(++reports==2)stopped.stop=true;});check(yes(result,"ExplorationStopped")&&result["Links"].size()==1&&!result["ExploreState"]["Pending"].empty(),"Stop retains discovered files and the unfinished page");resumed=explore(result,settings,cancel);check(resumed["Links"].size()==2&&!yes(resumed,"ExplorationStopped"),"A stopped scan resumes with a fresh cancellation token");
 fixture.page("/independent.html","<a href='/excluded-page.html'>file only</a><link rel='stylesheet' href='/style.css'>");fixture.page("/excluded-page.html","<a href='/never-follow.pdf'>never</a>");fixture.file("/style.css","body {color: red}","Content-Type: text/css\r\n");fixture.file("/never-follow.pdf","never");
 p=modernGrabber(fixture.url("/independent.html"));p["Depth"]=0;p["FileInclude"]="excluded-page.html, *.css";p["PageExcludePaths"]="/excluded-page.html";result=explore(p,settings,cancel);
 check(result["Links"].size()==2&&grabberHas(result,fixture.url("/excluded-page.html"))&&grabberHas(result,fixture.url("/style.css")),"Page exploration exclusions do not suppress matching HTML or CSS file collection");
 check(fixture.count("/excluded-page.html","HEAD")==1&&fixture.count("/excluded-page.html","GET")==0&&fixture.count("/never-follow.pdf")==0,"Collecting an excluded HTML file does not explore its children");
 p=modernGrabber(fixture.url("/resume.html"));p["MaxPages"]=1;auto persisted=explore(p,settings,cancel);manager.saveProject(persisted);Json restored;{Manager reopened(root/L"filter-state");for(const auto& candidate:reopened.state["Projects"])if(str(candidate,"Id")==str(persisted,"Id"))restored=candidate;}
 restored["MaxPages"]=2;auto fromDisk=explore(restored,settings,cancel);check(fromDisk["Links"].size()==2&&!yes(fromDisk,"ExplorationLimited"),"Actual saved project reload preserves the pending scan and collected files");
 p=modernGrabber(fixture.url("/scope/start.html"));p["FileInclude"]="<start page>";p["Depth"]=0;result=explore(p,settings,cancel);check(result["Links"].size()==1&&grabberHas(result,str(p,"StartUrl")),"Start-page token collects only the requested HTML document");
 auto capped=modernGrabber(fixture.url("/resume.html"));for(int i=0;i<1999;++i)capped["Links"].push_back({{"Url",fixture.url("/existing-"+std::to_string(i)+".pdf")},{"FileName","existing-"+std::to_string(i)+".pdf"},{"Size",1}});
 capped["ExploreState"]={{"Signature",GrabberFilters(capped).signature()},{"Pending",Json::array({{{"Url",str(capped,"StartUrl")},{"Depth",0},{"ExternalDepth",0},{"First",true}}})},{"Visited",Json::array()},{"Considered",Json::array()}};
 auto limited=explore(capped,settings,cancel);check(limited["Links"].size()==2000&&yes(limited,"ExplorationLimited")&&str(limited,"ExplorationLimit")=="files","The 2,000-file safety cap is reported accurately after results are moved");
 check(!limited["ExploreState"]["Pending"].empty()&&num(limited,"PagesVisited")==0,"A file-capped page retains its pending work instead of claiming completion");
 p=modernGrabber(fixture.url("/scope/start.html"));p["Depth"]=0;result=explore(p,settings,cancel);check(grabberHas(result,fixture.url("/scope/unknown.zip"))&&num(*std::find_if(result["Links"].begin(),result["Links"].end(),[&](const Json& link){return str(link,"Url")==fixture.url("/scope/unknown.zip");}),"Size",-1)==-1,"Unknown-size files remain collectible when no size limits are enabled");
}
