#pragma once
#include "GrabberBrowserSession.hpp"
static Json sessionCookie(std::string name,std::string value,std::string path="/",bool secure=false,std::string domain="127.0.0.1"){
 return {{"name",name},{"value",value},{"domain",domain},{"path",path},{"secure",secure},{"hostOnly",true}};
}
static void grabberSessionChecks(const fs::path& root){
 auto session=validateBrowserSession({{"Origin","http://127.0.0.1:9191"},{"UserAgent","UDM browser fixture"},{"LogoutPages","*/logout*"},{"Cookies",Json::array({sessionCookie("root","root-secret"),sessionCookie("private","private-secret","/private"),sessionCookie("secure","secure-secret","/",true)})}});
 auto persistent=session;persistent["Cookies"][0]["expirationDate"]=epoch()/1000+3600;check(headerValue(browserSessionHeaders(validateBrowserSession(persistent),"http://127.0.0.1:9191/",{}),"Cookie")=="root=root-secret","Persistent cookie expiry uses Unix seconds while the application clock uses milliseconds");
 auto headers=browserSessionHeaders(session,"http://127.0.0.1:9191/private/file.bin",{});
 check(headerValue(headers,"Cookie")=="private=private-secret; root=root-secret","Browser sessions preserve cookie path order and Secure restrictions");
 check(headerValue(browserSessionHeaders(session,"http://127.0.0.1:9191/private-other/file",{}),"Cookie")=="root=root-secret","Cookie path prefixes require a directory boundary");
 check(headerValue(browserSessionHeaders(session,"http://127.0.0.1:9192/private/file",{}),"Cookie").empty(),"A project browser session does not cross port boundaries");
 check(headerValue(browserSessionHeaders(session,"https://127.0.0.1:9191/private/file",{}),"Cookie").empty(),"A project browser session does not change scheme implicitly");
 check(headerValue(browserSessionHeaders(session,"http://localhost:9191/private/file",{{"Cookie","old=secret"}}),"Cookie").empty(),"Foreign origins never inherit project cookies or a captured static Cookie header");
 auto partitioned=session;auto extra=partitioned["Cookies"][0];extra["partitioned"]=true;extra["value"]="partition-secret";partitioned["Cookies"].push_back(extra);check(validateBrowserSession(partitioned)["Cookies"].size()==4,"Ordinary and partitioned cookies with the same name retain distinct identities");
 auto expired=session;expired["Cookies"][0]["expirationDate"]=epoch()/1000-1;check(headerValue(browserSessionHeaders(expired,"http://127.0.0.1:9191/",{}),"Cookie").empty(),"Expired cookies are omitted when a queued request starts");
 rejects([&]{browserSessionHeaders(session,"http://127.0.0.1:9191/logout?next=/",{});},"Logout exclusions are enforced before sending a request");
 auto oversized=session;oversized["Cookies"]=Json::array({sessionCookie("one",std::string(8192,'a')),sessionCookie("two",std::string(8192,'b'))});rejects([&]{validateBrowserSession(oversized);},"Oversized session headers fail at handoff before queued downloads are created");
 auto malformed=session;malformed["Cookies"][0]["domain"]="different.test";rejects([&]{validateBrowserSession(malformed);},"Session handoff rejects foreign cookie domains");
 malformed=session;malformed["Cookies"][0]["value"]="x\r\nCookie: stolen";rejects([&]{validateBrowserSession(malformed);},"Session handoff rejects cookie header injection");
 malformed=session;malformed["Cookies"][0]["expirationDate"]="tomorrow";rejects([&]{validateBrowserSession(malformed);},"Session handoff validates cookie expiry types");
 malformed={{"ProtectedBrowserSession",Json::object()}};rejects([&]{readBrowserSession(malformed);},"Malformed protected website sessions cannot become anonymous requests");
 malformed={{"ProtectedBrowserSession","broken"}};rejects([&]{readBrowserSession(malformed);},"Unreadable browser sessions require sign-in again");
 malformed={{"RequiresBrowserSessionCapture",true}};rejects([&]{browserSessionPreferences(defaultSettings(),malformed);},"Omitted exported sessions cannot silently become anonymous downloads");
 auto https=session;https["Origin"]="https://127.0.0.1:9191";check(headerValue(browserSessionHeaders(https,"https://127.0.0.1:9191/",{}),"Cookie")=="root=root-secret; secure=secure-secret","HTTPS requests include eligible Secure cookies");
 check(sessionDomainMatches("files.example.test",".example.test",false)&&!sessionDomainMatches("evil-example.test",".example.test",false)&&!sessionDomainMatches("files.example.test","example.test",true),"Domain cookies and host-only cookies retain separate matching rules");

 GrabberFilterFixture fixture;auto project=modernGrabber(fixture.url("/private/index.html"));project["BrowserLogin"]=true;project["LoginPage"]=fixture.url("/login");project["LogoutPages"]="*/logout*";
 fixture.page("/private/index.html","<a href='report.bin'>Signed-in report</a><a href='/logout'>Sign out</a><a href='redirect.bin'>Redirect</a>");fixture.file("/private/report.bin","session-report");fixture.redirect("/private/redirect.bin",fixture.url("/public/result.bin"));fixture.file("/public/result.bin","public-result");
 auto settings=defaultSettings();settings["ProxyMode"]="Connect directly";settings["Retries"]=0;settings["CategoryFolders"]=false;settings["DownloadFolder"]=utf8((root/L"session-downloads").wstring());project["FileInclude"]="*.bin";Cancel cancel;
 Manager manager(root/L"session-state");manager.setSettings(settings);project=beginGrabberBrowserLogin(manager,project);
 rejects([&]{explore(project,settings,cancel);},"Manual browser sign-in prevents exploration before session handoff");
 check(num(project["PendingBrowserLogin"],"Expires")-epoch()>14*60*1000&&num(project["PendingBrowserLogin"],"Expires")-epoch()<=15*60*1000,"A browser sign-in ticket remains available for fifteen minutes, not milliseconds");
 auto pending=pendingGrabberBrowserLogins(manager,fixture.url("/private/index.html"));check(pending["projects"].size()==1&&pending.dump().find("root-secret")==std::string::npos,"Pending sign-in exposes only matching project identity and no cookies");
 check(pendingGrabberBrowserLogins(manager,"https://other.test/")["projects"].empty(),"Other websites cannot enumerate this project's sign-in ticket");
 session["Origin"]=Url(fixture.url("/")).origin;Json message={{"projectId",str(project,"Id")},{"url",str(project,"StartUrl")},{"ticket",str(project["PendingBrowserLogin"],"Token")},{"session",session}};
 auto wrong=message;wrong["ticket"]="wrong";rejects([&]{completeGrabberBrowserLogin(manager,wrong);},"Browser session completion rejects a different ticket");
 wrong=message;wrong["url"]="https://other.test/";rejects([&]{completeGrabberBrowserLogin(manager,wrong);},"Browser session completion rejects another website's tab");
 auto before=manager.state["Projects"];{Handle locked(CreateFileW((manager.root/L"state.json").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));rejects([&]{completeGrabberBrowserLogin(manager,message);},"Failed browser-session persistence reports its save error");check(manager.state["Projects"]==before,"Failed browser-session save retains the original pending ticket");}
 check(yes(completeGrabberBrowserLogin(manager,message),"ok"),"A matching browser session completes the armed project login");
 auto stale=project;stale["Name"]="Edited while signing in";manager.saveProject(stale);auto merged=grabberProject(manager,str(project,"Id"));check(!merged.contains("PendingBrowserLogin")&&readBrowserSession(merged)==session&&str(merged,"Name")=="Edited while signing in","Saving a stale wizard draft retains a concurrently completed session and its other edits");
 check(yes(completeGrabberBrowserLogin(manager,message),"alreadySaved"),"Repeated completion safely acknowledges the same saved session");
 wrong=message;wrong["session"]["Cookies"][0]["value"]="changed";rejects([&]{completeGrabberBrowserLogin(manager,wrong);},"A replayed ticket cannot replace the session with different cookies");
 project=grabberProject(manager,str(project,"Id"));check(!project.contains("PendingBrowserLogin")&&readText(manager.root/L"state.json").find("root-secret")==std::string::npos,"Completed sign-in consumes its ticket and encrypts cookie values");
 {Manager reopened(manager.root);check(readBrowserSession(grabberProject(reopened,str(project,"Id")))==session,"A saved browser session survives an application restart");}
 auto collected=explore(project,settings,cancel);check(collected["Links"].size()==2&&fixture.count("/logout")==0,"Signed-in exploration collects files without visiting logout pages");
 check(fixture.has("/private/report.bin","Cookie: private=private-secret; root=root-secret")&&fixture.has("/public/result.bin","Cookie: root=root-secret")&&!fixture.has("/public/result.bin","private-secret"),"Metadata redirects recalculate cookie paths instead of forwarding the original header");
 manager.saveProject(collected);check(manager.addProject(collected,"Main queue",true)==2,"New collected downloads retain their protected browser session");
 for(auto job:manager.jobs)transfer(manager,job,std::make_shared<Cancel>());
 check(readText(manager.jobs[0]->target())=="session-report"&&readBrowserSession(manager.jobs[0]->data)==session,"Queued session downloads publish exact file bytes with retained cookie scope");
 auto redirected=manager.add(fixture.url("/private/redirect.bin"),"","session-redirect.bin","Main queue",true);redirected->data["ProtectedBrowserSession"]=protect(session.dump());transfer(manager,redirected,std::make_shared<Cancel>());check(readText(redirected->target())=="public-result"&&!fixture.has("/public/result.bin","private-secret"),"Actual file-transfer redirects recalculate cookie scope as well as metadata redirects");
 auto copied=manager.redownload(manager.jobs[0]);check(readBrowserSession(copied->data)==session,"Redownload retains the website session");
 auto catalog=exportCatalog(manager,{manager.jobs[0]},false);check(yes(catalog["Downloads"][0],"RequiresBrowserSessionCapture")&&!catalog["Downloads"][0].contains("ProtectedBrowserSession"),"Ordinary catalog export omits website session secrets and marks recapture");
 Manager imported(root/L"session-import");importCatalog(imported,catalog,utf8((root/L"session-import-files").wstring()));rejects([&]{imported.resume(imported.jobs[0]);},"Imported downloads without session data cannot silently resume anonymously");
 imported.refreshAddress(imported.jobs[0],str(imported.jobs[0]->data,"Url"),Headers{{"Cookie","private=private-secret; root=root-secret"}},str(project,"StartUrl"));imported.resume(imported.jobs[0]);transfer(imported,imported.jobs[0],std::make_shared<Cancel>());check(!yes(imported.jobs[0]->data,"RequiresBrowserSessionCapture")&&readText(imported.jobs[0]->target())=="session-report","Explicit browser address refresh recovers an imported session download with exact bytes");
 auto broken=manager.add(fixture.url("/private/report.bin"),"","old-cookie.bin","Main queue",true);broken->data["ProtectedBrowserSession"]="unreadable";manager.refreshAddress(broken,str(broken->data,"Url"),Headers{{"Cookie","fresh=accepted"}});check(!broken->data.contains("ProtectedBrowserSession")&&headerValue(readHeaders(broken->data),"Cookie")=="fresh=accepted","An approved fresh browser capture replaces stale or unreadable project cookies");
 auto offlineMissing=manager.add(fixture.url("/"),"","missing-session.zip","Main queue",true);offlineMissing->data["Status"]="Complete";offlineMissing->data["RequiresBrowserSessionCapture"]=true;offlineMissing->data["OfflineProject"]={{"StartUrl",fixture.url("/")},{"Depth",0},{"MaxPages",1},{"MaxMiB",2},{"ExternalAssets",false}};rejects([&]{manager.redownload(offlineMissing);},"Offline redownload cannot silently discard a required browser session");
 auto protectedCatalog=exportCatalog(manager,{manager.jobs[0]},true);Manager restored(root/L"session-import-protected");importCatalog(restored,protectedCatalog,utf8((root/L"session-import-protected-files").wstring()),true);check(readBrowserSession(restored.jobs[0]->data)==session,"Explicit encrypted catalog transfer retains website-session scope");
 auto templateItem=saveGrabberTemplate(manager,collected,"Browser login template");check(!templateItem["Settings"].contains("ProtectedBrowserSession")&&!templateItem["Settings"].contains("PendingBrowserLogin"),"Saved templates never include browser cookies or active tickets");
 auto offlineProject=project;offlineProject["Template"]="Offline website (ZIP)";auto archiveJob=manager.addOfflineProject(offlineProject,"Main queue",true);offlineTransfer(manager,archiveJob,std::make_shared<Cancel>());auto archiveCopy=manager.redownload(archiveJob);check(readBrowserSession(archiveCopy->data)==session,"Offline archive redownload preserves the full signed-in cookie scope and logout exclusions");
 auto repaired=project;repaired["ProtectedBrowserSession"]="broken";repaired["LoginPage"]=fixture.url("/login#/sign-in");repaired=beginGrabberBrowserLogin(manager,repaired);check(!repaired.contains("ProtectedBrowserSession")&&str(repaired["PendingBrowserLogin"],"LoginPage").find("#/sign-in")!=std::string::npos,"Starting sign-in repairs unreadable sessions and preserves SPA login fragments");
 auto expiredProject=beginGrabberBrowserLogin(manager,project);expiredProject["PendingBrowserLogin"]["Expires"]=epoch()-1;manager.saveProject(expiredProject);check(pendingGrabberBrowserLogins(manager,str(project,"StartUrl"))["projects"].empty(),"Expired browser sign-in requests are not offered by the extension");
 wrong=message;wrong["ticket"]=str(expiredProject["PendingBrowserLogin"],"Token");rejects([&]{completeGrabberBrowserLogin(manager,wrong);},"Expired browser sign-in tickets cannot save cookies");
 cancelGrabberBrowserLogin(manager,str(project,"Id"));check(!grabberProject(manager,str(project,"Id")).contains("PendingBrowserLogin"),"Canceling browser sign-in clears its pending ticket");
}
static int grabberSessionFeatureSpec(const fs::path& file){
 try{auto spec=Json::parse(readText(file));Manager manager(wide(str(spec,"root")));auto output=file.parent_path()/L"result.json";
  if(str(spec,"operation")=="seed"){
   auto prefs=defaultSettings();prefs["DownloadFolder"]=utf8((manager.root/L"downloads").wstring());prefs["CategoryFolders"]=false;prefs["ProxyMode"]="Connect directly";prefs["Retries"]=0;prefs["PrefetchFileInfo"]=false;prefs["Sound"]=false;prefs["SuppressProgressDialog"]=true;prefs["SuppressCompletionDialog"]=true;manager.setSettings(prefs);
   auto project=modernGrabber(str(spec,"url"));project["FileInclude"]="*.bin";project["BrowserLogin"]=true;project["LoginPage"]=str(spec,"login");project["LogoutPages"]="*/logout*";project=beginGrabberBrowserLogin(manager,project);atomicText(output,Json{{"projectId",str(project,"Id")},{"ticket",str(project["PendingBrowserLogin"],"Token")}}.dump(2));
  }else{auto project=manager.state["Projects"].at(0);Cancel cancel;project=explore(project,manager.state["Settings"],cancel);manager.saveProject(project);manager.addProject(project,"Main queue",true);Json files=Json::array();for(auto job:manager.jobs){transfer(manager,job,std::make_shared<Cancel>());files.push_back({{"path",utf8(job->target().wstring())},{"sha256",fileHash(job->target())},{"description",str(job->data,"Description")}});}atomicText(output,Json{{"files",files},{"errors",project["Errors"]},{"sessionSaved",!readBrowserSession(project).empty()}}.dump(2));}
  return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<std::endl;return 1;}
}
