// Included inside udm after Scheduler.
class GrabberDialog:public Form {
 Manager& manager;Json project;CComboBox *projects=nullptr,*preset=nullptr,*queue=nullptr;CWnd *name=nullptr,*address=nullptr,*extensions=nullptr,*depth=nullptr,*maximum=nullptr,*folder=nullptr,*status=nullptr,*heading=nullptr,*later=nullptr,*back=nullptr,*next=nullptr,*add=nullptr,*scan=nullptr,*stop=nullptr,*externalAssets=nullptr,*budget=nullptr,*offlineHint=nullptr;std::vector<CWnd*> explorationControls;
 CListCtrl* links=nullptr;std::shared_ptr<Cancel> cancellation;std::future<Json> work;bool running=false;int step=0;std::vector<std::vector<CWnd*>> pages;std::mutex reportMutex;std::string reportText;
 Json blank(){return {{"Id",guid()},{"Name","New project"},{"StartUrl","https://"},{"Template","Files"},{"Extensions","zip pdf jpg png mp4 mp3"},{"Depth",1},{"MaxPages",20},{"Folder",""},{"Links",Json::array()}};}
 bool offline(){return preset&&text(preset)=="Offline website (ZIP)";}
 void page(){static const char* title[]={"1. Name and starting page","2. File filters and download location","3. Explore, review and download"};heading->SetWindowText(cs(step==2&&offline()?"3. Save an offline website":title[step]));for(int i=0;i<3;++i)for(auto w:pages[i])w->ShowWindow(i==step?SW_SHOW:SW_HIDE);back->EnableWindow(step>0&&!running);next->ShowWindow(step<2?SW_SHOW:SW_HIDE);next->EnableWindow(!running);add->ShowWindow(step==2?SW_SHOW:SW_HIDE);add->EnableWindow(!running&&(offline()||links->GetItemCount()>0));add->SetWindowText(offline()?L"Add website":L"Add selected");if(externalAssets)externalAssets->EnableWindow(offline());if(budget)budget->EnableWindow(offline());if(extensions)extensions->EnableWindow(!offline());scan->EnableWindow(!running);stop->EnableWindow(running);projects->EnableWindow(!running);if(step==2){for(auto w:explorationControls)w->ShowWindow(offline()?SW_HIDE:SW_SHOW);if(offlineHint)offlineHint->ShowWindow(offline()?SW_SHOW:SW_HIDE);}}
 void fillProjects(){projects->ResetContent();Lock lock(manager.mutex);for(auto p:manager.state["Projects"])projects->AddString(cs(str(p,"Name")));projects->SelectString(-1,cs(str(project,"Name")));}
 void load(){name->SetWindowText(cs(str(project,"Name")));address->SetWindowText(cs(str(project,"StartUrl")));extensions->SetWindowText(cs(str(project,"Extensions")));folder->SetWindowText(cs(str(project,"Folder")));depth->SetWindowText(cs(std::to_string(num(project,"Depth",1))));maximum->SetWindowText(cs(std::to_string(num(project,"MaxPages",20))));preset->SelectString(-1,cs(str(project,"Template","Files")));externalAssets->SendMessage(BM_SETCHECK,yes(project,"ExternalAssets")?BST_CHECKED:BST_UNCHECKED);budget->SetWindowText(cs(std::to_string(num(project,"MaxMiB",256))));links->DeleteAllItems();for(int i=0;i<(int)project["Links"].size();++i){auto link=project["Links"][i];Url u(str(link,"Url"));links->InsertItem(i,cs(safeName(unescape(u.path))));links->SetItemText(i,1,cs(str(link,"Url")));links->SetCheck(i,yes(link,"Selected",true));}page();}
 void collect(){project["Name"]=trim(text(name));project["StartUrl"]=trim(text(address));project["Extensions"]=trim(text(extensions));project["Template"]=text(preset);project["Depth"]=std::stoll(text(depth));project["MaxPages"]=std::stoll(text(maximum));project["Folder"]=trim(text(folder));project["ExternalAssets"]=checked(externalAssets);project["MaxMiB"]=std::stoll(text(budget));for(int i=0;i<links->GetItemCount();++i)project["Links"][i]["Selected"]=links->GetCheck(i)!=FALSE;}
 void exploreNow(){if(running)return;collect();manager.saveProject(project);fillProjects();cancellation=std::make_shared<Cancel>();auto input=project;Json settings;{Lock lock(manager.mutex);settings=manager.state["Settings"];}auto token=cancellation;running=true;page();status->SetWindowText(L"Connecting to the starting page...");work=std::async(std::launch::async,[this,input,settings,token]{return explore(input,settings,*token,[this](std::string message){std::lock_guard<std::mutex> lock(reportMutex);reportText=std::move(message);});});}
 void poll(){if(running){std::string message;{std::lock_guard<std::mutex> lock(reportMutex);message=std::move(reportText);reportText.clear();}if(!message.empty())status->SetWindowText(cs(message));if(work.wait_for(std::chrono::milliseconds(0))==std::future_status::ready){running=false;try{project=work.get();manager.saveProject(project);load();status->SetWindowText(cs(std::to_string(project["Links"].size())+" files; "+std::to_string(num(project,"PagesVisited"))+" pages visited; "+std::to_string(project.value("Errors",Json::array()).size())+" errors."));}catch(const std::exception& e){status->SetWindowText(cs(e.what()));}page();}}}
 BOOL OnCommand(WPARAM w,LPARAM l)override{if(projects&&LOWORD(w)==projects->GetDlgCtrlID()&&HIWORD(w)==CBN_SELCHANGE&&!running){Lock lock(manager.mutex);for(auto p:manager.state["Projects"])if(str(p,"Name")==text(projects)){project=p;load();break;}return TRUE;}if(preset&&LOWORD(w)==preset->GetDlgCtrlID()&&HIWORD(w)==CBN_SELCHANGE){static const char* filters[]={"zip pdf jpg png mp4 mp3","jpg jpeg png gif webp avif svg","mp4 mkv webm mp3 m4a flac ogg wav","zip 7z rar tar gz iso","pdf doc docx xls xlsx ppt pptx txt epub","*"};extensions->SetWindowText(cs(filters[std::clamp(preset->GetCurSel(),0,5)]));page();return TRUE;}return Form::OnCommand(w,l);}
 void OnCancel()override{if(running){cancellation->stop=true;status->SetWindowText(L"Stopping exploration...");return;}Form::OnCancel();}
public:GrabberDialog(Manager& m,CWnd* owner):Form("Site Grabber",686,478,owner),manager(m){project=blank();init=[this]{label("Saved project",14,15,103);projects=combo({},"",124,11,418);button("New",554,11,117,[this]{if(running)return;project=blank();step=0;load();});heading=label("",14,53,657,25);control(L"STATIC","",SS_ETCHEDHORZ,14,83,657,2);
 size_t start=controls.size();label("Project name",24,112,139);name=edit("",176,108,485);label("Starting web page",24,154,139);address=edit("",176,150,485);label("Template",24,196,139);preset=combo({"Files","Images","Audio and video files","Archives and installers","Documents","Offline website (ZIP)"},"Files",176,192,485);label("Collect linked files, or choose Offline website (ZIP) to save static pages, styles, images and fonts for offline browsing.",24,250,637,51);label("Offline archives use the selected queue. Extract the ZIP and open index.html. Scripts and forms are disabled in the saved pages.",24,319,637,48);for(size_t i=start;i<controls.size();++i)pages.resize(1),pages[0].push_back(controls[i].get());
 start=controls.size();label("File extensions",24,109,139);extensions=edit("",176,105,485);label("Link depth (0-5)",24,153,139);depth=edit("1",176,149,97);label("Page limit (1-100)",330,153,176);maximum=edit("20",548,149,113);label("Save files to",24,197,139);folder=edit("",176,193,367);button("Browse...",554,192,107,[this]{auto value=chooseFolder(this,wide(text(folder)));if(!value.empty())folder->SetWindowText(value.c_str());});label("Blank uses category folders. Extensions apply to file collection; offline pages follow the depth and page limits.",24,235,637,36);externalAssets=check("Include assets from other hosts (such as image and font CDNs)",false,24,279,637);label("Offline budget (MiB)",24,323,165);budget=edit("256",198,319,85);label("Up to 2,000 resources; 32 MiB per asset.",301,323,360);pages.resize(2);for(size_t i=start;i<controls.size();++i)pages[1].push_back(controls[i].get());
 start=controls.size();scan=button("Explore",14,98,106,[this]{exploreNow();});stop=button("Stop",130,98,90,[this]{if(cancellation)cancellation->stop=true;});button("Check all",230,98,98,[this]{for(int i=0;i<links->GetItemCount();++i)links->SetCheck(i,TRUE);});button("Uncheck all",338,98,108,[this]{for(int i=0;i<links->GetItemCount();++i)links->SetCheck(i,FALSE);});button("Errors...",555,98,117,[this]{std::string text;for(auto e:project.value("Errors",Json::array()))text+=str(e,"Url")+"\r\n"+str(e,"Message")+"\r\n\r\n";if(text.empty())text="No exploration errors recorded.";Form log("Exploration log",630,346,this);log.init=[&]{log.edit(text,13,13,604,280,true,true);log.button("Close",516,307,100,[&]{log.close();});};log.DoModal();});links=make<CListCtrl>(WS_TABSTOP|WS_BORDER|LVS_REPORT|LVS_SHOWSELALWAYS,14,135,658,210);links->SetExtendedStyle(LVS_EX_CHECKBOXES|LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);links->InsertColumn(0,L"File name",LVCFMT_LEFT,rect(0,0,210,0).Width());links->InsertColumn(1,L"Address",LVCFMT_LEFT,rect(0,0,600,0).Width());for(size_t i=start;i<controls.size();++i)explorationControls.push_back(controls[i].get());offlineHint=label("Add this website to the selected queue. UDM will save pages within your depth and page limits, plus their styles, images, fonts and media.\r\n\r\nThe result is one ZIP archive. Extract it, then open index.html. Scripts and form submissions are disabled. Missing or oversized resources are listed in the archive report.\r\n\r\nYou can pause and resume the job from the main window. Uncheck Download later to start when the queue is enabled.",24,122,637,219);label("Queue",14,361,55);queue=combo(queueNames(manager),"Main queue",77,357,296);later=check("Download later",true,396,359,276);pages.resize(3);for(size_t i=start;i<controls.size();++i)pages[2].push_back(controls[i].get());
 status=label("Create a project or choose a saved project.",14,401,658,24);back=button("< Back",229,439,95,[this]{if(step>0){--step;page();}});next=button("Next >",334,439,95,[this]{collect();Url url(str(project,"StartUrl"));if(trim(str(project,"Name")).empty())throw std::runtime_error("Enter a project name.");if(step==1)manager.saveProject(project);step=std::min(2,step+1);page();});add=button("Add selected",334,439,117,[this]{collect();int count=manager.addProject(project,text(queue),checked(later));status->SetWindowText(cs("Added "+std::to_string(count)+(offline()?" website archive":" files")+(checked(later)?", paused.":" to the queue.")));fillProjects();});button("Save project",14,439,132,[this]{if(running)return;collect();manager.saveProject(project);fillProjects();status->SetWindowText(L"Project saved.");});button("Close",565,439,107,[this]{OnCancel();});pulse=[this]{poll();};fillProjects();load();};}
 ~GrabberDialog(){if(cancellation)cancellation->stop=true;if(work.valid())work.wait();}
};
