#pragma once
#include "GrabberProject.hpp"
static void grabberActionChecks(const fs::path& root){
 auto base=root/L"grabber-actions";Manager manager(base/L"state");manager.state["Settings"]["DownloadFolder"]=utf8((base/L"downloads").wstring());manager.state["Settings"]["ProxyMode"]="Connect directly";manager.state["Settings"]["Retries"]=0;manager.state["Settings"]["Parallel"]=3;manager.state["Queues"][0]["Enabled"]=false;manager.save();
 auto project=modernGrabber("https://source.example/path?private=session");project["SaveMode"]="Categories";project["FileExclude"]="secret*";project["DownloadParallel"]=2;project["MetadataParallel"]=3;project["DownloadWhileExploring"]=true;project["Cookie"]="must not copy";project["ProtectedHeaders"]="must not copy";project["Links"]=Json::array({{{"Url","https://source.example/a.pdf"},{"DownloadId","old-id"}}});project["ExploreState"]={{"Pending",Json::array()}};
 auto saved=saveGrabberTemplate(manager,project,"Reports");auto options=saved["Settings"];
 check(str(options,"FileExclude")=="secret*"&&num(options,"MetadataParallel")==3&&yes(options,"DownloadWhileExploring"),"Templates retain filter, concurrency and automatic-download choices");
 check(!options.contains("StartUrl")&&!options.contains("Links")&&!options.contains("ExploreState")&&!options.contains("Id")&&!options.contains("Cookie")&&!options.contains("ProtectedHeaders"),"Templates omit source pages, captured links, identities, scan state and credentials");
 auto blank=modernGrabber("https://");blank["Name"]="Keep this project";auto originalId=str(blank,"Id");auto applied=applyGrabberTemplate(blank,saved,manager.state["Settings"]);
 check(str(applied,"StartUrl")=="https://"&&str(applied,"Name")=="Keep this project"&&str(applied,"Id")==originalId,"Template application preserves the new project identity and unfinished starting-page input");
 check(str(applied,"FileExclude")=="secret*"&&!applied.contains("ExploreState"),"Applying a template resets stale scan continuation");
 rejects([&]{saveGrabberTemplate(manager,project,"REPORTS");},"Duplicate template names are rejected case insensitively");rejects([&]{saveGrabberTemplate(manager,project,"bad\nname");},"Template labels reject control characters");
 auto replaced=project;replaced["FileInclude"]="*.zip";auto updated=saveGrabberTemplate(manager,replaced,"Archives",str(saved,"Id"));check(str(updated,"Id")==str(saved,"Id")&&grabberTemplates(manager).size()==1&&str(updated["Settings"],"FileInclude")=="*.zip","Replacing a template preserves its identity without creating a duplicate");
 {Manager reopened(base/L"state");check(grabberTemplates(reopened)==grabberTemplates(manager),"Saved templates survive an actual catalog reload");}
 auto before=manager.snapshot();{
  Handle lock(CreateFileW((manager.root/L"state.json").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));check(bool(lock),"Template rollback fixture holds the catalog read-only");rejects([&]{saveGrabberTemplate(manager,project,"Blocked");},"Template persistence failure is reported");check(manager.snapshot()==before,"Failed template save restores the entire in-memory catalog");rejects([&]{deleteGrabberTemplate(manager,str(saved,"Id"));},"Template delete persistence failure is reported");check(manager.snapshot()==before,"Failed template deletion preserves the template");
 }
 manager.editCategory("","Books","pdf","",utf8((base/L"books").wstring()));project["SaveMode"]="Category";project["SaveCategory"]="Books";auto book=saveGrabberTemplate(manager,project,"Book files");manager.editCategory("Books","Library","pdf","",utf8((base/L"books").wstring()));check(str(grabberTemplates(manager)[1]["Settings"],"SaveCategory")=="Library","Category rename updates reusable template destinations");
 auto categoryBefore=manager.snapshot();{Handle lock(CreateFileW((manager.root/L"state.json").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));rejects([&]{manager.deleteCategory("Library");},"Category delete failure is reported with templates present");check(manager.snapshot()==categoryBefore,"Category failure rolls templates and projects back together");}
 manager.deleteCategory("Library");check(str(grabberTemplates(manager)[1]["Settings"],"SaveCategory")=="Other","Category deletion gives saved templates a usable fallback");deleteGrabberTemplate(manager,str(book,"Id"));check(grabberTemplates(manager).size()==1&&manager.jobs.empty(),"Deleting a template leaves download jobs untouched");
 project["SaveMode"]="Categories";auto bad=project;bad["MetadataParallel"]=0;rejects([&]{saveGrabberTemplate(manager,bad,"Invalid");},"Template validation rejects zero metadata concurrency");bad=project;bad["DownloadParallel"]=17;rejects([&]{validateGrabberActions(bad);},"Project download concurrency is bounded");bad=project;bad["DownloadWhileExploring"]="yes";rejects([&]{validateGrabberActions(bad);},"Automatic download mode requires an explicit boolean");
 GrabberFilterFixture fixture;fixture.page("/start.html","<a href='/one.pdf'>one</a><a href='/next.html'>next</a>");fixture.file("/one.pdf","first-download");fixture.file("/next.html","<a href='/two.pdf'>two</a>","Content-Type: text/html\r\n",false,false,1800);fixture.file("/two.pdf","second-download");
 auto live=modernGrabber(fixture.url("/start.html"));live["FileInclude"]="*.pdf";live["DownloadWhileExploring"]=true;live["DownloadParallel"]=1;live["DownloadQueue"]="Main queue";Cancel scanCancel;std::atomic_int updates{0};auto work=std::async(std::launch::async,[&]{return runGrabber(manager,live,scanCancel,{},[&](const Json&){++updates;});});
 bool completeWhileScanning=false;JobPtr first;auto deadline=GetTickCount64()+10000;while(GetTickCount64()<deadline){manager.tick();{Lock lock(manager.mutex);first=grabberJob(manager,str(live,"Id"),fixture.url("/one.pdf"));if(first&&str(first->data,"Status")=="Complete"){completeWhileScanning=work.wait_for(std::chrono::milliseconds(0))!=std::future_status::ready;break;}}Sleep(10);}
 check(first&&completeWhileScanning&&readText(first->target())=="first-download","A matched file finishes while a later page is still being explored");
 if(!first){scanCancel.stop=true;work.get();throw std::runtime_error("Live Grabber fixture did not create its first download.");}{Lock lock(manager.mutex);check(!yes(manager.state["Queues"][0],"Enabled")&&yes(first->data,"GrabberImmediate"),"Explicit project downloads do not enable a stopped queue");}
 scanCancel.stop=true;auto stopped=work.get();check(yes(stopped,"ExplorationStopped")&&stopped["Links"].size()==1&&!stopped["ExploreState"]["Pending"].empty()&&updates>0,"Live scan cancellation retains published files and pending exploration");
 check(str(stopped["Links"][0],"DownloadId")==first->id()&&!yes(stopped,"ExplorationRunning"),"Incremental checkpoint records real job identities and terminal scan state");
 {Manager reopened(base/L"state");auto restored=grabberProject(reopened,str(live,"Id"));check(restored["Links"]==stopped["Links"]&&restored["ExploreState"]==stopped["ExploreState"],"Interrupted incremental scan survives a real catalog reload");}
 stopped["DownloadWhileExploring"]=false;Cancel resumedCancel;auto resumed=runGrabber(manager,stopped,resumedCancel);check(resumed["Links"].size()==2&&manager.jobs.size()==1,"Resuming in exploration-only mode finds new files without auto-starting them");
 setGrabberSelection(manager,str(live,"Id"),{{fixture.url("/one.pdf"),false},{fixture.url("/two.pdf"),true}});auto selected=grabberProject(manager,str(live,"Id"));check(!yes(selected["Links"][0],"Selected")&&yes(selected["Links"][1],"Selected"),"Selection changes affect only the requested project links");
 renameGrabberFile(manager,str(live,"Id"),fixture.url("/two.pdf"),"renamed.pdf");selected=grabberProject(manager,str(live,"Id"));check(str(selected["Links"][1],"SaveName")=="renamed.pdf"&&str(selected["Links"][1],"FileName")=="two.pdf","Output-name editing preserves the server name used for file filters");
 rejects([&]{renameGrabberFile(manager,str(live,"Id"),fixture.url("/two.pdf"),"../escape.pdf");},"Collected output names reject path traversal");rejects([&]{renameGrabberFile(manager,str(live,"Id"),fixture.url("/one.pdf"),"changed.pdf");},"Already-added files keep their download-owned path");
 check(manager.addProject(selected,"Main queue",true,true)==1,"Start checked adds only the selected new result");JobPtr second=grabberJob(manager,str(live,"Id"),fixture.url("/two.pdf"));deadline=GetTickCount64()+10000;while(GetTickCount64()<deadline){manager.tick();{Lock lock(manager.mutex);if(str(second->data,"Status")=="Complete")break;}Sleep(10);}
 {Lock lock(manager.mutex);check(str(second->data,"Status")=="Complete"&&second->target().filename()==L"renamed.pdf"&&readText(second->target())=="second-download","Start checked uses the edited name and publishes the exact content");}
 auto stats=grabberStatistics(manager,grabberProject(manager,str(live,"Id")));check(num(stats,"Files")==2&&num(stats,"Complete")==2&&num(stats,"Selected")==1&&num(stats,"Received")==29,"Project statistics track selection, completion and actual bytes");
 check(grabberByteSum(INT64_MAX-2,10)==INT64_MAX&&grabberByteSum(-10,7)==7,"Project byte totals saturate safely instead of overflowing");
 auto roots=grabberTree(resumed);std::set<std::string> nodeIds;bool validParents=true;for(const auto& node:roots){validParents&=str(node,"Parent").empty()||nodeIds.count(str(node,"Parent"));nodeIds.insert(str(node,"Id"));}check(validParents&&nodeIds.count("page:"+fixture.url("/next.html")),"Site tree preserves parent-before-child referring-page ancestry");
 check(grabberRows(resumed,"page",fixture.url("/start.html"))==std::vector<size_t>{0}&&grabberRows(resumed,"page",fixture.url("/next.html"))==std::vector<size_t>{1},"Referring-page selection displays only its collected files");
 auto folders=modernGrabber("https://example.test/");folders["Links"]=Json::array({{{"Url","https://example.test/docs/a.pdf"}},{{"Url","https://example.test/docs/nested/b.pdf"}},{{"Url","https://example.test/docs-other/c.pdf"}}});check(grabberRows(folders,"folder","https://example.test/docs/")==std::vector<size_t>({0,1}),"Folder-tree selection includes descendants and excludes similarly named siblings");folders["PageParents"]={{"https://example.test/a","https://example.test/b"},{"https://example.test/b","https://example.test/a"}};check(grabberTree(folders).size()<20,"Malformed cyclic page ancestry cannot loop the tree builder");
 // Stop must stay stopped when subsequent automatic checkpoints revisit results.
 auto paused=modernGrabber(fixture.url("/start.html"));paused["Links"]=Json::array({{{"Url",fixture.url("/two.pdf")},{"FileName","two.pdf"},{"Size",15}}});paused["DownloadParallel"]=1;manager.addProject(paused,"Main queue",true,true);auto pending=grabberJob(manager,str(paused,"Id"),fixture.url("/two.pdf"));manager.pause(pending);manager.addProject(paused,"Main queue",false,true,false);check(str(pending->data,"Status")=="Paused"&&!yes(pending->data,"GrabberImmediate"),"New-file-only auto-start never restarts an explicitly stopped result");
 // A mid-batch destination failure also rolls existing resumed jobs back.
 auto rollback=paused;rollback["SaveMode"]="Folder";rollback["Folder"]=utf8((base/L"rollback").wstring());rollback["OriginalSubfolders"]=true;fs::create_directories(base/L"rollback");writeBytes(base/L"rollback/block",Bytes{'x'});rollback["Links"].push_back({{"Url",fixture.url("/block/three.pdf")},{"FileName","three.pdf"}});{Lock lock(manager.mutex);manager.save();auto stateBefore=manager.snapshot();auto diskBefore=readText(manager.root/L"state.json");pending->sessionLimit=17;rejects([&]{manager.addProject(rollback,"Main queue",false,true);},"An invalid later destination aborts a mixed resume/add batch");check(manager.snapshot()==stateBefore&&pending->sessionLimit==17&&readText(manager.root/L"state.json")==diskBefore,"Failed project start restores existing statuses, limits, jobs and durable history");}
 // Edits made after the first checkpoint must survive later crawler publications.
 manager.editCategory("","Live category","pdf","",utf8((base/L"live-category").wstring()));auto editable=modernGrabber(fixture.url("/start.html"));editable["SaveMode"]="Category";editable["SaveCategory"]="Live category";editable["DownloadWhileExploring"]=true;bool changed=false;Cancel editingCancel;
 auto edited=runGrabber(manager,editable,editingCancel,{},[&](const Json& output){if(changed||output["Links"].empty())return;changed=true;setGrabberSelection(manager,str(editable,"Id"),{{fixture.url("/one.pdf"),false}});manager.editCategory("Live category","Renamed live category","pdf","",utf8((base/L"live-category").wstring()));auto current=grabberProject(manager,str(editable,"Id"));current["DownloadWhileExploring"]=false;manager.saveProject(current);});
 check(changed&&edited["Links"].size()==2&&!yes(edited["Links"][0],"Selected")&&!yes(edited,"DownloadWhileExploring"),"Selection edits and disabling automatic downloads survive later scan checkpoints");
 check(str(edited,"SaveCategory")=="Renamed live category"&&!grabberJob(manager,str(editable,"Id"),fixture.url("/two.pdf")),"A category renamed during scanning stays valid and later files respect the disabled mode");
 for(auto job:manager.jobs)if(str(job->data,"ProjectId")==str(editable,"Id"))manager.pause(job);
 auto renamed=modernGrabber(fixture.url("/start.html"));bool nameChanged=false;Cancel renameCancel;auto renamedOutput=runGrabber(manager,renamed,renameCancel,{},[&](const Json& output){if(nameChanged||output["Links"].empty())return;nameChanged=true;renameGrabberFile(manager,str(renamed,"Id"),fixture.url("/one.pdf"),"live-edited.pdf");});
 check(nameChanged&&str(renamedOutput["Links"][0],"SaveName")=="live-edited.pdf","A filename edited while scanning is retained in the finished project");
 auto enable=modernGrabber(fixture.url("/start.html"));bool enabled=false;Cancel enableCancel;auto enabledOutput=runGrabber(manager,enable,enableCancel,{},[&](const Json& output){if(enabled||output["Links"].empty())return;enabled=true;auto current=grabberProject(manager,str(enable,"Id"));current["DownloadWhileExploring"]=true;manager.saveProject(current);});
 check(enabled&&yes(enabledOutput,"DownloadWhileExploring")&&grabberJob(manager,str(enable,"Id"),fixture.url("/one.pdf"))&&grabberJob(manager,str(enable,"Id"),fixture.url("/two.pdf")),"Enabling automatic downloads during a scan adds both retained and newly discovered selections");
 auto queuedStats=grabberStatistics(manager,enabledOutput);check(num(queuedStats,"TotalBytes")==29&&num(queuedStats,"UnknownSizes")==0,"Known file metadata remains visible while new downloads await their first request");
 for(auto job:manager.jobs)if(str(job->data,"ProjectId")==str(enable,"Id"))manager.pause(job);
 auto checkpoint=modernGrabber(fixture.url("/start.html"));Cancel checkpointCancel;int downstream=fixture.count("/next.html");rejects([&]{exploreWithUpdates(checkpoint,manager.state["Settings"],checkpointCancel,{},[](Json&){throw std::runtime_error("Fixture checkpoint failure");});},"A mid-scan checkpoint failure is propagated instead of being recorded as a page error");check(fixture.count("/next.html")==downstream,"A failed mid-scan checkpoint stops before requesting the next page");
 // Storage errors must stop the crawler rather than being mistaken for a bad page.
 auto failure=modernGrabber(fixture.url("/start.html"));Cancel failedCancel;int prior=fixture.count("/next.html");{Handle lock(CreateFileW((manager.root/L"state.json").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));rejects([&]{runGrabber(manager,failure,failedCancel);},"Initial incremental checkpoint failure stops exploration before network requests");}check(fixture.count("/next.html")==prior,"Persistence failure does not continue requesting downstream pages");
 // Explicit starts must neither exceed project limits nor launch unrelated queue work.
 Fixture payload;auto group=modernGrabber(payload.url("/index.html"));group["FileInclude"]="*.bin";group["DownloadParallel"]=1;for(const char* path:{"/one.bin","/two.bin","/three.bin"})group["Links"].push_back({{"Url",payload.url(path)},{"FileName",std::string(path+1)}});auto unrelated=manager.add(payload.url("/unrelated.bin"),"","unrelated.bin","Main queue",true);manager.addProject(group,"Main queue",false,true);int peak=0;deadline=GetTickCount64()+15000;bool allComplete=false;
 while(GetTickCount64()<deadline){manager.tick();{Lock lock(manager.mutex);int active=0,complete=0;for(auto job:manager.jobs)if(str(job->data,"ProjectId")==str(group,"Id")){active+=manager.isActive(job);complete+=str(job->data,"Status")=="Complete";}peak=std::max(peak,active);allComplete=complete==3;if(allComplete)break;}Sleep(5);}
 check(allComplete&&peak==1,"Immediate project scheduler respects the configured simultaneous-file limit");check(str(unrelated->data,"Status")=="Paused"&&!yes(manager.state["Queues"][0],"Enabled"),"Project starts leave unrelated queued downloads and queue settings unchanged");
 for(auto job:manager.jobs)if(str(job->data,"ProjectId")==str(group,"Id"))check(fs::file_size(job->target())==payload.payload.size(),"Immediate project transfer preserves complete HTTP payload length");
 manager.stop();
}
