#pragma once
static void guiChecks(const fs::path& root,Fixture& fixture){
 Json sample={{"FileName","Résumé.ISO"},{"Description","Installation media"},{"Url","https://files.example.com/image.iso"},{"DownloadPage","https://example.com/downloads"}};
 auto search=Json{{"Text","résumé"},{"FileName",true}};check(matchesDownload(sample,search),"Find performs Unicode case-insensitive filename matching");search["MatchCase"]=true;check(!matchesDownload(sample,search),"Find honors case-sensitive matching");search["MatchCase"]=false;search["WholeString"]=true;check(!matchesDownload(sample,search),"Find whole-string does not match a filename fragment");search["Text"]="résumé.iso";check(matchesDownload(sample,search),"Find whole-string matches the full filename");search={{"Text","media"},{"FileName",false},{"Description",true}};check(matchesDownload(sample,search),"Find description field is independently searchable");search["Description"]=false;check(!matchesDownload(sample,search),"Find does not search unchecked fields");search={{"Text","example.com/downloads"},{"FileName",false},{"Address",true}};check(matchesDownload(sample,search),"Find searches the parent web page");
 Headers headers={{"aUtHoRiZaTiOn","Basic "+b64(Bytes{'u',':','p',':','2'})},{"referer","https://origin.example/ref"},{"Cookie","session=fixture"}};check(basicLogin(headers)==std::make_pair(std::string("u"),std::string("p:2")),"Properties decodes case-insensitive Basic credentials and preserves password colons");setHeader(headers,"Referer","https://new.example/source");check(headers.size()==3&&headerValue(headers,"REFERER")=="https://new.example/source"&&headerValue(headers,"cookie")=="session=fixture","Editing Referer replaces casing aliases and preserves unrelated headers");sample["ProtectedHeaders"]=protect(legacyDictionary(Json(headers)).dump());search["Text"]="new.example";check(matchesDownload(sample,search),"Find searches protected Referer without changing stored headers");search["Text"]="";check(!matchesDownload(sample,search),"Empty Find is not a match-all request");
 Manager m(root/L"gui-state");auto prefs=m.state["Settings"];prefs["DownloadFolder"]=utf8((root/L"gui-files").wstring());prefs["CategoryFolders"]=false;m.setSettings(prefs);
 auto categoryFolder=utf8((root/L"research-files").wstring());m.editCategory("","Research","iso pdf","example.com",categoryFolder);auto job=m.add("https://files.example.com/data.iso");check(str(job->data,"Category")=="Research"&&str(job->data,"Folder")==categoryFolder,"Category rules apply extensions, subdomain and saved folder to new downloads");auto mismatch=m.add("https://elsewhere.invalid/data.iso");check(str(mismatch->data,"Category")!="Research","Category host rule does not match unrelated sites");auto target=job->target();m.editCategory("Research","Reference","iso pdf","example.com",categoryFolder);check(str(job->data,"Category")=="Reference"&&job->target()==target,"Renaming a category updates existing records without moving files");
 rejects([&]{m.editCategory("Reference","Documents","pdf","","");},"Category rename rejects built-in name collisions");rejects([&]{m.editCategory("Documents","Renamed","pdf","","");},"Built-in category names stay stable");rejects([&]{m.editCategory("Reference","Reference","pdf","example.com/path","");},"Category editor rejects a URL path in the host field");rejects([&]{m.editCategory("Reference","Reference","pdf","","relative");},"Category destination must be absolute");
 auto before=m.snapshot();auto blocker=m.root/L"state.json.tmp";fs::create_directory(blocker);rejects([&]{m.editCategory("Reference","Rollback","pdf","","");},"Category rename reports a persistence failure");check(str(job->data,"Category")=="Reference"&&m.state["Settings"]["CustomCategories"]==before["Settings"]["CustomCategories"],"Failed category rename rolls back both preferences and download metadata");fs::remove(blocker);m.deleteCategory("Reference");check(str(job->data,"Category")=="Other"&&job->target()==target&&m.state["Settings"]["CategoryRules"].empty(),"Deleting a custom category reassigns records and removes rules without moving files");rejects([&]{m.deleteCategory("Other");},"Built-in category deletion is rejected");
 auto q=defaultQueue("Later");q["Enabled"]=false;m.setQueue(q);m.configure(job,{{"Queue","Later"},{"QueueMember",false},{"Connections",16},{"LimitKbps",512},{"DownloadPage","https://example.com/downloads"},{"ProtectedHeaders",protect(legacyDictionary(Json(headers)).dump())}});check(str(job->data,"Queue")=="Later"&&!yes(job->data,"QueueMember")&&num(job->data,"Connections")==16&&num(job->data,"LimitKbps")==512&&basicLogin(readHeaders(job->data)).second=="p:2","Unfinished Properties saves queue, limits, source page and encrypted login");check(str(job->data,"ProtectedHeaders").find("session=fixture")==std::string::npos,"Properties does not store captured credentials in plaintext");
 auto unchanged=job->data;rejects([&]{m.configure(job,{{"Queue","Missing queue"}});},"Properties rejects a removed queue");rejects([&]{m.configure(job,{{"DownloadPage","ftp://example.com/page"}});},"Properties rejects an unsupported parent-page scheme");check(job->data==unchanged,"Rejected properties edits leave the full download record unchanged");
 m.configure(job,{{"Url","https://different.example/data.iso"}});auto cross=readHeaders(job->data);check(headerValue(cross,"Cookie").empty()&&headerValue(cross,"Authorization").empty()&&headerValue(cross,"Referer").empty()&&yes(job->data,"RefreshPendingValidation"),"Changing Properties to another origin clears account headers and requires resume validation");
 auto completed=m.add(fixture.url("/range"),"","properties.bin");transfer(m,completed,std::make_shared<Cancel>());auto hash=fileHash(completed->target());m.updateCompleted(completed,{{"Category","Documents"},{"Queue","Later"},{"Connections",4},{"LimitKbps",100},{"Description","Reviewed"}});check(str(completed->data,"Category")=="Documents"&&str(completed->data,"Queue")=="Later"&&num(completed->data,"Connections")==4&&fileHash(completed->target())==hash,"Completed advanced Properties edits metadata without changing file bytes");rejects([&]{m.updateCompleted(completed,{{"ExpectedSha256","invalid"}});},"Completed advanced Properties validates the expected hash");auto copy=m.redownload(completed);check(str(copy->data,"Category")=="Documents"&&num(copy->data,"LimitKbps")==100,"Redownload inherits completed advanced properties");
 fs::create_directory(blocker);rejects([&]{m.deleteQueue("Later");},"Queue deletion reports a persistence failure");check(str(job->data,"Queue")=="Later"&&m.state["Queues"].size()==2,"Failed queue deletion restores membership and the queue list");fs::remove(blocker);m.deleteQueue("Later");check(str(job->data,"Queue")=="Main queue"&&m.state["Queues"].size()==1,"Queue deletion reassigns records without deleting downloads");
 prefs=m.state["Settings"];prefs["ToolbarOrder"]={10,0,1,2,3,4,5,6,7,8,9};prefs["ToolbarHidden"]={5};prefs["ToolbarStyle"]="Icons only";prefs["ToolbarSize"]="Small";prefs["ProgressStartMode"]="Small size";prefs["ProgressInformationTab"]=false;m.setSettings(prefs);{Manager reopened(m.root);check(reopened.state["Settings"]["ToolbarOrder"]==prefs["ToolbarOrder"]&&str(reopened.state["Settings"],"ToolbarStyle")=="Icons only"&&!yes(reopened.state["Settings"],"ProgressInformationTab",true),"Toolbar order, style and progress preferences persist across restart");}m.stop();
}
