#pragma once
#include <string>
#include <vector>
namespace udm {
inline const std::vector<std::string>& helpTopicTitles(){
 static const std::vector<std::string> titles={"Help contents","Tutorials","Scheduler and queues","Grabber Help"};return titles;
}
inline std::string helpTopicText(size_t topic){
 static const char* texts[]={
"UDM HELP CONTENTS\r\n\r\nAdd a download\r\nUse Tasks > Add new download (Ctrl+N). Review the address and destination before starting. Downloads that need server authentication can use the authorization fields in Download File Info or Properties.\r\n\r\nControl a download\r\nSelect a row, then use File > Download Now to resume, or Stop Download to stop it and close its progress window. Downloads > Pause All keeps progress windows open; Stop All closes unfinished progress windows. Resuming from saved bytes depends on server support and the remote file remaining unchanged.\r\n\r\nProperties and files\r\nRight-click a download for Properties, Refresh download address, Show progress, Open, Open folder, Move/Rename, or ZIP contents. By default, double-clicking a completed download opens Properties. The context menu can change completed-download double-click behavior.\r\n\r\nExpired addresses\r\nUse Refresh download address for a supported download and follow its review. A replacement must represent the intended file; do not assume any new link is safe to append to existing partial data.\r\n\r\nAppearance and recovery\r\nView controls categories, sorting, columns, font and tray icon. Ctrl+Shift+F toggles the quick filter. Backup and recovery is under Tasks > Export; pause active downloads first and review the exact restore destinations.\r\n\r\nSelect another topic above, or use Previous / Next. Help is available offline.",
"TUTORIALS\r\n\r\nDownload a file\r\n1. Copy the direct file address.\r\n2. Choose Tasks > Add new download, or press Ctrl+N.\r\n3. Review the filename, destination, credentials and any confirmation prompt.\r\n4. Start the download and inspect its progress window.\r\n5. After completion, right-click the row to open the file or its folder.\r\n\r\nPause and resume\r\nUse Pause in the progress window to retain that window. Use Stop Download in File to stop a selected transfer and close its window. Select the stopped row and choose Download Now to resume. A server may require a restart if the original file changed or range requests are unavailable.\r\n\r\nLimit bandwidth\r\nDownloads > Speed Limiter provides Turn on, Turn off and Settings. Turning off remembers the last selected rate. Settings explains whether the configured limit is shared across downloads or applies to each one.\r\n\r\nCapture from a browser\r\nEnable UDM Browser Integration in your browser. On a supported video page, start playback and use UDM's panel to select an available stream. Availability depends on the site and stream type. If the panel has no supported file or playlist, refreshing alone does not guarantee a downloadable stream.\r\n\r\nFind a record\r\nUse Downloads > Find (Ctrl+F), then F3 for the next match. Use View > Arrange files to sort the list without losing the selected download.",
"SCHEDULER AND QUEUES\r\n\r\nCreate and select queues\r\nRight-click the queue tree to create a queue. Right-click downloads to move them to a queue or remove their queue membership. Open Downloads > Scheduler to edit queue settings.\r\n\r\nRun a named queue\r\nDownloads > Start queue and Stop queue list the current queue names. Their first Start or Stop entry applies to the queue selected in the tree; a named entry targets that queue directly.\r\n\r\nSchedules\r\nReview the start and stop time, days, parallel-file count, retry settings and optional repetition before enabling a schedule. Check whether the queue is configured for a one-time run or a recurring window. Starting a queue manually is different from merely editing its schedule.\r\n\r\nCompletion actions\r\nOnly select a completion action you intend, such as opening a file or powering down. Review any confirmation/countdown before it executes. Queue actions depend on the queue being complete; they should not be used as a substitute for checking failed downloads.\r\n\r\nIf saving fails\r\nQueue Start/Stop reports the save error. The previous queue state is retained when the catalog cannot be saved. Resolve the storage problem and retry. Do not assume a queue started just because its menu command was clicked.",
"GRABBER HELP\r\n\r\nStart a project\r\nTasks > Run site grabber opens the project workflow. Give the project a name and starting page, choose where to save, then configure explorer and file filters.\r\n\r\nLimit exploration\r\nUse site/subdomain, depth, page-count and file-size limits to keep the scan within the pages and files you want. Review whether external pages or assets should be included. Narrow filters before starting a large scan.\r\n\r\nReview results\r\nExplore first, then review the discovered links and selected files before downloading. Page links and downloadable files are different: a site can expose navigation without a directly downloadable media file.\r\n\r\nResume work\r\nSaved projects and supported exploration state can be reopened. A stopped scan may offer resume when its saved state and limits permit it. Review changed filters and destination choices before resuming.\r\n\r\nBrowser sessions and limitations\r\nSome sites require a browser login or create links dynamically. Use the available project/browser workflow when applicable. Not every rendered page, protected stream or platform is supported. A scan result is not proof that a server will permit the final transfer.\r\n\r\nManage results\r\nUse project filters and selections to avoid downloading unwanted files. Existing download records can be managed from the main list after they have been admitted."
 };
 return topic<4?texts[topic]:texts[0];
}
}
