#include "Core.hpp"
#include "HlsRecording.hpp"
#include "MediaStorage.hpp"
#include <iostream>
#include <fstream>
#include <future>
#include "StreamProgress.hpp"
using namespace udm;
static Json checks=Json::array();
static void check(bool ok,const std::string& name){checks.push_back({{"name",name},{"passed",ok}});}
template<class F>static void rejects(F f,const std::string& name){bool rejected=false;try{f();}catch(const std::exception&){rejected=true;}check(rejected,name);}
#include "LiveHlsTracksChecks.hpp"
#include "HlsRecordingChecks.hpp"
#include "LiveHlsChecks.hpp"
int wmain(int argc,wchar_t** argv){
 if(argc!=2||fs::exists(argv[1]))return 2;fs::path root=fs::absolute(argv[1]);fs::create_directories(root);WSADATA ws{};WSAStartup(MAKEWORD(2,2),&ws);CoInitializeEx(nullptr,COINIT_APARTMENTTHREADED);std::string error;
 try{
  hlsRecordingChecks(root);liveHlsChecks(root);liveHlsTracksChecks(root);std::map<std::string,std::string> base;
  for(const std::wstring kind:{L"video",L"audio"})for(const auto& entry:fs::directory_iterator(root/L"live-track-source"/kind))if(entry.is_regular_file())base["/"+utf8(kind)+"/"+utf8(entry.path().filename().wstring())]=readText(entry.path());
  base["/captions.m3u8"]="#EXTM3U\n#EXT-X-TARGETDURATION:2\n#EXT-X-MEDIA-SEQUENCE:77\n#EXTINF:2,\ncaption0.vtt\n#EXTINF:2,\ncaption1.vtt\n#EXT-X-ENDLIST\n";
  const std::string header="WEBVTT\nX-TIMESTAMP-MAP=LOCAL:00:00:00.000,MPEGTS:0\n\n";
  base["/caption0.vtt"]=header+"00:00:00.500 --> 00:00:01.500\nHola\n\n00:00:01.500 --> 00:00:02.500\nBoundary\n\n";
  base["/caption1.vtt"]=header+"00:00:01.500 --> 00:00:02.500\nBoundary\n\n00:00:02.500 --> 00:00:03.500\nMundo\n\n";
  Manager manager(root/L"data");manager.state["Settings"]["CategoryFolders"]=false;manager.state["Settings"]["DownloadFolder"]=utf8((root/L"outputs").wstring());manager.state["Settings"]["Retries"]=0;Cancel cancel;
  auto receive=[&](LiveTracksFixture& server,const std::string& name,bool audio){Json tracks=Json::array({{{"kind","video"},{"playlist",server.url("/video/source.m3u8")},{"segments",Json::array({{{"url",server.url("/video/part0.m4s")}}})}}});if(audio)tracks.push_back({{"kind","audio"},{"playlist",server.url("/audio/source.m3u8")},{"segments",Json::array({{{"url",server.url("/audio/part0.m4s")}}})}});tracks.push_back({{"kind","subtitle"},{"playlist",server.url("/captions.m3u8")},{"segments",Json::array({{{"url",server.url("/caption0.vtt")}}})}});return manager.receive({{"action","adaptive"},{"url",server.url("/player")},{"filename",name},{"plan",{{"type","hls"},{"live",true},{"height",180},{"audioExpected",audio},{"container","mp4"},{"subtitleName","Spanish captions"},{"subtitleLanguage","es-MX"},{"tracks",tracks}}}});};
  auto inspect=[&](JobPtr job,const std::string& name,bool audio){auto info=Json::parse(execute(appDir()/L"tools"/L"ffprobe.exe",{L"-v",L"error",L"-show_streams",L"-of",L"json",job->target().wstring()},30,cancel));int videos=0,audios=0,subtitles=0;for(const auto& stream:info["streams"]){videos+=str(stream,"codec_type")=="video";audios+=str(stream,"codec_type")=="audio";if(str(stream,"codec_type")=="subtitle"){++subtitles;check(str(stream,"codec_name")=="mov_text"&&str(stream["tags"],"language")=="spa"&&str(stream["tags"],"handler_name")=="Spanish captions",name+" preserves subtitle format, name and language");}}check(videos==1&&audios==(audio?1:0)&&subtitles==1,name+" contains exactly selected tracks");auto text=execute(appDir()/L"tools"/L"ffmpeg.exe",{L"-v",L"error",L"-i",job->target().wstring(),L"-map",L"0:s:0",L"-f",L"webvtt",L"pipe:1"},30,cancel);atomicText(root/wide(name+".vtt"),text);execute(appDir()/L"tools"/L"ffmpeg.exe",{L"-v",L"error",L"-xerror",L"-i",job->target().wstring(),L"-f",L"null",L"-"},30,cancel);check(str(job->data,"Status")=="Complete",name+" fully decodes and completes");return text;};
  for(bool audio:{false,true}){LiveTracksFixture server(base);auto job=receive(server,audio?"three-tracks":"two-tracks",audio);adaptiveTransfer(manager,job,std::make_shared<Cancel>());auto text=inspect(job,audio?"three-tracks":"two-tracks",audio);check(text.find("00:00.500 --> 00:01.500")!=std::string::npos&&text.find("00:02.500 --> 00:03.500")!=std::string::npos,"Independent subtitle sequence numbers preserve cue times");check(text.find("Boundary")==text.rfind("Boundary"),"Repeated boundary cue is included once");check(fs::is_empty(mediaWorkingDirectory(manager,job)/L"live-hls"),"Subtitle publication removes only its completed recording cache");}
  {auto files=base;auto& video=files["/video/source.m3u8"];video.erase(video.find("#EXT-X-ENDLIST"));video+="#EXT-X-DISCONTINUITY\n#EXTINF:2,\npart0.m4s\n#EXTINF:2,\npart1.m4s\n#EXT-X-ENDLIST\n";auto& captions=files["/captions.m3u8"];captions.erase(captions.find("#EXT-X-ENDLIST"));captions+="#EXT-X-DISCONTINUITY\n#EXTINF:2,\nrestart.vtt\n#EXTINF:2,\nlast.vtt\n#EXT-X-ENDLIST\n";files["/restart.vtt"]=header+"00:00:00.500 --> 00:00:01.500\nRestart\n\n";files["/last.vtt"]=header+"00:00:02.500 --> 00:00:03.500\nLast\n\n";LiveTracksFixture server(files);auto job=receive(server,"discontinuity",false);adaptiveTransfer(manager,job,std::make_shared<Cancel>());auto text=inspect(job,"discontinuity",false);check(text.find("00:04.500 --> 00:05.500")!=std::string::npos&&text.find("00:06.500 --> 00:07.500")!=std::string::npos,"Subtitle media clock reset maps to the continuous saved timeline");}
  {auto files=base;files["/caption0.vtt"]="WEBVTT\nX-TIMESTAMP-MAP=LOCAL:00:00:10.000,MPEGTS:0\n\n00:00:10.500 --> 00:00:11.500\nMapped\n\n";LiveTracksFixture server(files);auto job=receive(server,"timestamp-map",false);adaptiveTransfer(manager,job,std::make_shared<Cancel>());auto text=inspect(job,"timestamp-map",false);check(text.find("00:00.500 --> 00:01.500")!=std::string::npos&&text.find("Mapped")!=std::string::npos,"WebVTT local clock is synchronized by its MPEGTS timestamp map");}
  {auto files=base;for(const auto& path:{"/video/source.m3u8","/audio/source.m3u8","/captions.m3u8"})files[path].erase(files[path].find("#EXT-X-ENDLIST"));JobPtr paused;
   {LiveTracksFixture server(files);paused=receive(server,"pause-restart",true);paused->data["Status"]="Downloading";auto control=std::make_shared<Cancel>();control->deadline=GetTickCount64()+15000;auto task=std::async(std::launch::async,[&]{try{adaptiveTransfer(manager,paused,control);return false;}catch(const Cancelled&){return true;}});bool ready=false;auto until=GetTickCount64()+10000;
    while(GetTickCount64()<until){{Lock lock(manager.mutex);ready=real(paused->data,"LiveCapturedSeconds")>=3.9;}if(ready)break;Sleep(10);}control->stop=true;check(task.get()&&ready&&!fs::exists(paused->target()),"Pause retains all three live tracks without publishing output");paused->data["Status"]="Paused";manager.save();}
   Manager restored(manager.root);JobPtr saved;for(auto candidate:restored.jobs)if(candidate->id()==paused->id())saved=candidate;if(!saved)throw std::runtime_error("Missing restored subtitle job");requestLiveHlsFinish(restored,saved);adaptiveTransfer(restored,saved,std::make_shared<Cancel>());auto text=inspect(saved,"pause-restart",true);check(text.find("Hola")!=std::string::npos&&text.find("Mundo")!=std::string::npos,"Catalog reload and Stop and Save recover subtitle cues with the source offline");
  }
  JobPtr retained;{LiveTracksFixture server(base);retained=receive(server,"offline-retry",true);retained->data["ExpectedSha256"]=std::string(64,'0');rejects([&]{adaptiveTransfer(manager,retained,std::make_shared<Cancel>());},"Failed publication retains live subtitle receipts");check(!fs::exists(retained->target()),"Failed validation publishes no video");}retained->data["ExpectedSha256"]="";adaptiveTransfer(manager,retained,std::make_shared<Cancel>());inspect(retained,"offline-retry",true);check(fs::is_empty(mediaWorkingDirectory(manager,retained)/L"live-hls"),"Offline subtitle retry reloads sealed receipts and cleans them after success");
  {auto files=base;files["/header.vtt"]=header;files["/captions.m3u8"].insert(files["/captions.m3u8"].find("#EXTINF"),"#EXT-X-MAP:URI=\"header.vtt\"\n");for(const auto& path:{"/caption0.vtt","/caption1.vtt"})files[path].erase(0,header.size());LiveTracksFixture server(files);auto job=receive(server,"separate-header",true);adaptiveTransfer(manager,job,std::make_shared<Cancel>());auto text=inspect(job,"separate-header",true);check(text.find("Hola")!=std::string::npos&&text.find("00:02.500 --> 00:03.500")!=std::string::npos,"Separate WebVTT initialization preserves caption text and clock");}
  {auto files=base;files["/header.vtt"]=header;files["/header2.vtt"]="WEBVTT\nX-TIMESTAMP-MAP=LOCAL:00:00:10.000,MPEGTS:0\n\n";files["/captions.m3u8"]="#EXTM3U\n#EXT-X-TARGETDURATION:2\n#EXT-X-MEDIA-SEQUENCE:77\n#EXT-X-MAP:URI=\"header.vtt\"\n#EXTINF:2,\ncaption0.vtt\n#EXT-X-MAP:URI=\"header2.vtt\"\n#EXTINF:2,\ncaption1.vtt\n#EXT-X-ENDLIST\n";files["/caption0.vtt"].erase(0,header.size());files["/caption1.vtt"]="00:00:12.500 --> 00:00:13.500\nChanged map\n\n";JobPtr job;{LiveTracksFixture server(files);job=receive(server,"changed-header-offline",true);job->data["ExpectedSha256"]=std::string(64,'0');rejects([&]{adaptiveTransfer(manager,job,std::make_shared<Cancel>());},"Mapped subtitles retain receipts after failed output validation");}job->data["ExpectedSha256"]="";manager.save();Manager restored(manager.root);JobPtr saved;for(auto candidate:restored.jobs)if(candidate->id()==job->id())saved=candidate;if(!saved)throw std::runtime_error("Missing mapped subtitle job");adaptiveTransfer(restored,saved,std::make_shared<Cancel>());auto text=inspect(saved,"changed-header-offline",true);check(text.find("00:02.500 --> 00:03.500")!=std::string::npos&&text.find("Changed map")!=std::string::npos,"Changed initialization clocks survive catalog reload with server offline");}
  for(const std::string badMap:{"invalid-header","cue-in-header","oversized-header"}){auto files=base;files["/captions.m3u8"].insert(files["/captions.m3u8"].find("#EXTINF"),"#EXT-X-MAP:URI=\"header.vtt\"\n");files["/header.vtt"]=badMap=="invalid-header"?"not WebVTT":badMap=="cue-in-header"?base.at("/caption0.vtt"):std::string(2*1024*1024+1,'x');for(const auto& path:{"/caption0.vtt","/caption1.vtt"})files[path].erase(0,header.size());LiveTracksFixture server(files);auto job=receive(server,badMap,false);rejects([&]{adaptiveTransfer(manager,job,std::make_shared<Cancel>());},badMap+" initialization is rejected");check(!fs::exists(job->target()),badMap+" cannot publish output");}
  for(const std::string bad:{"malformed","oversized","initialization"}){auto files=base;if(bad=="malformed")files["/caption0.vtt"]="not WebVTT";else if(bad=="oversized")files["/caption0.vtt"]=std::string(2*1024*1024+1,'x');else files["/captions.m3u8"].insert(files["/captions.m3u8"].find("#EXTINF"),"#EXT-X-MAP:URI=\"header.vtt\"\n");LiveTracksFixture server(files);auto job=receive(server,"bad-"+bad,false);rejects([&]{adaptiveTransfer(manager,job,std::make_shared<Cancel>());},bad+" live subtitle input is rejected");check(!fs::exists(job->target()),bad+" subtitles cannot publish misleading output");}

  // Recorded HLS must apply its separate WebVTT header to every cue segment.
  for(const std::string mode:{"recorded-map","recorded-map-offline","recorded-bad-map"}){
   auto files=base;files["/header.vtt"]=mode=="recorded-bad-map"?base.at("/caption0.vtt"):header;
   for(const auto& path:{"/caption0.vtt","/caption1.vtt"})files[path].erase(0,header.size());
   JobPtr job;
   {LiveTracksFixture server(files);job=receive(server,mode,true);auto plan=Json::parse(reveal(str(job->data,"ProtectedAdaptive")));plan["live"]=false;
    for(auto& track:plan["tracks"]){auto kind=str(track,"kind");track.erase("playlist");track["segments"]=Json::array();if(kind=="subtitle"){track["webVttHeader"]=true;track["segments"].push_back({{"url",server.url("/header.vtt")}});for(int i=0;i<2;++i)track["segments"].push_back({{"url",server.url("/caption"+std::to_string(i)+".vtt")},{"timeline",i*2}});}else{track["segments"].push_back({{"url",server.url("/"+kind+"/init.mp4")}});for(int i=0;i<2;++i)track["segments"].push_back({{"url",server.url("/"+kind+"/part"+std::to_string(i)+".m4s")}});}}
    if(mode=="recorded-map"){
     auto invalid=plan;invalid["tracks"][0]["webVttHeader"]=true;rejects([&]{validateAdaptive(invalid);},"Video tracks cannot declare a WebVTT header");
     invalid=plan;invalid["tracks"].back()["webVttHeader"]="true";rejects([&]{validateAdaptive(invalid);},"WebVTT header selection requires a boolean");
     invalid=plan;invalid["tracks"].back()["segments"]=Json::array({invalid["tracks"].back()["segments"][0]});rejects([&]{validateAdaptive(invalid);},"A recorded header alone is not a subtitle track");
     invalid=plan;invalid["type"]="dash";rejects([&]{validateAdaptive(invalid);},"DASH cannot declare an HLS WebVTT header");
    }
    job->data["ProtectedAdaptive"]=protect(plan.dump());
    if(mode=="recorded-map-offline")job->data["ExpectedSha256"]=std::string(64,'0');
    if(mode=="recorded-map"){adaptiveTransfer(manager,job,std::make_shared<Cancel>());auto text=inspect(job,mode,true);check(text.find("00:00.500 --> 00:01.500")!=std::string::npos&&text.find("00:02.500 --> 00:03.500")!=std::string::npos,"Recorded mapped captions preserve both segment clocks");check(text.find("Boundary")==text.rfind("Boundary"),"Recorded mapped captions deduplicate boundary cues");}
    else{rejects([&]{adaptiveTransfer(manager,job,std::make_shared<Cancel>());},mode+" prevents publication");check(!fs::exists(job->target()),mode+" leaves no final file");}
   }
   if(mode=="recorded-map-offline"){job->data["ExpectedSha256"]="";manager.save();Manager restored(manager.root);JobPtr saved;for(auto candidate:restored.jobs)if(candidate->id()==job->id())saved=candidate;if(!saved)throw std::runtime_error("Missing recorded caption job");adaptiveTransfer(restored,saved,std::make_shared<Cancel>());auto text=inspect(saved,mode,true);check(text.find("Hola")!=std::string::npos&&text.find("Mundo")!=std::string::npos,"Recorded mapped caption receipts survive catalog reload with server offline");}
  }
 }catch(const std::exception& e){error=e.what();}bool passed=error.empty();for(const auto& row:checks)passed=passed&&yes(row,"passed");atomicText(root/L"results.json",Json{{"passed",passed},{"error",error},{"checks",checks}}.dump(2));std::cout<<checks.size()<<" checks; "<<error<<std::endl;CoUninitialize();WSACleanup();return passed?0:1;
}