// Drives and renders only native windows owned by this isolated test executable.
#define UDM_TOOLBAR_COMPONENT_TEST
#include "App.cpp"
namespace udm {
static Json results=Json::array();static fs::path output;static std::string failure;static std::wstring expectedTitle;static std::function<void(HWND)> action;static ULONGLONG began;
static void expect(bool value,const char* name){results.push_back({{"name",name},{"passed",value}});if(!value)throw std::runtime_error(name);}
static Json mainQueue(Manager& m){for(const auto& q:m.state["Queues"])if(str(q,"Name")=="Main queue")return q;throw std::runtime_error("Missing Main queue fixture");}
static std::wstring windowText(HWND w){wchar_t text[512]{};GetWindowTextW(w,text,512);return text;}
static HWND child(HWND parent,const wchar_t* label){for(HWND c=GetWindow(parent,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT))if(windowText(c)==label&&IsWindowVisible(c))return c;throw std::runtime_error("Missing owned test control: "+utf8(label));}
static std::vector<HWND> children(HWND parent,const wchar_t* type){std::vector<HWND> result;for(HWND c=GetWindow(parent,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT)){wchar_t name[128]{};GetClassNameW(c,name,128);if(!_wcsicmp(name,type))result.push_back(c);}return result;}
static void press(HWND w,const wchar_t* label){auto c=child(w,label);expect(IsWindowEnabled(c)!=FALSE,"Requested native button is enabled");SendMessageW(c,BM_CLICK,0,0);}
static void selectCombo(HWND parent,HWND control,int index){SendMessageW(control,CB_SETCURSEL,index,0);SendMessageW(parent,WM_COMMAND,MAKEWPARAM(GetDlgCtrlID(control),CBN_SELCHANGE),(LPARAM)control);}
static CRect bounds(HWND w){CRect r;GetWindowRect(w,&r);return r;}
static void capture(HWND w,const wchar_t* name){
 ShowWindow(w,SW_SHOWNOACTIVATE);RedrawWindow(w,nullptr,nullptr,RDW_INVALIDATE|RDW_ALLCHILDREN|RDW_UPDATENOW|RDW_ERASE);auto r=bounds(w);CImage img;img.Create(r.Width(),r.Height(),32);auto dc=img.GetDC();RECT fill{0,0,r.Width(),r.Height()};FillRect(dc,&fill,GetSysColorBrush(COLOR_BTNFACE));SendMessageW(w,WM_PRINT,(WPARAM)dc,PRF_NONCLIENT|PRF_CLIENT|PRF_ERASEBKGND|PRF_CHILDREN);
 for(HWND c=GetWindow(w,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT)){if(!(GetWindowLongW(c,GWL_STYLE)&WS_VISIBLE))continue;auto cr=bounds(c);auto saved=SaveDC(dc);IntersectClipRect(dc,cr.left-r.left,cr.top-r.top,cr.right-r.left,cr.bottom-r.top);SetViewportOrgEx(dc,cr.left-r.left,cr.top-r.top,nullptr);SendMessageW(c,WM_PRINT,(WPARAM)dc,PRF_NONCLIENT|PRF_CLIENT|PRF_ERASEBKGND|PRF_CHILDREN);RestoreDC(dc,saved);}
 img.ReleaseDC();if(FAILED(img.Save((output/name).c_str())))throw std::runtime_error("Could not render native test dialog");
}
static BOOL CALLBACK observe(HWND w,LPARAM){if(windowText(w)!=expectedTitle)return TRUE;try{ShowWindow(w,SW_SHOWNOACTIVATE);auto invoke=action;invoke(w);}catch(const std::exception& e){failure=e.what();PostMessageW(w,WM_CLOSE,0,0);}return FALSE;}
static void CALLBACK onTimer(HWND,UINT,UINT_PTR,DWORD){if(GetTickCount64()-began>12000){failure="Owned dialog test deadline";EnumThreadWindows(GetCurrentThreadId(),[](HWND w,LPARAM)->BOOL{PostMessageW(w,WM_CLOSE,0,0);return TRUE;},0);return;}EnumThreadWindows(GetCurrentThreadId(),observe,0);}
static void modal(Form& dialog,const wchar_t* caption,std::function<void(HWND)> callback){expectedTitle=caption;action=std::move(callback);began=GetTickCount64();auto timer=SetTimer(nullptr,0,80,onTimer);dialog.DoModal();KillTimer(nullptr,timer);action={};if(!failure.empty())throw std::runtime_error(failure);}

static HWND visibleList(HWND w){for(auto list:children(w,L"SysListView32"))if(IsWindowVisible(list))return list;throw std::runtime_error("No visible list");}
static void selectPage(HWND w,int index){auto tab=children(w,L"SysTabControl32").at(0);TabCtrl_SetCurSel(tab,index);NMHDR event{tab,(UINT_PTR)GetDlgCtrlID(tab),TCN_SELCHANGE};SendMessageW(w,WM_NOTIFY,event.idFrom,(LPARAM)&event);}
static std::wstring cell(HWND list,int row,int column){wchar_t value[512]{};ListView_GetItemText(list,row,column,value,512);return value;}
class LoginProtocolsUiApplication:public CWinApp {
 int code=1;
public:BOOL InitInstance()override{
 CWinApp::InitInstance();INITCOMMONCONTROLSEX common{sizeof(common),ICC_WIN95_CLASSES};InitCommonControlsEx(&common);AfxOleInit();int argc=0;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);
 try{if(argc!=2)throw std::runtime_error("Pass output directory");output=fs::path(argv[1]);fs::create_directories(output);Manager manager(output/L"state");auto before=manager.state["Settings"];Options options(manager,nullptr,{},[]{return std::vector<DialEntry>{};});
 modal(options,L"UDM Configuration",[&](HWND w){selectPage(w,6);auto list=visibleList(w);
 expect(!IsWindowEnabled(child(w,L"Edit"))&&!IsWindowEnabled(child(w,L"Remove")),"Empty saved-login list disables Edit and Remove");
 expect(Header_GetItemCount(ListView_GetHeader(list))==3,"Saved-login list exposes site user and password columns");
 expectedTitle=L"Site login";action=[&](HWND e){auto edits=children(e,L"Edit");expect(edits.size()==3,"Login editor exposes site user and password fields");expect((GetWindowLongW(edits[2],GWL_STYLE)&ES_PASSWORD)!=0,"Password editor remains masked");SetWindowTextW(edits[0],L"downloads.example.test/private");SetWindowTextW(edits[1],L"test-user");SetWindowTextW(edits[2],L"fixture-password");press(e,L"OK");};press(w,L"New");expectedTitle=L"not-open";
 expect(manager.state["Settings"]==before,"New login remains a draft before Apply");expect(ListView_GetItemCount(list)==1,"New saved-login row appears in draft");expect(cell(list,0,2)==L"********","Password list cell uses a fixed mask");
 expect(!IsWindowEnabled(child(w,L"Edit"))&&!IsWindowEnabled(child(w,L"Remove")),"Unselected populated list disables actions");
 ListView_SetItemState(list,0,LVIS_SELECTED|LVIS_FOCUSED,LVIS_SELECTED|LVIS_FOCUSED);expect(IsWindowEnabled(child(w,L"Edit"))&&IsWindowEnabled(child(w,L"Remove")),"Selected saved login enables actions");
 ListView_SetItemState(list,0,0,LVIS_SELECTED);expect(!IsWindowEnabled(child(w,L"Edit"))&&!IsWindowEnabled(child(w,L"Remove")),"Clearing saved-login selection disables actions");
 ListView_SetItemState(list,0,LVIS_SELECTED,LVIS_SELECTED);expectedTitle=L"Site login";action=[&](HWND e){auto edits=children(e,L"Edit");expect(windowText(edits[0])==L"downloads.example.test/private/"&&windowText(edits[1])==L"test-user","Edit loads the selected site and user");SetWindowTextW(edits[1],L"updated-user");press(e,L"OK");};press(w,L"Edit");expectedTitle=L"not-open";
 expect(cell(list,0,1)==L"updated-user","Edited username is reflected in the draft list");press(w,L"Apply");auto saved=manager.state["Settings"]["SiteLogins"];expect(saved.size()==1&&str(saved[0],"UserName")=="updated-user","Apply persists edited login");expect(str(saved[0],"ProtectedPassword")!="fixture-password"&&reveal(str(saved[0],"ProtectedPassword"))=="fixture-password","Password remains protected in saved settings");
 auto external=manager.state["Settings"];external["SiteLogins"].push_back(makeSiteLogin("https://other.example.test/","other-user","other-fixture"));external["ServerConnections"]=Json::array({{{"Host","cdn.example.test"},{"Connections",2}}});manager.setSettings(external);press(w,L"Apply");
 expect(ListView_GetItemCount(list)==2&&cell(list,1,1)==L"other-user","Unedited Apply refreshes concurrent saved-login changes");expect(!IsWindowEnabled(child(w,L"Edit"))&&!IsWindowEnabled(child(w,L"Remove")),"Refresh clears stale selection actions");capture(w,L"saved-logins.png");
 selectPage(w,4);auto servers=visibleList(w);expect(ListView_GetItemCount(servers)==1&&cell(servers,0,0)==L"cdn.example.test","Apply refreshes concurrent server-rule changes");selectPage(w,6);list=visibleList(w);
 ListView_SetItemState(list,1,LVIS_SELECTED,LVIS_SELECTED);press(w,L"Remove");ListView_SetItemState(list,0,LVIS_SELECTED,LVIS_SELECTED);press(w,L"Remove");expect(ListView_GetItemCount(list)==0&&!IsWindowEnabled(child(w,L"Edit"))&&!IsWindowEnabled(child(w,L"Remove")),"Removing last draft login disables actions");expect(manager.state["Settings"]["SiteLogins"].size()==2,"Draft removal leaves applied logins intact");press(w,L"Cancel");});
 expect(manager.state["Settings"]["SiteLogins"].size()==2,"Cancel preserves applied saved logins");Options reopenedOptions(manager,nullptr,{},[]{return std::vector<DialEntry>{};});modal(reopenedOptions,L"UDM Configuration",[&](HWND w){selectPage(w,6);auto list=visibleList(w);expect(ListView_GetItemCount(list)==2,"Reopened dialog shows persisted logins");ListView_SetItemState(list,1,LVIS_SELECTED,LVIS_SELECTED);press(w,L"Remove");press(w,L"Apply");expect(manager.state["Settings"]["SiteLogins"].size()==1,"Apply persists selected login removal");press(w,L"Cancel");});
 {Manager reopened(manager.root);expect(reopened.state["Settings"]["SiteLogins"].size()==1&&str(reopened.state["Settings"]["SiteLogins"][0],"UserName")=="updated-user","Saved-login edits and removals survive catalog reopening");}
Options protocols(manager,nullptr,{},[]{return std::vector<DialEntry>{};});modal(protocols,L"UDM Configuration",[&](HWND w){selectPage(w,6);
 for(int selected=1;selected<=2;++selected){expectedTitle=L"Site login";action=[&,selected](HWND e){auto combos=children(e,L"ComboBox");expect(combos.size()==1&&SendMessageW(combos[0],CB_GETCOUNT,0,0)==3&&IsWindowEnabled(combos[0]),"Saved-login protocol selector offers HTTPS HTTP and FTP");selectCombo(e,combos[0],selected);auto edits=children(e,L"Edit");SetWindowTextW(edits[0],L"protocol.example.test/private");SetWindowTextW(edits[1],L"protocol-user");SetWindowTextW(edits[2],L"protocol-fixture");press(e,L"OK");};press(w,L"New");expectedTitle=L"not-open";}
 press(w,L"Apply");auto logins=manager.state["Settings"]["SiteLogins"];expect(logins.size()==3&&str(logins[1],"Origin")=="http://protocol.example.test"&&str(logins[2],"Origin")=="ftp://protocol.example.test","Apply persists HTTP and FTP as separate login scopes");auto list=visibleList(w);
 for(int selected=1;selected<=2;++selected){ListView_SetItemState(list,selected,LVIS_SELECTED|LVIS_FOCUSED,LVIS_SELECTED|LVIS_FOCUSED);expectedTitle=L"Site login";action=[&,selected](HWND e){auto combo=children(e,L"ComboBox").at(0);expect(SendMessageW(combo,CB_GETCURSEL,0,0)==selected&&windowText(children(e,L"Edit").at(0))==L"protocol.example.test/private/","Editing a saved protocol retains its scheme and full server path");press(e,L"Cancel");};press(w,L"Edit");expectedTitle=L"not-open";}
 capture(w,L"protocol-logins.png");press(w,L"Cancel");});
{Manager restarted(manager.root);expect(restarted.state["Settings"]["SiteLogins"].size()==3,"All three protocols survive UI save and catalog restart");}code=0;
 }catch(const std::exception& e){failure=e.what();}if(argv)LocalFree(argv);if(!output.empty())atomicText(output/L"results.json",Json{{"passed",code==0},{"error",failure},{"checks",results}}.dump(2),false);return FALSE;}
 int ExitInstance()override{AfxOleTerm(FALSE);return code;}
};LoginProtocolsUiApplication application;
}