// Included inside MainWindow: persisted desktop interaction preferences.
 static constexpr int columnCount=12;
 const wchar_t* columnName(int index)const{static const wchar_t* names[]={L"File Name",L"Q",L"Size",L"Status",L"Time left",L"Transfer rate",L"Last Try Date",L"Description",L"Date added",L"Save to",L"Referer",L"Parent web page"};return names[index];}
 Json preferences(){Lock lock(manager.mutex);return manager.state["Settings"];}
 void preference(const char* key,const Json& value){auto p=preferences();p[key]=value;manager.setSettings(p);}
 Json listLayout(){Json widths=Json::array(),order=Json::array();int indices[columnCount]{};table.GetColumnOrderArray(indices,columnCount);for(int i=0;i<columnCount;++i){widths.push_back((int)(table.GetColumnWidth(i)/scale));order.push_back(indices[i]);}return {{"Widths",widths},{"Order",order},{"SortColumn",sortColumn},{"Ascending",ascending}};}
 void restoreLayout(){auto p=preferences();auto layout=p.value("ListLayout",Json::object());if(layout.contains("Widths")&&layout["Widths"].is_array()&&layout["Widths"].size()==columnCount)for(int i=0;i<columnCount;++i){int width=std::clamp<int>((int)layout["Widths"][i],i?0:40,1200);table.SetColumnWidth(i,px(width));}if(layout.contains("Order")&&layout["Order"].is_array()&&layout["Order"].size()==columnCount){int order[columnCount]{};std::set<int> seen;for(int i=0;i<columnCount;++i){order[i]=layout["Order"][i];if(order[i]<0||order[i]>=columnCount||!seen.insert(order[i]).second)return;}table.SetColumnOrderArray(columnCount,order);}sortColumn=(int)std::clamp<i64>(num(layout,"SortColumn",-1),-1,columnCount-1);ascending=yes(layout,"Ascending",true);}
 void rememberLayout(){if(!table.GetSafeHwnd())return;Lock lock(manager.mutex);manager.state["Settings"]["ListLayout"]=listLayout();}
 void customizeColumns(){
  Form d("Columns",460,362,this);std::vector<int> order(columnCount),widths(columnCount);std::vector<bool> shown(columnCount);table.GetColumnOrderArray(order.data(),columnCount);for(int i=0;i<columnCount;++i){static const int defaults[]={205,38,72,97,77,91,132,160,132,220,200,200};auto saved=preferences().value("ColumnWidths",Json::array());widths[i]=table.GetColumnWidth(i)>0?(int)(table.GetColumnWidth(i)/scale):saved.is_array()&&saved.size()==columnCount?(int)saved[i]:defaults[i];shown[i]=table.GetColumnWidth(i)>0;}
  CListCtrl* list=nullptr;CWnd* width=nullptr;
  auto collect=[&]{for(int row=0;row<columnCount;++row)shown[order[row]]=list->GetCheck(row)!=FALSE;shown[0]=true;};
  auto fill=[&](int selection){list->DeleteAllItems();for(int row=0;row<columnCount;++row){int index=order[row];list->InsertItem(row,columnName(index));list->SetCheck(row,shown[index]);list->SetItemText(row,1,cs(std::to_string(widths[index])));}if(selection>=0)list->SetItemState(selection,LVIS_SELECTED|LVIS_FOCUSED,LVIS_SELECTED|LVIS_FOCUSED);};
  d.init=[&]{d.label("Choose visible columns and their order. File Name stays visible.",12,12,436,32);list=d.make<CListCtrl>(WS_TABSTOP|WS_BORDER|LVS_SHOWSELALWAYS|LVS_REPORT|LVS_SINGLESEL,12,49,321,258);list->SetExtendedStyle(LVS_EX_CHECKBOXES|LVS_EX_FULLROWSELECT);list->InsertColumn(0,L"Column",LVCFMT_LEFT,215);list->InsertColumn(1,L"Width",LVCFMT_LEFT, 70);
   auto move=[&](int step){int row=list->GetNextItem(-1,LVNI_SELECTED);if(row<0||row+step<0||row+step>=columnCount)return;collect();std::swap(order[row],order[row+step]);fill(row+step);};
   d.button("Move up",345,50,102,[move]{move(-1);});d.button("Move down",345,85,102,[move]{move(1);});d.label("Width in pixels",345,132,102);width=d.edit("120",345,157,102);d.button("Set width",345,192,102,[&]{int row=list->GetNextItem(-1,LVNI_SELECTED);if(row<0)return;int n=std::stoi(text(width));if(n<40||n>1200)throw std::runtime_error("Use 40 to 1200 pixels.");collect();widths[order[row]]=n;fill(row);});d.button("Reset",345,246,102,[&]{int defaults[]={205,38,72,97,77,91,132,160,132,220,200,200};for(int i=0;i<columnCount;++i){order[i]=i;widths[i]=defaults[i];shown[i]=i<8;}fill(0);});
   d.accept=[&]{collect();table.SetColumnOrderArray(columnCount,order.data());for(int i=0;i<columnCount;++i)table.SetColumnWidth(i,shown[i]?px(widths[i]):0);preference("ColumnWidths",widths);rememberLayout();manager.save();d.close();};d.button("OK",255,323,92,d.accept);d.button("Cancel",357,323,90,[&]{d.close(IDCANCEL);});fill(0);
  };d.DoModal();
 }
 void chooseFont(){LOGFONTW value{};font.GetLogFont(&value);CFontDialog d(&value,CF_SCREENFONTS|CF_INITTOLOGFONTSTRUCT|CF_LIMITSIZE,nullptr,this);d.m_cf.nSizeMin=6;d.m_cf.nSizeMax=18;if(d.DoModal()!=IDOK)return;d.GetCurrentFont(&value);auto p=preferences();p["FontName"]=utf8(value.lfFaceName);p["FontHeight"]=std::clamp((int)(std::abs(value.lfHeight)/scale),8,24);p["FontWeight"]=value.lfWeight;manager.setSettings(p);applyAppearance();}
 void applyAppearance(){auto p=preferences();uiDark=yes(p,"DarkMode");themeFrame(m_hWnd);font.DeleteObject();font.CreateFontW(-px((int)num(p,"FontHeight",11)),0,0,0,(int)num(p,"FontWeight",400),FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,DEFAULT_QUALITY,DEFAULT_PITCH,wide(str(p,"FontName","Tahoma")).c_str());for(CWnd* w:{static_cast<CWnd*>(&table),static_cast<CWnd*>(&tree),static_cast<CWnd*>(&categoryHeading),static_cast<CWnd*>(&status),static_cast<CWnd*>(&search),static_cast<CWnd*>(&clipboard)})w->SetFont(&font);table.GetHeaderCtrl()->SetFont(&font);rebuildToolbar();table.SetExtendedStyle(uiDark?(table.GetExtendedStyle()&~LVS_EX_GRIDLINES):(table.GetExtendedStyle()|LVS_EX_GRIDLINES));table.theme();tree.SetBkColor(uiBackground());tree.SetTextColor(uiForeground());tree.SetItemHeight((SHORT)px(std::max(17,(int)num(p,"FontHeight",11)+5)));updateTray();CRect area;GetClientRect(&area);layout(area.Width(),area.Height());RedrawWindow(nullptr,nullptr,RDW_INVALIDATE|RDW_ALLCHILDREN|RDW_ERASE);}
 void updateTray(){auto choice=str(preferences(),"TrayIcon","Color");tray.hIcon=choice=="System"?LoadIcon(nullptr,IDI_APPLICATION):AfxGetApp()->LoadIcon(1);Shell_NotifyIconW(choice=="Hidden"?NIM_DELETE:NIM_ADD,&tray);if(choice!="Hidden")Shell_NotifyIconW(NIM_MODIFY,&tray);}
 afx_msg BOOL OnEraseBkgnd(CDC* dc){CRect area;GetClientRect(&area);dc->FillSolidRect(area,uiDark?uiBackground():GetSysColor(COLOR_BTNFACE));return TRUE;}
 afx_msg HBRUSH OnCtlColor(CDC* dc,CWnd* window,UINT type){if(uiDark&&(type==CTLCOLOR_STATIC||type==CTLCOLOR_EDIT)){dc->SetTextColor(uiForeground());dc->SetBkColor(uiBackground());return (HBRUSH)uiBrush().GetSafeHandle();}return CFrameWnd::OnCtlColor(dc,window,type);}
