#include "Core.hpp"
#include <ws2tcpip.h>
#include <iphlpapi.h>
#include <tlhelp32.h>
#include "../drivers/UdmWfpProtocol.h"
namespace udm {
static std::string address(int family,const void* p,unsigned port){char out[128]{};if(!InetNtopA(family,(void*)p,out,sizeof(out)))return "Unknown";return family==AF_INET6?"["+std::string(out)+"]:"+std::to_string(port):std::string(out)+":"+std::to_string(port);}
Monitor::Monitor():device(CreateFileW(L"\\\\.\\UdmWfp",GENERIC_READ|GENERIC_WRITE,0,nullptr,OPEN_EXISTING,0,nullptr)){if(!device){auto e=GetLastError();throw std::runtime_error(e==ERROR_FILE_NOT_FOUND?"UDM WFP driver is not installed or running.":e==ERROR_ACCESS_DENIED?"UDM WFP monitor requires administrator privileges.":"Cannot open UDM WFP monitor (Windows error "+std::to_string(e)+").");}}
void Monitor::watch(const std::vector<DWORD>& pids){std::set<DWORD> unique(pids.begin(),pids.end());if(unique.size()>UDM_WFP_MAX_PIDS||unique.count(0))throw std::runtime_error("Select up to 32 nonzero process identifiers.");UDM_WFP_WATCH w{};w.Version=UDM_WFP_VERSION;w.Size=sizeof(w);w.Count=(UINT32)unique.size();size_t i=0;for(auto p:unique)w.ProcessIds[i++]=p;DWORD n=0;if(!DeviceIoControl(device.h,IOCTL_UDM_WFP_WATCH,&w,sizeof(w),nullptr,0,&n,nullptr))throw std::runtime_error("Driver rejected the process watch request.");}
Json Monitor::snapshot(){Bytes data(sizeof(UDM_WFP_SNAPSHOT)+sizeof(UDM_WFP_FLOW)*UDM_WFP_MAX_FLOWS);DWORD n=0;if(!DeviceIoControl(device.h,IOCTL_UDM_WFP_SNAPSHOT,nullptr,0,data.data(),(DWORD)data.size(),&n,nullptr))throw std::runtime_error("Driver snapshot failed.");if(n<sizeof(UDM_WFP_SNAPSHOT))throw std::runtime_error("Truncated driver snapshot.");auto s=(UDM_WFP_SNAPSHOT*)data.data();if(s->Version!=UDM_WFP_VERSION||s->HeaderSize!=sizeof(*s)||s->RecordSize!=sizeof(UDM_WFP_FLOW)||s->Count>UDM_WFP_MAX_FLOWS||n!=sizeof(*s)+sizeof(UDM_WFP_FLOW)*s->Count)throw std::runtime_error("Unsupported driver snapshot format.");Json flows=Json::array();auto rows=(UDM_WFP_FLOW*)(s+1);for(UINT32 i=0;i<s->Count;++i){auto& r=rows[i];if((r.Family!=AF_INET&&r.Family!=AF_INET6)||(r.Protocol!=6&&r.Protocol!=17))throw std::runtime_error("Invalid driver flow metadata.");flows.push_back({{"ProcessId",r.ProcessId},{"Local",address(r.Family,r.LocalAddress,r.LocalPort)},{"Remote",address(r.Family,r.RemoteAddress,r.RemotePort)},{"Transport",r.Protocol==6?"TCP":"UDP"},{"State",r.Flags&UDM_FLOW_ACTIVE?"Active":"Closed"},{"Received",r.ReceivedBytes},{"Sent",r.SentBytes}});}return {{"Generation",s->Generation},{"Dropped",s->DroppedFlows},{"Connections",s->Connections},{"Received",s->ReceivedBytes},{"Sent",s->SentBytes},{"Watched",s->WatchedProcesses},{"Flows",flows}};}
Json diagnostics(){Json r={{"Administrator",false},{"CodeIntegrityEnabled",nullptr},{"TestSignedDriversAllowed",nullptr},{"MemoryIntegrityEnabled",nullptr},{"QueryError",nullptr},{"DriverStatus",""}};SID_IDENTIFIER_AUTHORITY authority=SECURITY_NT_AUTHORITY;PSID admins=nullptr;if(AllocateAndInitializeSid(&authority,2,SECURITY_BUILTIN_DOMAIN_RID,DOMAIN_ALIAS_RID_ADMINS,0,0,0,0,0,0,&admins)){BOOL member=FALSE;CheckTokenMembership(nullptr,admins,&member);r["Administrator"]=member!=FALSE;FreeSid(admins);}struct Integrity{ULONG length,options;};auto ntdll=GetModuleHandleW(L"ntdll.dll");using Query=LONG(NTAPI*)(ULONG,PVOID,ULONG,PULONG);auto q=(Query)GetProcAddress(ntdll,"NtQuerySystemInformation");if(q){Integrity ci{8,0};ULONG returned=0;LONG status=q(103,&ci,sizeof(ci),&returned);if(status==0&&returned==8){r["CodeIntegrityEnabled"]=(ci.options&1)!=0;r["TestSignedDriversAllowed"]=(ci.options&2)!=0;r["MemoryIntegrityEnabled"]=(ci.options&0x400)!=0;}else r["QueryError"]="Code Integrity query failed ("+std::to_string(status)+").";}else r["QueryError"]="Code Integrity query unavailable.";try{Monitor monitor;monitor.snapshot();r["DriverStatus"]="Available";}catch(const std::exception& e){r["DriverStatus"]=e.what();}return r;}
Json endpoints(){std::map<DWORD,std::string> names;DWORD currentSession=0;ProcessIdToSessionId(GetCurrentProcessId(),&currentSession);Handle processes(CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0));PROCESSENTRY32W entry{sizeof(entry)};if(processes&&Process32FirstW(processes.h,&entry))do{auto name=lower(utf8(entry.szExeFile));DWORD session=0;if((name=="udm.exe"||name=="chrome.exe"||name=="msedge.exe"||name=="firefox.exe")&&ProcessIdToSessionId(entry.th32ProcessID,&session)&&session==currentSession)names[entry.th32ProcessID]=name;}while(Process32NextW(processes.h,&entry));Json rows=Json::array();auto add=[&](DWORD pid,std::string local,std::string remote,const char* protocol,std::string state){if(names.count(pid))rows.push_back({{"ProcessId",pid},{"Process",names[pid]},{"Local",local},{"Remote",remote},{"Transport",protocol},{"State",state},{"Received",nullptr},{"Sent",nullptr}});};for(ULONG family:{AF_INET,AF_INET6}){ULONG size=0;auto result=GetExtendedTcpTable(nullptr,&size,FALSE,family,TCP_TABLE_OWNER_PID_ALL,0);if(result!=ERROR_INSUFFICIENT_BUFFER)throw std::runtime_error("Cannot read Windows TCP endpoints.");Bytes table(size);result=GetExtendedTcpTable(table.data(),&size,FALSE,family,TCP_TABLE_OWNER_PID_ALL,0);if(result==NO_ERROR){if(family==AF_INET){auto t=(MIB_TCPTABLE_OWNER_PID*)table.data();for(DWORD i=0;i<t->dwNumEntries;++i){auto& row=t->table[i];add(row.dwOwningPid,address(AF_INET,&row.dwLocalAddr,ntohs((u_short)row.dwLocalPort)),address(AF_INET,&row.dwRemoteAddr,ntohs((u_short)row.dwRemotePort)),"TCP",row.dwState==MIB_TCP_STATE_ESTAB?"Established":row.dwState==MIB_TCP_STATE_LISTEN?"Listening":std::to_string(row.dwState));}}else{auto t=(MIB_TCP6TABLE_OWNER_PID*)table.data();for(DWORD i=0;i<t->dwNumEntries;++i){auto& row=t->table[i];add(row.dwOwningPid,address(AF_INET6,row.ucLocalAddr,ntohs((u_short)row.dwLocalPort)),address(AF_INET6,row.ucRemoteAddr,ntohs((u_short)row.dwRemotePort)),"TCP",row.dwState==MIB_TCP_STATE_ESTAB?"Established":std::to_string(row.dwState));}}}size=0;GetExtendedUdpTable(nullptr,&size,FALSE,family,UDP_TABLE_OWNER_PID,0);table.resize(size);if(GetExtendedUdpTable(table.data(),&size,FALSE,family,UDP_TABLE_OWNER_PID,0)==NO_ERROR){if(family==AF_INET){auto t=(MIB_UDPTABLE_OWNER_PID*)table.data();for(DWORD i=0;i<t->dwNumEntries;++i){auto& row=t->table[i];add(row.dwOwningPid,address(AF_INET,&row.dwLocalAddr,ntohs((u_short)row.dwLocalPort)),"","UDP","Bound");}}else{auto t=(MIB_UDP6TABLE_OWNER_PID*)table.data();for(DWORD i=0;i<t->dwNumEntries;++i){auto& row=t->table[i];add(row.dwOwningPid,address(AF_INET6,row.ucLocalAddr,ntohs((u_short)row.dwLocalPort)),"","UDP","Bound");}}}}return rows;}
}
