#include "OfflineSite.hpp"
#include "OfflineArchive.hpp"
#include "GrabberDestinations.hpp"
#include "GrabberLinks.hpp"
#include <fstream>
#include <algorithm>
#include <regex>
#include <sstream>
#include <array>
namespace udm {
namespace {
bool space(char c){return c==' '||c=='\t'||c=='\r'||c=='\n'||c=='\f';}
std::string entities(std::string s){
 static const std::map<std::string,std::string> values={{"nbsp","\xc2\xa0"},{"amp","&"},{"quot","\""},{"apos","'"},{"lt","<"},{"gt",">"}};
 for(size_t i=0;(i=s.find('&',i))!=std::string::npos;){auto end=s.find(';',i+1);if(end==std::string::npos||end-i>12){++i;continue;}auto key=s.substr(i+1,end-i-1);std::string replacement;auto found=values.find(key);if(found!=values.end())replacement=found->second;
  else if(key.size()>1&&key[0]=='#')try{bool hex=key.size()>2&&(key[1]=='x'||key[1]=='X');auto digits=key.substr(hex?2:1);size_t used=0;unsigned long code=std::stoul(digits,&used,hex?16:10);if(used==digits.size()&&code>0&&code<=0x10ffff&&!(code>=0xd800&&code<=0xdfff)){std::wstring w;if(code>65535){code-=65536;w+=(wchar_t)(0xd800+(code>>10));w+=(wchar_t)(0xdc00+(code&1023));}else w+=(wchar_t)code;replacement=utf8(w);}}catch(...){}
  if(replacement.empty()){i=end+1;continue;}s.replace(i,end-i+1,replacement);i+=replacement.size();
 }return s;
}
std::string linkDescription(std::string raw){
 auto text=wide(raw);std::wstring clean;bool gap=false;
 for(wchar_t c:text){if(c<=32||c==127||c==0xa0){gap=!clean.empty();continue;}if(gap)clean+=L' ';gap=false;clean+=c;}
 auto result=utf8(clean);if(result.size()>1024){size_t end=1024;while(end&&(static_cast<unsigned char>(result[end])&0xc0)==0x80)--end;result.resize(end);}return trim(result);
}
std::string escaped(const std::string& text){std::string out;for(char c:text){if(c=='&')out+="&amp;";else if(c=='\"')out+="&quot;";else if(c=='\'')out+="&#39;";else if(c=='<')out+="&lt;";else if(c==' ')out+="%20";else out+=c;}return out;}
std::string canonical(const std::string& input){Url url(input);if(url.scheme!="http"&&url.scheme!="https")throw std::runtime_error("Offline sites require HTTP or HTTPS.");return url.origin+url.path+url.query;}
bool pageAddress(const std::string& address){auto ext=lower(utf8(fs::path(wide(Url(address).path)).extension().wstring()));return ext.empty()||ext==".html"||ext==".htm"||ext==".php"||ext==".asp"||ext==".aspx"||ext==".xhtml";}
void cssRefs(const std::string& text,size_t offset,bool html,std::vector<SiteReference>& out){
 auto low=lower(text);for(size_t i=0;i<text.size()&&out.size()<10000;){
  if(text.compare(i,2,"/*")==0){auto end=text.find("*/",i+2);i=end==std::string::npos?text.size():end+2;continue;}
  bool url=low.compare(i,3,"url")==0&&(i==0||!(isalnum((unsigned char)text[i-1])||text[i-1]=='-'||text[i-1]=='_'));
  bool imported=low.compare(i,7,"@import")==0;
  size_t start=i+(url?3:imported?7:0);if(!url&&!imported){if(text[i]=='\''||text[i]=='\"'){char quote=text[i++];while(i<text.size()&&text[i]!=quote){if(text[i]=='\\'&&i+1<text.size())++i;++i;}}++i;continue;}
  while(start<text.size()&&space(text[start]))++start;if(url){if(start==text.size()||text[start]!='('){++i;continue;}++start;while(start<text.size()&&space(text[start]))++start;}
  if(start>=text.size())break;char quote=text[start]=='\''||text[start]=='\"'?text[start++]:0;if(imported&&!quote){i=start;continue;}size_t end=start;bool escapedValue=false;
  while(end<text.size()&&(quote?text[end]!=quote:text[end]!=')'&&!space(text[end]))){if(text[end]=='\\'){escapedValue=true;if(end+1<text.size())++end;}++end;}
  if(end>start&&!escapedValue)out.push_back({offset+start,end-start,html?entities(text.substr(start,end-start)):text.substr(start,end-start),false,html,false,false,true});i=end+1;
 }
}
struct Attribute {std::string name,value;size_t start=0,length=0;};
std::vector<Attribute> attributes(const std::string& text,size_t at,size_t end){std::vector<Attribute> result;while(at<end){while(at<end&&(space(text[at])||text[at]=='/'))++at;size_t first=at;while(at<end&&!space(text[at])&&text[at]!='='&&text[at]!='>')++at;if(first==at)break;auto name=lower(text.substr(first,at-first));while(at<end&&space(text[at]))++at;if(at==end||text[at]!='=')continue;++at;while(at<end&&space(text[at]))++at;char quote=at<end&&(text[at]=='\''||text[at]=='\"')?text[at++]:0;first=at;while(at<end&&(quote?text[at]!=quote:!space(text[at])&&text[at]!='>'))++at;result.push_back({name,entities(text.substr(first,at-first)),first,at-first});if(quote&&at<end)++at;}return result;}
std::string documentBase(const std::string& text,const std::string& address){for(auto ref:siteReferences(text))if(ref.remove&&!ref.value.empty())try{return canonical(combineUrl(address,ref.value));}catch(...){}return address;}
uint32_t crcUpdate(uint32_t value,const char* bytes,size_t count){static const auto table=[] {std::array<uint32_t,256> t{};for(uint32_t i=0;i<256;++i){uint32_t v=i;for(int b=0;b<8;++b)v=(v>>1)^((v&1)?0xedb88320U:0);t[i]=v;}return t;}();for(size_t i=0;i<count;++i)value=table[(value^(unsigned char)bytes[i])&255]^(value>>8);return value;}
void zipSite(const fs::path& path,const std::vector<std::pair<std::string,fs::path>>& entries,const Cancel& cancel){
 if(entries.size()>65535)throw std::runtime_error("Too many offline archive entries.");std::set<std::wstring,OfflinePathLess> members;for(const auto& item:entries){validateOfflineArchivePath(item.first);if(!members.insert(wide(item.first)).second)throw std::runtime_error("Duplicate offline archive entry.");}for(const auto& item:entries){auto parent=fs::path(wide(item.first)).parent_path();while(!parent.empty()){if(members.count(parent.generic_wstring()))throw std::runtime_error("An offline file occupies another entry\'s folder.");parent=parent.parent_path();}}
 std::ofstream out(path,std::ios::binary|std::ios::trunc);if(!out)throw std::runtime_error("Cannot create offline archive.");
 auto put=[&](uint32_t value,int count){for(int i=0;i<count;++i){out.put((char)(value&255));value>>=8;}};
 struct Item{std::string name;uint32_t size,crc,offset;};std::vector<Item> directory;char buffer[65536];
 for(const auto& entry:entries){cancel.check();auto length=fs::file_size(entry.second);if(length>32*1024*1024)throw std::runtime_error("Invalid offline archive entry.");std::ifstream in(entry.second,std::ios::binary);uint32_t crc=0xffffffff;while(in){cancel.check();in.read(buffer,sizeof(buffer));crc=crcUpdate(crc,buffer,(size_t)in.gcount());}if(!in.eof())throw std::runtime_error("Cannot verify offline archive input.");crc^=0xffffffff;in.clear();in.seekg(0);
  auto offset=out.tellp();if(offset<0||(uint64_t)offset>0xffffffff)throw std::runtime_error("Offline archive is too large.");directory.push_back({entry.first,(uint32_t)length,crc,(uint32_t)offset});put(0x04034b50,4);put(20,2);put(0x800,2);put(0,2);put(0,2);put(33,2);put(crc,4);put((uint32_t)length,4);put((uint32_t)length,4);put((uint32_t)entry.first.size(),2);put(0,2);out<<entry.first;
  uint64_t written=0;uint32_t copiedCrc=0xffffffff;while(in){cancel.check();in.read(buffer,sizeof(buffer));auto count=(size_t)in.gcount();written+=count;if(written>length)throw std::runtime_error("Offline archive input changed.");copiedCrc=crcUpdate(copiedCrc,buffer,count);out.write(buffer,(std::streamsize)count);}if(!in.eof()||!out||written!=length||(copiedCrc^0xffffffff)!=crc)throw std::runtime_error("Cannot write unchanged offline archive input.");
 }
 auto start=out.tellp();for(const auto& item:directory){put(0x02014b50,4);put(20,2);put(20,2);put(0x800,2);put(0,2);put(0,2);put(33,2);put(item.crc,4);put(item.size,4);put(item.size,4);put((uint32_t)item.name.size(),2);put(0,2);put(0,2);put(0,2);put(0,2);put(0,4);put(item.offset,4);out<<item.name;}auto end=out.tellp();put(0x06054b50,4);put(0,2);put(0,2);put((uint32_t)directory.size(),2);put((uint32_t)directory.size(),2);put((uint32_t)(end-start),4);put((uint32_t)start,4);put(0,2);out.flush();if(!out)throw std::runtime_error("Cannot finish offline archive.");
}
}
std::vector<SiteReference> siteReferences(const std::string& text,bool css,bool preserveActive){
 std::vector<SiteReference> result;std::optional<size_t> anchor;std::string label;size_t textAt=0;
 auto addText=[&](size_t begin,size_t end){if(anchor&&begin<end&&label.size()<8192)label+=entities(text.substr(begin,std::min<size_t>(end-begin,8192-label.size())));};
 auto finishAnchor=[&]{if(anchor&&*anchor<result.size())result[*anchor].description=linkDescription(label);anchor.reset();label.clear();};
 if(css){cssRefs(text,0,false,result);return result;}auto low=lower(text);
 for(size_t at=0;(at=text.find('<',at))!=std::string::npos&&result.size()<10000;){
  addText(textAt,at);
  if(text.compare(at,4,"<!--")==0){auto end=text.find("-->",at+4);at=end==std::string::npos?text.size():end+3;textAt=at;continue;}size_t end=at+1;char quote=0;for(;end<text.size();++end){char c=text[end];if(quote){if(c==quote)quote=0;}else if(c=='\''||c=='\"')quote=c;else if(c=='>')break;}if(end==text.size())break;
  size_t nameEnd=at+1;while(nameEnd<end&&(isalnum((unsigned char)text[nameEnd])||text[nameEnd]=='-'))++nameEnd;auto tag=low.substr(at+1,nameEnd-at-1);auto attrs=attributes(text,nameEnd,end);
  const bool closeAnchor=low.compare(at,3,"</a")==0&&(at+3==end||space(text[at+3]));if(closeAnchor||tag=="a")finishAnchor();
  if(anchor&&(tag=="br"||tag=="p"||tag=="div"||tag=="li")&&label.size()<8192)label+=" ";
  if(tag=="script"){auto close=low.find("</script",end+1);auto closeEnd=close==std::string::npos?std::string::npos:text.find('>',close);size_t last=closeEnd==std::string::npos?text.size()-1:closeEnd;if(preserveActive){for(const auto& attr:attrs)if(attr.name=="src")result.push_back({attr.start,attr.length,attr.value,false,true,false});}else result.push_back({at,last-at+1,"",false,false,true});at=last+1;textAt=at;continue;}
  bool remove=tag=="base";for(const auto& attr:attrs)if(!preserveActive&&tag=="meta"&&attr.name=="http-equiv"&&(lower(attr.value)=="refresh"||lower(attr.value)=="content-security-policy"))remove=true;
  if(remove){std::string base;if(tag=="base")for(const auto& attr:attrs)if(attr.name=="href")base=attr.value;result.push_back({at,end-at+1,base,false,false,true});at=end+1;textAt=at;continue;}
  for(const auto& attr:attrs){
   if(anchor&&tag=="img"&&attr.name=="alt"&&label.size()<8192)label+=attr.value.substr(0,8192-label.size());
   if(attr.name=="style"){cssRefs(text.substr(attr.start,attr.length),attr.start,true,result);continue;}
   if(attr.name=="srcset"){auto raw=text.substr(attr.start,attr.length);for(size_t i=0;i<raw.size();){while(i<raw.size()&&(space(raw[i])||raw[i]==','))++i;size_t start=i;bool data=lower(raw.substr(i,5))=="data:";while(i<raw.size()&&!space(raw[i])&&(data||raw[i]!=','))++i;if(i>start&&!data)result.push_back({attr.start+start,i-start,entities(raw.substr(start,i-start)),false,true,false});while(i<raw.size()&&raw[i]!=',')++i;if(i<raw.size())++i;}continue;}
   bool page=(tag=="a"&&attr.name=="href")||((tag=="iframe"||tag=="frame")&&attr.name=="src");bool asset=(attr.name=="src"&&(tag=="img"||tag=="source"||tag=="video"||tag=="audio"||tag=="input"))||attr.name=="poster"||attr.name=="background"||(tag=="link"&&attr.name=="href");
   bool form=preserveActive&&((tag=="form"&&attr.name=="action")||((tag=="button"||tag=="input")&&attr.name=="formaction"));
   if(page||asset||form){result.push_back({attr.start,attr.length,attr.value,page,true,false,tag=="a"||form});if(tag=="a"&&attr.name=="href"&&!anchor)anchor=result.size()-1;}
  }
  if(tag=="style"){auto close=low.find("</style",end+1);if(close==std::string::npos)close=text.size();cssRefs(text.substr(end+1,close-end-1),end+1,false,result);at=close;textAt=at;continue;}
  at=end+1;textAt=at;
 }if(result.size()<10000&&text.find('<',textAt)==std::string::npos)addText(textAt,text.size());finishAnchor();return result;
}
std::string rewriteSiteDocument(const std::string& text,const std::string& address,bool css,const std::map<std::string,std::string>& files,const std::string& documentName){
 auto refs=siteReferences(text,css);auto base=css?address:documentBase(text,address);std::sort(refs.begin(),refs.end(),[](const SiteReference& a,const SiteReference& b){return a.offset>b.offset;});std::string output=text;
 for(const auto& ref:refs){if(ref.remove){output.erase(ref.offset,ref.length);continue;}auto raw=trim(ref.value);if(raw.empty()||(raw[0]=='#'&&base==address)||lower(raw).rfind("data:",0)==0)continue;try{auto url=canonical(combineUrl(base,raw));auto at=files.find(url);auto fragment=raw.find('#');std::string value=at==files.end()?(ref.navigation?url:"data:,"):documentName.empty()?at->second:offlineArchiveReference(documentName,at->second);if(fragment!=std::string::npos)value+=raw.substr(fragment);if(ref.css){std::string encoded;const char* hex="0123456789ABCDEF";for(unsigned char c:value){if(c<=32||c==39||c==34||c==40||c==41||c==92||c==60||c==62){encoded+='%';encoded+=hex[c>>4];encoded+=hex[c&15];}else encoded+=(char)c;}value=encoded;}output.replace(ref.offset,ref.length,ref.html?escaped(value):value);}catch(...) {}}
 if(!css){const std::string policy="<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'none'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; font-src 'self' data:; media-src 'self'; frame-src 'self'; form-action 'none'; base-uri 'none'\">";auto low=lower(output);auto head=low.find("<head");auto end=head==std::string::npos?std::string::npos:output.find('>',head);if(end!=std::string::npos)output.insert(end+1,policy);else output=policy+output;}
 return output;
}

std::string rewriteGrabberDocument(const std::string& text,const std::string& address,bool css,const std::map<std::string,std::string>& files){
 auto refs=siteReferences(text,css,true);auto base=css?address:documentBase(text,address);std::sort(refs.begin(),refs.end(),[](const SiteReference& a,const SiteReference& b){return a.offset>b.offset;});std::string output=text;
 for(const auto& ref:refs){if(ref.remove){output.erase(ref.offset,ref.length);continue;}auto raw=trim(ref.value);if(raw.empty()||(raw[0]=='#'&&base==address))continue;try{auto url=canonical(combineUrl(base,raw));auto found=files.find(url);std::string value=found==files.end()?url:found->second;auto fragment=raw.find('#');if(fragment!=std::string::npos)value+=raw.substr(fragment);
  if(ref.css){std::string encoded;const char* hex="0123456789ABCDEF";for(unsigned char c:value){if(c<=32||c==39||c==34||c=='('||c==')'||c==92||c=='<'||c=='>'){encoded+='%';encoded+=hex[c>>4];encoded+=hex[c&15];}else encoded+=(char)c;}value=encoded;}
  output.replace(ref.offset,ref.length,ref.html?escaped(value):value);}catch(const std::exception&){}}
 return output;
}
void validateOfflineProject(const Json& project){
 canonical(str(project,"StartUrl"));if(project.contains("OriginalSubfolders")&&!project["OriginalSubfolders"].is_boolean())throw std::runtime_error("Invalid offline folder-layout setting.");if(num(project,"Depth",1)<0||num(project,"Depth",1)>5||num(project,"MaxPages",20)<1||num(project,"MaxPages",20)>100||num(project,"MaxMiB",256)<1||num(project,"MaxMiB",256)>2048)throw std::runtime_error("Offline sites allow depth 0-5, 1-100 pages and a 1-2048 MiB budget.");
}
JobPtr Manager::addOfflineProject(const Json& project,const std::string& queue,bool paused){
 validateOfflineProject(project);Lock lock(mutex);auto dest=grabberDestination(project,state["Settings"],str(project,"StartUrl"),safeName(str(project,"Name","Website"))+".zip");auto job=add(str(project,"StartUrl"),dest.folder,dest.name,queue,true,grabberRequestHeaders(project,"",str(project,"StartUrl")));
 try{if(!dest.category.empty())job->data["Category"]=dest.category;job->data["OfflineProject"]={{"StartUrl",str(project,"StartUrl")},{"Depth",num(project,"Depth",1)},{"MaxPages",num(project,"MaxPages",20)},{"MaxMiB",num(project,"MaxMiB",256)},{"ExternalAssets",yes(project,"ExternalAssets")},{"OriginalSubfolders",yes(project,"OriginalSubfolders")}};job->data["ProjectId"]=str(project,"Id");if(yes(project,"BrowserLogin"))job->data["ProtectedBrowserSession"]=protect(grabberBrowserSession(project).dump());job->data["Description"]="Offline website. Extract the ZIP, then open index.html.";job->data["Connections"]=1;job->data["Status"]=paused?"Paused":"Queued";save();}catch(...){jobs.erase(std::remove(jobs.begin(),jobs.end(),job),jobs.end());throw;}return job;
}
void offlineTransfer(Manager& manager,JobPtr job,const std::shared_ptr<Cancel>& cancel){
 Json project,prefs;Headers headers;{Lock lock(manager.mutex);project=job->data["OfflineProject"];prefs=browserSessionPreferences(manager.state["Settings"],job->data);headers=readHeaders(job->data);}validateOfflineProject(project);const auto started=std::chrono::steady_clock::now();
 auto start=canonical(str(project,"StartUrl")),origin=Url(start).origin;OfflineArchiveLayout layout(start);const bool hierarchy=yes(project,"OriginalSubfolders");auto cache=manager.root/L"parts"/wide(job->id())/L"offline";fs::create_directories(cache);Json saved=Json::object();auto manifest=cache/L"cache.json";if(fs::exists(manifest)){try{auto prior=Json::parse(readText(manifest));if(prior.value("Project",Json())==project)saved=prior.value("Files",Json::object());}catch(...) {}}
 auto checkpoint=[&]{atomicText(manifest,Json{{"Project",project},{"Files",saved}}.dump(),false);};
 struct Pending{std::string url;int depth;bool page;};std::vector<Pending> pending={{start,0,true}};std::set<std::string> queued={start};Json errors=Json::array();std::map<std::string,std::string> files;std::vector<Json> completed;size_t pages=0;uint64_t total=0,wireTotal=0,budget=(uint64_t)num(project,"MaxMiB",256)*1024*1024;Rate rate;std::shared_ptr<HttpSession> pool;
 {Lock lock(manager.mutex);job->data["Segments"]=Json::array({{{"Index",0},{"Start",0},{"Done",0}}});job->data["Received"]=0;job->data["Size"]=-1;job->workers={{1,0,0,0,0,"Saving website"}};}
 try {for(size_t index=0;index<pending.size();++index){cancel->check();auto item=pending[index];if(wireTotal>=budget){errors.push_back({{"Url",item.url},{"Message","Website transfer budget reached."}});break;}if(item.page&&pages>=(size_t)num(project,"MaxPages",20)){errors.push_back({{"Url",item.url},{"Message","Page limit reached."}});continue;}
  try {Json entry;std::string local="resource-"+std::to_string(index)+".raw";fs::path raw=cache/wide(local);auto found=saved.find(item.url);bool cached=false;
   if(found!=saved.end()&&str(*found,"Raw")==local&&fs::is_regular_file(raw)&&fs::file_size(raw)<=32*1024*1024&&fileHash(raw)==str(*found,"Hash")){entry=*found;cached=true;}
   if(!cached){if(!pool)pool=std::make_shared<HttpSession>(prefs,browserSessionSaver(manager,job,prefs.value("ActiveBrowserSession",Json::object())));std::string address=item.url;std::unique_ptr<Http> response;for(int hops=0;hops<11;++hops){auto sendHeaders=headers;if(Url(address).origin!=origin)sendHeaders.clear();response=std::make_unique<Http>(address,sendHeaders,prefs,*cancel,std::nullopt,std::nullopt,"",nullptr,false,pool);if(response->status>=300&&response->status<400){auto next=canonical(combineUrl(address,response->header(L"Location")));if((item.page||!yes(project,"ExternalAssets"))&&Url(next).origin!=origin)throw std::runtime_error("Redirect leaves the selected website.");if(Url(address).scheme=="https"&&Url(next).scheme!="https")throw std::runtime_error("HTTPS downgrade redirect rejected.");address=next;response.reset();continue;}break;}
    if(!response)throw std::runtime_error("Too many website redirects.");if(response->status<200||response->status>=300)throw HttpRejected(response->status,response->header(L"Retry-After"));auto content=lower(response->header(L"Content-Type"));auto encoding=lower(response->header(L"Content-Encoding"));if(!encoding.empty()&&encoding!="identity")throw std::runtime_error("Site ignored identity encoding.");bool html=content.find("html")!=std::string::npos;bool css=content.find("text/css")!=std::string::npos;size_t limit=html||css?2*1024*1024:32*1024*1024;
    std::ofstream output(raw,std::ios::binary|std::ios::trunc);if(!output)throw std::runtime_error("Cannot save website resource.");char buffer[65536];size_t received=0;for(;;){auto count=response->read(buffer,sizeof(buffer),*cancel);if(!count)break;wireTotal+=count;if(received+count>limit||total+received+count>budget||wireTotal>budget)throw std::runtime_error("Website resource or total size limit reached.");manager.charge(count,*cancel,rate,job);output.write(buffer,count);if(!output)throw std::runtime_error("Cannot write website resource.");received+=count;manager.progress(job,count,0,&job->workers[0]);}output.flush();if(!output)throw std::runtime_error("Cannot flush website resource.");output.close();
    auto length=response->header(L"Content-Length");if(!length.empty()&&std::stoull(length)!=received)throw std::runtime_error("Website resource ended before Content-Length.");entry={{"Raw",local},{"Hash",fileHash(raw)},{"Url",address},{"ContentType",content},{"Html",html},{"Css",css}};saved[item.url]=entry;checkpoint();
   }
   if(auto duplicate=files.find(str(entry,"Url"));duplicate!=files.end()){files[item.url]=duplicate->second;continue;}
   auto size=fs::file_size(raw);if(total+size>budget)throw std::runtime_error("Website total size limit reached.");total+=size;bool html=yes(entry,"Html"),css=yes(entry,"Css");if(index==0&&!html)throw std::runtime_error("The starting URL did not return an HTML page.");if(html){if(pages>=(size_t)num(project,"MaxPages",20))throw std::runtime_error("Page limit reached.");++pages;}
   std::string extension=html?".html":css?".css":lower(utf8(fs::path(wide(Url(str(entry,"Url")).path)).extension().wstring()));if(!html&&!css){auto mime=str(entry,"ContentType");mime=trim(mime.substr(0,mime.find(';')));static const std::map<std::string,std::string> types={{"image/svg+xml",".svg"},{"image/png",".png"},{"image/jpeg",".jpg"},{"image/gif",".gif"},{"image/webp",".webp"},{"image/avif",".avif"},{"font/woff2",".woff2"},{"font/woff",".woff"},{"font/ttf",".ttf"},{"audio/mpeg",".mp3"},{"video/mp4",".mp4"}};auto type=types.find(mime);if(type!=types.end())extension=type->second;}if(extension.empty()||extension.size()>12||extension.find_first_not_of(".abcdefghijklmnopqrstuvwxyz0123456789")!=std::string::npos)extension=".bin";
   std::string name=hierarchy?layout.file(str(entry,"Url"),extension,index==0):index==0?"index.html":"resource-"+std::to_string(index)+extension;files[item.url]=name;files[str(entry,"Url")]=name;entry["Name"]=name;completed.push_back(entry);
   if(cached){Lock lock(manager.mutex);job->data["Received"]=num(job->data,"Received")+size;} {Lock lock(manager.mutex);job->data["OfflinePages"]=pages;job->data["OfflineResources"]=completed.size();job->workers[0].state="Saved "+std::to_string(completed.size())+" resources";}
   if(html||css){auto source=readText(raw,2*1024*1024);auto base=html?documentBase(source,str(entry,"Url")):str(entry,"Url");for(auto ref:siteReferences(source,css)){if(ref.remove)continue;auto rawUrl=trim(ref.value);if(rawUrl.empty()||(rawUrl[0]=='#'&&base==str(entry,"Url")))continue;try{auto address=canonical(combineUrl(base,rawUrl));if(Url(base).scheme=="https"&&Url(address).scheme!="https")continue;if(ref.page){if(item.depth>=(int)num(project,"Depth",1)||Url(address).origin!=origin||!pageAddress(address))continue;}else if(Url(address).origin!=origin&&!yes(project,"ExternalAssets"))continue;if(queued.count(address))continue;if(pending.size()>=2000){if(errors.size()<2000)errors.push_back({{"Url",address},{"Message","Resource count limit reached."}});break;}queued.insert(address);pending.push_back({address,item.depth+(ref.page?1:0),ref.page});}catch(...) {}}
   }
  }catch(const Cancelled&){throw;}catch(const std::exception& e){if(index==0)throw;auto failed=cache/wide("resource-"+std::to_string(index)+".raw");if(saved.find(item.url)==saved.end()){std::error_code ignored;fs::remove(failed,ignored);}if(errors.size()<2000)errors.push_back({{"Url",item.url},{"Message",e.what()}});}
 }
 cancel->check();std::vector<std::pair<std::string,fs::path>> archive;for(const auto& entry:completed){auto raw=cache/wide(str(entry,"Raw"));if(yes(entry,"Html")||yes(entry,"Css")){auto rewritten=cache/(wide(str(entry,"Raw"))+L".rewritten");atomicText(rewritten,rewriteSiteDocument(readText(raw,2*1024*1024),str(entry,"Url"),yes(entry,"Css"),files,str(entry,"Name")),false);archive.push_back({str(entry,"Name"),rewritten});}else archive.push_back({str(entry,"Name"),raw});}
 if(hierarchy&&!completed.empty()&&str(completed[0],"Name")!="index.html"){const auto& first=completed[0];auto entry=cache/L"index.html.rewritten";atomicText(entry,rewriteSiteDocument(readText(cache/wide(str(first,"Raw")),2*1024*1024),str(first,"Url"),false,files,"index.html"),false);archive.push_back({"index.html",entry});}
 auto info=cache/L"UDM-offline-report.json";atomicText(info,Json{{"StartUrl",start},{"Pages",pages},{"Resources",completed.size()},{"Bytes",total},{"Errors",errors},{"Created",date()},{"OriginalSubfolders",hierarchy},{"Entry",completed.empty()?"":str(completed[0],"Name")},{"Files",files},{"Notes","Extract this ZIP and open index.html. Static pages, styles, images, fonts and media are saved within the selected limits. Scripts and form submissions are disabled. Uncaptured links open their original website."}}.dump(2),false);archive.push_back({"UDM-offline-report.json",info});
 auto folder=job->target().parent_path();fs::create_directories(folder);auto staging=folder/(L".udm-"+wide(job->id())+L".assembling");{Lock lock(manager.mutex);job->data["Status"]="Verifying";job->data["OfflineErrors"]=errors;job->data["OfflineSavedBytes"]=total;}zipSite(staging,archive,*cancel);cancel->check();auto hash=fileHash(staging);{Lock lock(manager.mutex);if(!str(job->data,"ExpectedSha256").empty()&&lower(str(job->data,"ExpectedSha256"))!=hash)throw std::runtime_error("SHA-256 mismatch. The offline archive was not published.");}manager.publishFile(job,staging,hash);markZone(job->target());{Lock lock(manager.mutex);job->data["TransferSeconds"]=real(job->data,"TransferSeconds")+std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count();if(!errors.empty())job->data["Error"]="Saved with "+std::to_string(errors.size())+" omitted resources; see UDM-offline-report.json inside the ZIP.";manager.save();}
 // Archive paths never become cache paths. Only generated flat cache files are removed after verified publication and state persistence.
 std::error_code cleanup;for(auto it=fs::directory_iterator(cache,cleanup);!cleanup&&it!=fs::directory_iterator();it.increment(cleanup)){auto name=utf8(it->path().filename().wstring());if(name=="cache.json"||name=="UDM-offline-report.json"||std::regex_match(name,std::regex("resource-[0-9]+\\.raw(?:\\.rewritten)?|(?:index\\.html|resource-[0-9]+\\.[a-z0-9]+)\\.rewritten")))fs::remove(it->path(),cleanup);}if(!cleanup)fs::remove(cache,cleanup);
 }catch(...){Lock lock(manager.mutex);job->data["TransferSeconds"]=real(job->data,"TransferSeconds")+std::chrono::duration<double>(std::chrono::steady_clock::now()-started).count();throw;}
}
}
