// Drives and renders only native windows owned by this isolated test executable.
#define UDM_TOOLBAR_COMPONENT_TEST
#include "App.cpp"
namespace udm {
static Json results=Json::array();static fs::path output;static std::string failure;static std::wstring expectedTitle;static std::function<void(HWND)> action;static ULONGLONG began;
static void expect(bool value,const char* name){results.push_back({{"name",name},{"passed",value}});if(!value)throw std::runtime_error(name);}
static Json mainQueue(Manager& m){for(const auto& q:m.state["Queues"])if(str(q,"Name")=="Main queue")return q;throw std::runtime_error("Missing Main queue fixture");}
static std::wstring windowText(HWND w){wchar_t text[512]{};GetWindowTextW(w,text,512);return text;}
static HWND child(HWND parent,const wchar_t* label){for(HWND c=GetWindow(parent,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT))if(windowText(c)==label&&IsWindowVisible(c))return c;throw std::runtime_error("Missing owned test control: "+utf8(label));}
static std::vector<HWND> children(HWND parent,const wchar_t* type){std::vector<HWND> result;for(HWND c=GetWindow(parent,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT)){wchar_t name[128]{};GetClassNameW(c,name,128);if(!_wcsicmp(name,type))result.push_back(c);}return result;}
static void press(HWND w,const wchar_t* label){auto c=child(w,label);expect(IsWindowEnabled(c)!=FALSE,"Requested native button is enabled");SendMessageW(c,BM_CLICK,0,0);}
static void selectCombo(HWND parent,HWND control,int index){SendMessageW(control,CB_SETCURSEL,index,0);SendMessageW(parent,WM_COMMAND,MAKEWPARAM(GetDlgCtrlID(control),CBN_SELCHANGE),(LPARAM)control);}
static CRect bounds(HWND w){CRect r;GetWindowRect(w,&r);return r;}
static void capture(HWND w,const wchar_t* name){
 ShowWindow(w,SW_SHOWNOACTIVATE);RedrawWindow(w,nullptr,nullptr,RDW_INVALIDATE|RDW_ALLCHILDREN|RDW_UPDATENOW|RDW_ERASE);auto r=bounds(w);CImage img;img.Create(r.Width(),r.Height(),32);auto dc=img.GetDC();RECT fill{0,0,r.Width(),r.Height()};FillRect(dc,&fill,GetSysColorBrush(COLOR_BTNFACE));SendMessageW(w,WM_PRINT,(WPARAM)dc,PRF_NONCLIENT|PRF_CLIENT|PRF_ERASEBKGND|PRF_CHILDREN);
 for(HWND c=GetWindow(w,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT)){if(!(GetWindowLongW(c,GWL_STYLE)&WS_VISIBLE))continue;auto cr=bounds(c);auto saved=SaveDC(dc);IntersectClipRect(dc,cr.left-r.left,cr.top-r.top,cr.right-r.left,cr.bottom-r.top);SetViewportOrgEx(dc,cr.left-r.left,cr.top-r.top,nullptr);SendMessageW(c,WM_PRINT,(WPARAM)dc,PRF_NONCLIENT|PRF_CLIENT|PRF_ERASEBKGND|PRF_CHILDREN);RestoreDC(dc,saved);}
 img.ReleaseDC();if(FAILED(img.Save((output/name).c_str())))throw std::runtime_error("Could not render native test dialog");
}
static BOOL CALLBACK observe(HWND w,LPARAM){if(windowText(w)!=expectedTitle)return TRUE;try{ShowWindow(w,SW_SHOWNOACTIVATE);action(w);}catch(const std::exception& e){failure=e.what();PostMessageW(w,WM_CLOSE,0,0);}return FALSE;}
static void CALLBACK onTimer(HWND,UINT,UINT_PTR,DWORD){if(GetTickCount64()-began>12000){failure="Owned dialog test deadline";EnumThreadWindows(GetCurrentThreadId(),[](HWND w,LPARAM)->BOOL{PostMessageW(w,WM_CLOSE,0,0);return TRUE;},0);return;}EnumThreadWindows(GetCurrentThreadId(),observe,0);}
static void modal(Form& dialog,const wchar_t* caption,std::function<void(HWND)> callback){expectedTitle=caption;action=std::move(callback);began=GetTickCount64();auto timer=SetTimer(nullptr,0,80,onTimer);dialog.DoModal();KillTimer(nullptr,timer);action={};if(!failure.empty())throw std::runtime_error(failure);}

class OptionsTabsApplication:public CWinApp {
 int code=1;
public:BOOL InitInstance()override{
 CWinApp::InitInstance();INITCOMMONCONTROLSEX common{sizeof(common),ICC_WIN95_CLASSES|ICC_DATE_CLASSES};InitCommonControlsEx(&common);AfxOleInit();int argc=0;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);
 try{if(argc!=2)throw std::runtime_error("Pass isolated output directory");output=fs::path(argv[1]);fs::create_directories(output);Manager manager(output/L"state");auto initial=manager.state["Settings"];int sequence=0;for(bool skip:{false,true})for(bool later:{false,true})for(bool explicitLater:{false,true}){auto settings=initial;settings["SkipBrowserFileInfo"]=skip;settings["BrowserDownloadLater"]=later;settings["PrefetchFileInfo"]=false;manager.setSettings(settings);auto name="policy-"+std::to_string(++sequence)+".bin";auto job=manager.receive({{"action","add"},{"url","https://example.test/"+name},{"filename",name},{"downloadLater",explicitLater}});std::string expected=explicitLater?"Paused":!skip?"Awaiting confirmation":later?"Paused":"Queued";expect(str(job->data,"Status")==expected,"Real browser admission obeys dialog and explicit-later precedence");}manager.setSettings(initial);auto before=manager.snapshot();Options dialog(manager,nullptr,{},[]{return std::vector<DialEntry>{};});
 modal(dialog,L"UDM Configuration",[&](HWND w){auto tab=children(w,L"SysTabControl32").at(0);
 const wchar_t* names[]={L"General",L"File types",L"Save to",L"Downloads",L"Connection",L"Proxy / Socks",L"Sites Logins",L"Dial Up / VPN",L"Sounds"};
 const wchar_t* headings[]={L"Browser/System Integration",L"Downloaded file types",L"Categories, file types, folders",L"Default download settings",L"Connections and Limits",L"Proxy / socks configuration",L"User names and passwords for servers/sites",L"Dial up / VPN settings",L"Sound settings"};
 int editors=0;for(auto c=GetWindow(w,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT))if(IsWindowVisible(c)&&windowText(c)==L"Edit...")++editors;expect(editors==2,"Browser menu and video panel settings both have labeled Edit buttons");expect(TabCtrl_GetItemCount(tab)==9,"Configuration exposes all nine reference tabs");
 for(int i=0;i<9;++i){wchar_t name[128]{};TCITEMW item{};item.mask=TCIF_TEXT;item.pszText=name;item.cchTextMax=128;TabCtrl_GetItem(tab,i,&item);expect(std::wstring(name)==names[i],("Tab order: "+utf8(names[i])).c_str());TabCtrl_SetCurSel(tab,i);NMHDR notice{tab,(UINT_PTR)GetDlgCtrlID(tab),TCN_SELCHANGE};SendMessageW(w,WM_NOTIFY,notice.idFrom,(LPARAM)&notice);expect(IsWindowVisible(child(w,headings[i]))!=FALSE,("Correct settings page: "+utf8(names[i])).c_str());for(int j=0;j<9;++j){if(j==i)continue;for(auto c=GetWindow(w,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT))if(windowText(c)==headings[j])expect(!IsWindowVisible(c),"Inactive page heading remains hidden");}capture(w,(L"tab-"+std::to_wstring(i)+L".png").c_str());}
TabCtrl_SetCurSel(tab,3);NMHDR changed{tab,(UINT_PTR)GetDlgCtrlID(tab),TCN_SELCHANGE};SendMessageW(w,WM_NOTIFY,changed.idFrom,(LPARAM)&changed);auto start=child(w,L"Show start download dialog"),later=child(w,L"Do not start downloading; only add files to the queue");expect(!IsWindowEnabled(later),"Queue-only preference is disabled while start dialog is shown");SendMessageW(start,BM_CLICK,0,0);expect(IsWindowEnabled(later),"Hiding start dialog enables queue-only preference");SendMessageW(later,BM_CLICK,0,0);expect(SendMessageW(later,BM_GETCHECK,0,0)==BST_CHECKED,"Queue-only preference can be selected");SendMessageW(start,BM_CLICK,0,0);expect(!IsWindowEnabled(later)&&SendMessageW(later,BM_GETCHECK,0,0)==BST_CHECKED,"Showing dialog disables but remembers queue-only choice");SendMessageW(start,BM_CLICK,0,0);expect(IsWindowEnabled(later)&&SendMessageW(later,BM_GETCHECK,0,0)==BST_CHECKED,"Hiding dialog restores remembered queue-only choice");capture(w,L"download-policy.png"); press(w,L"Cancel");});expect(manager.snapshot()==before,"Browsing and canceling tabs preserves settings and catalog");code=0;
 }catch(const std::exception& e){failure=e.what();}if(argv)LocalFree(argv);if(!output.empty())atomicText(output/L"results.json",Json{{"passed",code==0},{"error",failure},{"checks",results}}.dump(2),false);return FALSE;}
 int ExitInstance()override{AfxOleTerm(FALSE);return code;}
};OptionsTabsApplication application;
}