#pragma once
static void overwriteChecks(const fs::path& root,Fixture& fixture){
 Manager m(root/L"overwrite-state");auto settings=m.state["Settings"];settings["DownloadFolder"]=utf8((root/L"overwrite-files").wstring());settings["CategoryFolders"]=false;settings["PrefetchFileInfo"]=false;settings["Retries"]=0;m.setSettings(settings);
 auto seed=[&](const char* path,const char* name){auto job=m.add(fixture.url(path),"",name);job->data["Size"]=(i64)fixture.payload.size();job->data["Received"]=262144;job->data["ETag"]="\"fixture-v1\"";job->data["RangeSupported"]=true;job->data["Segments"]=Json::array({{{"Index",0},{"Start",0},{"End",(i64)fixture.payload.size()-1},{"Done",262144}}});auto parts=m.root/L"parts"/wide(job->id());fs::create_directories(parts);writeBytes(parts/L"0000.part",Bytes(262144,'x'));m.save();return job;};
 auto expected=root/L"overwrite-expected.bin";writeBytes(expected,Bytes(fixture.payload.begin(),fixture.payload.end()));auto digest=fileHash(expected);
 auto original=seed("/overwrite","retained-name.bin");auto id=original->id();auto oldTarget=original->target();auto oldParts=m.root/L"parts"/wide(id);original->data["Description"]="preserved description";original->data["Connections"]=3;m.save();
 auto incoming=m.offerDownload(fixture.url("/overwrite"));auto oldData=original->data,pendingData=incoming->data;auto oldCount=m.jobs.size();auto catalogHash=fileHash(m.root/L"state.json");auto blocker=m.root/L"state.json.tmp";fs::create_directory(blocker);
 rejects([&]{m.resolveDuplicate(incoming,"Replace",true);},"Overwrite reports a catalog write failure before discarding saved parts");fs::remove(blocker);
 check(original->data==oldData&&incoming->data==pendingData&&m.jobs.size()==oldCount&&str(m.state["Settings"],"DuplicatePolicy")=="Ask"&&fileHash(m.root/L"state.json")==catalogHash,"Failed remembered overwrite restores preference, records and saved catalog atomically");
 check(fs::file_size(oldParts/L"0000.part")==262144,"Failed overwrite preserves the entire existing prefix");
 auto restarted=m.resolveDuplicate(incoming,"Replace",true);
 check(restarted==original&&restarted->id()==id&&restarted->target()==oldTarget&&m.jobs.size()==oldCount-1,"Unfinished overwrite keeps the original record and filename");
 check(num(restarted->data,"Received")==0&&num(restarted->data,"Size")==-1&&restarted->data["Segments"].empty()&&str(restarted->data,"ETag").empty(),"Overwrite clears stale ranges, validators and byte counters");
 check(str(restarted->data,"Description")=="preserved description"&&num(restarted->data,"Connections")==3,"Overwrite retains the download's chosen metadata and connection settings");
 check(!str(restarted->data,"RestartAttempt").empty()&&fs::path(wide(str(restarted->data,"PartsFolder")))!=oldParts&&!fs::exists(oldParts/L"0000.part"),"Committed overwrite uses fresh parts and retires the old generation");
 check(str(m.state["Settings"],"DuplicatePolicy")=="Replace","Overwrite and its remembered preference commit together");
 check(m.presentOffer(restarted)==OfferPresentation::Information,"Explicit overwrite reaches File Info instead of accidental Existing resume");
 fixture.resumedPrefix=false;transfer(m,restarted,std::make_shared<Cancel>());
 check(str(restarted->data,"Status")=="Complete"&&!fixture.resumedPrefix&&fileHash(oldTarget)==digest,"Actual unfinished overwrite starts from zero and publishes exact HTTP bytes");
 auto replacement=m.offerDownload(fixture.url("/overwrite"));check(str(replacement->data,"DuplicateOf").empty()&&str(replacement->data,"ReplacementOf")==id&&fileHash(oldTarget)==digest,"Remembered overwrite prepares completed-file replacement without another duplicate prompt");
 check(m.offerDownload(fixture.url("/overwrite"))==replacement,"Repeated remembered overwrite reuses its pending replacement instead of nesting one");m.remove(replacement);
 auto another=seed("/auto-restart","auto.bin");auto oldAttempt=str(another->data,"RestartAttempt");auto automatic=m.offerDownload(fixture.url("/auto-restart"),"","","Main queue",false);
 check(automatic==another&&str(automatic->data,"Status")=="Queued"&&str(automatic->data,"RestartAttempt")!=oldAttempt,"Remembered overwrite preserves an immediate-start request for an unfinished download");m.pause(automatic);
 auto browser=seed("/browser-overwrite","browser.bin");auto prefs=m.state["Settings"];prefs["SkipBrowserFileInfo"]=true;m.setSettings(prefs);auto offered=m.receive({{"action","add"},{"url",fixture.url("/browser-overwrite")}});
 check(offered==browser&&str(offered->data,"Status")=="Queued"&&m.pendingOffers.empty(),"Browser overwrite respects disabled File Info and queues the restarted record");m.pause(offered);
 prefs["SkipBrowserFileInfo"]=false;m.setSettings(prefs);offered=m.receive({{"action","add"},{"url",fixture.url("/browser-overwrite")}});
 check(offered==browser&&str(offered->data,"Status")=="Awaiting confirmation","Browser overwrite still requires File Info when that preference is enabled");m.pause(offered);
 offered=m.receive({{"action","cli-add"},{"url",fixture.url("/browser-overwrite")},{"silent",true}});check(offered==browser&&str(offered->data,"Status")=="Queued","Silent command-line overwrite uses the fresh-download routing");m.pause(offered);
 auto missing=m.add(fixture.url("/missing-overwrite"),"","missing.bin");missing->data["Status"]="Complete";missing->data["Size"]=17;m.save();auto restored=m.offerDownload(fixture.url("/missing-overwrite"));
 check(restored==missing&&num(restored->data,"Received")==0&&str(restored->data,"Status")=="Paused","Overwrite can restore a completed record whose file was removed");
 transfer(m,restored,std::make_shared<Cancel>());check(fileHash(restored->target())==digest,"Missing completed file is restored with exact downloaded bytes");
 auto edited=m.add(fixture.url("/edited-overwrite"),"","edited.bin");fs::create_directories(edited->target().parent_path());writeBytes(edited->target(),Bytes{'e','d','i','t'});edited->data["Status"]="Complete";edited->data["Sha256"]=std::string(64,'0');edited->data["Size"]=100;edited->data["ScanResult"]={{"Status","Finished"},{"ExitCode",0}};
 auto editedIncoming=m.offerDownload(fixture.url("/edited-overwrite"));auto previous=fs::path(wide(str(editedIncoming->data,"PreviousPath")));transfer(m,editedIncoming,std::make_shared<Cancel>());
 check(fileHash(editedIncoming->target())==digest&&readText(previous)=="edit"&&str(edited->data,"Sha256")==fileHash(previous)&&num(edited->data,"Size")==4,"Explicit overwrite replaces an edited file and keeps an accurately recorded previous copy");
 check(!edited->data.contains("ScanResult"),"An edited previous copy cannot retain a scan result for different bytes");
 auto occupied=seed("/occupied-overwrite","occupied.bin");writeBytes(occupied->target(),Bytes{'u','s','e','r'});auto occupiedBefore=occupied->data;rejects([&]{m.offerDownload(fixture.url("/occupied-overwrite"));},"Unfinished overwrite cannot destroy a different file occupying its destination");check(readText(occupied->target())=="user"&&occupied->data==occupiedBefore,"Rejected occupied-path overwrite leaves both record and user file intact");
 auto queued=seed("/queued-overwrite","queued.bin");m.resume(queued);auto generation=str(queued->data,"RestartAttempt");check(m.offerDownload(fixture.url("/queued-overwrite"))==queued&&str(queued->data,"RestartAttempt")==generation,"Repeated overwrite request does not reset an already queued transfer");m.pause(queued);
 auto locked=seed("/locked-parts","locked.bin");auto lockedParts=m.root/L"parts"/wide(locked->id());writeBytes(lockedParts/L"notes.txt",Bytes{'n','o','t','e'});
 {Handle hold(CreateFileW((lockedParts/L"0000.part").c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));check((bool)hold,"Old-part lock fixture opens successfully");m.offerDownload(fixture.url("/locked-parts"));check(fs::exists(lockedParts/L"0000.part")&&!str(locked->data,"RestartAttempt").empty(),"Locked old parts do not prevent a committed fresh restart");}
 m.recoverRestarts();check(!fs::exists(lockedParts/L"0000.part")&&readText(lockedParts/L"notes.txt")=="note","Cleanup retries locked parts and preserves unrelated files");
 auto custom=seed("/custom-overwrite","custom.bin");prefs=m.state["Settings"];prefs["TemporaryFolder"]=utf8((root/L"overwrite-custom-temporary").wstring());m.setSettings(prefs);m.offerDownload(fixture.url("/custom-overwrite"));check(fs::path(wide(str(custom->data,"PartsFolder"))).parent_path()==root/L"overwrite-custom-temporary"/L"UDM-parts","Fresh overwrite honors the selected temporary directory");
 {Manager reopen(m.root);check(str(reopen.state["Settings"],"DuplicatePolicy")=="Replace","Remembered overwrite survives process restart");bool found=false;for(auto item:reopen.jobs)if(item->id()==custom->id())found=str(item->data,"PartsFolder")==str(custom->data,"PartsFolder");check(found,"Fresh parts selection survives process restart");}
 // Crash receipts distinguish a prepared action from a catalog commit.
 for(int phase=0;phase<3;++phase){Manager recovery(root/(L"restart-recovery-"+std::to_wstring(phase)));auto job=recovery.add(fixture.url("/restart-recovery"));auto before=job->data;auto attempt=guid();auto parts=recovery.root/L"parts"/wide(job->id());fs::create_directories(parts);auto part=parts/L"0000.part";writeBytes(part,Bytes{'o','l','d'});auto op=Json{{"Schema",1},{"Id",job->id()},{"Attempt",attempt},{"Before",before},{"Parts",utf8(parts.wstring())},{"Files",Json::array({{{"Name","0000.part"},{"Size",3},{"Stamp",fs::last_write_time(part).time_since_epoch().count()}}})},{"Committed",false}};
  if(phase){job->data["RestartAttempt"]=attempt;job->data["PartsFolder"]=utf8((recovery.root/L"parts"/wide(attempt)).wstring());}recovery.save();auto journal=recovery.root/L"restarts"/(wide(attempt)+L".json");atomicText(journal,op.dump(),false);if(phase==2)writeBytes(part,Bytes{'e','d','i','t'});recovery.recoverRestarts();
  check(phase==0?(readText(part)=="old"&&!fs::exists(journal)):phase==1?(!fs::exists(part)&&!fs::exists(journal)):(readText(part)=="edit"&&fs::exists(journal)),("Restart cleanup recovers commit phase "+std::to_string(phase)+" without deleting uncommitted or changed bytes").c_str());
 }
 m.stop();
}
