// Exercises only the properties dialog belonging to this isolated fixture.
#define UDM_TOOLBAR_COMPONENT_TEST
#include "App.cpp"
namespace udm {
static fs::path renderRoot;
static CRect bounds(HWND window){CRect r;::GetWindowRect(window,&r);return r;}
static bool shown(HWND window){return (::GetWindowLongW(window,GWL_STYLE)&WS_VISIBLE)!=0;}
static void captureComponent(HWND window,const fs::path& file){
 ::ShowWindow(window,SW_SHOWNOACTIVATE);::RedrawWindow(window,nullptr,nullptr,RDW_INVALIDATE|RDW_ALLCHILDREN|RDW_UPDATENOW|RDW_ERASE);
 auto r=bounds(window);CImage image;image.Create(r.Width(),r.Height(),32);auto dc=image.GetDC();
 RECT all{0,0,r.Width(),r.Height()};FillRect(dc,&all,GetSysColorBrush(COLOR_BTNFACE));
 SendMessageW(window,WM_PRINT,(WPARAM)dc,PRF_NONCLIENT|PRF_CLIENT|PRF_ERASEBKGND|PRF_CHILDREN);
 for(auto child=::GetWindow(window,GW_CHILD);child;child=::GetWindow(child,GW_HWNDNEXT)){
  if(!shown(child))continue;auto c=bounds(child);auto save=SaveDC(dc);
  IntersectClipRect(dc,c.left-r.left,c.top-r.top,c.right-r.left,c.bottom-r.top);
  SetViewportOrgEx(dc,c.left-r.left,c.top-r.top,nullptr);
  SendMessageW(child,WM_PRINT,(WPARAM)dc,PRF_NONCLIENT|PRF_CLIENT|PRF_ERASEBKGND|PRF_CHILDREN);RestoreDC(dc,save);
 }
 image.ReleaseDC();if(FAILED(image.Save(file.c_str())))throw std::runtime_error("Could not render own test window");
}
static Json results=Json::array();static std::string failure;static std::function<void(HWND)> action;static ULONGLONG began;
static void expect(bool value,const char* name){results.push_back({{"name",name},{"passed",value}});if(!value)throw std::runtime_error(name);}
static std::wstring label(HWND w){wchar_t text[256]{};GetWindowTextW(w,text,256);return text;}
static HWND named(HWND w,const wchar_t* name){for(auto c=GetWindow(w,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT))if(label(c)==name)return c;throw std::runtime_error("Missing fixture button");}
static HWND typed(HWND w,const wchar_t* type){for(auto c=GetWindow(w,GW_CHILD);c;c=GetWindow(c,GW_HWNDNEXT)){wchar_t name[128]{};GetClassNameW(c,name,128);if(!_wcsicmp(name,type))return c;}throw std::runtime_error("Missing fixture control");}
static void click(HWND w,const wchar_t* name){auto c=named(w,name);expect(IsWindowEnabled(c)!=FALSE,"Requested properties-dialog action is enabled");SendMessageW(c,BM_CLICK,0,0);}
static void select(HWND list,int row){LVITEMW item{};item.stateMask=LVIS_SELECTED|LVIS_FOCUSED;SendMessageW(list,LVM_SETITEMSTATE,-1,(LPARAM)&item);if(row>=0){item.state=LVIS_SELECTED|LVIS_FOCUSED;SendMessageW(list,LVM_SETITEMSTATE,row,(LPARAM)&item);}}
static BOOL CALLBACK observe(HWND w,LPARAM){if(label(w)!=L"File Properties")return TRUE;try{auto once=std::move(action);if(once)once(w);}catch(const std::exception& e){failure=e.what();PostMessageW(w,WM_CLOSE,0,0);}return FALSE;}
static void CALLBACK tick(HWND,UINT,UINT_PTR,DWORD){if(GetTickCount64()-began>15000){failure="Properties dialog deadline";EnumThreadWindows(GetCurrentThreadId(),[](HWND w,LPARAM)->BOOL{PostMessageW(w,WM_CLOSE,0,0);return TRUE;},0);return;}EnumThreadWindows(GetCurrentThreadId(),observe,0);}
class ToolbarComponentTest {
public:static void run(MainWindow& frame){
 frame.ShowWindow(SW_SHOWNOACTIVATE);
 auto job=frame.manager.add("https://fixture.example/download","","fixture.bin");job->data["Description"]="original";
 auto open=[&](std::function<void(HWND)> callback,bool doubleClick=false){action=std::move(callback);began=GetTickCount64();auto timer=SetTimer(nullptr,0,75,tick);if(doubleClick){auto at=std::find(frame.visible.begin(),frame.visible.end(),job);expect(at!=frame.visible.end(),"Completed download is visible before double-click");NMITEMACTIVATE notification{};notification.hdr.hwndFrom=frame.table.GetSafeHwnd();notification.hdr.code=NM_DBLCLK;notification.iItem=(int)std::distance(frame.visible.begin(),at);LRESULT result=0;expect(frame.OnNotify(0,(LPARAM)&notification,&result)!=FALSE,"Main-window double-click notification is handled");}else fileProperties(&frame,frame.manager,job);KillTimer(nullptr,timer);if(!failure.empty())throw std::runtime_error(failure);};
 auto edits=[](HWND w){std::vector<HWND> list;for(auto child=GetWindow(w,GW_CHILD);child;child=GetWindow(child,GW_HWNDNEXT)){wchar_t type[80]{};GetClassNameW(child,type,80);if(!_wcsicmp(type,L"Edit"))list.push_back(child);}return list;};
 auto before=job->snapshot();
 open([&](HWND w){auto fields=edits(w);expect(fields.size()==6,"Properties exposes destination, address, description, Referer, login and password");expect(!IsWindowEnabled(named(w,L"Open")),"Incomplete file cannot be opened");expect(IsWindowEnabled(named(w,L"&Browse...")),"Inactive destination can be browsed");expect(SendMessageW(fields[5],EM_GETPASSWORDCHAR,0,0)!=0,"Password is masked by default");SetWindowTextW(fields[2],L"discarded");SendMessageW(w,WM_CLOSE,0,0);});
 expect(job->snapshot()==before,"Closing Properties without OK preserves the entire record");
 open([&](HWND w){auto fields=edits(w);SetWindowTextW(fields[2],L"saved description");SetWindowTextW(fields[3],L"https://fixture.example/source");SetWindowTextW(fields[4],L"fixture-user");SetWindowTextW(fields[5],L"fixture-password");click(w,L"OK");});
 expect(str(job->data,"Description")=="saved description","OK saves description");auto headers=readHeaders(job->data);expect(headerValue(headers,"Referer")=="https://fixture.example/source","OK saves Referer");expect(basicLogin(headers)==std::make_pair(std::string("fixture-user"),std::string("fixture-password")),"OK saves protected basic authentication");
 fs::create_directories(job->target().parent_path());atomicText(job->target(),"fixture bytes",false);job->data["Status"]="Complete";job->data["Size"]=13;job->data["Received"]=13;
 auto other=frame.manager.add("https://fixture.example/other","","other.bin");frame.refresh();auto otherAt=std::find(frame.visible.begin(),frame.visible.end(),other);select(frame.table.GetSafeHwnd(),(int)std::distance(frame.visible.begin(),otherAt));expect(frame.selected().size()==1&&frame.selected().front()==other,"Another row is selected before completed-file double-click");
 open([&](HWND w){auto fields=edits(w);expect(label(fields[1])==L"https://fixture.example/download","Completed-file double-click opens the clicked record's Properties");expect(IsWindowEnabled(named(w,L"Open")),"Complete file can be opened");expect(IsWindowEnabled(named(w,L"&Move...")),"Complete file exposes Move");expect((GetWindowLongW(fields[0],GWL_STYLE)&ES_READONLY)!=0,"Complete destination is read-only until Move");expect(label(fields[2])==L"saved description","Properties reopens with saved description");
 auto link=dynamic_cast<StaticHyperlink*>(CWnd::FromHandlePermanent(named(w,L"https://fixture.example/source")));auto form=dynamic_cast<Form*>(CWnd::FromHandlePermanent(w));expect(link&&form,"Source-page control is the native Static hyperlink implementation");int activations=0;form->bind(link,[&]{activations++;});link->SetFocus();expect(::GetFocus()==link->GetSafeHwnd(),"Source-page Static link accepts keyboard focus");
 MSG key{};key.hwnd=link->GetSafeHwnd();key.message=WM_KEYDOWN;key.wParam=VK_RETURN;expect(link->PreTranslateMessage(&key)&&activations==1,"Enter activates the source-page link once");key.lParam=1L<<30;expect(link->PreTranslateMessage(&key)&&activations==1,"Held Enter does not repeatedly activate the link");key.message=WM_KEYUP;key.lParam=0;expect(link->PreTranslateMessage(&key)&&activations==1,"Enter release does not activate twice");key.message=WM_KEYDOWN;key.wParam=VK_SPACE;expect(link->PreTranslateMessage(&key)&&activations==2,"Space activates the source-page link");
 link->EnableWindow(FALSE);link->PreTranslateMessage(&key);expect(activations==2,"Disabled source-page link ignores keyboard activation");link->EnableWindow(TRUE);SendMessageW(link->GetSafeHwnd(),WM_LBUTTONDOWN,MK_LBUTTON,MAKELPARAM(2,2));SendMessageW(link->GetSafeHwnd(),WM_LBUTTONUP,0,MAKELPARAM(2,2));expect(activations==3,"Native Static mouse notification activates the source-page link once");
 const auto reference=Json::parse(R"ref([{"id":1325,"x":7,"y":36,"width":44,"height":9,"title":"Type:","class":130},{"id":1093,"x":58,"y":36,"width":253,"height":9,"title":"Static","class":130},{"id":1299,"x":7,"y":48,"width":43,"height":9,"title":"Status:","class":130},{"id":1098,"x":58,"y":48,"width":253,"height":9,"title":"Static","class":130},{"id":1324,"x":7,"y":60,"width":43,"height":9,"title":"Size:","class":130},{"id":1095,"x":58,"y":60,"width":253,"height":9,"title":"Static","class":130},{"id":1323,"x":7,"y":77,"width":45,"height":9,"title":"Save To:","class":130},{"id":1096,"x":58,"y":74,"width":197,"height":14,"title":"","class":129},{"id":1082,"x":261,"y":74,"width":50,"height":14,"title":"&Browse...","class":128},{"id":1619,"x":7,"y":96,"width":44,"height":9,"title":"Address:","class":130},{"id":1097,"x":58,"y":93,"width":253,"height":14,"title":"","class":129},{"id":1298,"x":7,"y":115,"width":47,"height":9,"title":"Description:","class":130},{"id":1099,"x":58,"y":112,"width":253,"height":14,"title":"","class":129},{"id":1741,"x":7,"y":136,"width":304,"height":9,"title":"The web page from which this file was obtained:","class":130},{"id":1734,"x":7,"y":149,"width":304,"height":9,"title":"Unknown","class":130},{"id":1570,"x":7,"y":171,"width":47,"height":9,"title":"Referer:","class":130},{"id":1569,"x":58,"y":167,"width":253,"height":14,"title":"","class":129},{"id":1322,"x":23,"y":188,"width":50,"height":9,"title":"Login","class":130},{"id":1033,"x":80,"y":185,"width":126,"height":13,"title":"","class":129},{"id":1289,"x":21,"y":205,"width":52,"height":9,"title":"Password","class":130},{"id":1041,"x":80,"y":203,"width":126,"height":13,"title":"","class":129},{"id":1164,"x":172,"y":227,"width":50,"height":14,"title":"Open","class":128},{"id":1092,"x":261,"y":227,"width":50,"height":14,"title":"OK","class":128}])ref");
 for(UINT dpi:{96u,144u,192u}){auto suggested=bounds(w);SendMessageW(w,WM_DPICHANGED,MAKEWPARAM(dpi,dpi),(LPARAM)&suggested);CRect client;GetClientRect(w,&client);for(auto child=GetWindow(w,GW_CHILD);child;child=GetWindow(child,GW_HWNDNEXT)){if(!shown(child))continue;auto rect=bounds(child);MapWindowPoints(nullptr,w,(POINT*)&rect,2);expect(rect.left>=0&&rect.top>=0&&rect.right<=client.right&&rect.bottom<=client.bottom,"Properties controls fit inside client area at tested DPI");}CFont referenceFont;referenceFont.CreateFontW(-MulDiv(8,dpi,72),0,0,0,FW_NORMAL,FALSE,FALSE,FALSE,DEFAULT_CHARSET,OUT_DEFAULT_PRECIS,CLIP_DEFAULT_PRECIS,DEFAULT_QUALITY,DEFAULT_PITCH,L"Tahoma");auto dc=GetDC(w);auto units=DialogUnits::measure(dc,(HFONT)referenceFont.GetSafeHandle());ReleaseDC(w,dc);
 LOGFONTW actualFont{};GetObjectW((HFONT)SendMessageW(fields[2],WM_GETFONT,0,0),sizeof(actualFont),&actualFont);expect(actualFont.lfHeight==-MulDiv(8,dpi,72)&&!wcscmp(actualFont.lfFaceName,L"Tahoma"),"Properties field uses the reference point size and font at tested DPI");
 for(const auto& ref:reference){auto target=CRect(units.rect((int)ref["x"],(int)ref["y"],(int)ref["width"],(int)ref["height"]));bool matched=false;
 for(auto child=GetWindow(w,GW_CHILD);child;child=GetWindow(child,GW_HWNDNEXT)){auto actual=bounds(child);MapWindowPoints(nullptr,w,(POINT*)&actual,2);if(actual!=target)continue;
 wchar_t type[80]{};GetClassNameW(child,type,80);const int role=ref["class"];if((role==130&&_wcsicmp(type,L"Static"))||(role==129&&_wcsicmp(type,L"Edit"))||(role==128&&_wcsicmp(type,L"Button")))continue;
 auto title=str(ref,"title");if(title=="Static"||title.empty()||title=="Unknown"||title=="&Browse..."||label(child)==wide(title))matched=true;
 }if(!matched){Json observed=Json::array();for(auto child=GetWindow(w,GW_CHILD);child;child=GetWindow(child,GW_HWNDNEXT)){auto actual=bounds(child);MapWindowPoints(nullptr,w,(POINT*)&actual,2);wchar_t type[80]{};GetClassNameW(child,type,80);observed.push_back({{"title",utf8(label(child))},{"class",utf8(type)},{"rect",{actual.left,actual.top,actual.right,actual.bottom}}});}atomicText(renderRoot/L"geometry-failure.json",Json{{"dpi",dpi},{"units",{units.x,units.y}},{"reference",ref},{"expected",{target.left,target.top,target.right,target.bottom}},{"controls",observed}}.dump(2),false);}expect(matched,"Properties reference geometry, static labels and control classes match");}
 captureComponent(w,renderRoot/wide("properties-"+std::to_string(dpi)+".png"));}SendMessageW(w,WM_CLOSE,0,0);},true);
 expect(frame.selected().size()==1&&frame.selected().front()==job,"Double-click selects only the clicked completed row");
 }

};class PropertiesDialogApplication:public CWinApp {
 int code=1;
public:BOOL InitInstance()override{CWinApp::InitInstance();INITCOMMONCONTROLSEX common{sizeof(common),ICC_WIN95_CLASSES|ICC_DATE_CLASSES};InitCommonControlsEx(&common);AfxOleInit();int argc=0;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);fs::path output;std::unique_ptr<Manager> manager;MainWindow* frame=nullptr;
 try{if(argc!=2)throw std::runtime_error("Pass isolated output directory");output=argv[1];renderRoot=output;fs::create_directories(output);manager=std::make_unique<Manager>(output/L"state");auto p=manager->state["Settings"];p["DownloadFolder"]=utf8((output/L"downloads").wstring());p["CategoryFolders"]=false;p["CloseToTray"]=false;p["ClipboardMonitor"]=false;manager->setSettings(p);frame=new MainWindow(*manager);m_pMainWnd=frame;ToolbarComponentTest::run(*frame);code=0;}catch(const std::exception& e){failure=e.what();}
 if(frame){frame->SendMessage(WM_CLOSE);m_pMainWnd=nullptr;}manager.reset();if(argv)LocalFree(argv);if(!output.empty())atomicText(output/L"results.json",Json{{"passed",code==0},{"error",failure},{"checks",results}}.dump(2),false);return FALSE;}
 int ExitInstance()override{AfxOleTerm(FALSE);return code;}
};PropertiesDialogApplication application;
}
