#pragma once
static void queueChecks(const udm::fs::path& root,Fixture&){
 Fixture fixture;
 using namespace udm;
 Manager m(root/L"queue19");auto prefs=m.state["Settings"];prefs["DownloadFolder"]=utf8((root/L"queue19-files").wstring());prefs["CategoryFolders"]=false;prefs["Connections"]=1;prefs["Retries"]=0;m.setSettings(prefs);
 auto q=defaultQueue();auto before=m.state["Queues"];q["RepeatMinutes"]=-1;rejects([&]{m.setQueue(q);},"Negative repeat interval rejected");q=defaultQueue();q["FinishAction"]="Shut down";q["FinishDelaySeconds"]=1;rejects([&]{m.setQueue(q);},"Completion actions require a cancellable countdown");q["FinishDelaySeconds"]=30;q["RepeatMinutes"]=5;rejects([&]{m.setQueue(q);},"Power actions and repeating queues cannot be combined");check(m.state["Queues"]==before,"Invalid queue settings leave all saved queues unchanged");
 auto second=defaultQueue("Other");m.setQueue(second);auto both=m.state["Queues"];both[0]["Parallel"]=7;both[1]["Parallel"]=99;rejects([&]{m.setQueues(both);},"Batch queue apply rejects one invalid draft");check(num(m.state["Queues"][0],"Parallel")==2,"Batch queue apply is atomic across drafts");
 auto a=m.add(fixture.url("/range"),"","a.bin");auto b=m.add(fixture.url("/range"),"","b.bin");m.reorder(b,"Main queue",a);check(m.jobs[0]==b,"Drag reorder places a pending file before its target");m.reorder(a,"Other");check(str(a->data,"Queue")=="Other"&&yes(a->data,"QueueMember"),"Drag reorder moves pending membership across queues");auto oldJobs=m.jobs;auto oldData=b->data;auto blocked=m.root/L"state.json.tmp";fs::create_directory(blocked);rejects([&]{m.reorder(b,"Other",a);},"Reorder reports persistence failure");fs::remove(blocked);check(m.jobs==oldJobs&&b->data==oldData,"Reorder restores order and metadata on write failure");m.remove(a);m.remove(b);
 auto wait=[&]{for(int i=0;i<1000;++i){bool work=false;{Lock lock(m.mutex);m.tick();for(auto j:m.jobs)work|=m.isActive(j)||str(j->data,"Status")=="Queued"||yes(j->data,"SyncPending");}if(!work){m.tick();return;}Sleep(10);}throw std::runtime_error("Queue fixture timed out");};
 q=defaultQueue();q["FinishAction"]="Exit UDM";m.setQueue(q);auto successful=m.add(fixture.url("/range"),"","complete.bin");m.queueRun("Main queue",true);wait();auto events=m.takeQueueCompletions();check(events.size()==1&&str(events[0],"Action")=="Exit UDM"&&m.completionReady("Main queue"),"Successful queue emits one completion action without executing it");m.tick();check(m.takeQueueCompletions().empty(),"Idle queue does not repeat its completion action");
 auto rejected=m.add(fixture.url("/expired"),"","expired.bin");q["FileRetries"]=2;q["RetryDelaySeconds"]=1;m.setQueue(q);m.queueRun("Main queue",true);wait();check(str(rejected->data,"Status")=="Failed"&&num(rejected->data,"QueueAttempts")==0&&m.takeQueueCompletions().empty(),"Permanent HTTP rejection suppresses retries and completion actions");m.remove(rejected);
 auto transient=m.add(fixture.url("/always-busy"),"","retry.bin");auto count=fixture.alwaysBusy.load();m.queueRun("Main queue",true);wait();check(fixture.alwaysBusy-count==3&&num(transient->data,"QueueAttempts")==2&&str(transient->data,"Status")=="Failed","Whole-file retries are delayed and bounded");m.remove(transient);
 q["FinishAction"]="None";q["FileRetries"]=0;q["RepeatMinutes"]=5;q["Synchronize"]=true;m.setQueue(q);auto requestsBeforeEnrollment=fixture.requests.load();m.queueRun("Main queue",true);wait();check(!yes(successful->data,"QueueMember")&&fixture.requests==requestsBeforeEnrollment,"Changing queue mode does not silently enroll a previously completed file");m.reorder(successful,"Main queue");check(yes(successful->data,"QueueMember"),"Completed direct file is explicitly enrolled in synchronization");auto originalHash=fileHash(successful->target());auto size=m.jobs.size();auto requests=fixture.requests.load();m.queueRun("Main queue",true);wait();check(m.jobs.size()==size&&str(successful->data,"SyncStatus")=="Up to date"&&fixture.requests-requests==1,"Unchanged synchronization uses one range probe without redownloading");check(fileHash(successful->target())==originalHash&&parseDate(m.state["Queues"][0]["NextRunUtc"])>epoch(),"Synchronization preserves bytes and schedules its next cycle");
 auto sourceData=successful->data;writeBytes(successful->target(),Bytes{'l','o','c','a','l'});successful->data["GrabberSourceHash"]=originalHash;successful->data["GrabberSourceBytes"]=fixture.payload.size();successful->data["Sha256"]=fileHash(successful->target());successful->data["GrabberConvertedHash"]=successful->data["Sha256"];successful->data["Size"]=5;successful->data["Received"]=5;requests=fixture.requests.load();m.queueRun("Main queue",true);wait();check(m.jobs.size()==size&&str(successful->data,"SyncStatus")=="Up to date"&&fixture.requests-requests==1&&readText(successful->target())=="local","Synchronization compares converted pages against their original server length and preserves local links");writeBytes(successful->target(),Bytes(fixture.payload.begin(),fixture.payload.end()));successful->data=sourceData;
 successful->data["ProjectId"]=guid();successful->data["GrabberContentType"]="text/html";successful->data["GrabberDiscoveredUrl"]=fixture.url("/range");successful->data["ETag"]="\"older-version\"";m.queueRun("Main queue",true);wait();JobPtr updated;for(auto j:m.jobs)if(str(j->data,"ReplacedDownload")==successful->id())updated=j;check(updated&&str(updated->data,"Status")=="Complete"&&fileHash(updated->target())==originalHash,"Changed remote validator downloads and verifies a replacement");check(updated&&str(successful->data,"PreviousVersionOf")==updated->id()&&fileHash(successful->target())==originalHash,"Synchronization retains the previous version and its history");
 check(updated&&yes(updated->data,"QueueMember")&&!yes(successful->data,"QueueMember"),"Synchronization keeps only the current published version enrolled");{Manager reopened(m.root);JobPtr current;for(auto j:reopened.jobs)if(updated&&j->id()==updated->id())current=j;check(current&&yes(current->data,"QueueMember"),"Published synchronization membership survives catalog reload");}
 check(updated&&str(updated->data,"ProjectId")==str(successful->data,"ProjectId")&&str(updated->data,"GrabberContentType")=="text/html"&&str(updated->data,"GrabberSourceHash").empty(),"Synchronized replacements retain project association without reusing a previous page source");
 requests=fixture.requests.load();m.queueRun("Main queue",true);wait();check(fixture.requests-requests==1&&m.jobs.size()==size+1,"Later synchronization checks only the latest version");
 auto pending=m.add(fixture.url("/range"),"","pending.bin","Other");check(m.completionReady("Main queue"),"Unrelated manually paused downloads do not prevent completion");m.resume(pending);check(!m.completionReady("Main queue"),"New queued work cancels a pending power action");m.pause(pending);
 q["Enabled"]=false;m.setQueue(q);requests=fixture.requests.load();m.state["Queues"][0]["NextRunUtc"]=date(epoch()-1000);m.tick();check(fixture.requests==requests,"Disabled repeating queue makes no requests");m.stop();
}
