#include "QueueCompletion.hpp"
#include "Core.hpp"
#include <ws2tcpip.h>
using namespace udm;
class RetryServer{SOCKET listener=INVALID_SOCKET;std::thread worker;std::atomic_bool stop{false};public:int port;std::atomic_int bad{0},good{0},always{0},failureStatus{404};std::atomic_bool allow{false};RetryServer(){listener=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);sockaddr_in a{};a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(bind(listener,(sockaddr*)&a,sizeof(a))||listen(listener,16))throw std::runtime_error("Server bind failed");int n=sizeof(a);getsockname(listener,(sockaddr*)&a,&n);port=ntohs(a.sin_port);worker=std::thread([&]{while(!stop){fd_set f;FD_ZERO(&f);FD_SET(listener,&f);timeval t{0,100000};if(select(0,&f,nullptr,nullptr,&t)<=0)continue;auto s=accept(listener,nullptr,nullptr);DWORD timeout=2000;setsockopt(s,SOL_SOCKET,SO_RCVTIMEO,(char*)&timeout,sizeof(timeout));std::string request;char buf[4096];while(request.find("\r\n\r\n")==std::string::npos&&request.size()<32768){int k=recv(s,buf,sizeof(buf),0);if(k<=0)break;request.append(buf,k);}bool fail=false;if(request.find(" /always ")!=std::string::npos){++always;fail=true;}else if(request.find(" /bad ")!=std::string::npos){++bad;fail=!allow;}else ++good;std::string body=fail?"missing":std::string(8192,'G');std::string response=std::string("HTTP/1.1 ")+(fail?(std::to_string(failureStatus.load())+" Rejected"):std::string("200 OK"))+"\r\nContent-Length: "+std::to_string(body.size())+"\r\nContent-Type: application/octet-stream\r\nConnection: close\r\n\r\n"+body;size_t sent=0;while(sent<response.size()){int k=send(s,response.data()+sent,(int)(response.size()-sent),0);if(k<=0)break;sent+=k;}shutdown(s,SD_BOTH);closesocket(s);}});}~RetryServer(){stop=true;if(worker.joinable())worker.join();closesocket(listener);}std::string url(const char*p){return "http://127.0.0.1:"+std::to_string(port)+p;}};

int wmain(int argc,wchar_t**argv){if(argc!=2)return 2;fs::path root=argv[1];if(fs::exists(root))return 3;fs::create_directories(root);WSADATA w{};WSAStartup(MAKEWORD(2,2),&w);CoInitializeEx(nullptr,COINIT_MULTITHREADED);Json checks=Json::array();std::string error;auto check=[&](bool ok,const char*n){checks.push_back({{"name",n},{"passed",ok}});if(!ok)throw std::runtime_error(n);};try{
 RetryServer server;Manager m(root/L"data");auto prefs=m.state["Settings"];prefs["DownloadFolder"]=utf8((root/L"files").wstring());prefs["CategoryFolders"]=false;prefs["Connections"]=1;prefs["Parallel"]=1;prefs["Retries"]=0;m.setSettings(prefs);
 auto pump=[&](auto ready){auto start=epoch();while(epoch()-start<15000){m.tick();{Lock lock(m.mutex);if(ready())return;}Sleep(20);}throw std::runtime_error("Fixture timeout");};
 auto q=defaultQueue();q["FileRetryLimitEnabled"]=true;q["FileRetries"]=0;q["FinishAction"]="Exit UDM";m.setQueue(q);auto failed=m.add(server.url("/always"),"","failed.bin");
 auto run=[&]{m.queueRun("Main queue",true);pump([&]{return str(failed->data,"Status")=="Failed"&&!m.isActive(failed);});m.tick();auto events=m.takeQueueCompletions();if(events.size()!=1)throw std::runtime_error("Expected one completion");return events[0];};
 auto a=run();check(m.completionEventReady(a),"First completed run can start its countdown");
 auto b=run();check(!m.completionEventReady(a)&&m.completionEventReady(b),"Rapid completed restart never revives previous countdown");check(str(a,"Cycle")!=str(b,"Cycle"),"Each queue run has a distinct identity");
 int invoked=0;executeQueueCompletion(a,[&]{return m.completionEventReady(a);},[&](const std::string&,bool,const std::string&){++invoked;});check(invoked==0,"Stale event cannot dispatch an action");
 auto current=m.state["Queues"][0];current["Parallel"]=2;current["CompletionCycle"]="caller-forged";m.setQueue(current);check(m.completionEventReady(b),"Unrelated Apply preserves event and ignores caller-supplied identity");
 auto previous=m.state;fs::create_directory(root/L"data"/L"state.json.tmp");bool rejected=false;try{m.queueRun("Main queue",true);}catch(...){rejected=true;}fs::remove(root/L"data"/L"state.json.tmp");check(rejected,"Failed-start fixture rejects state save");check(m.state==previous&&m.completionEventReady(b),"Failed queue start restores identity and global epoch exactly");
 auto missing=b;missing.erase("Cycle");check(!m.completionEventReady(missing),"Completion without run identity fails closed");missing=b;missing.erase("WorkEpoch");check(!m.completionEventReady(missing),"Completion without work epoch fails closed");
 current=m.state["Queues"][0];current["FinishDelaySeconds"]=45;m.setQueue(current);check(!m.completionEventReady(b),"Changing finish policy invalidates pending event");
 auto c=run();auto other=defaultQueue("Other queue");m.setQueue(other);auto item=m.add(server.url("/good"),"","other.bin","Other queue");m.queueRun("Other queue",true);pump([&]{return str(item->data,"Status")=="Complete"&&!m.isActive(item);});m.tick();check(m.completionReady("Main queue")&&!m.completionEventReady(c),"Another completed download invalidates old countdown even when idle again");
 auto individualEvent=run();auto individual=m.add(server.url("/good"),"","individual.bin","Other queue");m.queueRun("Other queue",false);m.resume(individual);pump([&]{return str(individual->data,"Status")=="Complete"&&!m.isActive(individual);});m.tick();check(m.completionReady("Main queue")&&!m.completionEventReady(individualEvent),"Individual Resume invalidates countdown without starting a queue");
 auto d=run();m.queueRun("Main queue",false);check(!m.completionEventReady(d),"Stop cancels current completion event");auto e=run();check(!m.completionEventReady(d)&&m.completionEventReady(e),"Stop and restart do not resurrect canceled event");
 auto once=defaultQueue("Once finish");once["RunOnce"]=true;once["StartOnceUtc"]=date(epoch()-1000);once["StopOnceUtc"]=date(epoch()+60000);once["FinishAction"]="Exit UDM";m.setQueue(once);auto one=m.add(server.url("/good"),"","once.bin","Once finish");m.queueRun("Once finish",true);pump([&]{return str(one->data,"Status")=="Complete"&&!m.isActive(one);});m.tick();auto events=m.takeQueueCompletions();check(events.size()==1&&m.completionEventReady(events[0]),"Automatic one-time disarming retains valid event");m.stop();
 }catch(const std::exception&e){error=e.what();}atomicText(root/L"results.json",Json{{"passed",error.empty()},{"error",error},{"checks",checks},{"systemActionsExecuted",false}}.dump(2),false);CoUninitialize();WSACleanup();return error.empty()?0:1;}
