// Included inside udm, after Form.
inline bool selectBatch(CWnd* parent,Manager& manager,const std::vector<std::string>& urls){
 Form d("Import links to UDM",690,454,parent);std::set<int> added;Headers headers;CWnd* confirm=nullptr;
 d.init=[&]{d.label("Check the files you want to download:",13,13,664);auto list=d.make<CListCtrl>(WS_TABSTOP|WS_BORDER|LVS_SHOWSELALWAYS|LVS_REPORT,13,39,664,251);list->SetExtendedStyle(LVS_EX_CHECKBOXES|LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);list->InsertColumn(0,L"File name",LVCFMT_LEFT,d.rect(0,0,210,0).Width());list->InsertColumn(1,L"Address",LVCFMT_LEFT,d.rect(0,0,620,0).Width());for(int i=0;i<(int)urls.size();++i){list->InsertItem(i,cs(safeName(unescape(Url(urls[i]).path))));list->SetItemText(i,1,cs(urls[i]));list->SetCheck(i,TRUE);}
 d.button("Check all",13,300,94,[list,&added]{for(int i=0;i<list->GetItemCount();++i)if(!added.count(i))list->SetCheck(i,TRUE);});d.button("Uncheck all",117,300,100,[list]{for(int i=0;i<list->GetItemCount();++i)list->SetCheck(i,FALSE);});
 d.button("Authorization...",232,300,133,[&]{Form auth("Batch authorization",432,147,&d);auth.init=[&]{auto existing=basicLogin(headers);auth.label("Login",13,17,82);auto user=auth.edit(existing.first,104,13,313);auth.label("Password",13,53,82);auto password=auth.edit(existing.second,104,49,313,23,false,false,true);auth.label("These credentials apply to every selected URL.",13,85,404);auth.accept=[&,user,password]{if(text(user).find(':')!=std::string::npos)throw std::runtime_error("Login cannot contain a colon.");auto plain=text(user)+":"+text(password);setHeader(headers,"Authorization",text(user).empty()&&text(password).empty()?"":"Basic "+b64(Bytes(plain.begin(),plain.end())));validateHeaders(headers);auth.close();};auth.button("OK",229,111,89,auth.accept);auth.button("Cancel",328,111,89,[&]{auth.close(IDCANCEL);});};auth.DoModal();});
 auto report=d.label("",382,306,294);d.label("Queue",13,344,54);auto queue=d.combo(queueNames(manager),"Main queue",74,340,250);d.label("Save to",13,380,54);auto folder=d.edit("",74,376,494);d.button("Browse...",578,375,99,[&,folder]{auto value=chooseFolder(&d,wide(text(folder)));if(!value.empty())folder->SetWindowText(value.c_str());});auto paused=d.check("Download later",true,345,340,260);
 d.pulse=[list,report,&added,&confirm]{int count=0;for(int i=0;i<list->GetItemCount();++i)if(list->GetCheck(i)&&!added.count(i))++count;if(confirm)confirm->EnableWindow(count>0);report->SetWindowText(cs(std::to_string(count)+" selected, "+std::to_string(added.size())+" added"));};
 d.accept=[&,list,queue,folder,paused]{auto dest=trim(text(folder));if(!dest.empty()&&!fs::path(wide(dest)).is_absolute())throw std::runtime_error("Choose an absolute destination folder, or leave it blank for category defaults.");bool ask;{Lock lock(manager.mutex);ask=yes(manager.state["Settings"],"QueuePromptBatch",true);}std::optional<DownloadQueueChoice> choice;if(ask){choice=chooseDownloadQueue(&d,manager,text(queue),!d.checked(paused));if(!choice)return;ensureDownloadQueue(manager,*choice);}bool any=false;for(int i=0;i<(int)urls.size();++i)if(list->GetCheck(i)&&!added.count(i)){manager.offerDownload(urls[i],dest,"",choice?choice->name:text(queue),choice?true:d.checked(paused),headers);added.insert(i);list->SetCheck(i,FALSE);any=true;}if(!any)throw std::runtime_error("Select at least one file.");if(choice)finishDownloadQueue(manager,*choice,"QueuePromptBatch");d.close();};confirm=d.button("OK",478,416,94,d.accept);d.button("Cancel",583,416,94,[&]{d.close(IDCANCEL);});};return d.DoModal()==IDOK;
}
inline void batchDialog(CWnd* parent,Manager& manager,std::string initial=""){
 if(!trim(initial).empty()){auto urls=expand(initial);if(!urls.empty())selectBatch(parent,manager,urls);return;}
 Form d("Add batch download",580,341,parent);d.init=[&]{d.label("Enter addresses, one per line. Use [001-100] or [a-z] for a sequence.",13,13,554,34);auto input=d.edit("",13,53,554,226,false,true);d.accept=[&,input]{auto urls=expand(text(input));if(urls.empty())throw std::runtime_error("Enter at least one URL.");if(selectBatch(&d,manager,urls))d.close();};d.button("Preview links...",337,301,128,d.accept);d.button("Cancel",475,301,92,[&]{d.close(IDCANCEL);});};d.DoModal();
}
inline void serverRulesDialog(CWnd* owner,Json& prefs){
 Form d("Server connection limits",531,326,owner);auto rules=prefs.value("ServerConnections",Json::array());CListCtrl* list=nullptr;
 auto fill=[&](int selection){list->DeleteAllItems();for(int i=0;i<(int)rules.size();++i){list->InsertItem(i,cs(str(rules[i],"Host")));list->SetItemText(i,1,cs(std::to_string(num(rules[i],"Connections"))));}if(selection>=0)list->SetItemState(selection,LVIS_SELECTED|LVIS_FOCUSED,LVIS_SELECTED|LVIS_FOCUSED);};
 auto change=[&](int index){Json rule=index>=0?rules[index]:Json{{"Host",""},{"Connections",8}};Form e(index<0?"New server limit":"Edit server limit",401,151,&d);e.init=[&]{e.label("Server name",13,18,104);auto host=e.edit(str(rule,"Host"),127,14,260);e.label("Max. connections",13,57,109);auto count=e.combo({"1","2","4","8","16","24","32"},std::to_string(num(rule,"Connections",8)),127,53,113,true);e.label("Applies to this host and its subdomains.",13,88,374);e.accept=[&,host,count]{auto h=lower(trim(text(host)));auto n=std::stoll(text(count));if(h.empty()||Url("https://"+h+"/").host!=h||n<1||n>32)throw std::runtime_error("Enter a host name and 1 to 32 connections.");for(int i=0;i<(int)rules.size();++i)if(i!=index&&lower(str(rules[i],"Host"))==h)throw std::runtime_error("This server already has a rule.");Json value={{"Host",h},{"Connections",n}};if(index<0){if(rules.size()>=100)throw std::runtime_error("Keep at most 100 server rules.");rules.push_back(value);}else rules[index]=value;e.close();};e.button("OK",199,113,88,e.accept);e.button("Cancel",299,113,88,[&]{e.close(IDCANCEL);});};if(e.DoModal()==IDOK)fill(index<0?(int)rules.size()-1:index);};
 d.init=[&]{d.label("New downloads use the most specific matching server rule.",13,13,505,29);list=d.make<CListCtrl>(WS_TABSTOP|WS_BORDER|LVS_SHOWSELALWAYS|LVS_REPORT|LVS_SINGLESEL,13,48,393,231);list->SetExtendedStyle(LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);list->InsertColumn(0,L"Server",LVCFMT_LEFT,d.rect(0,0,267,0).Width());list->InsertColumn(1,L"Connections",LVCFMT_LEFT,d.rect(0,0,98,0).Width());d.button("New...",419,49,98,[change]{change(-1);});auto editButton=d.button("Edit...",419,87,98,[&,change]{int row=list->GetNextItem(-1,LVNI_SELECTED);if(row>=0)change(row);});auto deleteButton=d.button("Delete",419,125,98,[&]{int row=list->GetNextItem(-1,LVNI_SELECTED);if(row>=0){rules.erase(row);fill(std::min(row,(int)rules.size()-1));}});d.accept=[&]{prefs["ServerConnections"]=rules;d.close();};d.button("OK",318,291,94,d.accept);d.button("Cancel",423,291,94,[&]{d.close(IDCANCEL);});d.pulse=[&,editButton,deleteButton]{bool selected=list->GetNextItem(-1,LVNI_SELECTED)>=0;editButton->EnableWindow(selected);deleteButton->EnableWindow(selected);};fill(rules.empty()?-1:0);d.pulse();};d.DoModal();
}
