#include "ServerConnections.hpp"
#include <iostream>
using namespace udm;
int wmain(int argc,wchar_t** argv){if(argc!=2)return 2;fs::path root=argv[1];if(fs::exists(root))return 3;fs::create_directories(root);Json checks=Json::array();auto check=[&](bool ok,const char* name){checks.push_back({{"name",name},{"passed",ok}});if(!ok)throw std::runtime_error(name);};
try{Manager m(root/L"state");auto p=m.state["Settings"];p["Connections"]=16;p["DownloadFolder"]=utf8((root/L"files").wstring());p["CategoryFolders"]=false;
p["ServerConnections"]=Json::array({{{"Host","example.test"},{"Connections",8}},{{"Host","cdn*.example.test"},{"Scheme","https"},{"Connections",4}},{{"Host","cdn*.example.test"},{"Scheme","http"},{"Connections",2}},{{"Host","files*.example.test"},{"Scheme","ftp"},{"Connections",1}},{{"Host","cdn1.example.test"},{"Scheme","https"},{"Connections",6}}});m.setSettings(p);
auto actual=[&](const char* url,i64 expected){auto j=m.add(url,"","","Main queue",true);check(num(j->data,"Connections")==expected,url);};
actual("https://cdn2.example.test/file",4);actual("http://cdn2.example.test/file",2);actual("ftp://files9.example.test/file",1);actual("https://files9.example.test/file",8);actual("https://cdn1.example.test/file",6);actual("https://example.test/file",8);actual("https://child.example.test/file",8);actual("https://notexample.test/file",16);actual("https://cdn2.example.test.attacker.test/file",16);actual("https://CDN2.EXAMPLE.TEST/file",4);
{Manager reopened(m.root);check(reopened.state["Settings"]["ServerConnections"]==p["ServerConnections"],"Protocol and wildcard rules survive catalog restart");auto j=reopened.add("http://cdn7.example.test/file","","","Main queue",true);check(num(j->data,"Connections")==2,"Reopened rules apply to actual new downloads");}
check(connectionHostGlob("cdn-a-b.test","cdn*test"),"Asterisk spans multiple host labels and characters");check(!connectionHostGlob("cdn.test.evil","cdn.test"),"Glob requires whole host match");check(connectionHostGlob("anything.test","*"),"All-host wildcard matches");check(!connectionHostGlob("example.test","*.example.test"),"Subdomain wildcard does not silently match apex");
for(auto rule:std::vector<Json>{{{"Host","host.test/path"},{"Connections",2}},{{"Host","user@host.test"},{"Connections",2}},{{"Host","host.test:443"},{"Connections",2}},{{"Host","host.test"},{"Scheme","rtmp"},{"Connections",2}},{{"Host","*"},{"Connections",33}},{{"Host",""},{"Connections",1}}}){bool rejected=false;try{auto invalid=p;invalid["ServerConnections"]=Json::array({rule});m.setSettings(invalid);}catch(...){rejected=true;}check(rejected,"Invalid scoped connection rule is rejected");}
check(m.state["Settings"]["ServerConnections"]==p["ServerConnections"],"Rejected rules leave settings unchanged");
}catch(const std::exception& e){checks.push_back({{"name",e.what()},{"passed",false}});}bool passed=true;for(auto& c:checks)passed&=yes(c,"passed");atomicText(root/L"results.json",Json{{"passed",passed},{"checks",checks}}.dump(2),false);std::cout<<checks.size()<<" checks, passed="<<passed<<std::endl;return passed?0:1;}