#include "SiteLogins.hpp"
#include <iostream>
using namespace udm;
int wmain(int argc,wchar_t** argv){if(argc!=2)return 2;fs::path root=argv[1];if(fs::exists(root))return 3;fs::create_directories(root);Json checks=Json::array();auto check=[&](bool ok,const char* name){checks.push_back({{"name",name},{"passed",ok}});if(!ok)throw std::runtime_error(name);};auto rejects=[&](auto action,const char* name){bool rejected=false;try{action();}catch(...){rejected=true;}check(rejected,name);};
try{Manager m(root/L"state");auto p=m.state["Settings"];p["DownloadFolder"]=utf8((root/L"files").wstring());p["CategoryFolders"]=false;p["SiteLogins"]=Json::array();
for(const std::string scheme:{"https","http","ftp"}){p["SiteLogins"].push_back(makeSiteLogin(scheme+"://same.example.test/",scheme+"-root","fixture-secret"));p["SiteLogins"].push_back(makeSiteLogin(scheme+"://same.example.test/private/",scheme+"-private","fixture-secret"));}
m.setSettings(p);auto user=[&](const std::string& address,const Headers& h=Headers{},bool sensitive=true){return basicLogin(siteRequestHeaders(address,h,m.state["Settings"],sensitive)).first;};
for(const std::string scheme:{"https","http","ftp"}){auto base=scheme+"://same.example.test";check(user(base+"/file")==scheme+"-root","Saved login stays within its selected protocol");check(user(base+"/private/file")==scheme+"-private","Each protocol selects its longest matching folder");check(user(base+"/privateer/file")==scheme+"-root","Folder names require a path boundary");check(user(scheme+"://same.example.test:12345/private/file").empty(),"Saved login does not cross ports");check(user(scheme+"://child.same.example.test/private/file").empty(),"Saved login does not cross subdomains");check(user(base+"/private/%2fother").empty(),"Ambiguous encoded separators receive no saved login");check(user(base+"/private/file",{},false).empty(),"Redirect policy suppresses even a matching saved destination login");Headers manual;setBasicLogin(manual,"explicit","manual-secret");check(user(base+"/private/file",manual)=="explicit","Explicit per-download login overrides saved protocol login");setBasicLogin(manual,"","",false);check(user(base+"/private/file",manual).empty(),"Per-download removal suppresses automatic saved login");auto job=m.add(base+"/private/file","",scheme+".bin","Main queue",true);check(readHeaders(job->data).empty(),"Saved credentials remain request-time settings rather than job copies");m.setDownloadLogin(job,"remembered","remember-fixture",true);check(user(base+"/other/file")=="remembered"&&user(base+"/private/file")==scheme+"-private","Remember this site updates only its root and preserves folder overrides");}
{Manager reopened(m.root);check(reopened.state["Settings"]["SiteLogins"].size()==6,"Protocol-distinct saved logins survive catalog reopening");check(readText(m.root/L"state.json").find("fixture-secret")==std::string::npos&&readText(m.root/L"state.json").find("remember-fixture")==std::string::npos,"Saved passwords remain protected on disk");}
for(const char* address:{"mms://same.example.test/","https://same.example.test/?query=1","ftp://same.example.test/private/../","http://same.example.test/#fragment"})rejects([&]{makeSiteLogin(address,"u","p");},"Unsupported protocol or ambiguous login scope is rejected");
rejects([&]{makeSiteLogin("ftp://same.example.test/","u","p\r\nNOOP");},"FTP saved password rejects command delimiters");auto bad=m.state["Settings"];bad["SiteLogins"].push_back(bad["SiteLogins"][0]);rejects([&]{m.setSettings(bad);},"Duplicate protocol-specific scope is rejected");check(m.state["Settings"]["SiteLogins"].size()==6,"Rejected login settings preserve saved data");
}catch(const std::exception& e){checks.push_back({{"name",e.what()},{"passed",false}});}bool passed=true;for(auto& c:checks)passed&=yes(c,"passed");atomicText(root/L"results.json",Json{{"passed",passed},{"checks",checks}}.dump(2),false);std::cout<<checks.size()<<" checks, passed="<<passed<<std::endl;return passed?0:1;}