#pragma once
#include <shlobj.h>
#include <atlbase.h>
#include "Core.hpp"
namespace udm {
inline fs::path startupShortcut(){PWSTR value=nullptr;if(FAILED(SHGetKnownFolderPath(FOLDERID_Startup,0,nullptr,&value)))throw std::runtime_error("Cannot locate your Windows Startup folder.");fs::path path=fs::path(value)/L"UDM.lnk";CoTaskMemFree(value);return path;}
inline bool startupEnabled(){auto path=startupShortcut();if(!fs::exists(path))return false;CComPtr<IShellLinkW> link;CComPtr<IPersistFile> file;if(FAILED(link.CoCreateInstance(CLSID_ShellLink))||FAILED(link.QueryInterface(&file))||FAILED(file->Load(path.c_str(),STGM_READ)))return false;wchar_t target[32768]{};if(FAILED(link->GetPath(target,32768,nullptr,SLGP_RAWPATH)))return false;return lower(utf8(fs::path(target).lexically_normal().wstring()))==lower(utf8((appDir()/L"UDM.exe").wstring()));}
inline void setStartup(bool enabled){auto path=startupShortcut();if(fs::exists(path)&&!startupEnabled())throw std::runtime_error("A Startup item named UDM already belongs to another installation.");if(enabled){CComPtr<IShellLinkW> link;CComPtr<IPersistFile> file;if(FAILED(link.CoCreateInstance(CLSID_ShellLink))||FAILED(link.QueryInterface(&file)))throw std::runtime_error("Cannot create the UDM Startup shortcut.");auto exe=appDir()/L"UDM.exe";if(FAILED(link->SetPath(exe.c_str()))||FAILED(link->SetArguments(L"--background"))||FAILED(link->SetWorkingDirectory(appDir().c_str())))throw std::runtime_error("Cannot configure the UDM Startup shortcut.");link->SetDescription(L"Start UDM in the notification area");auto temp=path;temp+=L".tmp";if(FAILED(file->Save(temp.c_str(),TRUE)))throw std::runtime_error("Cannot save the UDM Startup shortcut.");if(!MoveFileExW(temp.c_str(),path.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH))throw std::runtime_error("Cannot publish the UDM Startup shortcut.");}else if(fs::exists(path)&&!DeleteFileW(path.c_str()))throw std::runtime_error("Cannot remove the UDM Startup shortcut.");}
}
