#include "Core.hpp"
#include <ws2tcpip.h>
#include <iostream>
#include <regex>
using namespace udm;
class Server{
 SOCKET listener=INVALID_SOCKET;std::thread worker;std::atomic_bool stopping{false};
 static void sendAll(SOCKET s,const std::string& v){size_t n=0;while(n<v.size()){int k=send(s,v.data()+n,(int)std::min<size_t>(65536,v.size()-n),0);if(k<=0)return;n+=k;}}
 void serve(SOCKET s){DWORD timeout=3000;setsockopt(s,SOL_SOCKET,SO_RCVTIMEO,(char*)&timeout,sizeof(timeout));std::string req;char buf[4096];while(req.find("\r\n\r\n")==std::string::npos&&req.size()<32768){int n=recv(s,buf,sizeof(buf),0);if(n<=0)return;req.append(buf,n);}
 if(failures>0){--failures;{std::lock_guard<std::mutex> l(mutex);requests.push_back({{"at",epoch()},{"status",failureStatus.load()}});}sendAll(s,"HTTP/1.1 "+std::to_string(failureStatus.load())+" Rejected\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");return;} auto body=payload(version.load());std::smatch m;size_t first=0,last=body.size()-1;bool ranged=std::regex_search(req,m,std::regex("Range: bytes=([0-9]+)-([0-9]*)",std::regex::icase));if(ranged){first=std::stoull(m[1]);if(m[2].length())last=std::min(last,(size_t)std::stoull(m[2]));}
 if(first>last||last>=body.size()){sendAll(s,"HTTP/1.1 416 Range Not Satisfiable\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");return;}
 bool head=req.rfind("HEAD ",0)==0;auto length=last-first+1;int v=body[0]-'A'+1;
 {std::lock_guard<std::mutex> l(mutex);requests.push_back({{"at",epoch()},{"version",v},{"first",first},{"last",last},{"head",head}});}
 std::string h=std::string("HTTP/1.1 ")+(ranged?"206 Partial Content":"200 OK")+"\r\nContent-Type: application/octet-stream\r\nAccept-Ranges: bytes\r\nETag: \"version-"+std::to_string(v)+"\"\r\nContent-Length: "+std::to_string(length)+"\r\nConnection: close\r\n";
 if(ranged)h+="Content-Range: bytes "+std::to_string(first)+"-"+std::to_string(last)+"/"+std::to_string(body.size())+"\r\n";
 sendAll(s,h+"\r\n");if(!head){if(length>8192&&bodyFailures>0){--bodyFailures;sendAll(s,body.substr(first,8192));return;}sendAll(s,body.substr(first,length));}}
public:
 int port=0;std::atomic_int version{1},failures{0},failureStatus{503},bodyFailures{0};std::mutex mutex;Json requests=Json::array();
 static std::string payload(int v){return std::string(262147,(char)('A'+v-1));}
 Server(){listener=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);sockaddr_in a{};a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(listener==INVALID_SOCKET||bind(listener,(sockaddr*)&a,sizeof(a))||listen(listener,16))throw std::runtime_error("Local server failed");int n=sizeof(a);getsockname(listener,(sockaddr*)&a,&n);port=ntohs(a.sin_port);worker=std::thread([this]{while(!stopping){fd_set set;FD_ZERO(&set);FD_SET(listener,&set);timeval t{0,100000};if(select(0,&set,nullptr,nullptr,&t)>0){auto s=accept(listener,nullptr,nullptr);if(s!=INVALID_SOCKET){try{serve(s);}catch(...){}shutdown(s,SD_BOTH);closesocket(s);}}}});}
 ~Server(){stopping=true;if(worker.joinable())worker.join();closesocket(listener);}
 Json log(){std::lock_guard<std::mutex> l(mutex);return requests;}
};
int wmain(int argc,wchar_t**argv){if(argc!=2)return 2;fs::path root=argv[1];if(fs::exists(root))return 3;fs::create_directories(root);WSADATA w{};WSAStartup(MAKEWORD(2,2),&w);CoInitializeEx(nullptr,COINIT_MULTITHREADED);Json checks=Json::array();std::string error;auto check=[&](bool ok,const char*n){checks.push_back({{"name",n},{"passed",ok}});if(!ok)throw std::runtime_error(n);};try{Server server;Manager m(root/L"data");auto prefs=m.state["Settings"];prefs["DownloadFolder"]=utf8((root/L"files").wstring());prefs["CategoryFolders"]=false;prefs["Connections"]=1;prefs["Parallel"]=1;prefs["Retries"]=0;m.setSettings(prefs);auto q=defaultQueue("Replacement retry");q["Enabled"]=false;q["Synchronize"]=true;q["FileRetryLimitEnabled"]=true;q["FileRetries"]=1;q["RetryDelaySeconds"]=1;m.setQueue(q);auto first=m.add("http://127.0.0.1:"+std::to_string(server.port)+"/payload.bin","","payload.bin","Replacement retry");auto pump=[&](auto ready,const char*message){auto began=epoch();while(epoch()-began<20000){m.tick();{Lock lock(m.mutex);if(ready())return;}Sleep(20);}throw std::runtime_error(message);};m.queueRun("Replacement retry",true);pump([&]{return str(first->data,"Status")=="Complete"&&!m.isActive(first);},"Initial file timeout");m.tick();check(readText(first->target())==Server::payload(1),"Initial version is complete and verified");q["FinishAction"]="Exit UDM";m.setQueue(q);server.version=2;server.bodyFailures=1;m.queueRun("Replacement retry",true);JobPtr second;
 pump([&]{for(auto j:m.jobs)if(j!=first&&str(j->data,"ReplacementOf")==first->id()){second=j;return str(j->data,"Status")=="Queued"&&num(j->data,"QueueAttempts")==1&&!m.isActive(j);}return false;},"Replacement did not enter queued retry");check(readText(first->target())==Server::payload(1)&&str(first->data,"Status")=="Complete","Truncated replacement leaves old saved file usable");check(!str(second->data,"ReplacementOf").empty(),"Pending replacement retains its original-file link");check(m.takeQueueCompletions().empty(),"Failed in-progress replacement emits no completion");pump([&]{return str(second->data,"Status")=="Complete"&&!m.isActive(second);},"Replacement retry failed to recover");m.tick();check(readText(second->target())==Server::payload(2)&&readText(first->target())==Server::payload(1),"Retry publishes exact new version and preserves exact old version");check(str(second->data,"SyncStatus")=="Updated; previous version retained"&&str(first->data,"SyncStatus")=="Previous version","Recovered replacement has correct synchronization labels");check(parseDate(second->data.value("LastSync",Json()))>0&&!yes(second->data,"SynchronizationReplacement"),"Publication records sync time and clears pending marker");check(m.takeQueueCompletions().size()==1,"Recovered replacement permits one queue completion event");m.tick();check(m.takeQueueCompletions().empty(),"Recovered completion does not repeat");
 server.version=3;server.failures=1;server.bodyFailures=10;m.queueRun("Replacement retry",true);JobPtr third;pump([&]{for(auto j:m.jobs)if(str(j->data,"ReplacementOf")==second->id()){third=j;return str(j->data,"Status")=="Failed"&&!m.isActive(j);}return false;},"Shared retry budget failure timeout");m.tick();check(num(second->data,"QueueAttempts")==1&&num(third->data,"QueueAttempts")==1,"Probe retry count carries into replacement budget");check(readText(second->target())==Server::payload(2)&&str(second->data,"Status")=="Complete","Exhausted replacement keeps last successful file intact");{auto events=m.takeQueueCompletions();check(events.size()==1&&num(events[0],"FailedFiles")==1,"Exhausted bounded replacement finishes with disclosed failure");}auto count=server.log().size();auto start=epoch();while(epoch()-start<1300){m.tick();Sleep(20);}check(server.log().size()==count&&str(third->data,"Status")=="Failed","Exhausted shared budget prevents another transfer");
 q["FileRetryLimitEnabled"]=false;m.setQueue(q);m.queueRun("Replacement retry",true);pump([&]{return str(third->data,"Status")=="Queued"&&num(third->data,"QueueAttempts")>=1&&!m.isActive(third);},"Stop-case retry not queued");m.queueRun("Replacement retry",false);count=server.log().size();start=epoch();while(epoch()-start<1300){m.tick();Sleep(20);}check(server.log().size()==count&&!m.isActive(third),"Stop cancels further replacement retry requests");check(readText(second->target())==Server::payload(2)&&m.takeQueueCompletions().empty(),"Stopped replacement preserves saved file and no completion action");m.stop();atomicText(root/L"requests.json",server.log().dump(2),false);{Manager reopened(root/L"data");bool current=false,prior=false,pending=false;for(auto j:reopened.jobs){if(j->id()==second->id())current=readText(j->target())==Server::payload(2);if(j->id()==first->id())prior=readText(j->target())==Server::payload(1);if(j->id()==third->id())pending=str(j->data,"ReplacementOf")==second->id();}check(current&&prior&&pending,"Saved versions and pending replacement relationship survive restart");}
 }catch(const std::exception&e){error=e.what();}atomicText(root/L"results.json",Json{{"passed",error.empty()},{"error",error},{"checks",checks}}.dump(2),false);CoUninitialize();WSACleanup();return error.empty()?0:1;}