#include "Core.hpp"
#include <ws2tcpip.h>
#include <iostream>
#include <regex>
using namespace udm;
class Server{
 SOCKET listener=INVALID_SOCKET;std::thread worker;std::atomic_bool stopping{false};
 static void sendAll(SOCKET s,const std::string& v){size_t n=0;while(n<v.size()){int k=send(s,v.data()+n,(int)std::min<size_t>(65536,v.size()-n),0);if(k<=0)return;n+=k;}}
 void serve(SOCKET s){DWORD timeout=3000;setsockopt(s,SOL_SOCKET,SO_RCVTIMEO,(char*)&timeout,sizeof(timeout));std::string req;char buf[4096];while(req.find("\r\n\r\n")==std::string::npos&&req.size()<32768){int n=recv(s,buf,sizeof(buf),0);if(n<=0)return;req.append(buf,n);}
 if(failures>0){--failures;{std::lock_guard<std::mutex> l(mutex);requests.push_back({{"at",epoch()},{"status",failureStatus.load()}});}sendAll(s,"HTTP/1.1 "+std::to_string(failureStatus.load())+" Rejected\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");return;} auto body=payload(version.load());std::smatch m;size_t first=0,last=body.size()-1;bool ranged=std::regex_search(req,m,std::regex("Range: bytes=([0-9]+)-([0-9]*)",std::regex::icase));if(ranged){first=std::stoull(m[1]);if(m[2].length())last=std::min(last,(size_t)std::stoull(m[2]));}
 if(first>last||last>=body.size()){sendAll(s,"HTTP/1.1 416 Range Not Satisfiable\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");return;}
 bool head=req.rfind("HEAD ",0)==0;auto length=last-first+1;int v=body[0]=='A'?1:2;
 {std::lock_guard<std::mutex> l(mutex);requests.push_back({{"at",epoch()},{"version",v},{"first",first},{"last",last},{"head",head}});}
 std::string h=std::string("HTTP/1.1 ")+(ranged?"206 Partial Content":"200 OK")+"\r\nContent-Type: application/octet-stream\r\nAccept-Ranges: bytes\r\nETag: \"version-"+std::to_string(v)+"\"\r\nContent-Length: "+std::to_string(length)+"\r\nConnection: close\r\n";
 if(ranged)h+="Content-Range: bytes "+std::to_string(first)+"-"+std::to_string(last)+"/"+std::to_string(body.size())+"\r\n";
 sendAll(s,h+"\r\n");if(!head)sendAll(s,body.substr(first,length));}
public:
 int port=0;std::atomic_int version{1},failures{0},failureStatus{503};std::mutex mutex;Json requests=Json::array();
 static std::string payload(int v){return std::string(262147,v==1?'A':'B');}
 Server(){listener=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);sockaddr_in a{};a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(listener==INVALID_SOCKET||bind(listener,(sockaddr*)&a,sizeof(a))||listen(listener,16))throw std::runtime_error("Local server failed");int n=sizeof(a);getsockname(listener,(sockaddr*)&a,&n);port=ntohs(a.sin_port);worker=std::thread([this]{while(!stopping){fd_set set;FD_ZERO(&set);FD_SET(listener,&set);timeval t{0,100000};if(select(0,&set,nullptr,nullptr,&t)>0){auto s=accept(listener,nullptr,nullptr);if(s!=INVALID_SOCKET){try{serve(s);}catch(...){}shutdown(s,SD_BOTH);closesocket(s);}}}});}
 ~Server(){stopping=true;if(worker.joinable())worker.join();closesocket(listener);}
 Json log(){std::lock_guard<std::mutex> l(mutex);return requests;}
};
int wmain(int argc,wchar_t**argv){if(argc!=2)return 2;fs::path root=argv[1];if(fs::exists(root))return 3;fs::create_directories(root);WSADATA w{};WSAStartup(MAKEWORD(2,2),&w);CoInitializeEx(nullptr,COINIT_MULTITHREADED);Json checks=Json::array();std::string error;auto check=[&](bool ok,const char*n){checks.push_back({{"name",n},{"passed",ok}});if(!ok)throw std::runtime_error(n);};try{Server server;Manager m(root/L"data");auto prefs=m.state["Settings"];prefs["DownloadFolder"]=utf8((root/L"files").wstring());prefs["CategoryFolders"]=false;prefs["Connections"]=1;prefs["Parallel"]=1;prefs["Retries"]=0;m.setSettings(prefs);auto q=defaultQueue("Sync retry");q["Enabled"]=false;q["Synchronize"]=true;q["FileRetryLimitEnabled"]=true;q["FileRetries"]=1;q["RetryDelaySeconds"]=1;m.setQueue(q);auto job=m.add("http://127.0.0.1:"+std::to_string(server.port)+"/payload.bin","","payload.bin","Sync retry");auto pump=[&](auto predicate,const char*phase){auto start=epoch();while(epoch()-start<15000){m.tick();{Lock lock(m.mutex);if(predicate())return;}Sleep(20);}throw std::runtime_error(phase);};m.queueRun("Sync retry",true);pump([&]{return str(job->data,"Status")=="Complete"&&!m.isActive(job);},"Initial download timeout");m.tick();check(readText(job->target())==Server::payload(1),"Initial saved file contains exact original bytes");auto hash=fileHash(job->target());q["FinishAction"]="Exit UDM";m.setQueue(q);server.version=2;server.failures=1;auto before=server.log().size();m.queueRun("Sync retry",true);
 pump([&]{return yes(job->data,"SyncPending")&&num(job->data,"QueueAttempts")==1;},"Retry was not queued");auto due=parseDate(job->data["NotBefore"]);check(str(job->data,"Status")=="Complete"&&fileHash(job->target())==hash,"Failed check keeps completed status and original file intact");check(due>epoch()&&due-epoch()<=1000,"Synchronization retry obeys configured wait");auto count=server.log().size();while(epoch()<due-100){m.tick();Sleep(10);}check(server.log().size()==count,"Pending synchronization does not probe before retry deadline");JobPtr updated;
 pump([&]{for(auto j:m.jobs)if(j!=job&&str(j->data,"Status")=="Complete"&&!m.isActive(j)){updated=j;return true;}return false;},"Recovered replacement timeout");m.tick();check(readText(updated->target())==Server::payload(2)&&readText(job->target())==Server::payload(1),"Recovered retry publishes new bytes and retains prior version");check(!yes(job->data,"QueueMember")&&yes(updated->data,"QueueMember"),"Only successfully published version remains enrolled");check(m.takeQueueCompletions().size()==1,"Recovered synchronization may complete its queue once");check(num(job->data,"QueueAttempts")==1,"Synchronization retry counted once");
 server.failures=10;m.queueRun("Sync retry",true);pump([&]{return yes(updated->data,"SyncRetryFailed")&&num(updated->data,"QueueAttempts")==1&&!m.isActive(updated)&&!yes(updated->data,"SyncPending");},"Bounded synchronization failure timeout");m.tick();check(fileHash(updated->target())!=hash&&readText(updated->target())==Server::payload(2),"Exhausted check retries preserve last good saved version");{auto events=m.takeQueueCompletions();check(events.size()==1&&num(events[0],"FailedFiles")==1,"Exhausted bounded synchronization finishes with disclosed failure");}count=server.log().size();auto wait=epoch();while(epoch()-wait<1200){m.tick();Sleep(20);}check(server.log().size()==count,"Retry limit prevents another failed synchronization probe");
 q["FileRetryLimitEnabled"]=false;m.setQueue(q);server.failures=3;m.queueRun("Sync retry",true);pump([&]{return str(updated->data,"SyncStatus")=="Up to date"&&!m.isActive(updated)&&num(updated->data,"QueueAttempts")==3;},"Unlimited synchronization recovery timeout");m.tick();check(m.jobs.size()==2&&readText(updated->target())==Server::payload(2),"Unlimited failed probes eventually recover without redundant versions");check(m.takeQueueCompletions().size()==1,"Recovered unchanged check clears failure for completion");
 server.failures=10;m.queueRun("Sync retry",true);pump([&]{return yes(updated->data,"SyncPending")&&num(updated->data,"QueueAttempts")==1;},"Stop test retry not pending");m.queueRun("Sync retry",false);count=server.log().size();wait=epoch();while(epoch()-wait<1500){m.tick();Sleep(20);}check(server.log().size()==count&&!yes(updated->data,"SyncPending")&&!m.isActive(updated),"Stop cancels pending synchronization retries");check(readText(updated->target())==Server::payload(2)&&m.takeQueueCompletions().empty(),"Stopping retries preserves file and emits no completion");server.failureStatus=401;server.failures=10;m.queueRun("Sync retry",true);pump([&]{return yes(updated->data,"SyncRetryFailed")&&!m.isActive(updated);},"Authentication rejection timeout");m.tick();check(!yes(updated->data,"SyncPending")&&num(updated->data,"QueueAttempts")==0,"Authentication rejection requires credentials instead of unlimited retries");count=server.log().size();wait=epoch();while(epoch()-wait<1300){m.tick();Sleep(20);}check(server.log().size()==count,"Authentication rejection does not repeat background probes");check(readText(updated->target())==Server::payload(2),"Authentication failure preserves saved version");m.stop();atomicText(root/L"requests.json",server.log().dump(2),false);{Manager reopened(root/L"data");check(reopened.jobs.size()==2&&readText(reopened.jobs.back()->target())==Server::payload(2),"Recovered current and prior versions survive restart");}
 }catch(const std::exception&e){error=e.what();}atomicText(root/L"results.json",Json{{"passed",error.empty()},{"error",error},{"checks",checks},{"clockAdvanced",false}}.dump(2),false);CoUninitialize();WSACleanup();return error.empty()?0:1;}