#pragma once
#include "Ui.hpp"
#include <future>
#include "Startup.hpp"
#include "BrowserSettingsUi.hpp"
namespace udm {
inline void categoryRule(CWnd* owner,Json& prefs){Form d("Category settings",463,198,owner);d.init=[&]{std::vector<std::string> categories={"Archives","Documents","Music","Programs","Video","Images","Other"};for(auto c:prefs["CustomCategories"])categories.push_back(c.get<std::string>());d.label("Category",10,15,87);auto cat=d.combo(categories,"Archives",105,11,348);d.label("Extensions",10,51,87);auto extensions=d.edit("",105,47,348);d.label("Sites (optional)",10,87,94);auto hosts=d.edit("",105,83,348);d.label("Separate extensions and host names with spaces. Use * for all file types.",10,122,443,34);d.button("Load rule",10,161,87,[cat,extensions,hosts,&prefs]{for(auto r:prefs["CategoryRules"])if(str(r,"Category")==text(cat)){extensions->SetWindowText(cs(str(r,"Extensions")));hosts->SetWindowText(cs(str(r,"Hosts")));return;}extensions->SetWindowText(L"");hosts->SetWindowText(L"");});d.accept=[&,cat,extensions,hosts]{auto ex=words(text(extensions));for(auto s:ex)if(s!="*"&&!std::regex_match(s,std::regex("[a-z0-9_-]{1,30}")))throw std::runtime_error("Use plain extensions such as zip mp4 pdf.");for(auto h:words(text(hosts)))Url("https://"+h+"/");auto& rules=prefs["CategoryRules"];rules.erase(std::remove_if(rules.begin(),rules.end(),[&](const Json& r){return str(r,"Category")==text(cat);}),rules.end());if(!ex.empty())rules.push_back({{"Category",text(cat)},{"Extensions",text(extensions)},{"Hosts",text(hosts)}});d.close();};d.button("Save",273,161,83,d.accept);d.button("Cancel",366,161,87,[&]{d.close(IDCANCEL);});};d.DoModal();}
#include "DialogPreferences.hpp"
class Options:public Form {
 Manager& manager;Json prefs;CTabCtrl* tabs=nullptr;std::vector<std::vector<CWnd*>> pages;std::vector<std::function<void()>> bindings;CListCtrl* logins=nullptr;
 void page(){int current=tabs->GetCurSel();for(size_t i=0;i<pages.size();++i)for(auto w:pages[i])w->ShowWindow((int)i==current?SW_SHOW:SW_HIDE);}
 void boolean(const char* key,std::string title,int y){auto c=check(title,yes(prefs,key),26,y,552);bindings.push_back([this,c,key]{prefs[key]=checked(c);});}
 CWnd* field(const char* key,std::string title,int y,bool number=false,bool secret=false){label(title,26,y+4,210);auto c=edit(secret?reveal(str(prefs,key)):number?std::to_string(num(prefs,key)):str(prefs,key),242,y,327,23,false,false,secret);bindings.push_back([this,c,key,number,secret]{prefs[key]=number?Json(std::stoll(text(c))):Json(secret?protect(text(c)):text(c));});return c;}
 void applyOptions(){for(auto& apply:bindings)apply();Json old;{Lock lock(manager.mutex);old=manager.state["Settings"];}bool started=startupEnabled();manager.setSettings(prefs);try{if(started!=yes(prefs,"RunAtLogin"))setStartup(yes(prefs,"RunAtLogin"));}catch(...){manager.setSettings(old);throw;}}
 void refreshLogins(){logins->DeleteAllItems();int i=0;for(auto login:prefs["SiteLogins"]){logins->InsertItem(i,cs(str(login,"Origin")));logins->SetItemText(i++,1,cs(str(login,"UserName")));}}
 void login(bool editing=false){Json existing;int row=logins->GetNextItem(-1,LVNI_SELECTED);if(editing&&row>=0)existing=prefs["SiteLogins"][row];else if(editing)return;Form d("Site login",456,166,this);d.init=[&]{d.label("HTTPS site",10,15,93);auto site=d.edit(str(existing,"Origin","https://"),111,11,335);d.label("User name",10,50,93);auto user=d.edit(str(existing,"UserName"),111,46,335);d.label("Password",10,85,93);auto password=d.edit(reveal(str(existing,"ProtectedPassword")),111,81,335,23,false,false,true);d.accept=[&,site,user,password]{Url u(text(site));if(u.scheme!="https")throw std::runtime_error("Saved logins require HTTPS.");if(text(user).empty()||text(user).find(':')!=std::string::npos)throw std::runtime_error("Enter a user name without a colon.");auto& list=prefs["SiteLogins"];list.erase(std::remove_if(list.begin(),list.end(),[&](const Json& l){return str(l,"Origin")==u.origin||(!str(existing,"Origin").empty()&&str(l,"Origin")==str(existing,"Origin"));}),list.end());list.push_back({{"Origin",u.origin},{"UserName",text(user)},{"ProtectedPassword",protect(text(password))}});d.close();};d.button("Save",270,127,82,d.accept);d.button("Cancel",364,127,82,[&]{d.close(IDCANCEL);});};d.DoModal();refreshLogins();}
 BOOL OnNotify(WPARAM w,LPARAM l,LRESULT* result)override{if(tabs&&((NMHDR*)l)->hwndFrom==tabs->m_hWnd&&((NMHDR*)l)->code==TCN_SELCHANGE){page();*result=0;return TRUE;}return Form::OnNotify(w,l,result);}
public:
 Options(Manager& m,CWnd* parent):Form("UDM Configuration",602,423,parent),manager(m){Lock l(m.mutex);prefs=m.state["Settings"];prefs["RunAtLogin"]=startupEnabled();init=[this]{tabs=make<CTabCtrl>(WS_TABSTOP,9,9,584,366);const wchar_t* names[]={L"General",L"File types",L"Save to",L"Downloads",L"Connection",L"Proxy",L"Site logins",L"Sounds",L"Duplicates"};for(int p=0;p<9;++p){tabs->InsertItem(p,names[p]);size_t before=controls.size();switch(p){case 0:boolean("ClipboardMonitor","Monitor copied URLs",49);boolean("CloseToTray","Close the main window to the notification area",81);boolean("SkipBrowserFileInfo","Start browser downloads without the File Info dialog",113);boolean("SuppressProgressDialog","Do not show a download progress dialog automatically",145);boolean("SuppressCompletionDialog","Do not show the completion dialog",177);boolean("RunAtLogin","Start UDM when I sign in to Windows",209);label("Browser integration uses the UDM extension and native messaging host.",26,244,550,30);button("Configure browser integration...",26,280,282,[this]{browserIntegration(this,prefs);});break;
 case 1:field("CaptureExtensions","Capture these file extensions",58);field("CaptureExcludedHosts","Excluded host names",108);label("Enter extensions or host names separated by spaces. Automatic handoff is controlled by the extension.",26,159,540,56);break;
 case 2:{auto folder=field("DownloadFolder","Default download folder",52);button("Browse...",468,87,100,[this,folder]{auto result=chooseFolder(this,wide(text(folder)));if(!result.empty())folder->SetWindowText(result.c_str());});boolean("CategoryFolders","Create separate folders for file categories",130);button("Category rules",26,174,150,[this]{categoryRule(this,prefs);});button("Add category",190,174,150,[this]{auto name=prompt(this,"Add category");if(name.empty())return;if(safeName(name)!=name)throw std::runtime_error("Choose a valid category name.");for(auto value:prefs["CustomCategories"])if(lower(value.get<std::string>())==lower(name))throw std::runtime_error("That category exists.");prefs["CustomCategories"].push_back(name);});field("TemporaryFolder","Temporary folder (blank = default)",228);boolean("UseServerDate","Use the server file date for completed downloads",269);break;}
 case 3:field("Parallel","Simultaneous downloads (1-16)",51,true);field("Retries","Retries per connection (0-10)",90,true);field("ScanProgram","Virus scanner program (optional)",146);field("ScanArguments","Scanner arguments",185);boolean("PrefetchFileInfo","Download HTTP files while File Info is open",231);button("Customize progress dialog...",26,266,259,[this]{progressPreferences(this,prefs);});label("Files are published after confirmation. {file} inserts the scanner file path.",26,304,547,36);break;
 case 4:field("Connections","Connections per download (1-32)",53,true);field("LimitKbps","Global speed limit (KB/s; 0 = off)",94,true);field("QuotaMb","Download quota (MB; 0 = off)",135,true);field("QuotaHours","Quota period (hours; 1-168)",176,true);button("Per-server connection limits",26,223,235,[this]{serverRulesDialog(this,prefs);});label("Server limits apply to newly added downloads. Existing files keep their own connection setting.",26,268,541,50);break;
 case 5:{label("Connection",26,58,210);auto choice=combo({"Use Windows proxy / PAC settings","Connect directly","Use a proxy server","Use a SOCKS5 proxy"},str(prefs,"ProxyMode",str(prefs,"Proxy").empty()?"Use Windows proxy / PAC settings":"Use a proxy server"),242,54,327);bindings.push_back([this,choice]{prefs["ProxyMode"]=text(choice);});field("Proxy","Proxy host:port",100);field("ProxyBypass","Bypass proxy for (semicolon list)",142);field("ProxyUser","Proxy user name",184);field("ProxySecret","Proxy password",226,false,true);label("HTTP and SOCKS5 proxies support HTTP(S) downloads. SOCKS5 resolves destination names through the proxy; credentials are encrypted in Windows.",26,274,540,52);break;}
 case 6:logins=make<CListCtrl>(WS_TABSTOP|WS_BORDER|LVS_SHOWSELALWAYS|LVS_REPORT|LVS_SINGLESEL,25,51,543,237);logins->SetExtendedStyle(LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);logins->InsertColumn(0,L"HTTPS origin",LVCFMT_LEFT,340);logins->InsertColumn(1,L"User name",LVCFMT_LEFT,181);button("New...",25,302,99,[this]{login();});button("Edit...",137,302,99,[this]{login(true);});button("Remove",249,302,99,[this]{int i=logins->GetNextItem(-1,LVNI_SELECTED);if(i>=0){prefs["SiteLogins"].erase(i);refreshLogins();}});refreshLogins();break;
 case 7:{const char* enabled[]={"Sound","FailureSoundEnabled","PauseSoundEnabled"};const char* file[]={"CompletionSoundFile","FailureSoundFile","PauseSoundFile"};const char* title[]={"Download complete","Download failed","Download paused"};for(int i=0;i<3;++i){int y=51+i*91;auto on=check(title[i],yes(prefs,enabled[i],i==0),26,y,541);auto path=edit(str(prefs,file[i]),26,y+28,336);button("Browse...",372,y+27,94,[this,path]{CFileDialog chooser(TRUE,L"wav",nullptr,OFN_FILEMUSTEXIST,L"Wave sound|*.wav||",this);if(chooser.DoModal()==IDOK)path->SetWindowText(chooser.GetPathName());});button("Play",476,y+27,92,[path]{auto value=trim(text(path));if(value.empty())MessageBeep(MB_OK);else if(!PlaySoundW(wide(value).c_str(),nullptr,SND_FILENAME|SND_ASYNC|SND_NODEFAULT))throw std::runtime_error("Windows could not play this WAV file.");});auto e=enabled[i],f=file[i];bindings.push_back([this,on,path,e,f]{auto value=trim(text(path));if(!value.empty()&&!fs::is_regular_file(fs::path(wide(value))))throw std::runtime_error("Choose an existing sound file.");prefs[e]=checked(on);prefs[f]=value;});}label("Leave the sound file blank to use the Windows notification sound.",26,336,541,29);break;}
 case 8:{label("When an address is already in your download history:",26,58,540,35);std::vector<std::string> choices={"Ask me what to do","Download another numbered copy","Show existing download / resume saved parts"};auto mode=str(prefs,"DuplicatePolicy","Ask");auto selected=mode=="Numbered"?1:mode=="Existing"?2:0;auto choice=combo(choices,choices[selected],26,102,541);bindings.push_back([this,choice]{prefs["DuplicatePolicy"]=choice->GetCurSel()==1?"Numbered":choice->GetCurSel()==2?"Existing":"Ask";});label("With Ask selected, a completed file can also be replaced. Replacement always requires your choice for that file and retains its previous version.",26,155,540,58);label("Active downloads and repeated browser handoffs reuse the existing task. Addresses with different query strings or account credentials stay separate.",26,236,540,62);break;}}
 std::vector<CWnd*> items;for(size_t i=before;i<controls.size();++i)items.push_back(controls[i].get());pages.push_back(items);}
 accept=[this]{applyOptions();close();};button("Apply",312,386,83,[this]{applyOptions();});button("OK",407,386,83,accept);button("Cancel",502,386,83,[this]{close(IDCANCEL);});page();};}
};
inline SYSTEMTIME toLocal(i64 ms){if(!ms)ms=epoch();ULARGE_INTEGER u{};u.QuadPart=(ms+11644473600000LL)*10000;FILETIME utc{u.LowPart,u.HighPart},local{};FileTimeToLocalFileTime(&utc,&local);SYSTEMTIME result{};FileTimeToSystemTime(&local,&result);return result;}
inline i64 fromLocal(SYSTEMTIME t){FILETIME local{},utc{};if(!SystemTimeToFileTime(&t,&local)||!LocalFileTimeToFileTime(&local,&utc))throw std::runtime_error("Invalid local date.");ULARGE_INTEGER u{};u.LowPart=utc.dwLowDateTime;u.HighPart=utc.dwHighDateTime;return (i64)(u.QuadPart/10000)-11644473600000LL;}
#include "SchedulerUi.hpp"
#include "GrabberUi.hpp"
class NetworkDialog:public Form {
 DECLARE_MESSAGE_MAP()
 CListCtrl* table=nullptr;CWnd* status=nullptr;std::unique_ptr<Monitor> monitor;std::map<DWORD,FILETIME> watched;
 void update(){Json rows;if(monitor){std::vector<DWORD> live;for(auto it=watched.begin();it!=watched.end();){Handle process(OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,it->first));FILETIME a{},b{},c{},d{};if(!process||!GetProcessTimes(process.h,&a,&b,&c,&d)||CompareFileTime(&a,&it->second)!=0)it=watched.erase(it);else{live.push_back(it->first);++it;}}monitor->watch(live);auto snap=monitor->snapshot();rows=snap["Flows"];status->SetWindowText(cs("WFP watching "+std::to_string(num(snap,"Watched"))+" processes. Dropped observations: "+std::to_string(num(snap,"Dropped"))));}else{rows=endpoints();status->SetWindowText(cs("Windows TCP / UDP endpoints. "+std::to_string(rows.size())+" connections. UDP remote peers require WFP."));}table->SetRedraw(FALSE);table->DeleteAllItems();int i=0;for(auto row:rows){table->InsertItem(i,cs(str(row,"Process","Process")+" ("+std::to_string(num(row,"ProcessId"))+")"));int column=1;for(auto key:{"Local","Remote","Transport","State"})table->SetItemText(i,column++,cs(str(row,key)));table->SetItemText(i,5,cs(monitor?bytes(num(row,"Received")):"--"));table->SetItemText(i,6,cs(monitor?bytes(num(row,"Sent")):"--"));++i;}table->SetRedraw(TRUE);table->Invalidate();}
 afx_msg void OnTimer(UINT_PTR id){try{update();}catch(const std::exception& e){status->SetWindowText(cs(e.what()));}Form::OnTimer(id);}
public:explicit NetworkDialog(CWnd* parent):Form("UDM network integration",805,484,parent){init=[this]{label("Browser and UDM connections",12,12,770);status=label("Reading connections...",12,40,778,39);table=make<CListCtrl>(WS_TABSTOP|WS_BORDER|LVS_SHOWSELALWAYS|LVS_REPORT|LVS_SINGLESEL,12,83,780,320);table->SetExtendedStyle(LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);const wchar_t* names[]={L"Process",L"Local endpoint",L"Remote endpoint",L"Protocol",L"State",L"Received",L"Sent"};int widths[]={130,175,175,58,79,74,64};for(int i=0;i<7;++i)table->InsertColumn(i,names[i],LVCFMT_LEFT,widths[i]);button("Start WFP monitor",12,418,157,[this]{auto driver=std::make_unique<Monitor>();std::set<DWORD> pids={GetCurrentProcessId()};for(auto row:endpoints())pids.insert((DWORD)num(row,"ProcessId"));watched.clear();for(auto pid:pids){if(watched.size()==32)break;Handle process(OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid));FILETIME a{},b{},c{},d{};if(process&&GetProcessTimes(process.h,&a,&b,&c,&d))watched[pid]=a;}std::vector<DWORD> live;for(auto& [pid,time]:watched)live.push_back(pid);driver->watch(live);monitor=std::move(driver);update();});button("Stop monitor",184,418,136,[this]{if(monitor)monitor->watch({});monitor.reset();watched.clear();update();});button("Driver status",337,418,128,[this]{auto info=diagnostics();if(monitor)info["DriverStatus"]="Available; this window owns monitoring.";MessageBox(cs(info.dump(2)),L"Driver status",MB_OK|MB_ICONINFORMATION);});button("Close",693,445,99,[this]{close();});label("The optional WFP driver observes traffic metadata and counters. It does not expose HTTPS video URLs.",12,454,670,26);update();SetTimer(1,1000,nullptr);};}
 ~NetworkDialog(){if(monitor)try{monitor->watch({});}catch(...) {}}
};
BEGIN_MESSAGE_MAP(NetworkDialog,Form)
 ON_WM_TIMER()
END_MESSAGE_MAP()
}
