#pragma once
static void workflowChecks(const fs::path& root,Fixture& fixture){
 Manager m(root/L"workflow-state");auto prefs=m.state["Settings"];prefs["DownloadFolder"]=utf8((root/L"workflow-files").wstring());prefs["CategoryFolders"]=false;prefs["Connections"]=32;prefs["ServerConnections"]=Json::array({{{"Host","127.0.0.1"},{"Connections",4}}});prefs["QuotaHours"]=6;m.setSettings(prefs);
 auto job=m.add(fixture.url("/range"),"","move-original.bin");check(num(job->data,"Connections")==4,"Per-server connection limit overrides the 32-connection default");
 auto other=m.add("https://example.com/file.bin");check(num(other->data,"Connections")==32,"32 connections survive job creation");
 auto invalid=prefs;invalid["Connections"]=33;rejects([&]{m.setSettings(invalid);},"Connection settings reject counts above 32");invalid=prefs;invalid["QuotaHours"]=0;rejects([&]{m.setSettings(invalid);},"Quota rejects an empty period");
 transfer(m,job,std::make_shared<Cancel>());auto original=job->target();auto digest=fileHash(original);auto destination=original.parent_path()/L"renamed.bin";
 m.relocate(job,destination);check(!fs::exists(original)&&fs::is_regular_file(destination)&&fileHash(destination)==digest&&job->target()==destination,"Move/Rename relocates complete bytes and updates history");
 auto collision=destination.parent_path()/L"collision-existing.bin";writeBytes(collision,Bytes{'k','e','e','p'});rejects([&]{m.relocate(job,collision);},"Move/Rename refuses an existing destination");check(readText(collision)=="keep"&&fileHash(destination)==digest,"Move collision preserves both files");
 auto reserved=m.add(fixture.url("/range"),"","reserved.bin");rejects([&]{m.relocate(job,reserved->target());},"Move/Rename refuses another record's reserved path");
 auto stateTemp=m.root/L"state.json.tmp";fs::create_directory(stateTemp);rejects([&]{m.relocate(job,destination.parent_path()/L"rollback.bin");},"Move/Rename reports a state-write failure");fs::remove(stateTemp);check(job->target()==destination&&fs::exists(destination)&&!fs::exists(destination.parent_path()/L"rollback.bin")&&!fs::exists(m.root/L"file-operation.json"),"State-write failure rolls back the file move");
 m.updateCompleted(job,{{"Description","Edited description"},{"DownloadPage","https://example.com/download"}});check(str(job->data,"Description")=="Edited description"&&recoveryPage(job->data)=="https://example.com/download","Completed properties persist description and source page");
 auto copy=m.redownload(job);check(copy->id()!=job->id()&&copy->target()!=job->target()&&num(copy->data,"Received")==0&&str(copy->data,"Status")=="Paused"&&fileHash(job->target())==digest,"Redownload creates a fresh numbered copy and preserves the original");
 check(str(copy->data,"Description")=="Edited description"&&str(copy->data,"DownloadPage")=="https://example.com/download","Redownload retains descriptive metadata");
 m.setMembership(copy,false);m.queueRun("Main queue",true);check(str(copy->data,"Status")=="Paused"&&!yes(copy->data,"QueueMember"),"Starting a queue excludes removed membership");m.setMembership(copy,true);m.queueRun("Main queue",true);check(str(copy->data,"Status")=="Queued","Re-adding queue membership makes the file eligible");m.pause(copy);
 rejects([&]{m.setMembership(job,true);},"Completed files cannot enter pending queues without Redownload");
 // Simulate termination after a move but before history publication.
 auto crashDest=destination.parent_path()/L"recovered.bin";auto before=job->data,after=before;after["FileName"]="recovered.bin";
 atomicText(m.root/L"file-operation.json",Json{{"Id",job->id()},{"Source",utf8(destination.wstring())},{"Destination",utf8(crashDest.wstring())},{"Before",before},{"After",after}}.dump(),false);fs::rename(destination,crashDest);m.recoverFileOperation();check(job->target()==crashDest&&fileHash(crashDest)==digest&&!fs::exists(m.root/L"file-operation.json"),"Interrupted move recovers history from the verified destination");
 prefs=m.state["Settings"];prefs["TemporaryFolder"]=utf8((root/L"custom-temporary").wstring());m.setSettings(prefs);auto temp=m.add(fixture.url("/range"),"","custom-parts.bin");transfer(m,temp,std::make_shared<Cancel>());check(str(temp->data,"PartsFolder").find("custom-temporary")!=std::string::npos&&fileHash(temp->target())==digest,"Custom temporary folder produces the exact completed file");
 auto pending=m.add(fixture.url("/range"),"","prefetch.bin");auto prefetchStarted=GetTickCount64();m.beginPrefetch(pending);
 for(int i=0;i<600;++i){Sleep(10);Lock lock(m.mutex);if(num(pending->data,"Received")>=num(pending->data,"Size")&&num(pending->data,"Size")>0)break;}
 {Lock lock(m.mutex);check(num(pending->data,"Received")>0&&yes(pending->data,"ConfirmationPending")&&!fs::exists(pending->target()),"Prefetch receives bytes but cannot publish before confirmation");}
 Sleep(300);m.endPrefetch(pending);check(real(pending->data,"TransferSeconds")+.2<(GetTickCount64()-prefetchStarted)/1000.0,"Prefetch network-time metrics exclude confirmation waiting");check(!m.isActive(pending)&&str(pending->data,"Status")=="Paused"&&!fs::exists(pending->target()),"Canceling File Info stops prefetch without publishing");
 auto saved=num(pending->data,"Received");m.configure(pending,{{"FileName","confirmed-prefetch.bin"}});transfer(m,pending,std::make_shared<Cancel>());check(saved>0&&fileHash(pending->target())==digest,"Confirmed prefetch reuses saved parts after a filename change");
 auto blocked=m.add(fixture.url("/stall-body"),"","prefetch-stall.bin");m.beginPrefetch(blocked);Sleep(150);auto start=GetTickCount64();m.endPrefetch(blocked);check(!m.isActive(blocked)&&GetTickCount64()-start<2000,"Canceling a stalled prefetch is prompt");
 auto cross=fs::temp_directory_path()/(L"udm-move-"+wide(guid()));fs::create_directories(cross);auto crossFile=cross/L"cross-volume.bin";auto savedTarget=job->target();m.relocate(job,crossFile);check(fs::exists(crossFile)&&!fs::exists(savedTarget)&&fileHash(crossFile)==digest,"Cross-volume Move/Rename preserves exact bytes");m.relocate(job,savedTarget);fs::remove(cross);
 auto datedPrefs=m.state["Settings"];datedPrefs["UseServerDate"]=true;m.setSettings(datedPrefs);auto dated=m.add(fixture.url("/dated"),"","server-date.bin");transfer(m,dated,std::make_shared<Cancel>());FILETIME created{},written{};{Handle handle(CreateFileW(dated->target().c_str(),FILE_READ_ATTRIBUTES,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr));GetFileTime(handle.h,&created,nullptr,&written);}SYSTEMTIME observed{};FileTimeToSystemTime(&written,&observed);check(observed.wYear==2015&&observed.wMonth==10&&observed.wDay==21&&observed.wHour==7&&CompareFileTime(&created,&written)==0,"Server date applies to both creation and last-write timestamps");
 auto wideJob=m.add(fixture.url("/range"),"","32-workers.bin");m.configure(wideJob,{{"Connections",32}});transfer(m,wideJob,std::make_shared<Cancel>());check(wideJob->workers.size()==32&&fileHash(wideJob->target())==digest,"The actual HTTP worker pool accepts 32 connections and preserves bytes");
 m.state["QuotaStart"]=date(epoch()-2*3600000LL);m.state["QuotaBytes"]=17;Rate rate;Cancel quotaCancel;m.charge(1,quotaCancel,rate,wideJob);check(num(m.state,"QuotaBytes")==18,"Six-hour quota does not reset after only two hours");m.state["QuotaStart"]=date(epoch()-7*3600000LL);m.charge(1,quotaCancel,rate,wideJob);check(num(m.state,"QuotaBytes")==1,"Quota resets when its configured period elapses");
 auto ordinary=prefs;ordinary["PrefetchFileInfo"]=false;m.setSettings(ordinary);auto noPrefetch=m.add(fixture.url("/range"),"","prefetch-disabled.bin");m.beginPrefetch(noPrefetch);check(!m.isActive(noPrefetch)&&num(noPrefetch->data,"Received")==0,"Disabled prefetch leaves the server untouched");
 auto savedSettings=m.state["Settings"];savedSettings["CompletedDoubleClick"]="Open";savedSettings["DarkMode"]=true;savedSettings["FontName"]="Segoe UI";savedSettings["FontHeight"]=12;savedSettings["TrayIcon"]="Hidden";m.setSettings(savedSettings);
 {Manager reopened(m.root);check(str(reopened.state["Settings"],"CompletedDoubleClick")=="Open"&&yes(reopened.state["Settings"],"DarkMode")&&num(reopened.state["Settings"],"FontHeight")==12&&str(reopened.state["Settings"],"TrayIcon")=="Hidden","Interaction and appearance preferences survive restart");}
 m.stop();
}
