#pragma once
#include "Ui.hpp"
#include <future>
namespace udm {
inline void categoryRule(CWnd* owner,Json& prefs){Form d("Category settings",463,198,owner);d.init=[&]{std::vector<std::string> categories={"Archives","Documents","Music","Programs","Video","Images","Other"};for(auto c:prefs["CustomCategories"])categories.push_back(c.get<std::string>());d.label("Category",10,15,87);auto cat=d.combo(categories,"Archives",105,11,348);d.label("Extensions",10,51,87);auto extensions=d.edit("",105,47,348);d.label("Sites (optional)",10,87,94);auto hosts=d.edit("",105,83,348);d.label("Separate extensions and host names with spaces. Use * for all file types.",10,122,443,34);d.button("Load rule",10,161,87,[cat,extensions,hosts,&prefs]{for(auto r:prefs["CategoryRules"])if(str(r,"Category")==text(cat)){extensions->SetWindowText(cs(str(r,"Extensions")));hosts->SetWindowText(cs(str(r,"Hosts")));return;}extensions->SetWindowText(L"");hosts->SetWindowText(L"");});d.accept=[&,cat,extensions,hosts]{auto ex=words(text(extensions));for(auto s:ex)if(s!="*"&&!std::regex_match(s,std::regex("[a-z0-9_-]{1,30}")))throw std::runtime_error("Use plain extensions such as zip mp4 pdf.");for(auto h:words(text(hosts)))Url("https://"+h+"/");auto& rules=prefs["CategoryRules"];rules.erase(std::remove_if(rules.begin(),rules.end(),[&](const Json& r){return str(r,"Category")==text(cat);}),rules.end());if(!ex.empty())rules.push_back({{"Category",text(cat)},{"Extensions",text(extensions)},{"Hosts",text(hosts)}});d.close();};d.button("Save",273,161,83,d.accept);d.button("Cancel",366,161,87,[&]{d.close(IDCANCEL);});};d.DoModal();}
class Options:public Form {
 Manager& manager;Json prefs;CTabCtrl* tabs=nullptr;std::vector<std::vector<CWnd*>> pages;std::vector<std::function<void()>> bindings;CListCtrl* logins=nullptr;
 void page(){int current=tabs->GetCurSel();for(size_t i=0;i<pages.size();++i)for(auto w:pages[i])w->ShowWindow((int)i==current?SW_SHOW:SW_HIDE);}
 void boolean(const char* key,std::string title,int y){auto c=check(title,yes(prefs,key),26,y,552);bindings.push_back([this,c,key]{prefs[key]=checked(c);});}
 CWnd* field(const char* key,std::string title,int y,bool number=false,bool secret=false){label(title,26,y+4,210);auto c=edit(secret?reveal(str(prefs,key)):number?std::to_string(num(prefs,key)):str(prefs,key),242,y,327,23,false,false,secret);bindings.push_back([this,c,key,number,secret]{prefs[key]=number?Json(std::stoll(text(c))):Json(secret?protect(text(c)):text(c));});return c;}
 void refreshLogins(){logins->DeleteAllItems();int i=0;for(auto login:prefs["SiteLogins"]){logins->InsertItem(i,cs(str(login,"Origin")));logins->SetItemText(i++,1,cs(str(login,"UserName")));}}
 void login(){Form d("Site login",456,166,this);d.init=[&]{d.label("HTTPS site",10,15,93);auto site=d.edit("https://",111,11,335);d.label("User name",10,50,93);auto user=d.edit("",111,46,335);d.label("Password",10,85,93);auto password=d.edit("",111,81,335,23,false,false,true);d.accept=[&,site,user,password]{Url u(text(site));if(u.scheme!="https")throw std::runtime_error("Saved logins require HTTPS.");if(text(user).empty()||text(user).find(':')!=std::string::npos)throw std::runtime_error("Enter a user name without a colon.");auto& list=prefs["SiteLogins"];list.erase(std::remove_if(list.begin(),list.end(),[&](const Json& l){return str(l,"Origin")==u.origin;}),list.end());list.push_back({{"Origin",u.origin},{"UserName",text(user)},{"ProtectedPassword",protect(text(password))}});d.close();};d.button("Save",270,127,82,d.accept);d.button("Cancel",364,127,82,[&]{d.close(IDCANCEL);});};d.DoModal();refreshLogins();}
 BOOL OnNotify(WPARAM w,LPARAM l,LRESULT* result)override{if(tabs&&((NMHDR*)l)->hwndFrom==tabs->m_hWnd&&((NMHDR*)l)->code==TCN_SELCHANGE){page();*result=0;return TRUE;}return Form::OnNotify(w,l,result);}
public:
 Options(Manager& m,CWnd* parent):Form("UDM Configuration",602,423,parent),manager(m){Lock l(m.mutex);prefs=m.state["Settings"];init=[this]{tabs=make<CTabCtrl>(WS_TABSTOP,9,9,584,366);const wchar_t* names[]={L"General",L"File types",L"Save to",L"Downloads",L"Connection",L"Proxy",L"Site logins",L"Sounds"};for(int p=0;p<8;++p){tabs->InsertItem(p,names[p]);size_t before=controls.size();switch(p){case 0:boolean("ClipboardMonitor","Monitor copied URLs",49);boolean("CloseToTray","Close the main window to the notification area",81);boolean("SkipBrowserFileInfo","Start browser downloads without the File Info dialog",113);boolean("SuppressProgressDialog","Do not show a download progress dialog automatically",145);boolean("SuppressCompletionDialog","Do not show the completion dialog",177);label("Browser integration uses the UDM extension and native messaging host.",26,224,550,36);button("Browser integration help",26,280,192,[this]{MessageBox(L"Load browser/chromium or browser/firefox, then run browser/register-host.ps1 with the extension ID.\n\nThe native C++ host uses the same browser protocol as your existing extension.",L"Browser integration",MB_OK|MB_ICONINFORMATION);});break;
 case 1:field("CaptureExtensions","Capture these file extensions",58);field("CaptureExcludedHosts","Excluded host names",108);label("Enter extensions or host names separated by spaces. Automatic handoff is controlled by the extension.",26,159,540,56);break;
 case 2:{auto folder=field("DownloadFolder","Default download folder",52);button("Browse...",468,87,100,[this,folder]{auto result=chooseFolder(this,wide(text(folder)));if(!result.empty())folder->SetWindowText(result.c_str());});boolean("CategoryFolders","Create separate folders for file categories",130);button("Category rules",26,174,150,[this]{categoryRule(this,prefs);});button("Add category",190,174,150,[this]{auto name=prompt(this,"Add category");if(name.empty())return;if(safeName(name)!=name)throw std::runtime_error("Choose a valid category name.");for(auto value:prefs["CustomCategories"])if(lower(value.get<std::string>())==lower(name))throw std::runtime_error("That category exists.");prefs["CustomCategories"].push_back(name);});label("Per-category destinations can be remembered in Download File Info.",26,234,545,42);break;}
 case 3:field("Parallel","Simultaneous downloads (1-16)",51,true);field("Retries","Retries per connection (0-10)",90,true);field("ScanProgram","Virus scanner program (optional)",146);field("ScanArguments","Scanner arguments",185);label("Use {file} in scanner arguments. The scanner runs only after a completed file is saved.",26,232,547,49);break;
 case 4:field("Connections","Connections per download (1-16)",53,true);field("LimitKbps","Global speed limit (KB/s; 0 = off)",97,true);field("QuotaMb","Hourly quota (MB; 0 = off)",141,true);label("Servers must support validated byte ranges for segmented transfer and reliable resume. Individual limits are in each download's Speed Limiter tab.",26,200,541,82);break;
 case 5:field("Proxy","Proxy server (blank = Windows)",58);field("ProxyUser","Proxy user name",102);field("ProxySecret","Proxy password",146,false,true);label("Passwords and captured request headers are encrypted for your Windows account.",26,209,540,52);break;
 case 6:logins=make<CListCtrl>(LVS_REPORT|LVS_SINGLESEL,25,51,543,237);logins->SetExtendedStyle(LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);logins->InsertColumn(0,L"HTTPS origin",LVCFMT_LEFT,340);logins->InsertColumn(1,L"User name",LVCFMT_LEFT,181);button("Add / update",25,302,136,[this]{login();});button("Remove",172,302,99,[this]{int i=logins->GetNextItem(-1,LVNI_SELECTED);if(i>=0){prefs["SiteLogins"].erase(i);refreshLogins();}});refreshLogins();break;
 case 7:boolean("Sound","Play a sound when a download finishes",59);label("UDM uses the Windows notification sound.",26,107,537);break;}
 std::vector<CWnd*> items;for(size_t i=before;i<controls.size();++i)items.push_back(controls[i].get());pages.push_back(items);}
 accept=[this]{for(auto& apply:bindings)apply();manager.setSettings(prefs);close();};button("OK",407,386,83,accept);button("Cancel",502,386,83,[this]{close(IDCANCEL);});page();};}
};
inline SYSTEMTIME toLocal(i64 ms){if(!ms)ms=epoch();ULARGE_INTEGER u{};u.QuadPart=(ms+11644473600000LL)*10000;FILETIME utc{u.LowPart,u.HighPart},local{};FileTimeToLocalFileTime(&utc,&local);SYSTEMTIME result{};FileTimeToSystemTime(&local,&result);return result;}
inline i64 fromLocal(SYSTEMTIME t){FILETIME local{},utc{};if(!SystemTimeToFileTime(&t,&local)||!LocalFileTimeToFileTime(&local,&utc))throw std::runtime_error("Invalid local date.");ULARGE_INTEGER u{};u.LowPart=utc.dwLowDateTime;u.HighPart=utc.dwHighDateTime;return (i64)(u.QuadPart/10000)-11644473600000LL;}
class Scheduler:public Form {
 Manager& manager;CComboBox* queue=nullptr;CWnd *enabled=nullptr,*scheduled=nullptr,*once=nullptr,*parallel=nullptr,*retry=nullptr,*startTime=nullptr,*stopTime=nullptr;CWnd* days[7]{};CDateTimeCtrl *startDate=nullptr,*stopDate=nullptr;CListCtrl* list=nullptr;std::vector<JobPtr> rows;std::string selected;bool loading=false;
 void load(){Lock l(manager.mutex);selected=text(queue);Json q=defaultQueue(selected);for(auto r:manager.state["Queues"])if(str(r,"Name")==selected)q=r;enabled->SendMessage(BM_SETCHECK,yes(q,"Enabled",true));scheduled->SendMessage(BM_SETCHECK,yes(q,"Scheduled"));once->SendMessage(BM_SETCHECK,yes(q,"RunOnce"));parallel->SetWindowText(cs(std::to_string(num(q,"Parallel",2))));retry->SetWindowText(cs(q.value("Retries",Json()).is_null()?"":std::to_string(num(q,"Retries"))));auto time=[](i64 n){char b[10];sprintf_s(b,"%02lld:%02lld",n/60,n%60);return std::string(b);};startTime->SetWindowText(cs(time(num(q,"StartMinute"))));stopTime->SetWindowText(cs(time(num(q,"StopMinute",1440))));for(int i=0;i<7;++i)days[i]->SendMessage(BM_SETCHECK,(num(q,"Days",127)&(1LL<<i))?BST_CHECKED:BST_UNCHECKED);auto a=toLocal(parseDate(q.value("StartOnceUtc",Json()))),b=toLocal(parseDate(q.value("StopOnceUtc",Json())));startDate->SetTime(&a);stopDate->SetTime(&b);rows.clear();list->DeleteAllItems();for(auto j:manager.jobs)if(str(j->data,"Queue")==selected){int i=(int)rows.size();rows.push_back(j);list->InsertItem(i,cs(str(j->data,"FileName")));list->SetItemText(i,1,cs(str(j->data,"Status")));}}
 void save(){Json q;{Lock l(manager.mutex);for(auto r:manager.state["Queues"])if(str(r,"Name")==selected)q=r;}auto parse=[](const std::string& s){std::smatch m;if(!std::regex_match(s,m,std::regex("([0-9]{1,2}):([0-9]{2})")))throw std::runtime_error("Use HH:MM for times.");int hour=std::stoi(m[1]),minute=std::stoi(m[2]);if(hour>24||minute>59||(hour==24&&minute))throw std::runtime_error("Invalid time.");return hour*60+minute;};q["Enabled"]=checked(enabled);q["Scheduled"]=checked(scheduled);q["RunOnce"]=checked(once);q["Parallel"]=std::stoll(text(parallel));q["Retries"]=text(retry).empty()?Json():Json(std::stoll(text(retry)));q["StartMinute"]=parse(text(startTime));q["StopMinute"]=parse(text(stopTime));int mask=0;for(int i=0;i<7;++i)if(checked(days[i]))mask|=1<<i;q["Days"]=mask;SYSTEMTIME a{},b{};startDate->GetTime(&a);stopDate->GetTime(&b);q["StartOnceUtc"]=date(fromLocal(a));q["StopOnceUtc"]=date(fromLocal(b));manager.setQueue(q);}
 BOOL OnCommand(WPARAM w,LPARAM l)override{if(queue&&LOWORD(w)==queue->GetDlgCtrlID()&&HIWORD(w)==CBN_SELCHANGE){try{load();}catch(const std::exception& e){error(this,e);}return TRUE;}return Form::OnCommand(w,l);}
public:Scheduler(Manager& m,CWnd* parent,std::string name="Main queue"):Form("Scheduler",635,498,parent),manager(m),selected(std::move(name)){init=[this]{label("Queue",12,14,43);queue=combo(queueNames(manager),selected,60,10,329);button("New",401,10,94,[this]{auto name=prompt(this,"New queue");if(name.empty())return;auto q=defaultQueue(name);q["Enabled"]=false;manager.setQueue(q);queue->AddString(cs(name));queue->SelectString(-1,cs(name));load();});button("Delete queue",506,10,116,[this]{manager.deleteQueue(selected);queue->ResetContent();for(auto name:queueNames(manager))queue->AddString(cs(name));queue->SetCurSel(0);load();});enabled=check("Queue enabled",true,14,49,177);scheduled=check("Daily schedule",false,211,49,187);once=check("Run once on dates below",false,405,49,219);label("Start at",15,88,69);startTime=edit("00:00",89,83,85);label("Stop at",211,88,69);stopTime=edit("24:00",290,83,84);const char* names[]={"Sun","Mon","Tue","Wed","Thu","Fri","Sat"};for(int i=0;i<7;++i)days[i]=check(names[i],true,15+i*85,120,80);label("Start date",15,159,72);startDate=make<CDateTimeCtrl>(WS_TABSTOP|DTS_SHORTDATEFORMAT,90,155,216,24);startDate->SetFormat(L"yyyy-MM-dd HH:mm");label("Stop date",327,159,72);stopDate=make<CDateTimeCtrl>(WS_TABSTOP|DTS_SHORTDATEFORMAT,406,155,215,24);stopDate->SetFormat(L"yyyy-MM-dd HH:mm");label("Files at a time",15,197,113);parallel=edit("2",132,193,60);label("Retries (blank = default)",243,197,202);retry=edit("",455,193,67);list=make<CListCtrl>(LVS_REPORT|LVS_SINGLESEL,15,235,607,175);list->SetExtendedStyle(LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);list->InsertColumn(0,L"Files in the queue",LVCFMT_LEFT,450);list->InsertColumn(1,L"Status",LVCFMT_LEFT,133);button("Move up",15,419,94,[this]{int i=list->GetNextItem(-1,LVNI_SELECTED);if(i>=0){manager.move(rows[i],-1);load();}});button("Move down",119,419,101,[this]{int i=list->GetNextItem(-1,LVNI_SELECTED);if(i>=0){manager.move(rows[i],1);load();}});button("Start now",290,419,100,[this]{save();manager.queueRun(selected,true);load();});button("Stop",401,419,92,[this]{manager.queueRun(selected,false);load();});accept=[this]{save();close();};button("Apply",435,462,89,[this]{save();});button("Close",534,462,88,[this]{close();});load();};}};
class GrabberDialog:public Form {
 DECLARE_MESSAGE_MAP()
 Manager& manager;Json project;CComboBox *projects=nullptr,*queue=nullptr;CWnd *name=nullptr,*address=nullptr,*extensions=nullptr,*depth=nullptr,*maximum=nullptr,*status=nullptr;CListCtrl* links=nullptr;std::shared_ptr<Cancel> cancelWork;std::future<Json> work;bool running=false;
 void showProject(){name->SetWindowText(cs(str(project,"Name","New project")));address->SetWindowText(cs(str(project,"StartUrl","https://")));extensions->SetWindowText(cs(str(project,"Extensions","zip pdf jpg png mp4 mp3")));depth->SetWindowText(cs(std::to_string(num(project,"Depth",1))));maximum->SetWindowText(cs(std::to_string(num(project,"MaxPages",20))));links->DeleteAllItems();int i=0;for(auto l:project["Links"]){links->InsertItem(i,cs(str(l,"Url")));links->SetCheck(i++,yes(l,"Selected",true));}}
 void collect(){project["Name"]=text(name);project["StartUrl"]=text(address);project["Extensions"]=text(extensions);project["Depth"]=std::stoll(text(depth));project["MaxPages"]=std::stoll(text(maximum));for(int i=0;i<links->GetItemCount();++i)project["Links"][i]["Selected"]=links->GetCheck(i)!=FALSE;}
 afx_msg void OnTimer(UINT_PTR id){if(running&&work.wait_for(std::chrono::milliseconds(0))==std::future_status::ready){running=false;try{project=work.get();manager.saveProject(project);showProject();status->SetWindowText(cs("Found "+std::to_string(project["Links"].size())+" files."));}catch(const std::exception& e){status->SetWindowText(cs(e.what()));}}Form::OnTimer(id);}
 BOOL OnCommand(WPARAM w,LPARAM l)override{if(projects&&LOWORD(w)==projects->GetDlgCtrlID()&&HIWORD(w)==CBN_SELCHANGE&&!running){Lock lock(manager.mutex);for(auto p:manager.state["Projects"])if(str(p,"Name")==text(projects)){project=p;showProject();break;}return TRUE;}return Form::OnCommand(w,l);}
 void OnCancel()override{if(running){cancelWork->stop=true;status->SetWindowText(L"Stopping exploration...");return;}Form::OnCancel();}
public:GrabberDialog(Manager& m,CWnd* parent):Form("Site Grabber",646,488,parent),manager(m){project={{"Id",guid()},{"Name","New project"},{"StartUrl","https://"},{"Extensions","zip pdf jpg png mp4 mp3"},{"Depth",1},{"MaxPages",20},{"Links",Json::array()}};init=[this]{std::vector<std::string> names;{Lock l(manager.mutex);for(auto p:manager.state["Projects"])names.push_back(str(p,"Name"));}label("Saved project",12,14,96);projects=combo(names,"",114,10,393);button("New",520,10,112,[this]{if(running)return;project={{"Id",guid()},{"Name","New project"},{"StartUrl","https://"},{"Extensions","zip pdf jpg png mp4 mp3"},{"Depth",1},{"MaxPages",20},{"Links",Json::array()}};showProject();});label("Name",12,50,96);name=edit("",114,46,518);label("Start page",12,86,96);address=edit("",114,82,518);label("File extensions",12,122,96);extensions=edit("",114,118,518);label("Depth",12,159,48);depth=edit("1",66,155,54);label("Maximum pages",147,159,124);maximum=edit("20",277,155,58);button("Explore",382,153,112,[this]{if(running)return;collect();manager.saveProject(project);cancelWork=std::make_shared<Cancel>();auto p=project;Json prefs;{Lock l(manager.mutex);prefs=manager.state["Settings"];}auto c=cancelWork;running=true;status->SetWindowText(L"Exploring pages on the starting site...");work=std::async(std::launch::async,[p,prefs,c]{return explore(p,prefs,*c);});});button("Stop",509,153,123,[this]{if(cancelWork)cancelWork->stop=true;});links=make<CListCtrl>(LVS_REPORT|LVS_NOSORTHEADER,12,195,620,198);links->SetExtendedStyle(LVS_EX_CHECKBOXES|LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);links->InsertColumn(0,L"Files found",LVCFMT_LEFT,596);status=label("",12,402,620);queue=combo(queueNames(manager),"Main queue",12,437,249);button("Add selected",275,437,121,[this]{if(running)throw std::runtime_error("Wait for exploration to finish.");collect();int count=manager.addProject(project,text(queue),true);status->SetWindowText(cs("Added "+std::to_string(count)+" files, paused."));});button("Save project",405,437,119,[this]{if(running)return;collect();manager.saveProject(project);status->SetWindowText(L"Project saved.");});button("Close",534,437,98,[this]{OnCancel();});showProject();SetTimer(1,200,nullptr);};}
 ~GrabberDialog(){if(cancelWork)cancelWork->stop=true;if(work.valid())work.wait();}
};
BEGIN_MESSAGE_MAP(GrabberDialog,Form)
 ON_WM_TIMER()
END_MESSAGE_MAP()
class NetworkDialog:public Form {
 DECLARE_MESSAGE_MAP()
 CListCtrl* table=nullptr;CWnd* status=nullptr;std::unique_ptr<Monitor> monitor;std::map<DWORD,FILETIME> watched;
 void update(){Json rows;if(monitor){std::vector<DWORD> live;for(auto it=watched.begin();it!=watched.end();){Handle process(OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,it->first));FILETIME a{},b{},c{},d{};if(!process||!GetProcessTimes(process.h,&a,&b,&c,&d)||CompareFileTime(&a,&it->second)!=0)it=watched.erase(it);else{live.push_back(it->first);++it;}}monitor->watch(live);auto snap=monitor->snapshot();rows=snap["Flows"];status->SetWindowText(cs("WFP watching "+std::to_string(num(snap,"Watched"))+" processes. Dropped observations: "+std::to_string(num(snap,"Dropped"))));}else{rows=endpoints();status->SetWindowText(cs("Windows TCP / UDP endpoints. "+std::to_string(rows.size())+" connections. UDP remote peers require WFP."));}table->SetRedraw(FALSE);table->DeleteAllItems();int i=0;for(auto row:rows){table->InsertItem(i,cs(str(row,"Process","Process")+" ("+std::to_string(num(row,"ProcessId"))+")"));int column=1;for(auto key:{"Local","Remote","Transport","State"})table->SetItemText(i,column++,cs(str(row,key)));table->SetItemText(i,5,cs(monitor?bytes(num(row,"Received")):"--"));table->SetItemText(i,6,cs(monitor?bytes(num(row,"Sent")):"--"));++i;}table->SetRedraw(TRUE);table->Invalidate();}
 afx_msg void OnTimer(UINT_PTR id){try{update();}catch(const std::exception& e){status->SetWindowText(cs(e.what()));}Form::OnTimer(id);}
public:explicit NetworkDialog(CWnd* parent):Form("UDM network integration",805,484,parent){init=[this]{label("Browser and UDM connections",12,12,770);status=label("Reading connections...",12,40,778,39);table=make<CListCtrl>(LVS_REPORT|LVS_SINGLESEL,12,83,780,320);table->SetExtendedStyle(LVS_EX_FULLROWSELECT|LVS_EX_DOUBLEBUFFER);const wchar_t* names[]={L"Process",L"Local endpoint",L"Remote endpoint",L"Protocol",L"State",L"Received",L"Sent"};int widths[]={130,175,175,58,79,74,64};for(int i=0;i<7;++i)table->InsertColumn(i,names[i],LVCFMT_LEFT,widths[i]);button("Start WFP monitor",12,418,157,[this]{auto driver=std::make_unique<Monitor>();std::set<DWORD> pids={GetCurrentProcessId()};for(auto row:endpoints())pids.insert((DWORD)num(row,"ProcessId"));watched.clear();for(auto pid:pids){if(watched.size()==32)break;Handle process(OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,pid));FILETIME a{},b{},c{},d{};if(process&&GetProcessTimes(process.h,&a,&b,&c,&d))watched[pid]=a;}std::vector<DWORD> live;for(auto& [pid,time]:watched)live.push_back(pid);driver->watch(live);monitor=std::move(driver);update();});button("Stop monitor",184,418,136,[this]{if(monitor)monitor->watch({});monitor.reset();watched.clear();update();});button("Driver status",337,418,128,[this]{auto info=diagnostics();if(monitor)info["DriverStatus"]="Available; this window owns monitoring.";MessageBox(cs(info.dump(2)),L"Driver status",MB_OK|MB_ICONINFORMATION);});button("Close",693,445,99,[this]{close();});label("The optional WFP driver observes traffic metadata and counters. It does not expose HTTPS video URLs.",12,454,670,26);update();SetTimer(1,1000,nullptr);};}
 ~NetworkDialog(){if(monitor)try{monitor->watch({});}catch(...) {}}
};
BEGIN_MESSAGE_MAP(NetworkDialog,Form)
 ON_WM_TIMER()
END_MESSAGE_MAP()
}
