using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Media;
using System.Windows.Forms;

namespace Udm {
    public sealed class MainWindow : Form {
        readonly Manager manager;
        readonly PipeServer pipe;
        readonly TreeView navigation;
        readonly FlowLayoutPanel toolbar;
        readonly DataGridView grid;
        readonly Label summary,details,heading,empty;
        readonly TextBox search;
        readonly Timer refresh;
        readonly NotifyIcon tray;
        readonly Label clipboardOffer;
        readonly Panel clipboardPanel;
        readonly Dictionary<string,DownloadProgressDialog> progressWindows=new Dictionary<string,DownloadProgressDialog>();
        readonly HashSet<string> infoWindows=new HashSet<string>();
        readonly Queue<Action> uiRequests=new Queue<Action>();
        string filter="all",lastClipboard="",offeredUrl="";
        bool quitting,closed;
        readonly Color blue=Color.FromArgb(39,96,222),ink=Color.FromArgb(26,39,59),muted=Color.FromArgb(105,119,139);
        public MainWindow(Manager m,PipeServer server,bool background) {
            SuspendLayout();AutoScaleDimensions=new SizeF(96,96);AutoScaleMode=AutoScaleMode.Dpi;manager=m;pipe=server;Text="UDM Download Manager";Size=new Size(762,460);MinimumSize=new Size(720,400);StartPosition=FormStartPosition.CenterScreen;Font=new Font("Tahoma",8.25f);BackColor=Color.White;ink=Color.FromArgb(235,237,239);muted=Color.FromArgb(180,185,191);
            Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);
            var menu=new MenuStrip{BackColor=Color.White,ForeColor=ink,Font=Font,Padding=new Padding(2,0,0,0),Height=21};
            var tasks=new ToolStripMenuItem("Tasks");tasks.DropDownItems.Add("Add new download",null,delegate{Add("");});tasks.DropDownItems.Add("Add batch download",null,delegate{using(var d=new BatchPatternDialog(manager))d.ShowDialog(this);});tasks.DropDownItems.Add("Run site grabber",null,delegate{using(var d=new GrabDialog(manager))d.ShowDialog(this);BuildTree();});tasks.DropDownItems.Add(new ToolStripSeparator());tasks.DropDownItems.Add("Import",null,delegate{Import();});tasks.DropDownItems.Add("Export",null,delegate{Export();});tasks.DropDownItems.Add("Exit",null,delegate{quitting=true;Close();});
            var file=new ToolStripMenuItem("File");file.DropDownItems.Add("Resume",null,delegate{ForSelected(manager.Resume);});file.DropDownItems.Add("Stop",null,delegate{ForSelected(manager.Pause);});file.DropDownItems.Add("Delete",null,delegate{RemoveSelected();});file.DropDownItems.Add("Properties",null,delegate{Properties();});file.DropDownItems.Add("Open",null,delegate{OpenFile();});file.DropDownItems.Add("Open folder",null,delegate{ShowFolder();});
            var downloads=new ToolStripMenuItem("Downloads");downloads.DropDownItems.Add("Pause all",null,delegate{lock(manager.Sync)foreach(var d in manager.State.Downloads)manager.Pause(d);});downloads.DropDownItems.Add("Delete all completed",null,delegate{RemoveCompleted();});downloads.DropDownItems.Add("Scheduler",null,delegate{EditQueue();});downloads.DropDownItems.Add("Start queue",null,delegate{SetQueueRunning(true);});downloads.DropDownItems.Add("Stop queue",null,delegate{SetQueueRunning(false);});downloads.DropDownItems.Add("Options",null,delegate{Settings();});
            var view=new ToolStripMenuItem("View");
            var help=new ToolStripMenuItem("Help");help.DropDownItems.Add("Browser integration",null,delegate{IntegrationHelp();});help.DropDownItems.Add("Network integration",null,delegate{using(var d=new NetworkMonitorDialog())d.ShowDialog(this);});help.DropDownItems.Add("About UDM",null,delegate{MessageBox.Show(this,"UDM 0.6.1 — original Windows download manager\n\nReference-aligned desktop layout, parallel transfers and browser integration.\n\nSee docs/deep-inspection.md for verified behavior and remaining differences.","About UDM");});
            menu.Items.AddRange(new ToolStripItem[]{tasks,file,downloads,view,help});MainMenuStrip=menu;
            var bar=toolbar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=61,Padding=new Padding(0),BackColor=Color.White,WrapContents=false};
            bar.Controls.Add(Button("Add URL",()=>Add(""),true,"add"));bar.Controls.Add(Button("Resume",()=>ForSelected(manager.Resume),false,"resume"));bar.Controls.Add(Button("Stop",()=>ForSelected(manager.Pause),false,"stop"));bar.Controls.Add(Button("Stop All",()=>{lock(manager.Sync)foreach(var j in manager.State.Downloads.Where(d=>manager.IsActive(d)||d.Status=="Queued").ToArray())manager.Pause(j);},false,"stopall"));bar.Controls.Add(Button("Delete",RemoveSelected,false,"remove"));bar.Controls.Add(Button("Delete Co...",RemoveCompleted,false,"complete"));bar.Controls.Add(Button("Options",Settings,false,"settings"));bar.Controls.Add(Button("Scheduler",EditQueue,false,"schedule"));bar.Controls.Add(Button("Start Queue",()=>SetQueueRunning(true),false,"startqueue"));bar.Controls.Add(Button("Stop Queue",()=>SetQueueRunning(false),false,"stopqueue"));bar.Controls.Add(Button("Grabber",()=>{using(var d=new GrabDialog(manager))d.ShowDialog(this);BuildTree();},false,"grabber"));
            var content=new SplitContainer{Dock=DockStyle.Fill,FixedPanel=FixedPanel.Panel1,SplitterDistance=136,Panel1MinSize=110,SplitterWidth=4,BackColor=Color.FromArgb(228,234,242)};
            navigation=new TreeView{Dock=DockStyle.Fill,BorderStyle=BorderStyle.None,BackColor=Color.FromArgb(247,249,252),ForeColor=ink,Font=new Font("Tahoma",8.25f),ItemHeight=16,FullRowSelect=false,HideSelection=false,ShowLines=true,ShowRootLines=true,Indent=14};content.Panel1.Controls.Add(navigation);var categoryHeading=new Label{Text="Categories",Dock=DockStyle.Top,Height=18,BorderStyle=BorderStyle.FixedSingle};content.Panel1.Controls.Add(categoryHeading);
            var navIcons=new ImageList{ImageSize=new Size(16,16),ColorDepth=ColorDepth.Depth32Bit};foreach(string key in Icons.Names)navIcons.Images.Add(key,Icons.Get(key,16));navigation.ImageList=navIcons;navigation.ImageKey="folder";navigation.SelectedImageKey="folder";
            var navMenu=new ContextMenuStrip();navMenu.Items.Add("Edit queue / schedule",Icons.Get("schedule",20),delegate{EditQueue();});navMenu.Items.Add("Create queue",Icons.Get("queue",20),delegate{using(var d=new NameDialog("Enter queue name","Enter a name for the new queue.","New queue"))if(d.ShowDialog(this)==DialogResult.OK){var created=manager.CreateQueue(d.Value);using(var s=new SchedulerDialog(manager,created))s.ShowDialog(this);}BuildTree();});navigation.ContextMenuStrip=navMenu;
            var top=new Panel{Visible=false,Dock=DockStyle.Top,Height=29,Padding=new Padding(5)};heading=new Label{Text="All downloads",Font=new Font("Segoe UI",9,FontStyle.Bold),ForeColor=ink,Dock=DockStyle.Left,Width=250};
            search=new TextBox{Dock=DockStyle.Right,Width=230,Font=new Font("Segoe UI",11),AccessibleName="Search downloads"};var searchLabel=new Label{Text="Search",Dock=DockStyle.Right,Width=65,TextAlign=ContentAlignment.MiddleLeft,ForeColor=muted};top.Controls.Add(heading);top.Controls.Add(searchLabel);top.Controls.Add(search);
            grid=new DataGridView{Dock=DockStyle.Fill,BackgroundColor=Color.White,BorderStyle=BorderStyle.None,AllowUserToAddRows=false,AllowUserToDeleteRows=false,AllowUserToResizeRows=false,ReadOnly=true,RowHeadersVisible=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,MultiSelect=true,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.None,EnableHeadersVisualStyles=false,GridColor=Color.FromArgb(237,240,245),CellBorderStyle=DataGridViewCellBorderStyle.Single,ColumnHeadersHeight=43};
            grid.ColumnHeadersDefaultCellStyle=new DataGridViewCellStyle{BackColor=Color.FromArgb(249,250,252),ForeColor=muted,Font=new Font("Tahoma",8.25f),Padding=new Padding(0)};
            grid.DefaultCellStyle=new DataGridViewCellStyle{Font=new Font("Tahoma",8.25f),BackColor=Color.FromArgb(56,56,56),ForeColor=ink,SelectionBackColor=Color.FromArgb(47,76,107),SelectionForeColor=ink,Padding=new Padding(2)};grid.RowTemplate.Height=17;grid.ColumnHeadersHeight=20;
            string[] titles={"File name","Q","Size","Status","Time left","Transfer rate","Last Try Date","Description"};int[] weights={155,23,76,65,74,96,100,140};for(int i=0;i<titles.Length;i++)grid.Columns.Add(new DataGridViewTextBoxColumn{HeaderText=titles[i],Width=weights[i],MinimumWidth=i==1?20:40,SortMode=DataGridViewColumnSortMode.Automatic});
            empty=new Label{Text="Ready when you are.\n\nAdd a URL, paste a batch, or drop a link here.",Font=new Font("Segoe UI",14),ForeColor=muted,AutoSize=false,Size=new Size(500,120),TextAlign=ContentAlignment.MiddleCenter,BackColor=Color.White};grid.Controls.Add(empty);grid.Resize+=delegate{empty.Location=new Point(Math.Max(0,(grid.Width-empty.Width)/2),Math.Max(70,(grid.Height-empty.Height)/2));};
            details=new Label{Visible=false,Dock=DockStyle.Bottom,Height=97,Padding=new Padding(22,15,18,8),BackColor=Color.FromArgb(248,250,253),ForeColor=muted,Text="Select a download to inspect its destination, resume capability and transfer pieces."};
            clipboardPanel=new Panel{Dock=DockStyle.Top,Height=43,Visible=false,BackColor=Color.FromArgb(232,241,255)};clipboardOffer=new Label{Dock=DockStyle.Fill,Padding=new Padding(18,10,0,0),AutoEllipsis=true};var clipAdd=Button("Add copied URL",()=>{clipboardPanel.Visible=false;Add(offeredUrl);},false);clipAdd.Dock=DockStyle.Right;var clipHide=Button("Dismiss",()=>clipboardPanel.Visible=false,false);clipHide.Dock=DockStyle.Right;clipboardPanel.Controls.Add(clipboardOffer);clipboardPanel.Controls.Add(clipAdd);clipboardPanel.Controls.Add(clipHide);
            content.Panel2.BackColor=Color.White;content.Panel2.Controls.Add(grid);content.Panel2.Controls.Add(details);content.Panel2.Controls.Add(clipboardPanel);content.Panel2.Controls.Add(top);
            summary=new Label{Visible=false,Dock=DockStyle.Bottom,Height=24,BackColor=ink,ForeColor=Color.White,Padding=new Padding(20,8,10,0),Font=new Font("Segoe UI",9)};
            Controls.Add(content);Controls.Add(summary);Controls.Add(bar);Controls.Add(menu);var categoriesItem=new ToolStripMenuItem("Categories"){Checked=true,CheckOnClick=true};categoriesItem.CheckedChanged+=delegate{content.Panel1Collapsed=!categoriesItem.Checked;};view.DropDownItems.Add(categoriesItem);var detailsItem=new ToolStripMenuItem("Download details"){CheckOnClick=true};detailsItem.CheckedChanged+=delegate{details.Visible=detailsItem.Checked;};view.DropDownItems.Add(detailsItem);var searchItem=new ToolStripMenuItem("Find file");searchItem.Click+=delegate{top.Visible=!top.Visible;if(top.Visible)search.Focus();};view.DropDownItems.Add(searchItem);var statusItem=new ToolStripMenuItem("Status bar"){CheckOnClick=true};statusItem.CheckedChanged+=delegate{summary.Visible=statusItem.Checked;};view.DropDownItems.Add(statusItem);
            navigation.NodeMouseDoubleClick+=delegate(object sender,TreeNodeMouseClickEventArgs e){string tag=e.Node.Tag as string??"";if(tag=="grabber"||tag.StartsWith("project:")){var project=tag=="grabber"?null:manager.State.Projects.FirstOrDefault(p=>p.Id==tag.Substring(8));using(var d=new GrabDialog(manager,project))d.ShowDialog(this);BuildTree();}};navigation.AfterSelect+=delegate{filter=navigation.SelectedNode.Tag as string ?? "all";heading.Text=navigation.SelectedNode.Text.Trim();RefreshRows();};search.TextChanged+=delegate{RefreshRows();};grid.SelectionChanged+=delegate{UpdateDetails();};grid.CellDoubleClick+=delegate{ShowSelectedProgress();};grid.CellPainting+=PaintProgress;grid.Paint+=PaintEmptyRows;
            var context=new ContextMenuStrip();context.Items.Add("Resume",null,delegate{ForSelected(manager.Resume);});context.Items.Add("Pause",null,delegate{ForSelected(manager.Pause);});context.Items.Add("Properties / refresh URL…",null,delegate{Properties();});context.Items.Add("Open file",null,delegate{OpenFile();});context.Items.Add("Show in folder",null,delegate{ShowFolder();});context.Items.Add("Copy URL",null,delegate{var j=Selected().FirstOrDefault();if(j!=null)Clipboard.SetText(j.Url);});context.Items.Add("Move up in queue",null,delegate{MoveInQueue(-1);});context.Items.Add("Move down in queue",null,delegate{MoveInQueue(1);});context.Items.Add("Remove record",null,delegate{RemoveSelected();});grid.ContextMenuStrip=context;
            AllowDrop=true;DragEnter+=delegate(object sender,DragEventArgs e){if(e.Data.GetDataPresent(DataFormats.Text))e.Effect=DragDropEffects.Copy;};DragDrop+=delegate(object sender,DragEventArgs e){Add(e.Data.GetData(DataFormats.Text) as string);};
            KeyPreview=true;KeyDown+=delegate(object sender,KeyEventArgs e){if(e.Control&&e.KeyCode==Keys.N){Add("");e.SuppressKeyPress=true;}if(e.KeyCode==Keys.Delete&&grid.Focused){RemoveSelected();e.SuppressKeyPress=true;}if(e.Control&&e.KeyCode==Keys.F){top.Visible=true;search.Focus();e.SuppressKeyPress=true;}};
            tray=new NotifyIcon{Text="UDM Download Manager",Icon=Icon,Visible=true};tray.DoubleClick+=delegate{Reveal();};var trayMenu=new ContextMenuStrip();trayMenu.Items.Add("Open UDM",null,delegate{Reveal();});trayMenu.Items.Add("Add URL",null,delegate{Reveal();Add("");});trayMenu.Items.Add("Exit",null,delegate{quitting=true;Close();});tray.ContextMenuStrip=trayMenu;
            manager.Started+=j=>Post(()=>ShowProgress(j,false));
            manager.Completed+=j=>Post(()=>{DownloadProgressDialog current;if(progressWindows.TryGetValue(j.Id,out current))current.CloseForCompletion();tray.ShowBalloonTip(3000,"Download complete",j.FileName,ToolTipIcon.Info);if(manager.State.Settings.Sound)SystemSounds.Asterisk.Play();if(!manager.State.Settings.SuppressCompletionDialog&&!j.SuppressCompletionDialog)new DownloadCompleteDialog(manager,j).Show(this);});
            pipe.DownloadReceived+=j=>Post(()=>{if(j.Status=="Awaiting confirmation"&&infoWindows.Add(j.Id)){var dialog=new DownloadInfoDialog(manager,j);dialog.FormClosed+=delegate{infoWindows.Remove(j.Id);};dialog.Show(this);dialog.Activate();}});
            pipe.ShowRequested+=()=>{if(IsHandleCreated&&!IsDisposed)BeginInvoke((Action)Reveal);};
            refresh=new Timer{Interval=1000};refresh.Tick+=delegate{DrainUiRequests();RefreshRows();CheckClipboard();};refresh.Start();BuildTree();RefreshRows();
            FormClosing+=async delegate(object sender,FormClosingEventArgs e){if(closed)return;if(!quitting&&manager.State.Settings.CloseToTray){e.Cancel=true;Hide();return;}e.Cancel=true;Enabled=false;refresh.Stop();summary.Text="Pausing downloads and saving progress…";try{pipe.Dispose();await manager.Stop();closed=true;tray.Visible=false;Close();}catch(Exception ex){Enabled=true;quitting=false;refresh.Start();MessageBox.Show(this,"Unable to save UDM state: "+ex.Message,"UDM");}};
            ApplyMenuIcons(menu.Items);foreach(ToolStripItem rootItem in menu.Items)rootItem.Image=null;ApplyMenuIcons(context.Items);ApplyMenuIcons(trayMenu.Items);
            ResumeLayout(true);Shown+=delegate{float dpi;using(var graphics=CreateGraphics())dpi=graphics.DpiX/96f;content.SplitterDistance=(int)Math.Round(136*dpi);navigation.ItemHeight=(int)Math.Round(16*dpi);grid.RowTemplate.Height=(int)Math.Round(17*dpi);foreach(DataGridViewRow row in grid.Rows)row.Height=grid.RowTemplate.Height;grid.ColumnHeadersHeight=(int)Math.Round(20*dpi);for(int i=0;i<weights.Length;i++)grid.Columns[i].Width=(int)Math.Round(weights[i]*dpi);AppTheme.Apply(this);grid.ClearSelection();if(background)Hide();};
        }
        public void Reveal(){Show();WindowState=FormWindowState.Normal;Activate();}
        void Post(Action action){lock(uiRequests)uiRequests.Enqueue(action);}
        void DrainUiRequests(){for(;;){Action action;lock(uiRequests){if(uiRequests.Count==0)return;action=uiRequests.Dequeue();}Guard(action);}}
        void ShowProgress(Download job,bool force){if(!force&&manager.State.Settings.SuppressProgressDialog)return;DownloadProgressDialog dialog;if(progressWindows.TryGetValue(job.Id,out dialog)){dialog.Show();dialog.Activate();return;}dialog=new DownloadProgressDialog(manager,job);progressWindows[job.Id]=dialog;dialog.FormClosed+=delegate{progressWindows.Remove(job.Id);};dialog.Show(this);}
        void ShowSelectedProgress(){var job=Selected().FirstOrDefault();if(job==null)return;if(job.Status=="Complete")new DownloadCompleteDialog(manager,job).Show(this);else ShowProgress(job,true);}
        Button Button(string text,Action action,bool primary,string icon=null){var b=new ClassicToolbarButton{Text=text,Width=icon==null?105:60,Height=icon==null?28:61,Padding=new Padding(0),Margin=new Padding(0),Font=new Font("Tahoma",8.25f),FlatStyle=FlatStyle.Flat,TextImageRelation=TextImageRelation.ImageAboveText,ImageAlign=ContentAlignment.TopCenter,TextAlign=ContentAlignment.BottomCenter,AutoEllipsis=true};if(icon!=null)b.Image=Icons.Get(icon,28);b.FlatAppearance.BorderSize=0;b.Click+=delegate{Guard(action);};return b;}
        static void ApplyMenuIcons(ToolStripItemCollection items){foreach(ToolStripItem item in items){string s=item.Text.ToLowerInvariant(),key=s.Contains("add")?"add":s.Contains("resume")?"resume":s.Contains("pause")?"pause":s.Contains("remove")?"remove":s.Contains("schedul")?"schedule":s.Contains("queue")?"queue":s.Contains("grabber")?"grabber":s.Contains("setting")||s.Contains("properties")?"settings":s.Contains("browser")?"browser":s.Contains("folder")?"folder":s.Contains("import")?"import":s.Contains("export")?"export":s.Contains("url")?"link":"info";item.Image=Icons.Get(key,20);var menu=item as ToolStripMenuItem;if(menu!=null&&menu.HasDropDownItems)ApplyMenuIcons(menu.DropDownItems);}}
        static void ApplyTreeIcons(TreeNodeCollection nodes){foreach(TreeNode node in nodes){string tag=node.Tag as string??"",name=node.Text.ToLowerInvariant(),key=tag.StartsWith("category:")?name:tag.StartsWith("queue:")?"queue":name=="downloading"?"resume":name=="queued"?"queue":name=="paused"?"pause":name=="complete"?"complete":name=="failed"?"failed":name=="all downloads"?"all":"folder";node.ImageKey=key;node.SelectedImageKey=key;ApplyTreeIcons(node.Nodes);}}
        void Guard(Action action){try{action();RefreshRows();}catch(Exception ex){MessageBox.Show(this,ex.Message,"UDM",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
        void Add(string url){using(var d=new AddressDialog(manager,url))d.ShowDialog(this);BuildTree();RefreshRows();}
        void Settings(){using(var d=new SettingsDialog(manager))d.ShowDialog(this);}
        void BuildTree(){navigation.BeginUpdate();navigation.Nodes.Clear();var all=new TreeNode("All Downloads"){Tag="all"};foreach(string c in manager.Categories.Where(c=>c!="Images"&&c!="Other"))all.Nodes.Add(new TreeNode(ClassicLayout.CategoryLabel(c)){Tag="category:"+c});navigation.Nodes.Add(all);foreach(string status in new[]{"Unfinished","Finished"}){var parent=new TreeNode(status){Tag=status=="Finished"?"status:Complete":"unfinished"};foreach(string c in manager.Categories.Where(c=>c!="Images"&&c!="Other"))parent.Nodes.Add(new TreeNode(ClassicLayout.CategoryLabel(c)){Tag=(status=="Finished"?"finished:":"unfinished:")+c});navigation.Nodes.Add(parent);}var projects=new TreeNode("Grabber projects"){Tag="grabber"};foreach(var project in manager.State.Projects)projects.Nodes.Add(new TreeNode(project.Name){Tag="project:"+project.Id});navigation.Nodes.Add(projects);var qs=new TreeNode("Queues"){Tag="all"};foreach(var q in manager.State.Queues)qs.Nodes.Add(new TreeNode(q.Name){Tag="queue:"+q.Name});navigation.Nodes.Add(qs);all.Expand();ApplyTreeIcons(navigation.Nodes);navigation.EndUpdate();}
        IEnumerable<Download> Selected(){return grid.SelectedRows.Cast<DataGridViewRow>().Select(r=>r.Tag as Download).Where(d=>d!=null).ToArray();}
        void ForSelected(Action<Download> action){Guard(()=>{foreach(var j in Selected())action(j);});}
        void RemoveSelected(){var list=Selected().ToList();if(list.Count==0)return;if(MessageBox.Show(this,"Remove "+list.Count+" download record(s) and their partial data? Completed files will stay on disk.","Remove records",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;Guard(()=>{foreach(var j in list)manager.Remove(j);});}
        void RemoveCompleted(){if(MessageBox.Show(this,"Remove completed download records? Files will stay on disk.","Remove completed",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;Guard(()=>{foreach(var j in manager.State.Downloads.Where(d=>d.Status=="Complete").ToArray())manager.Remove(j);});}
        void Properties(){var j=Selected().FirstOrDefault();if(j!=null)using(var d=new PropertiesDialog(manager,j))d.ShowDialog(this);}
        void EditQueue(){string name=filter.StartsWith("queue:")?filter.Substring(6):"Main queue";var q=manager.State.Queues.FirstOrDefault(x=>x.Name==name)??manager.State.Queues[0];using(var d=new SchedulerDialog(manager,q))d.ShowDialog(this);BuildTree();}
        void SetQueueRunning(bool enabled){string name=filter.StartsWith("queue:")?filter.Substring(6):"Main queue";var q=manager.State.Queues.FirstOrDefault(x=>x.Name==name)??manager.State.Queues[0];manager.RunQueue(q,enabled);}
        void MoveInQueue(int direction){var j=Selected().FirstOrDefault();if(j!=null)manager.MoveWithinQueue(j,direction);}
        void OpenFile(){Guard(()=>{var j=Selected().FirstOrDefault();if(j==null||j.Status!="Complete")return;if(File.Exists(j.Target))Process.Start(new ProcessStartInfo(j.Target){UseShellExecute=true});});}
        void ShowFolder(){Guard(()=>{var j=Selected().FirstOrDefault();if(j==null)return;if(File.Exists(j.Target))Process.Start("explorer.exe","/select,\""+j.Target+"\"");else if(Directory.Exists(j.Folder))Process.Start("explorer.exe","\""+j.Folder+"\"");});}
        void Import(){using(var d=new OpenFileDialog{Filter="URL lists|*.txt;*.lst|All files|*.*"})if(d.ShowDialog(this)==DialogResult.OK)Guard(()=>{var file=new FileInfo(d.FileName);if(file.Length>1024*1024)throw new IOException("Import lists up to 1 MB.");Add(File.ReadAllText(d.FileName));});}
        void Export(){using(var d=new SaveFileDialog{Filter="URL list|*.txt",FileName="udm-downloads.txt"})if(d.ShowDialog(this)==DialogResult.OK)Guard(()=>{var selected=Selected().ToArray();File.WriteAllLines(d.FileName,(selected.Length>0?selected:manager.State.Downloads.ToArray()).Select(j=>j.Url));});}
        void IntegrationHelp(){MessageBox.Show(this,"Browser integration is included as source in browser/chromium and browser/firefox.\n\n1. Load the unpacked extension in your browser.\n2. Run browser/register-host.ps1 with its extension ID.\n3. Use the extension menu to send links or media to UDM.\n\nAutomatic handoff is opt-in. See browser/README.md for setup and limits.\n\nHelp > Network integration shows browser connections. The optional WFP monitor has been compiled but still requires signing and isolated kernel testing.","Browser integration");}
        void CheckClipboard(){if(!manager.State.Settings.ClipboardMonitor)return;try{if(!Clipboard.ContainsText())return;string value=Clipboard.GetText().Trim();if(value==lastClipboard)return;lastClipboard=value;Uri uri;if(value.Length<8192&&Uri.TryCreate(value,UriKind.Absolute,out uri)&&(uri.Scheme=="http"||uri.Scheme=="https"||uri.Scheme=="ftp")){offeredUrl=value;clipboardOffer.Text="Copied URL: "+uri.Host+uri.AbsolutePath;clipboardPanel.Visible=true;}}catch(System.Runtime.InteropServices.ExternalException){}}
        void RefreshRows(){if(IsDisposed)return;lock(manager.Sync){var visible=manager.State.Downloads.Where(j=>(filter=="all"||(filter=="grabber"&&!string.IsNullOrEmpty(j.ProjectId))||(filter.StartsWith("project:")&&j.ProjectId==filter.Substring(8))||(filter=="unfinished"&&j.Status!="Complete")||(filter.StartsWith("finished:")&&j.Status=="Complete"&&j.Category==filter.Substring(9))||(filter.StartsWith("unfinished:")&&j.Status!="Complete"&&j.Category==filter.Substring(11))||(filter.StartsWith("status:")&&j.Status==filter.Substring(7))||(filter.StartsWith("category:")&&j.Category==filter.Substring(9))||(filter.StartsWith("queue:")&&j.Queue==filter.Substring(6)))&&(search.Text.Length==0||j.FileName.IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0||j.Url.IndexOf(search.Text,StringComparison.OrdinalIgnoreCase)>=0)).ToArray();var keep=new HashSet<string>(visible.Select(j=>j.Id));for(int i=grid.Rows.Count-1;i>=0;i--)if(!keep.Contains(((Download)grid.Rows[i].Tag).Id))grid.Rows.RemoveAt(i);var map=grid.Rows.Cast<DataGridViewRow>().ToDictionary(r=>((Download)r.Tag).Id);
            foreach(var j in visible){DataGridViewRow row;if(!map.TryGetValue(j.Id,out row)){int i=grid.Rows.Add();row=grid.Rows[i];row.Tag=j;}string eta=j.Speed>0&&j.Size>0?TimeSpan.FromSeconds(Math.Min(31536000,(j.Size-j.Received)/j.Speed)).ToString(@"hh\:mm\:ss"):"—";object[] values={j.FileName,j.Queue=="Main queue"?"":j.Queue,Names.Bytes(j.Size),j.Status=="Downloading"?j.Percent.ToString("0.0")+"%":j.Status,eta,j.Speed>0?Names.Bytes(j.Speed)+"/s":"—",j.LastAttempt.HasValue?j.LastAttempt.Value.ToLocalTime().ToString("MMM d HH:mm"):"—",j.Description??""};for(int i=0;i<values.Length;i++)if(!Equals(row.Cells[i].Value,values[i]))row.Cells[i].Value=values[i];row.Cells[3].Style.ForeColor=j.Status=="Complete"?Color.LightGreen:j.Status=="Failed"?Color.IndianRed:ink;}
            empty.Visible=false;empty.Text=manager.State.Downloads.Count==0?"Ready when you are.\n\nAdd a URL, paste a batch, or drop a link here.":"No downloads match this view.";
            int active=manager.State.Downloads.Count(j=>manager.IsActive(j));summary.Text=manager.StorageError.Length>0?"Storage error: "+manager.StorageError:string.Format("{0} downloads     •     {1} active     •     {2}/s     •     Limit: {3}     •     Hour: {4}",manager.State.Downloads.Count,active,Names.Bytes(manager.State.Downloads.Sum(j=>j.Speed)),manager.State.Settings.LimitKbps==0?"Unlimited":manager.State.Settings.LimitKbps+" KB/s",Names.Bytes(manager.State.QuotaBytes));UpdateDetails();}}
        void UpdateDetails(){var chosen=Selected().ToArray();if(toolbar!=null){toolbar.Controls[1].Enabled=chosen.Any(d=>!manager.IsActive(d)&&d.Status!="Complete");toolbar.Controls[2].Enabled=chosen.Any(d=>manager.IsActive(d)||d.Status=="Queued");toolbar.Controls[3].Enabled=manager.State.Downloads.Any(d=>manager.IsActive(d)||d.Status=="Queued");toolbar.Controls[4].Enabled=chosen.Length>0;}var j=chosen.FirstOrDefault();if(j==null){details.Text="Select a download to inspect its destination, resume capability and transfer pieces.";return;}lock(manager.Sync){int pieces=j.Video==null?j.Segments.Count:j.Video.Segments.Count+(j.Audio==null?0:j.Audio.Segments.Count);details.Text=j.Target+"\n"+Names.Bytes(j.Received)+" received  •  "+pieces+" pieces  •  "+(j.RangeSupported?"Resume supported":"Resume requires a fresh transfer")+"  •  "+(j.FormatDescription??j.Category)+(j.Error.Length>0?"\n"+j.Error:j.TimingSummary.Length>0?"\n"+j.TimingSummary:j.Sha256.Length>0?"\nSHA-256: "+j.Sha256:"");}}
        void PaintProgress(object sender,DataGridViewCellPaintingEventArgs e){if(e.RowIndex<0||e.ColumnIndex!=0)return;var j=grid.Rows[e.RowIndex].Tag as Download;if(j==null)return;e.PaintBackground(e.CellBounds,true);e.Graphics.DrawImage(Icons.Get(j.Category.ToLowerInvariant(),18),e.CellBounds.X+4,e.CellBounds.Y+(e.CellBounds.Height-18)/2,18,18);TextRenderer.DrawText(e.Graphics,j.FileName,grid.Font,new Rectangle(e.CellBounds.X+28,e.CellBounds.Y,e.CellBounds.Width-31,e.CellBounds.Height),ink,TextFormatFlags.EndEllipsis|TextFormatFlags.VerticalCenter);e.Handled=true;}
        void PaintEmptyRows(object sender,PaintEventArgs e){int top=grid.ColumnHeadersHeight;int first=grid.FirstDisplayedScrollingRowIndex;if(first>=0){int last=Math.Min(grid.Rows.Count-1,first+grid.DisplayedRowCount(true)-1);if(last>=first)top=Math.Max(top,grid.GetRowDisplayRectangle(last,false).Bottom);}int bottom=grid.ClientSize.Height;foreach(Control c in grid.Controls)if(c is HScrollBar&&c.Visible)bottom=Math.Min(bottom,c.Top);using(var pen=new Pen(grid.GridColor)){for(int y=top;y<bottom;y+=grid.RowTemplate.Height)e.Graphics.DrawLine(pen,0,y,grid.ClientSize.Width,y);foreach(DataGridViewColumn c in grid.Columns)if(c.Visible){var r=grid.GetCellDisplayRectangle(c.Index,-1,true);if(r.Width>0)e.Graphics.DrawLine(pen,r.Right-1,top,r.Right-1,bottom);}}}
        static Icon MakeIcon(){using(var bitmap=new Bitmap(32,32))using(var g=Graphics.FromImage(bitmap)){g.SmoothingMode=SmoothingMode.AntiAlias;g.Clear(Color.FromArgb(39,96,222));using(var pen=new Pen(Color.White,3)){g.DrawLine(pen,16,6,16,21);g.DrawLine(pen,16,21,9,14);g.DrawLine(pen,16,21,23,14);g.DrawLine(pen,7,26,25,26);}return Icon.FromHandle(bitmap.GetHicon());}}
        protected override void Dispose(bool disposing){if(disposing){if(refresh!=null)refresh.Dispose();if(tray!=null)tray.Dispose();}base.Dispose(disposing);}
    }
}
