using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Udm {
    [DataContract] public sealed class SabrFormat {
        [DataMember] public string id;
        [DataMember] public string lastModified;
        [DataMember] public string xtags;
        [DataMember] public string mime;
        internal byte[] Encode(){ulong itag,lmt;if(!ulong.TryParse(id,out itag)||itag==0||itag>999999||!ulong.TryParse(lastModified,out lmt)||lmt==0)throw new ArgumentException("The browser did not capture a complete stream identity.");var p=new Proto().Set(1,itag).Set(2,lmt);if(!string.IsNullOrEmpty(xtags)){if(xtags.Length>2048)throw new ArgumentException("Invalid stream tags.");p.Set(3,xtags);}return p.Encode();}
    }
    [DataContract] public sealed class SabrOffer {
        [DataMember] public string url;
        [DataMember] public string body;
        [DataMember] public string videoId;
        [DataMember] public double capturedAt;
        [DataMember] public long durationMs;
        [DataMember] public SabrFormat video;
        [DataMember] public SabrFormat audio;
        internal void Validate(string source){MediaTransfer.ValidateSource(source);MediaTransfer.ValidateStream(url);var page=new Uri(source);string id=page.Host=="youtu.be"?page.AbsolutePath.Trim('/'):System.Web.HttpUtility.ParseQueryString(page.Query)["v"];if(id!=videoId||!System.Text.RegularExpressions.Regex.IsMatch(videoId??"",@"^[\w-]{11}$"))throw new ArgumentException("The captured stream belongs to a different video.");if(durationMs<=0||durationMs>86400000)throw new ArgumentException("Only recorded videos up to 24 hours are supported.");double now=(DateTime.UtcNow-new DateTime(1970,1,1,0,0,0,DateTimeKind.Utc)).TotalMilliseconds;if(double.IsNaN(capturedAt)||double.IsInfinity(capturedAt)||capturedAt<now-300000||capturedAt>now+30000)throw new ArgumentException("The browser streaming session expired. Refresh the video and capture it again.");if(body==null||body.Length>175000)throw new ArgumentException("Streaming request is too large.");byte[] bytes=Convert.FromBase64String(body);if(bytes.Length==0||bytes.Length>131072)throw new ArgumentException("Invalid streaming request.");var request=Proto.Parse(bytes);if(request.Bytes(5)==null||request.Bytes(19)==null)throw new ArgumentException("Incomplete browser streaming session.");if(video==null||audio==null||!(video.mime??"").StartsWith("video/mp4")||!(audio.mime??"").StartsWith("audio/mp4"))throw new ArgumentException("Choose MP4 video and audio formats.");video.Encode();audio.Encode();}
    }
    public sealed partial class Manager {
        public Download AddSabr(string source,string name,int height,int pixelHeight,SabrOffer offer,Dictionary<string,string> headers){
            if(offer==null)throw new ArgumentException("Browser streaming capture is missing.");offer.Validate(source);if(height<144||height>4320||pixelHeight<1||pixelHeight>4320)throw new ArgumentException("Invalid stream dimensions.");MediaTransfer.RequireTool("ffmpeg.exe");
            lock(Sync){var job=Add(source,null,Names.MediaTitle(name),"Main queue",true,headers,"",null);try{job.SourceUrl=source;job.MediaHeight=height;job.MediaPixelHeight=pixelHeight;job.MediaFormatId=offer.video.id;job.ExactMediaQuality=true;job.ProtectedSabr=Secrets.Protect(Json.Write(offer));MediaTransfer.SetStreams(this,job,offer.url,offer.url,"Browser streaming capture · "+height+"p");job.Status="Queued";Save();return job;}catch{State.Downloads.Remove(job);Save();throw;}}
        }
    }
    internal sealed class SabrTransfer {
        sealed class Track {
            public readonly SabrFormat Format;public byte[] Identity;public readonly Download Child;public bool Initialized,HasInit;public long EndTime,ExpectedEnd,EndSequence=-1;public int LastSequence=-1,FirstSequence=-1;public readonly SortedDictionary<int,string> Files=new SortedDictionary<int,string>();public string InitFile;
            public Track(SabrFormat format,Download child,long duration){Format=format;Identity=format.Encode();Child=child;ExpectedEnd=duration;}
            public bool Complete {get{return HasInit&&EndTime>=ExpectedEnd-100&&(EndSequence<0||LastSequence>=EndSequence);}}
            public byte[] Buffered(){return new Proto().Set(1,Identity).Set(2,0UL).Set(3,(ulong)Math.Max(0,EndTime)).Set(4,(ulong)Math.Max(0,FirstSequence)).Set(5,(ulong)Math.Max(0,LastSequence)).Set(6,new Proto().Set(1,0UL).Set(2,(ulong)Math.Max(0,EndTime)).Set(3,1000UL).Encode()).Encode();}
        }
        sealed class Pending : IDisposable {public Track Track;public FileStream File;public string Path;public bool Init,Skip;public int Sequence;public long Start,Duration,Expected,Received;public void Dispose(){if(File!=null)File.Dispose();}}
        readonly Manager owner;readonly Download job;readonly SabrOffer offer;readonly Track[] tracks;readonly Proto original;readonly Dictionary<ulong,byte[]> contexts=new Dictionary<ulong,byte[]>();readonly HashSet<ulong> activeContexts=new HashSet<ulong>();readonly Dictionary<int,Pending> pending=new Dictionary<int,Pending>();readonly RateGate rate=new RateGate();byte[] cookie;string endpoint;int requestNumber,backoff;
        public SabrTransfer(Manager manager,Download download,SabrOffer captured){owner=manager;job=download;offer=captured;offer.Validate(job.SourceUrl);original=Proto.Parse(Convert.FromBase64String(offer.body));endpoint=offer.url;tracks=new[]{new Track(offer.video,job.Video,offer.durationMs),new Track(offer.audio,job.Audio,offer.durationMs)};var context=Proto.Parse(original.Bytes(19));cookie=context.Bytes(3);foreach(var field in context.Fields.Where(f=>f.Id==5&&f.Wire==2)){var value=Proto.Parse(field.Bytes);ulong id=value.Number(1);if(value.Bytes(2)!=null){contexts[id]=value.Bytes(2);activeContexts.Add(id);}}}
        internal static bool SameFormat(byte[] expected,byte[] actual){var a=Proto.Parse(expected);var b=Proto.Parse(actual);return a.Number(1)==b.Number(1)&&a.Number(2)==b.Number(2)&&a.Text(3)==b.Text(3);}
        byte[] Request(){var request=Proto.Parse(original.Encode());request.Remove(2,3,16,17,18);foreach(var track in tracks){request.Add(track==tracks[0]?17:16,track.Identity);if(track.Initialized)request.Add(2,track.Identity);if(track.EndTime>0)request.Add(3,track.Buffered());}long time=tracks.Min(t=>t.EndTime);request.Set(4,(ulong)time);var state=Proto.Parse(request.Bytes(1)).Set(16,(ulong)job.MediaHeight).Set(21,1UL).Set(22,0UL).Set(26,3UL).Set(28,(ulong)time).Set(40,3UL).Float(35,1);request.Set(1,state.Encode());var context=Proto.Parse(request.Bytes(19));context.Remove(5,6);if(cookie!=null)context.Set(3,cookie);foreach(var pair in contexts){if(activeContexts.Contains(pair.Key))context.Add(5,new Proto().Set(1,pair.Key).Set(2,pair.Value).Encode());else context.Fields.Add(new ProtoField{Id=6,Wire=0,Number=pair.Key});}request.Set(19,context.Encode());return request.Encode();}
        Track Find(byte[] identity){return tracks.FirstOrDefault(t=>SameFormat(t.Identity,identity));}
        void Identity(string video){if(video.Length>0&&video!=offer.videoId)throw new IOException("Streaming response belongs to another video. No output was published.");}
        long Timing(Proto header,int field,int rangeField){if(header.Has(field))return checked((long)header.Number(field));var range=Proto.Parse(header.Bytes(15));ulong scale=range.Number(3);return scale>0?checked((long)(1000*range.Number(rangeField)/scale)):0;}
        void Metadata(Proto data){Identity(data.Text(1));var identity=data.Bytes(2);if(identity==null)return;var track=Find(identity);if(track==null)return;string mime=data.Text(5);if(!mime.StartsWith(track==tracks[0]?"video/mp4":"audio/mp4",StringComparison.OrdinalIgnoreCase))throw new IOException("Streaming format changed unexpectedly.");track.Initialized=true;if(data.Number(3)>0)track.ExpectedEnd=checked((long)data.Number(3));else if(data.Number(10)>0&&data.Number(9)>0)track.ExpectedEnd=checked((long)(1000*data.Number(9)/data.Number(10)));if(track.ExpectedEnd<=0||Math.Abs(track.ExpectedEnd-offer.durationMs)>5000)throw new IOException("Streaming duration does not match the selected video.");if(data.Has(4))track.EndSequence=checked((long)data.Number(4));}
        void Header(Proto header){Identity(header.Text(2));byte[] identity=header.Bytes(13)??new Proto().Set(1,header.Number(3)).Set(2,header.Number(4)).Set(3,header.Text(5)).Encode();var track=Find(identity);int id=checked((int)header.Number(1));if(id<0||id>255)throw new IOException("Invalid media header identifier.");if(pending.ContainsKey(id))throw new IOException("Streaming response contains overlapping segment identifiers.");if(header.Number(7)!=0)throw new IOException("Compressed streaming segments are not supported.");if(track==null){pending[id]=new Pending{Skip=true};return;}if(!track.Initialized)throw new IOException("Media arrived before format initialization.");bool init=header.Number(8)!=0;int sequence=checked((int)header.Number(9));long length=checked((long)header.Number(14));if(sequence<0||length<=0||length>64*1024*1024)throw new IOException("Invalid media segment metadata.");var p=new Pending{Track=track,Init=init,Sequence=sequence,Start=Timing(header,11,1),Duration=Timing(header,12,2),Expected=length,Skip=init?track.HasInit:track.Files.ContainsKey(sequence)};if(!p.Skip){p.Path=Path.Combine(track.Child.Folder,(track==tracks[0]?"video":"audio")+"-"+(init?"init":sequence.ToString("D8"))+".sabrpart");p.File=new FileStream(p.Path,FileMode.Create,FileAccess.Write,FileShare.Read);}pending[id]=p;}
        void End(byte[] bytes){if(bytes.Length!=1)throw new IOException("Invalid media segment terminator.");Pending p;if(!pending.TryGetValue(bytes[0],out p))throw new IOException("Media ended without a matching header.");pending.Remove(bytes[0]);using(p){if(p.Skip)return;if(p.Received!=p.Expected)throw new IOException("Streaming segment is incomplete.");p.File.Flush(true);p.File.Dispose();p.File=null;var t=p.Track;if(p.Init){t.HasInit=true;t.InitFile=p.Path;}else{if(p.Duration<=0||p.Start<0||p.Start>t.EndTime+250||p.Start<t.EndTime-250||(t.LastSequence>=0&&p.Sequence!=t.LastSequence+1))throw new IOException("Streaming response has a gap or out-of-order segment.");if(t.FirstSequence<0)t.FirstSequence=p.Sequence;t.LastSequence=p.Sequence;t.EndTime=p.Start+p.Duration;t.Files[p.Sequence]=p.Path;}t.Child.Received+=p.Received;}}
        async Task Part(UmpPart part,CancellationToken ct){if(part.Type==12)throw new IOException("Encrypted media is not supported.");if(part.Type==21){if(part.Data.Length<2)throw new IOException("Empty streaming media.");Pending p;if(!pending.TryGetValue(part.Data[0],out p))throw new IOException("Media arrived without a matching header.");if(!p.Skip){int length=part.Data.Length-1;if(p.Received+length>p.Expected)throw new IOException("Media exceeds its declared segment length.");
                // A framed response may exceed the entire hourly quota. Charge small chunks
                // so it can make progress across quota windows and remain cancellable.
                for(int offset=1;offset<part.Data.Length;){int chunk=Math.Min(65536,part.Data.Length-offset);ct.ThrowIfCancellationRequested();await owner.WaitForQuota(chunk,ct).ConfigureAwait(false);await owner.GlobalRate.Wait(chunk,owner.State.Settings.LimitKbps,ct).ConfigureAwait(false);await rate.Wait(chunk,job.EffectiveLimitKbps,ct).ConfigureAwait(false);await p.File.WriteAsync(part.Data,offset,chunk,ct).ConfigureAwait(false);offset+=chunk;p.Received+=chunk;lock(owner.Sync){p.Track.Child.TransferredBytes+=chunk;job.TransferredBytes=tracks.Sum(t=>t.Child.TransferredBytes);job.Received=tracks.Sum(t=>t.Child.Received)+pending.Values.Where(v=>!v.Skip).Sum(v=>v.Received);}}
            }return;}
            if(part.Type==22){End(part.Data);return;}if(!new uint[]{20,35,42,43,44,46,57,58,59}.Contains(part.Type))return;var data=Proto.Parse(part.Data);
            switch(part.Type){case 20:Header(data);break;case 42:Metadata(data);break;case 35:Identity(data.Text(8));cookie=data.Bytes(7)??cookie;backoff=checked((int)Math.Min(60000UL,data.Number(4)));break;case 43:string url=data.Text(1);MediaTransfer.ValidateStream(url);endpoint=url;break;case 44:throw new IOException("The streaming server returned an error (code "+data.Number(2)+"). Refresh the video in the browser.");case 46:throw new IOException("The streaming server requested a fresh browser session.");case 58:if(data.Number(1)==3)throw new IOException("The streaming server requires browser attestation. Refresh playback in the browser.");break;
                case 57:ulong id=data.Number(1);if(data.Bytes(3)!=null&&!(data.Number(5)==2&&contexts.ContainsKey(id))){if(contexts.Count>=100&&!contexts.ContainsKey(id))throw new IOException("Too many streaming context updates.");contexts[id]=data.Bytes(3);if(data.Number(4)!=0)activeContexts.Add(id);}break;
                case 59:foreach(ulong idStart in data.Numbers(1))activeContexts.Add(idStart);foreach(ulong idStop in data.Numbers(2))activeContexts.Remove(idStop);foreach(ulong idDelete in data.Numbers(3)){contexts.Remove(idDelete);activeContexts.Remove(idDelete);}break;
            }
        }
        public async Task Run(CancellationToken ct,HttpMessageHandler transport=null){foreach(var track in tracks){Directory.CreateDirectory(track.Child.Folder);track.Child.Received=0;track.Child.Status="Downloading";}job.Size=-1;job.RangeSupported=false;int stalled=0;
            try{using(var handler=transport??new HttpClientHandler{AllowAutoRedirect=false,UseCookies=false})using(var client=new HttpClient(handler){Timeout=Timeout.InfiniteTimeSpan}){
                if(transport==null&&!string.IsNullOrWhiteSpace(owner.State.Settings.Proxy)){var proxy=new System.Net.WebProxy(owner.State.Settings.Proxy);if(!string.IsNullOrEmpty(owner.State.Settings.ProxyUser))proxy.Credentials=new System.Net.NetworkCredential(owner.State.Settings.ProxyUser,Secrets.Reveal(owner.State.Settings.ProxySecret));((HttpClientHandler)handler).Proxy=proxy;}
                while(!tracks.All(t=>t.Complete)){ct.ThrowIfCancellationRequested();if(requestNumber>20000)throw new IOException("Streaming request limit reached.");long before=tracks.Sum(t=>t.EndTime);var url=new UriBuilder(endpoint);var query=System.Web.HttpUtility.ParseQueryString(url.Query);query["rn"]=(requestNumber++).ToString();url.Query=query.ToString();byte[] body=Request();if(body.Length>262144)throw new IOException("Streaming context is too large.");using(var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct)){timeout.CancelAfter(60000);using(var request=new HttpRequestMessage(HttpMethod.Post,url.Uri)){request.Content=new ByteArrayContent(body);request.Content.Headers.ContentType=new System.Net.Http.Headers.MediaTypeHeaderValue("application/x-protobuf");request.Headers.TryAddWithoutValidation("Accept","application/vnd.yt-ump");request.Headers.TryAddWithoutValidation("Accept-Encoding","identity");var headers=owner.ReadHeaders(job);foreach(var h in headers.Where(h=>h.Key=="User-Agent"||h.Key=="Referer"))request.Headers.TryAddWithoutValidation(h.Key,h.Value);
                    using(var response=await client.SendAsync(request,HttpCompletionOption.ResponseHeadersRead,timeout.Token).ConfigureAwait(false)){if(!response.IsSuccessStatusCode)throw new IOException("HTTP "+(int)response.StatusCode+": the server rejected the browser streaming session.");if(response.Content.Headers.ContentType==null||response.Content.Headers.ContentType.MediaType!="application/vnd.yt-ump")throw new IOException("The streaming server returned an unexpected content type.");using(var stream=await response.Content.ReadAsStreamAsync().ConfigureAwait(false)){UmpPart part;int parts=0;while((part=await Ump.Read(stream,timeout.Token).ConfigureAwait(false))!=null){if(++parts>100000)throw new IOException("Too many streaming response parts.");await Part(part,timeout.Token).ConfigureAwait(false);}}}
                }}if(pending.Count!=0)throw new IOException("Streaming response ended inside a media segment.");stalled=tracks.Sum(t=>t.EndTime)>before?0:stalled+1;if(stalled>=8)throw new IOException("The browser streaming session stopped supplying media. Refresh playback and try again.");if(backoff>0&&!tracks.All(t=>t.Complete))await Task.Delay(backoff,ct).ConfigureAwait(false);}
                foreach(var track in tracks){if(track.Files.Count==0||!track.HasInit)throw new IOException("Streaming response is missing required media.");using(var output=new FileStream(track.Child.Target,FileMode.Create,FileAccess.Write,FileShare.Read)){foreach(string file in new[]{track.InitFile}.Concat(track.Files.Values)){using(var input=File.OpenRead(file))await input.CopyToAsync(output,81920,ct).ConfigureAwait(false);}output.Flush(true);}track.Child.Size=new FileInfo(track.Child.Target).Length;track.Child.Received=track.Child.Size;track.Child.Status="Complete";}
            }}catch(OperationCanceledException ex){if(ct.IsCancellationRequested)throw;throw new IOException("The browser streaming request timed out. Refresh playback and retry.",ex);}finally{foreach(var p in pending.Values){p.Dispose();if(p.Path!=null)try{File.Delete(p.Path);}catch(IOException){}}pending.Clear();foreach(var track in tracks){foreach(string file in new[]{track.InitFile}.Concat(track.Files.Values).Where(f=>f!=null))try{File.Delete(file);}catch(IOException){}}}
        }
    }
}
