using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Windows.Forms;

namespace Udm {
    public sealed class NameDialog:Form {
        public string Value;
        public NameDialog(string title,string prompt,string initial){ClassicLayout.Form(this,title,225,74);MinimizeBox=false;ClassicLayout.Label(this,prompt,7,6,210,20);var text=ClassicLayout.Text(this,initial,7,29,210);AcceptButton=ClassicLayout.Button(this,"OK",105,53,50,()=>{Value=text.Text.Trim();if(Value.Length==0)throw new ArgumentException("Enter a name.");DialogResult=DialogResult.OK;Close();});CancelButton=ClassicLayout.Button(this,"Cancel",167,53,50,Close);Shown+=delegate{text.Focus();text.SelectAll();};AppTheme.Apply(this);}
    }
    public sealed class SchedulerDialog:Form {
        readonly Manager manager;readonly TreeView tree;readonly ListView files;readonly Label title;readonly CheckBox enabled,scheduled,stopEnabled;readonly RadioButton once,daily;readonly DateTimePicker start,stop,date;readonly CheckBox[] days;readonly NumericUpDown parallel,retries;readonly System.Windows.Forms.Timer timer;QueueRule selected;bool loading;
        public SchedulerDialog(Manager owner,QueueRule initial){manager=owner;ClassicLayout.Form(this,"Scheduler",434,286);MinimizeBox=false;
            ClassicLayout.Place(this,new PictureBox{Image=Icons.Get("schedule",28),SizeMode=PictureBoxSizeMode.Zoom},7,4,20,20);ClassicLayout.Label(this,"Queues",32,14,75);tree=ClassicLayout.Place(this,new TreeView{HideSelection=false,ShowLines=false},7,27,115,233);ClassicLayout.Place(this,new Label{BorderStyle=BorderStyle.Fixed3D},131,7,1,272);title=ClassicLayout.Label(this,"",142,3,285);title.TextAlign=ContentAlignment.TopCenter;
            var tabs=ClassicLayout.Place(this,new TabControl(),142,14,285,248);var schedule=new TabPage("Schedule");var list=new TabPage("Files in the queue");tabs.TabPages.AddRange(new[]{schedule,list});
            enabled=ClassicLayout.Check(schedule,"Enable queue",7,5,250,true);ClassicLayout.Line(schedule,7,24,266);scheduled=ClassicLayout.Check(schedule,"Start download at",7,40,97,false);start=Time(schedule,110,37);
            once=ClassicLayout.Place(schedule,new RadioButton{Text="Once at"},12,60,62,12);date=ClassicLayout.Place(schedule,new DateTimePicker{Format=DateTimePickerFormat.Short},80,58,125,15);daily=ClassicLayout.Place(schedule,new RadioButton{Text="Daily",Checked=true},12,80,45,12);
            days=new CheckBox[7];string[] labels={"Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"};for(int i=0;i<7;i++)days[i]=ClassicLayout.Check(schedule,labels[i],62+(i/3)*73,80+(i%3)*14,73,true);
            ClassicLayout.Line(schedule,7,122,266);stopEnabled=ClassicLayout.Check(schedule,"Stop download at",7,132,99,false);stop=Time(schedule,110,129);ClassicLayout.Label(schedule,"Retries per connection",7,158,190);retries=Number(schedule,manager.State.Settings.Retries,0,10,216,155,42);
            ClassicLayout.Label(schedule,"UDM must be running at the scheduled time. An overnight window belongs to its starting weekday.",7,181,260,33);
            ClassicLayout.Label(list,"Download",7,8,41);parallel=Number(list,2,1,16,53,5,30);ClassicLayout.Label(list,"files at the same time",88,8,140);files=ClassicLayout.Place(list,new ListView{View=View.Details,FullRowSelect=true,HideSelection=false,MultiSelect=false,GridLines=true},8,25,264,179);files.Columns.Add("File name",ClassicLayout.X(153));files.Columns.Add("Size",ClassicLayout.X(48));files.Columns.Add("Status",ClassicLayout.X(60));
            ClassicLayout.Button(list,"↑",8,210,20,()=>MoveSelected(-1));ClassicLayout.Button(list,"↓",32,210,20,()=>MoveSelected(1));var move=ClassicLayout.Button(list,"Move to...",57,210,65,()=>{});move.Click+=delegate{var job=SelectedFile();if(job==null)return;var menu=new ContextMenuStrip();foreach(var q in manager.State.Queues.Where(q=>q!=selected)){string name=q.Name;menu.Items.Add(name,null,delegate{try{manager.MoveToQueue(job,name);RefreshFiles();}catch(Exception ex){MessageBox.Show(this,ex.Message,"UDM");}});}menu.Closed+=delegate{menu.Dispose();};menu.Show(move,new Point(0,move.Height));};
            ClassicLayout.Button(this,"New queue",13,265,50,()=>{using(var d=new NameDialog("Enter queue name","Enter a name for the new queue.","New queue"))if(d.ShowDialog(this)==DialogResult.OK){var q=manager.CreateQueue(d.Value);BuildTree(q);}});
            ClassicLayout.Button(this,"Delete",67,265,50,()=>{if(selected==null)return;if(MessageBox.Show(this,"Delete this queue? Its files will remain and unfinished files will be paused in the main queue.","Delete queue",MessageBoxButtons.YesNo,MessageBoxIcon.Question)==DialogResult.Yes){manager.DeleteQueue(selected);BuildTree(manager.State.Queues[0]);}});
            ClassicLayout.Button(this,"Start now",143,265,50,()=>{Apply();manager.RunQueue(selected,true);LoadQueue(selected);});ClassicLayout.Button(this,"Stop",197,265,50,()=>{manager.RunQueue(selected,false);LoadQueue(selected);});ClassicLayout.Button(this,"Help",259,265,50,()=>MessageBox.Show(this,"Start now runs the selected queue immediately. Stop pauses its unfinished downloads. Use Apply to save dates, weekday windows, retry counts and concurrency.\n\nOne-time schedules disable themselves when their queued files finish. Move files with the arrows on the Files in the queue tab.","Scheduler"));ClassicLayout.Button(this,"Apply",322,265,50,Apply);CancelButton=ClassicLayout.Button(this,"Close",376,265,50,Close);
            tree.AfterSelect+=delegate{LoadQueue(tree.SelectedNode.Tag as QueueRule);};once.CheckedChanged+=delegate{EnableSchedule();};scheduled.CheckedChanged+=delegate{EnableSchedule();};stopEnabled.CheckedChanged+=delegate{EnableSchedule();};BuildTree(initial);timer=new System.Windows.Forms.Timer{Interval=1000};timer.Tick+=delegate{RefreshFiles();};timer.Start();FormClosed+=delegate{timer.Dispose();};AppTheme.Apply(this);
        }
        static NumericUpDown Number(Control parent,decimal value,int minimum,int maximum,int x,int y,int width){return ClassicLayout.Place(parent,new NumericUpDown{Minimum=minimum,Maximum=maximum,Value=Math.Max(minimum,Math.Min(maximum,value))},x,y,width,14);}
        static DateTimePicker Time(Control parent,int x,int y){return ClassicLayout.Place(parent,new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="HH:mm",ShowUpDown=true},x,y,65,15);}
        void BuildTree(QueueRule target){tree.Nodes.Clear();foreach(var q in manager.State.Queues){var n=new TreeNode(q.Name){Tag=q};tree.Nodes.Add(n);if(q==target)tree.SelectedNode=n;}if(tree.SelectedNode==null&&tree.Nodes.Count>0)tree.SelectedNode=tree.Nodes[0];}
        void LoadQueue(QueueRule q){if(q==null)return;loading=true;selected=q;title.Text=q.Name;enabled.Checked=q.Enabled;scheduled.Checked=q.Scheduled||q.RunOnce;once.Checked=q.RunOnce;daily.Checked=!q.RunOnce;date.Value=q.StartOnceUtc.HasValue?q.StartOnceUtc.Value.ToLocalTime().Date:DateTime.Today;start.Value=q.RunOnce&&q.StartOnceUtc.HasValue?q.StartOnceUtc.Value.ToLocalTime():DateTime.Today.AddMinutes(q.StartMinute);stop.Value=q.RunOnce&&q.StopOnceUtc.HasValue?q.StopOnceUtc.Value.ToLocalTime():DateTime.Today.AddMinutes(q.StopMinute==1440?0:q.StopMinute);stopEnabled.Checked=q.RunOnce?q.StopOnceUtc.HasValue:q.Scheduled&&q.StopMinute!=1440;parallel.Value=q.Parallel;retries.Value=q.Retries??manager.State.Settings.Retries;for(int i=0;i<7;i++)days[i].Checked=(q.Days&(1<<i))!=0;loading=false;EnableSchedule();RefreshFiles();}
        void EnableSchedule(){if(loading)return;start.Enabled=scheduled.Checked;once.Enabled=daily.Enabled=scheduled.Checked;date.Enabled=scheduled.Checked&&once.Checked;foreach(var day in days)day.Enabled=scheduled.Checked&&!once.Checked;stop.Enabled=stopEnabled.Checked;}
        void Apply(){if(selected==null)return;var q=Json.Read<QueueRule>(Json.Write(selected));q.Enabled=enabled.Checked;q.Parallel=(int)parallel.Value;q.Retries=(int)retries.Value;q.RunOnce=scheduled.Checked&&once.Checked;q.Scheduled=scheduled.Checked&&!once.Checked;q.StartMinute=start.Value.Hour*60+start.Value.Minute;q.StopMinute=stopEnabled.Checked?stop.Value.Hour*60+stop.Value.Minute:1440;q.Days=0;for(int i=0;i<7;i++)if(days[i].Checked)q.Days|=1<<i;if(q.RunOnce){var local=date.Value.Date.Add(start.Value.TimeOfDay);q.StartOnceUtc=local.ToUniversalTime();var end=date.Value.Date.Add(stop.Value.TimeOfDay);if(end<=local)end=end.AddDays(1);q.StopOnceUtc=stopEnabled.Checked?(DateTime?)end.ToUniversalTime():null;}manager.UpdateQueue(selected,q);}
        Download SelectedFile(){return files.SelectedItems.Count==0?null:files.SelectedItems[0].Tag as Download;}
        void MoveSelected(int direction){var job=SelectedFile();if(job==null)return;manager.MoveWithinQueue(job,direction);RefreshFiles();}
        void RefreshFiles(){if(selected==null||IsDisposed)return;string keep=SelectedFile()==null?null:SelectedFile().Id;lock(manager.Sync){files.BeginUpdate();files.Items.Clear();foreach(var job in manager.State.Downloads.Where(d=>d.Queue==selected.Name)){var row=new ListViewItem(job.FileName){Tag=job,Selected=job.Id==keep};row.SubItems.Add(Names.Bytes(job.Size));row.SubItems.Add(job.Status);files.Items.Add(row);}files.EndUpdate();}}
    }
    public sealed class PropertiesDialog:Form {
        public PropertiesDialog(Manager manager,Download job){ClassicLayout.Form(this,"File Properties",318,246);MinimizeBox=false;bool readOnly=job.Status=="Complete";var oldHeaders=manager.ReadHeaders(job);
            ClassicLayout.Place(this,new PictureBox{Image=Icons.Get(job.Category.ToLowerInvariant(),28),SizeMode=PictureBoxSizeMode.Zoom},7,7,20,20);ClassicLayout.Label(this,job.FileName,58,13,253);ClassicLayout.Line(this,7,31,304);
            foreach(var row in new[]{new[]{"Type:",job.FormatDescription??job.Category},new[]{"Status:",job.Status},new[]{"Size:",Names.Bytes(job.Size)}}){int index=row[0]=="Type:"?0:row[0]=="Status:"?1:2;ClassicLayout.Label(this,row[0],7,36+12*index,44);ClassicLayout.Label(this,row[1],58,36+12*index,253);}
            ClassicLayout.Label(this,"Save To:",7,77,45);var destination=ClassicLayout.Text(this,job.Target,58,74,197,readOnly);var browse=ClassicLayout.Button(this,"Browse...",261,74,50,()=>{using(var d=new SaveFileDialog{FileName=Path.GetFileName(destination.Text),InitialDirectory=Path.GetDirectoryName(destination.Text),OverwritePrompt=true})if(d.ShowDialog(this)==DialogResult.OK)destination.Text=d.FileName;});browse.Enabled=!readOnly;
            ClassicLayout.Label(this,"Address:",7,96,44);var address=ClassicLayout.Text(this,job.SourceUrl??job.Url,58,93,253,readOnly||job.SourceUrl!=null);ClassicLayout.Label(this,"Description:",7,115,48);var description=ClassicLayout.Text(this,job.Description??"",58,112,253);
            ClassicLayout.Line(this,7,131,304);ClassicLayout.Label(this,"The web page from which this file was obtained:",7,136,304);ClassicLayout.Label(this,job.SourceUrl??(oldHeaders.ContainsKey("Referer")?oldHeaders["Referer"]:"Unknown"),7,149,304);ClassicLayout.Line(this,7,161,304);
            ClassicLayout.Label(this,"Referer:",7,171,47);var referer=ClassicLayout.Text(this,oldHeaders.ContainsKey("Referer")?oldHeaders["Referer"]:"",58,167,253,readOnly);ClassicLayout.Label(this,"Login",23,188,50);var login=ClassicLayout.Text(this,"",80,185,126,readOnly);ClassicLayout.Label(this,"Password",21,205,52);var password=ClassicLayout.Text(this,"",80,203,126,readOnly);password.UseSystemPasswordChar=true;
            if(oldHeaders.ContainsKey("Authorization")&&oldHeaders["Authorization"].StartsWith("Basic ",StringComparison.OrdinalIgnoreCase))try{string decoded=Encoding.UTF8.GetString(Convert.FromBase64String(oldHeaders["Authorization"].Substring(6)));int colon=decoded.IndexOf(':');if(colon>=0){login.Text=decoded.Substring(0,colon);password.Text=decoded.Substring(colon+1);}}catch(FormatException){}
            string originalAuthority=new Uri(job.Url).GetLeftPart(UriPartial.Authority);bool changedOrigin=false;address.TextChanged+=delegate{Uri u;if(Uri.TryCreate(address.Text,UriKind.Absolute,out u)&&u.GetLeftPart(UriPartial.Authority)!=originalAuthority){changedOrigin=true;login.Clear();password.Clear();referer.Clear();}};
            ClassicLayout.Line(this,7,220,304);ClassicLayout.Button(this,"Advanced...",7,227,64,()=>{Hide();using(var d=new TransferOptionsDialog(manager,job))d.ShowDialog(Owner);Close();});var open=ClassicLayout.Button(this,"Open",172,227,50,()=>DownloadUi.OpenFile(job));open.Enabled=readOnly;
            AcceptButton=ClassicLayout.Button(this,"OK",261,227,50,()=>{if(readOnly){lock(manager.Sync){job.Description=description.Text;manager.Save();}}else{var headers=new Dictionary<string,string>(oldHeaders,StringComparer.OrdinalIgnoreCase);if(changedOrigin){headers.Remove("Authorization");headers.Remove("Cookie");headers.Remove("Referer");}if(login.Text.Length>0)headers["Authorization"]="Basic "+Convert.ToBase64String(Encoding.UTF8.GetBytes(login.Text+":"+password.Text));else headers.Remove("Authorization");if(referer.Text.Length>0)headers["Referer"]=referer.Text;else headers.Remove("Referer");manager.EditProperties(job,address.Text,destination.Text,description.Text,headers);}Close();});AppTheme.Apply(this);
        }
    }
    public sealed class BatchPatternDialog:Form {
        public BatchPatternDialog(Manager manager){ClassicLayout.Form(this,"Batch download",316,238);MinimizeBox=false;ClassicLayout.Label(this,"Add sequential file names using an asterisk, such as image*.jpg. Review the generated addresses before downloading.",7,7,302,30);ClassicLayout.Label(this,"Address",7,42,45);var address=ClassicLayout.Text(this,"https://",58,39,251);var numbers=ClassicLayout.Place(this,new RadioButton{Text="Numbers",Checked=true},91,65,80,12);var letters=ClassicLayout.Place(this,new RadioButton{Text="Letters"},188,65,80,12);ClassicLayout.Label(this,"Replace * with",7,65,80);
            ClassicLayout.Label(this,"From",7,88,30);var first=ClassicLayout.Text(this,"1",40,85,51);ClassicLayout.Label(this,"To",108,88,22);var last=ClassicLayout.Text(this,"10",135,85,51);ClassicLayout.Label(this,"Digits",202,88,38);var digits=ClassicLayout.Place(this,new NumericUpDown{Minimum=1,Maximum=6,Value=3},245,85,64,14);
            var auth=ClassicLayout.Check(this,"Use authorization",7,108,130,false);ClassicLayout.Label(this,"Login",7,128,40);var login=ClassicLayout.Text(this,"",50,125,98);ClassicLayout.Label(this,"Password",158,128,55);var password=ClassicLayout.Text(this,"",217,125,92);password.UseSystemPasswordChar=true;login.Enabled=password.Enabled=false;auth.CheckedChanged+=delegate{login.Enabled=password.Enabled=auth.Checked;};
            var preview=ClassicLayout.Place(this,new TextBox{Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Vertical},7,149,302,57);Action update=()=>{try{var urls=BatchPattern.Expand(address.Text,first.Text,last.Text,(int)digits.Value,letters.Checked);preview.Text=urls.Count+" files\r\n"+string.Join("\r\n",urls.Take(2))+"\r\n...\r\n"+urls.Last();}catch(Exception ex){preview.Text=ex.Message;}};address.TextChanged+=delegate{update();};first.TextChanged+=delegate{update();};last.TextChanged+=delegate{update();};digits.ValueChanged+=delegate{update();};letters.CheckedChanged+=delegate{if(letters.Checked){first.Text="a";last.Text="z";}else{first.Text="1";last.Text="10";}digits.Enabled=!letters.Checked;update();};
            AcceptButton=ClassicLayout.Button(this,"OK",197,216,50,()=>{var urls=BatchPattern.Expand(address.Text,first.Text,last.Text,(int)digits.Value,letters.Checked);var headers=new Dictionary<string,string>();if(auth.Checked)headers["Authorization"]="Basic "+Convert.ToBase64String(Encoding.UTF8.GetBytes(login.Text+":"+password.Text));using(var d=new BatchSelectionDialog(manager,urls,headers))if(d.ShowDialog(this)==DialogResult.OK)Close();});CancelButton=ClassicLayout.Button(this,"Cancel",259,216,50,Close);update();AppTheme.Apply(this);
        }
    }
    public sealed class BatchSelectionDialog:Form {
        public BatchSelectionDialog(Manager manager,List<string> urls,Dictionary<string,string> headers){ClassicLayout.Form(this,"Download selected files",380,254);MinimizeBox=false;ClassicLayout.Label(this,"Select the files to add",7,7,300);var list=ClassicLayout.Place(this,new CheckedListBox{CheckOnClick=true,HorizontalScrollbar=true},7,23,366,169);foreach(string url in urls)list.Items.Add(url,true);ClassicLayout.Button(this,"Check all",7,198,60,()=>{for(int i=0;i<list.Items.Count;i++)list.SetItemChecked(i,true);});ClassicLayout.Button(this,"Uncheck all",74,198,64,()=>{for(int i=0;i<list.Items.Count;i++)list.SetItemChecked(i,false);});var queue=ClassicLayout.Place(this,new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList},180,198,193,14);queue.Items.AddRange(manager.State.Queues.Select(q=>(object)q.Name).ToArray());queue.SelectedIndex=0;Action<bool> add=paused=>{foreach(string url in list.CheckedItems)manager.Add(url,null,null,queue.Text,paused,headers,"",null);DialogResult=DialogResult.OK;Close();};ClassicLayout.Button(this,"Download Later",96,230,89,()=>add(true));AcceptButton=ClassicLayout.Button(this,"Start Download",191,230,89,()=>add(false));CancelButton=ClassicLayout.Button(this,"Cancel",286,230,87,Close);AppTheme.Apply(this);}
    }
    public sealed class GrabDialog:Form {
        readonly CancellationTokenSource cancel=new CancellationTokenSource();
        public GrabDialog(Manager manager,GrabProject existing=null){var project=existing==null?new GrabProject():Json.Read<GrabProject>(Json.Write(existing));ClassicLayout.Form(this,"UDM Site Grabber",520,330);MinimizeBox=false;
            ClassicLayout.Label(this,"Project",7,9,44);var name=ClassicLayout.Text(this,project.Name,54,6,240);ClassicLayout.Label(this,"Start page",7,31,44);var url=ClassicLayout.Text(this,project.StartUrl,54,28,459);ClassicLayout.Label(this,"File types",7,53,44);var types=ClassicLayout.Text(this,project.Extensions,54,50,240);ClassicLayout.Label(this,"Depth",304,53,34);var depth=ClassicLayout.Place(this,new NumericUpDown{Minimum=0,Maximum=5,Value=project.Depth},338,50,38,14);ClassicLayout.Label(this,"Max pages",389,53,67);var pages=ClassicLayout.Place(this,new NumericUpDown{Minimum=1,Maximum=100,Value=project.MaxPages},458,50,55,14);
            var status=ClassicLayout.Label(this,"Explore a site, then select files. Projects and selections are saved locally.",7,76,506,22);var results=ClassicLayout.Place(this,new CheckedListBox{CheckOnClick=true,HorizontalScrollbar=true},7,101,506,177);foreach(var link in project.Links)results.Items.Add(link,link.Selected);var queue=ClassicLayout.Place(this,new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList},339,284,174,14);queue.Items.AddRange(manager.State.Queues.Select(q=>(object)q.Name).ToArray());queue.SelectedIndex=0;
            Action save=()=>{project.Name=name.Text.Trim();project.StartUrl=url.Text.Trim();project.Extensions=types.Text;project.Depth=(int)depth.Value;project.MaxPages=(int)pages.Value;project.Links=results.Items.Cast<GrabLink>().ToList();for(int i=0;i<results.Items.Count;i++)project.Links[i].Selected=results.GetItemChecked(i);manager.SaveProject(Json.Read<GrabProject>(Json.Write(project)));};
            var explore=ClassicLayout.Button(this,"Explore",7,306,60,()=>{});explore.Click+=async delegate{if(explore.Tag!=null)return;try{save();explore.Tag=true;explore.Enabled=false;var found=await Grabber.Explore(project.StartUrl,project.Depth,project.MaxPages,project.Extensions,new Progress<string>(s=>{if(!IsDisposed)status.Text=s;}),cancel.Token);var old=project.Links.ToDictionary(l=>l.Url);results.Items.Clear();foreach(var item in found){GrabLink link;if(!old.TryGetValue(item.Url,out link))link=new GrabLink{Url=item.Url};results.Items.Add(link,link.Selected);}project.LastExplored=DateTime.UtcNow;save();status.Text=found.Count+" matching files. Project saved.";}catch(OperationCanceledException){}catch(Exception ex){if(!IsDisposed)status.Text=ex.Message;}finally{if(!IsDisposed){explore.Tag=null;explore.Enabled=true;}}};
            ClassicLayout.Button(this,"Save project",74,306,74,()=>{save();status.Text="Project saved.";});ClassicLayout.Button(this,"Check all",7,282,60,()=>{for(int i=0;i<results.Items.Count;i++)results.SetItemChecked(i,true);});ClassicLayout.Button(this,"Uncheck all",74,282,74,()=>{for(int i=0;i<results.Items.Count;i++)results.SetItemChecked(i,false);});ClassicLayout.Button(this,"Download Later",207,306,95,()=>{save();status.Text=manager.AddProjectFiles(project,queue.Text,true)+" files added paused.";});ClassicLayout.Button(this,"Start Download",309,306,95,()=>{save();status.Text=manager.AddProjectFiles(project,queue.Text,false)+" files added to UDM.";});CancelButton=ClassicLayout.Button(this,"Close",418,306,95,Close);FormClosing+=delegate{cancel.Cancel();};FormClosed+=delegate{cancel.Dispose();};AppTheme.Apply(this);
        }
    }
}
