using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;

namespace Udm {
    public sealed partial class Manager {
        public static void ValidateCaptureRules(string extensions,string hosts){if(Words(extensions).Any(x=>!Regex.IsMatch(x,@"^[a-z0-9_-]{1,30}$")))throw new ArgumentException("Use file extensions such as zip mp4 pdf, separated by spaces.");foreach(string h in Words(hosts))if(Uri.CheckHostName(h)==UriHostNameType.Unknown)throw new ArgumentException("Use host names such as example.com, separated by spaces.");}
        static string Named(string value,string kind){string name=(value??"").Trim();if(name.Length==0||name.Length>80||name.IndexOfAny(new[]{'\r','\n','\t'})>=0)throw new ArgumentException("Enter a "+kind+" name up to 80 characters.");return name;}
        public int RetriesFor(string queue){lock(Sync){var q=State.Queues.FirstOrDefault(x=>x.Name==queue);return q!=null&&q.Retries.HasValue?q.Retries.Value:State.Settings.Retries;}}
        public QueueRule CreateQueue(string value){string name=Named(value,"queue");lock(Sync){if(State.Queues.Any(q=>q.Name.Equals(name,StringComparison.OrdinalIgnoreCase)))throw new ArgumentException("That queue already exists.");var rule=new QueueRule{Name=name,Enabled=false};State.Queues.Add(rule);try{Save();}catch{State.Queues.Remove(rule);throw;}return rule;}}
        public void UpdateQueue(QueueRule target,QueueRule edited){
            if(edited.Parallel<1||edited.Parallel>16||edited.StartMinute<0||edited.StartMinute>1439||edited.StopMinute<0||edited.StopMinute>1440||edited.Days<0||edited.Days>127||edited.Retries<0||edited.Retries>10)throw new ArgumentException("Invalid queue settings.");
            if(edited.Scheduled&&!edited.RunOnce&&edited.Days==0)throw new ArgumentException("Select at least one weekday.");
            if(edited.RunOnce&&(!edited.StartOnceUtc.HasValue||(edited.StopOnceUtc.HasValue&&edited.StopOnceUtc<=edited.StartOnceUtc)))throw new ArgumentException("Choose a start date and a later stop date.");
            lock(Sync){if(!State.Queues.Contains(target))throw new ArgumentException("Queue no longer exists.");var old=Json.Read<QueueRule>(Json.Write(target));
                Action<QueueRule> copy=q=>{target.Enabled=q.Enabled;target.Parallel=q.Parallel;target.Scheduled=q.Scheduled;target.StartMinute=q.StartMinute;target.StopMinute=q.StopMinute;target.Days=q.Days;target.RunOnce=q.RunOnce;target.StartOnceUtc=q.StartOnceUtc;target.StopOnceUtc=q.StopOnceUtc;target.Retries=q.Retries;target.OnceStarted=q.OnceStarted;};
                edited.OnceStarted=target.OnceStarted&&edited.StartOnceUtc==target.StartOnceUtc;copy(edited);try{Save();}catch{copy(old);throw;}
            }
        }
        public void DeleteQueue(QueueRule rule){lock(Sync){if(!State.Queues.Contains(rule))return;if(State.Queues.Count==1||rule.Name=="Main queue")throw new InvalidOperationException("The main queue cannot be deleted.");var members=State.Downloads.Where(d=>d.Queue==rule.Name).ToArray();if(members.Any(IsActive))throw new InvalidOperationException("Stop this queue before deleting it.");var destination=State.Queues.First(q=>q!=rule);int index=State.Queues.IndexOf(rule);var statuses=members.Select(d=>d.Status).ToArray();foreach(var job in members){job.Queue=destination.Name;if(job.Status!="Complete")job.Status="Paused";}State.Queues.Remove(rule);try{Save();}catch{State.Queues.Insert(index,rule);for(int i=0;i<members.Length;i++){members[i].Queue=rule.Name;members[i].Status=statuses[i];}throw;}}}
        public void RunQueue(QueueRule rule,bool enabled){lock(Sync){if(!State.Queues.Contains(rule))throw new ArgumentException("Queue no longer exists.");rule.Enabled=enabled;rule.ManualRun=enabled;if(enabled)rule.OnceStarted=false;foreach(var d in State.Downloads.Where(d=>d.Queue==rule.Name)){if(enabled&&!IsActive(d)&&new[]{"Paused","Failed","Queued"}.Contains(d.Status)){d.Status="Queued";d.Error="";d.SessionLimitKbps=null;schedulePaused.Remove(d.Id);}else if(!enabled&&(IsActive(d)||d.Status=="Queued")){schedulePaused.Remove(d.Id);if(IsActive(d)){d.Status="Pausing";active[d.Id].Cancel();}else d.Status="Paused";}}Save();}}
        public void MoveWithinQueue(Download job,int direction){if(direction!=1&&direction!=-1)throw new ArgumentException("Choose up or down.");lock(Sync){var siblings=State.Downloads.Where(d=>d.Queue==job.Queue).ToList();int from=siblings.IndexOf(job),to=from+direction;if(from<0||to<0||to>=siblings.Count)return;int a=State.Downloads.IndexOf(job),b=State.Downloads.IndexOf(siblings[to]);State.Downloads[a]=siblings[to];State.Downloads[b]=job;try{Save();}catch{State.Downloads[b]=siblings[to];State.Downloads[a]=job;throw;}}}
        public void MoveToQueue(Download job,string queue){lock(Sync){if(IsActive(job))throw new InvalidOperationException("Pause this file before changing its queue.");if(!State.Queues.Any(q=>q.Name==queue))throw new ArgumentException("Choose an existing queue.");string old=job.Queue;job.Queue=queue;try{Save();}catch{job.Queue=old;throw;}}}
        public void EditProperties(Download job,string address,string destination,string description,Dictionary<string,string> headers){
            Uri next=Names.Url(address);if(!Path.IsPathRooted(destination))throw new ArgumentException("Choose a complete destination path.");destination=Path.GetFullPath(destination);string name=Path.GetFileName(destination);if(Names.Safe(name)!=name)throw new ArgumentException("Choose a valid file name.");
            headers=ValidateHeaders(headers);if(!new Uri(job.Url).GetLeftPart(UriPartial.Authority).Equals(next.GetLeftPart(UriPartial.Authority),StringComparison.OrdinalIgnoreCase)){headers.Remove("Authorization");headers.Remove("Cookie");headers.Remove("Referer");}string protectedHeaders=headers.Count==0?"":Secrets.Protect(Json.Write(headers));
            lock(Sync){if(IsActive(job))throw new InvalidOperationException("Pause this download before editing it.");if(job.Status=="Complete")throw new InvalidOperationException("Completed download locations are read-only.");if(job.SourceUrl!=null&&address!=job.SourceUrl)throw new ArgumentException("Refresh video streams from the browser panel.");
                if((!destination.Equals(job.Target,StringComparison.OrdinalIgnoreCase)&&File.Exists(destination))||State.Downloads.Any(d=>d.Id!=job.Id&&d.Target.Equals(destination,StringComparison.OrdinalIgnoreCase)))throw new IOException("That destination already exists.");
                string oldUrl=job.Url,oldFolder=job.Folder,oldName=job.FileName,oldDescription=job.Description,oldHeaders=job.ProtectedHeaders;
                job.Url=next.AbsoluteUri;job.FileName=name;job.Folder=Path.GetDirectoryName(destination);job.Description=description??"";job.ProtectedHeaders=protectedHeaders;
                try{Save();}catch{job.Url=oldUrl;job.Folder=oldFolder;job.FileName=oldName;job.Description=oldDescription;job.ProtectedHeaders=oldHeaders;throw;}
            }
        }
        public Dictionary<string,string> ReadHeaders(Download job){return string.IsNullOrEmpty(job.ProtectedHeaders)?new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase):new Dictionary<string,string>(Json.Read<Dictionary<string,string>>(Secrets.Reveal(job.ProtectedHeaders)),StringComparer.OrdinalIgnoreCase);}
        static Dictionary<string,string> ValidateHeaders(Dictionary<string,string> source){var copy=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase);foreach(var h in source??new Dictionary<string,string>()){if(!new[]{"Authorization","Cookie","Referer","User-Agent"}.Contains(h.Key,StringComparer.OrdinalIgnoreCase)||h.Value==null||h.Value.Length>16384||h.Value.IndexOfAny(new[]{'\r','\n'})>=0)throw new ArgumentException("Invalid request header.");copy[h.Key]=h.Value;}return copy;}
        Dictionary<string,string> HeadersFor(Uri uri,Dictionary<string,string> original){var headers=ValidateHeaders(original);lock(Sync){if(!headers.ContainsKey("Authorization")){var login=State.Settings.SiteLogins.FirstOrDefault(s=>s.Origin.Equals(uri.GetLeftPart(UriPartial.Authority),StringComparison.OrdinalIgnoreCase));if(login!=null)headers["Authorization"]="Basic "+Convert.ToBase64String(Encoding.UTF8.GetBytes(login.UserName+":"+Secrets.Reveal(login.ProtectedPassword)));}}return headers;}
        public void SaveSiteLogin(string site,string user,string password){var uri=Names.Url(site);if(uri.Scheme!="https")throw new ArgumentException("Saved site logins require an HTTPS origin.");if(string.IsNullOrWhiteSpace(user)||user.Contains(":"))throw new ArgumentException("Enter a user name without a colon.");string origin=uri.GetLeftPart(UriPartial.Authority);var login=new SiteLogin{Origin=origin,UserName=user,ProtectedPassword=Secrets.Protect(password)};lock(Sync){var existing=State.Settings.SiteLogins.FirstOrDefault(s=>s.Origin.Equals(origin,StringComparison.OrdinalIgnoreCase));if(existing!=null)State.Settings.SiteLogins.Remove(existing);State.Settings.SiteLogins.Add(login);try{Save();}catch{State.Settings.SiteLogins.Remove(login);if(existing!=null)State.Settings.SiteLogins.Add(existing);throw;}}}
        public void RemoveSiteLogin(SiteLogin item){lock(Sync){int i=State.Settings.SiteLogins.IndexOf(item);if(i<0)return;State.Settings.SiteLogins.RemoveAt(i);try{Save();}catch{State.Settings.SiteLogins.Insert(i,item);throw;}}}
        public static string[] Words(string value){return Regex.Split(value??"",@"[\s,;]+").Select(s=>s.Trim().ToLowerInvariant()).Where(s=>s.Length>0).Distinct().ToArray();}
        string CategoryFor(Uri uri,string file){lock(Sync){string ext=Path.GetExtension(file).TrimStart('.');foreach(var rule in State.Settings.CategoryRules){bool extension=Words(rule.Extensions).Any(x=>x=="*"||x.TrimStart('*','.')==ext.ToLowerInvariant());bool host=string.IsNullOrWhiteSpace(rule.Hosts)||Words(rule.Hosts).Any(h=>uri.Host.Equals(h.TrimStart('*','.'),StringComparison.OrdinalIgnoreCase)||uri.Host.EndsWith("."+h.TrimStart('*','.'),StringComparison.OrdinalIgnoreCase));if(extension&&host&&Categories.Contains(rule.Category,StringComparer.OrdinalIgnoreCase))return rule.Category;}}return Names.Category(file);}
        public void SaveCategoryRule(string category,string extensions,string hosts){if(!Categories.Contains(category,StringComparer.OrdinalIgnoreCase))throw new ArgumentException("Choose an existing category.");string normalized=string.Join(" ",Words(extensions).Select(x=>x=="*"?x:x.TrimStart('*','.')));if(Words(normalized).Any(x=>x!="*"&&!Regex.IsMatch(x,@"^[a-z0-9_-]{1,30}$")))throw new ArgumentException("Use file extensions separated by spaces.");foreach(string h in Words(hosts))if(Uri.CheckHostName(h.TrimStart('*','.'))==UriHostNameType.Unknown)throw new ArgumentException("Use host names separated by spaces.");lock(Sync){var old=State.Settings.CategoryRules.FirstOrDefault(r=>r.Category==category);if(old!=null)State.Settings.CategoryRules.Remove(old);var rule=new CategoryRule{Category=category,Extensions=normalized,Hosts=string.Join(" ",Words(hosts))};if(normalized.Length>0)State.Settings.CategoryRules.Add(rule);try{Save();}catch{State.Settings.CategoryRules.Remove(rule);if(old!=null)State.Settings.CategoryRules.Add(old);throw;}}}
        public void SaveProject(GrabProject project){Named(project.Name,"project");var uri=Names.Url(project.StartUrl);if(uri.Scheme=="ftp"||project.Depth<0||project.Depth>5||project.MaxPages<1||project.MaxPages>100)throw new ArgumentException("Choose an HTTP page, depth 0–5, and 1–100 pages.");Guid id;if(!Guid.TryParseExact(project.Id,"N",out id))throw new ArgumentException("Invalid project identifier.");if(project.Links==null||project.Links.Count>2000)throw new ArgumentException("A project can contain at most 2,000 files.");foreach(var link in project.Links){var u=Names.Url(link.Url);if(u.GetLeftPart(UriPartial.Authority)!=uri.GetLeftPart(UriPartial.Authority))throw new ArgumentException("Project files must belong to the starting site.");}lock(Sync){if(State.Projects.Any(p=>p.Id!=project.Id&&p.Name.Equals(project.Name,StringComparison.OrdinalIgnoreCase)))throw new ArgumentException("That project name already exists.");int index=State.Projects.FindIndex(p=>p.Id==project.Id);var previous=index<0?null:State.Projects[index];if(index<0)State.Projects.Add(project);else State.Projects[index]=project;try{Save();}catch{if(index<0)State.Projects.Remove(project);else State.Projects[index]=previous;throw;}}}
        public int AddProjectFiles(GrabProject project,string queue,bool paused){lock(Sync){SaveProject(project);int count=0;foreach(var link in project.Links.Where(l=>l.Selected)){if(State.Downloads.Any(d=>d.ProjectId==project.Id&&d.Url==link.Url))continue;var job=Add(link.Url,null,null,queue,paused,null,"",null);job.ProjectId=project.Id;link.DownloadId=job.Id;count++;}Save();return count;}}
    }
    public static class BatchPattern {
        public static List<string> Expand(string pattern,string first,string last,int digits,bool letters){
            if(string.IsNullOrWhiteSpace(pattern)||!pattern.Contains("*"))throw new ArgumentException("Put an asterisk where the sequence belongs.");if(digits<1||digits>6)throw new ArgumentException("Use 1–6 digits.");int begin,end;
            if(letters){if(first==null||last==null||first.Length!=1||last.Length!=1||!Regex.IsMatch(first+last,@"^(?:[A-Z]{2}|[a-z]{2})$"))throw new ArgumentException("Use two letters with the same case.");begin=first[0];end=last[0];}
            else if(!int.TryParse(first,out begin)||!int.TryParse(last,out end)||begin<0||end>999999)throw new ArgumentException("Use numbers from 0 to 999999.");
            if(end<begin||end-begin>999)throw new ArgumentException("A batch may contain 1–1,000 files.");var urls=new List<string>();for(int i=begin;i<=end;i++){string value=letters?((char)i).ToString():i.ToString(new string('0',digits));string url=pattern.Replace("*",value);Names.Url(url);urls.Add(url);}return urls;
        }
    }
}
